# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1366, 810)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.hlMainSections = QtGui.QHBoxLayout()
        self.hlMainSections.setSpacing(0)
        self.hlMainSections.setObjectName(_fromUtf8("hlMainSections"))
        self.vlUISelect = QtGui.QVBoxLayout()
        self.vlUISelect.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.vlUISelect.setSpacing(0)
        self.vlUISelect.setObjectName(_fromUtf8("vlUISelect"))
        self.leInformation = QtGui.QLineEdit(self.centralwidget)
        self.leInformation.setReadOnly(True)
        self.leInformation.setObjectName(_fromUtf8("leInformation"))
        self.vlUISelect.addWidget(self.leInformation)
        self.listInformation = QtGui.QListWidget(self.centralwidget)
        self.listInformation.setObjectName(_fromUtf8("listInformation"))
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listInformation.addItem(item)
        self.vlUISelect.addWidget(self.listInformation)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlUISelect.addItem(spacerItem)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.vlUISelect.addWidget(self.lineEdit)
        self.listAssembly = QtGui.QListWidget(self.centralwidget)
        self.listAssembly.setObjectName(_fromUtf8("listAssembly"))
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listAssembly.addItem(item)
        self.vlUISelect.addWidget(self.listAssembly)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vlUISelect.addItem(spacerItem1)
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.vlUISelect.addWidget(self.lineEdit_2)
        self.listShippingAndReceiving = QtGui.QListWidget(self.centralwidget)
        self.listShippingAndReceiving.setObjectName(_fromUtf8("listShippingAndReceiving"))
        item = QtGui.QListWidgetItem()
        self.listShippingAndReceiving.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listShippingAndReceiving.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listShippingAndReceiving.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listShippingAndReceiving.addItem(item)
        self.vlUISelect.addWidget(self.listShippingAndReceiving)
        self.vlUISelect.setStretch(0, 1)
        self.vlUISelect.setStretch(1, 7)
        self.vlUISelect.setStretch(2, 1)
        self.vlUISelect.setStretch(3, 1)
        self.vlUISelect.setStretch(4, 11)
        self.vlUISelect.setStretch(5, 1)
        self.vlUISelect.setStretch(6, 1)
        self.vlUISelect.setStretch(7, 4)
        self.hlMainSections.addLayout(self.vlUISelect)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hlMainSections.addItem(spacerItem2)
        self.hlUIpane = QtGui.QHBoxLayout()
        self.hlUIpane.setSpacing(0)
        self.hlUIpane.setObjectName(_fromUtf8("hlUIpane"))
        self.swPages = QtGui.QStackedWidget(self.centralwidget)
        self.swPages.setFrameShape(QtGui.QFrame.Box)
        self.swPages.setObjectName(_fromUtf8("swPages"))
        self.hlUIpane.addWidget(self.swPages)
        self.hlMainSections.addLayout(self.hlUIpane)
        self.hlMainSections.setStretch(0, 8)
        self.hlMainSections.setStretch(1, 1)
        self.hlMainSections.setStretch(2, 40)
        self.gridLayout.addLayout(self.hlMainSections, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listInformation.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.leInformation.setText(_translate("MainWindow", "Information", None))
        __sortingEnabled = self.listInformation.isSortingEnabled()
        self.listInformation.setSortingEnabled(False)
        item = self.listInformation.item(0)
        item.setText(_translate("MainWindow", "modules", None))
        item = self.listInformation.item(1)
        item.setText(_translate("MainWindow", "baseplates", None))
        item = self.listInformation.item(2)
        item.setText(_translate("MainWindow", "sensors", None))
        item = self.listInformation.item(3)
        item.setText(_translate("MainWindow", "PCBs", None))
        item = self.listInformation.item(4)
        item.setText(_translate("MainWindow", "kapton placement steps", None))
        item = self.listInformation.item(5)
        item.setText(_translate("MainWindow", "sensor placement steps", None))
        item = self.listInformation.item(6)
        item.setText(_translate("MainWindow", "PCB placement steps", None))
        item = self.listInformation.item(7)
        item.setText(_translate("MainWindow", "supplies", None))
        item = self.listInformation.item(8)
        item.setText(_translate("MainWindow", "tooling", None))
        self.listInformation.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setText(_translate("MainWindow", "Production and testing routines", None))
        __sortingEnabled = self.listAssembly.isSortingEnabled()
        self.listAssembly.setSortingEnabled(False)
        item = self.listAssembly.item(0)
        item.setText(_translate("MainWindow", "baseplate height measurement", None))
        item = self.listAssembly.item(1)
        item.setText(_translate("MainWindow", "kapton application", None))
        item = self.listAssembly.item(2)
        item.setText(_translate("MainWindow", "kapton insulation test", None))
        item = self.listAssembly.item(3)
        item.setText(_translate("MainWindow", "sensor application", None))
        item = self.listAssembly.item(4)
        item.setText(_translate("MainWindow", "PCB application", None))
        item = self.listAssembly.item(5)
        item.setText(_translate("MainWindow", "wirebonding", None))
        item = self.listAssembly.item(6)
        item.setText(_translate("MainWindow", "DAQ (unbiased)", None))
        item = self.listAssembly.item(7)
        item.setText(_translate("MainWindow", "IV curve", None))
        item = self.listAssembly.item(8)
        item.setText(_translate("MainWindow", "encapsulation", None))
        self.listAssembly.setSortingEnabled(__sortingEnabled)
        self.lineEdit_2.setText(_translate("MainWindow", "Shipping and receiving", None))
        __sortingEnabled = self.listShippingAndReceiving.isSortingEnabled()
        self.listShippingAndReceiving.setSortingEnabled(False)
        item = self.listShippingAndReceiving.item(0)
        item.setText(_translate("MainWindow", "Receiving baseplates", None))
        item = self.listShippingAndReceiving.item(1)
        item.setText(_translate("MainWindow", "Receiving sensors", None))
        item = self.listShippingAndReceiving.item(2)
        item.setText(_translate("MainWindow", "Receiving PCBs", None))
        item = self.listShippingAndReceiving.item(3)
        item.setText(_translate("MainWindow", "Shipping", None))
        self.listShippingAndReceiving.setSortingEnabled(__sortingEnabled)

