# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routine_iv.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 737)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(550, 350, 541, 381))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlActive = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlActive.setObjectName(_fromUtf8("vlActive"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 350, 541, 381))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.vlAll = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vlAll.setObjectName(_fromUtf8("vlAll"))
        self.cbAllPlotType = QtGui.QComboBox(Form)
        self.cbAllPlotType.setGeometry(QtCore.QRect(40, 290, 71, 22))
        self.cbAllPlotType.setObjectName(_fromUtf8("cbAllPlotType"))
        self.cbAllPlotType.addItem(_fromUtf8(""))
        self.cbAllPlotType.addItem(_fromUtf8(""))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 310, 41, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.cbAllXAxis = QtGui.QComboBox(Form)
        self.cbAllXAxis.setGeometry(QtCore.QRect(40, 310, 71, 21))
        self.cbAllXAxis.setObjectName(_fromUtf8("cbAllXAxis"))
        self.cbAllXAxis.addItem(_fromUtf8(""))
        self.cbAllXAxis.addItem(_fromUtf8(""))
        self.cbAllXAxis.addItem(_fromUtf8(""))
        self.cbAllXAxis.addItem(_fromUtf8(""))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 330, 41, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.cbAllYAxis = QtGui.QComboBox(Form)
        self.cbAllYAxis.setGeometry(QtCore.QRect(40, 330, 71, 21))
        self.cbAllYAxis.setObjectName(_fromUtf8("cbAllYAxis"))
        self.cbAllYAxis.addItem(_fromUtf8(""))
        self.cbAllYAxis.addItem(_fromUtf8(""))
        self.cbAllYAxis.addItem(_fromUtf8(""))
        self.cbAllYAxis.addItem(_fromUtf8(""))
        self.ckAllPlotAsc = QtGui.QCheckBox(Form)
        self.ckAllPlotAsc.setGeometry(QtCore.QRect(120, 290, 101, 17))
        self.ckAllPlotAsc.setChecked(True)
        self.ckAllPlotAsc.setObjectName(_fromUtf8("ckAllPlotAsc"))
        self.ckAllPlotDesc = QtGui.QCheckBox(Form)
        self.ckAllPlotDesc.setGeometry(QtCore.QRect(120, 310, 101, 17))
        self.ckAllPlotDesc.setChecked(True)
        self.ckAllPlotDesc.setObjectName(_fromUtf8("ckAllPlotDesc"))
        self.ckAllUpdate = QtGui.QCheckBox(Form)
        self.ckAllUpdate.setGeometry(QtCore.QRect(230, 310, 101, 17))
        self.ckAllUpdate.setChecked(True)
        self.ckAllUpdate.setObjectName(_fromUtf8("ckAllUpdate"))
        self.ckAllHideZero = QtGui.QCheckBox(Form)
        self.ckAllHideZero.setGeometry(QtCore.QRect(120, 330, 101, 17))
        self.ckAllHideZero.setChecked(True)
        self.ckAllHideZero.setObjectName(_fromUtf8("ckAllHideZero"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(0, 290, 41, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(230, 330, 121, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.dsbAllUpdateInterval = QtGui.QDoubleSpinBox(Form)
        self.dsbAllUpdateInterval.setGeometry(QtCore.QRect(350, 330, 81, 21))
        self.dsbAllUpdateInterval.setMinimum(1.0)
        self.dsbAllUpdateInterval.setMaximum(2147483647.0)
        self.dsbAllUpdateInterval.setProperty("value", 5.0)
        self.dsbAllUpdateInterval.setObjectName(_fromUtf8("dsbAllUpdateInterval"))
        self.dsbActiveUpdateInterval = QtGui.QDoubleSpinBox(Form)
        self.dsbActiveUpdateInterval.setGeometry(QtCore.QRect(670, 330, 81, 21))
        self.dsbActiveUpdateInterval.setMinimum(1.0)
        self.dsbActiveUpdateInterval.setMaximum(2147483647.0)
        self.dsbActiveUpdateInterval.setObjectName(_fromUtf8("dsbActiveUpdateInterval"))
        self.ckActiveUpdate = QtGui.QCheckBox(Form)
        self.ckActiveUpdate.setGeometry(QtCore.QRect(550, 310, 91, 17))
        self.ckActiveUpdate.setChecked(True)
        self.ckActiveUpdate.setObjectName(_fromUtf8("ckActiveUpdate"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(550, 330, 121, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 61, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbModuleID = QtGui.QSpinBox(Form)
        self.sbModuleID.setGeometry(QtCore.QRect(60, 0, 61, 21))
        self.sbModuleID.setMaximum(2147483647)
        self.sbModuleID.setSingleStep(0)
        self.sbModuleID.setProperty("value", 0)
        self.sbModuleID.setObjectName(_fromUtf8("sbModuleID"))
        self.leModuleReady = QtGui.QLineEdit(Form)
        self.leModuleReady.setGeometry(QtCore.QRect(0, 40, 171, 21))
        self.leModuleReady.setText(_fromUtf8(""))
        self.leModuleReady.setReadOnly(True)
        self.leModuleReady.setObjectName(_fromUtf8("leModuleReady"))
        self.leModuleExists = QtGui.QLineEdit(Form)
        self.leModuleExists.setGeometry(QtCore.QRect(0, 20, 171, 21))
        self.leModuleExists.setText(_fromUtf8(""))
        self.leModuleExists.setReadOnly(True)
        self.leModuleExists.setObjectName(_fromUtf8("leModuleExists"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 0, 51, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 120, 101, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.cbKeithleyPort = QtGui.QComboBox(Form)
        self.cbKeithleyPort.setGeometry(QtCore.QRect(100, 120, 71, 21))
        self.cbKeithleyPort.setObjectName(_fromUtf8("cbKeithleyPort"))
        self.cbKeithleyPort.addItem(_fromUtf8(""))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 90, 121, 21))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pbKeithleyQuery = QtGui.QPushButton(Form)
        self.pbKeithleyQuery.setGeometry(QtCore.QRect(0, 160, 51, 21))
        self.pbKeithleyQuery.setObjectName(_fromUtf8("pbKeithleyQuery"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 140, 101, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.cbKeithleyBaud = QtGui.QComboBox(Form)
        self.cbKeithleyBaud.setGeometry(QtCore.QRect(100, 140, 71, 21))
        self.cbKeithleyBaud.setObjectName(_fromUtf8("cbKeithleyBaud"))
        self.cbKeithleyBaud.addItem(_fromUtf8(""))
        self.leKeithleyQueryResponse = QtGui.QLineEdit(Form)
        self.leKeithleyQueryResponse.setGeometry(QtCore.QRect(50, 160, 121, 21))
        self.leKeithleyQueryResponse.setText(_fromUtf8(""))
        self.leKeithleyQueryResponse.setReadOnly(True)
        self.leKeithleyQueryResponse.setObjectName(_fromUtf8("leKeithleyQueryResponse"))
        self.cbArduinoPort = QtGui.QComboBox(Form)
        self.cbArduinoPort.setEnabled(False)
        self.cbArduinoPort.setGeometry(QtCore.QRect(100, 190, 71, 21))
        self.cbArduinoPort.setObjectName(_fromUtf8("cbArduinoPort"))
        self.cbArduinoPort.addItem(_fromUtf8(""))
        self.pbArduinoQuery = QtGui.QPushButton(Form)
        self.pbArduinoQuery.setEnabled(False)
        self.pbArduinoQuery.setGeometry(QtCore.QRect(0, 230, 51, 21))
        self.pbArduinoQuery.setObjectName(_fromUtf8("pbArduinoQuery"))
        self.leArduinoQueryResponse = QtGui.QLineEdit(Form)
        self.leArduinoQueryResponse.setEnabled(False)
        self.leArduinoQueryResponse.setGeometry(QtCore.QRect(50, 230, 121, 21))
        self.leArduinoQueryResponse.setText(_fromUtf8(""))
        self.leArduinoQueryResponse.setReadOnly(True)
        self.leArduinoQueryResponse.setObjectName(_fromUtf8("leArduinoQueryResponse"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 190, 101, 20))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.cbArduinoBaud = QtGui.QComboBox(Form)
        self.cbArduinoBaud.setEnabled(False)
        self.cbArduinoBaud.setGeometry(QtCore.QRect(100, 210, 71, 21))
        self.cbArduinoBaud.setObjectName(_fromUtf8("cbArduinoBaud"))
        self.cbArduinoBaud.addItem(_fromUtf8(""))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 210, 101, 20))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(210, 0, 141, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 20, 141, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(210, 40, 141, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(210, 80, 141, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(210, 60, 141, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(350, 0, 61, 21))
        self.doubleSpinBox.setMinimum(0.85)
        self.doubleSpinBox.setMaximum(65535.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.spinBox = QtGui.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(350, 20, 61, 21))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(350, 40, 61, 21))
        self.doubleSpinBox_2.setMinimum(1.0)
        self.doubleSpinBox_2.setMaximum(65535.0)
        self.doubleSpinBox_2.setProperty("value", 5.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.spinBox_2 = QtGui.QSpinBox(Form)
        self.spinBox_2.setGeometry(QtCore.QRect(350, 60, 61, 21))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(100)
        self.spinBox_2.setProperty("value", 10)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(350, 80, 61, 21))
        self.doubleSpinBox_3.setMinimum(1.0)
        self.doubleSpinBox_3.setMaximum(65535.0)
        self.doubleSpinBox_3.setProperty("value", 3.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(210, 110, 141, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.spinBox_3 = QtGui.QSpinBox(Form)
        self.spinBox_3.setGeometry(QtCore.QRect(350, 110, 61, 21))
        self.spinBox_3.setMinimum(1)
        self.spinBox_3.setMaximum(1090)
        self.spinBox_3.setSingleStep(10)
        self.spinBox_3.setProperty("value", 1090)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.radioButton = QtGui.QRadioButton(Form)
        self.radioButton.setGeometry(QtCore.QRect(210, 130, 141, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.buttonGroup = QtGui.QButtonGroup(Form)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(210, 150, 141, 17))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.buttonGroup.addButton(self.radioButton_2)
        self.spinBox_4 = QtGui.QSpinBox(Form)
        self.spinBox_4.setGeometry(QtCore.QRect(350, 130, 61, 21))
        self.spinBox_4.setMaximum(2147483647)
        self.spinBox_4.setProperty("value", 600)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(210, 180, 121, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(210, 200, 121, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(210, 240, 121, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(210, 220, 121, 17))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(330, 180, 81, 21))
        self.doubleSpinBox_4.setMaximum(65535.0)
        self.doubleSpinBox_4.setProperty("value", 2.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(330, 200, 81, 21))
        self.doubleSpinBox_5.setMaximum(65535.0)
        self.doubleSpinBox_5.setProperty("value", 2.0)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(330, 240, 81, 21))
        self.doubleSpinBox_6.setMaximum(65535.0)
        self.doubleSpinBox_6.setProperty("value", 10.0)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(330, 220, 81, 21))
        self.doubleSpinBox_7.setMaximum(65535.0)
        self.doubleSpinBox_7.setProperty("value", 10.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.pushButton_3 = QtGui.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 0, 75, 21))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 20, 75, 21))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 40, 75, 21))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 60, 75, 21))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(560, 0, 151, 20))
        self.lineEdit_17.setText(_fromUtf8(""))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.progressBar = QtGui.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(710, 0, 381, 20))
        self.progressBar.setMaximum(1000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(560, 20, 151, 20))
        self.lineEdit_18.setText(_fromUtf8(""))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.progressBar_2 = QtGui.QProgressBar(Form)
        self.progressBar_2.setEnabled(True)
        self.progressBar_2.setGeometry(QtCore.QRect(710, 20, 191, 20))
        self.progressBar_2.setMaximum(1000)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(False)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(560, 60, 91, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(560, 80, 91, 20))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setEnabled(False)
        self.lineEdit_21.setGeometry(QtCore.QRect(830, 60, 91, 20))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setEnabled(False)
        self.lineEdit_22.setGeometry(QtCore.QRect(830, 80, 91, 20))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(650, 60, 161, 20))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.lineEdit_24 = QtGui.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(650, 80, 161, 20))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.lineEdit_25 = QtGui.QLineEdit(Form)
        self.lineEdit_25.setEnabled(False)
        self.lineEdit_25.setGeometry(QtCore.QRect(920, 80, 171, 20))
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.lineEdit_26 = QtGui.QLineEdit(Form)
        self.lineEdit_26.setEnabled(False)
        self.lineEdit_26.setGeometry(QtCore.QRect(920, 60, 171, 20))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.plainTextEdit = QtGui.QPlainTextEdit(Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(450, 120, 361, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.pushButton_7 = QtGui.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(450, 80, 75, 21))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(Form)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(830, 140, 261, 121))
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.lineEdit_27 = QtGui.QLineEdit(Form)
        self.lineEdit_27.setGeometry(QtCore.QRect(830, 120, 261, 20))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))

        self.retranslateUi(Form)
        self.cbAllPlotType.setCurrentIndex(0)
        self.cbAllXAxis.setCurrentIndex(1)
        self.cbAllYAxis.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.cbAllPlotType.setItemText(0, _translate("Form", "Bins", None))
        self.cbAllPlotType.setItemText(1, _translate("Form", "Raw data", None))
        self.lineEdit_10.setText(_translate("Form", "X axis", None))
        self.cbAllXAxis.setItemText(0, _translate("Form", "Time", None))
        self.cbAllXAxis.setItemText(1, _translate("Form", "Voltage", None))
        self.cbAllXAxis.setItemText(2, _translate("Form", "Current", None))
        self.cbAllXAxis.setItemText(3, _translate("Form", "Vsource", None))
        self.lineEdit_9.setText(_translate("Form", "Y axis", None))
        self.cbAllYAxis.setItemText(0, _translate("Form", "Time", None))
        self.cbAllYAxis.setItemText(1, _translate("Form", "Voltage", None))
        self.cbAllYAxis.setItemText(2, _translate("Form", "Current", None))
        self.cbAllYAxis.setItemText(3, _translate("Form", "Vsource", None))
        self.ckAllPlotAsc.setText(_translate("Form", "Plot ascending", None))
        self.ckAllPlotDesc.setText(_translate("Form", "Plot descending", None))
        self.ckAllUpdate.setText(_translate("Form", "Update plots", None))
        self.ckAllHideZero.setText(_translate("Form", "Hide 0V data", None))
        self.lineEdit_11.setText(_translate("Form", "Plot", None))
        self.lineEdit_12.setText(_translate("Form", "Plot update interval (s)", None))
        self.ckActiveUpdate.setText(_translate("Form", "Update plots", None))
        self.lineEdit_13.setText(_translate("Form", "Plot update interval (s)", None))
        self.lineEdit.setText(_translate("Form", "Module ID", None))
        self.leModuleReady.setPlaceholderText(_translate("Form", "Module ready for IV?", None))
        self.leModuleExists.setPlaceholderText(_translate("Form", "Module exists?", None))
        self.pushButton.setText(_translate("Form", "go to", None))
        self.lineEdit_2.setText(_translate("Form", "Keithley COM port", None))
        self.cbKeithleyPort.setItemText(0, _translate("Form", "none", None))
        self.pushButton_2.setText(_translate("Form", "Refresh COM port list", None))
        self.pbKeithleyQuery.setToolTip(_translate("Form", "Queries *IDN?", None))
        self.pbKeithleyQuery.setText(_translate("Form", "Query", None))
        self.lineEdit_3.setText(_translate("Form", "Keithley baud rate", None))
        self.cbKeithleyBaud.setItemText(0, _translate("Form", "9600", None))
        self.leKeithleyQueryResponse.setToolTip(_translate("Form", "Response to *IDN? query", None))
        self.leKeithleyQueryResponse.setPlaceholderText(_translate("Form", "Response", None))
        self.cbArduinoPort.setItemText(0, _translate("Form", "none", None))
        self.pbArduinoQuery.setToolTip(_translate("Form", "Queries *IDN?", None))
        self.pbArduinoQuery.setText(_translate("Form", "Query", None))
        self.leArduinoQueryResponse.setToolTip(_translate("Form", "Response to *IDN? query", None))
        self.leArduinoQueryResponse.setPlaceholderText(_translate("Form", "Response", None))
        self.lineEdit_4.setText(_translate("Form", "Arduino COM port", None))
        self.cbArduinoBaud.setItemText(0, _translate("Form", "9600", None))
        self.lineEdit_5.setText(_translate("Form", "Arduino baud rate", None))
        self.lineEdit_6.setText(_translate("Form", "Current read interval (s)", None))
        self.lineEdit_7.setText(_translate("Form", "Ascending step size (V)", None))
        self.lineEdit_8.setText(_translate("Form", "Ascending step interval (s)", None))
        self.lineEdit_14.setText(_translate("Form", "Decending step interval (s)", None))
        self.lineEdit_15.setText(_translate("Form", "Decending step size (V)", None))
        self.lineEdit_16.setText(_translate("Form", "Target voltage (V)", None))
        self.radioButton.setText(_translate("Form", "Wait at target for (s)", None))
        self.radioButton_2.setText(_translate("Form", "Wait at target for user", None))
        self.checkBox.setText(_translate("Form", "Stop if  I(uA)         > ", None))
        self.checkBox_2.setText(_translate("Form", "Stop if  P(mW)       > ", None))
        self.checkBox_3.setText(_translate("Form", "Descend if  P(mW) > ", None))
        self.checkBox_4.setText(_translate("Form", "Descend if  I(uA)   > ", None))
        self.pushButton_3.setText(_translate("Form", "Start", None))
        self.pushButton_4.setText(_translate("Form", "Pause", None))
        self.pushButton_5.setText(_translate("Form", "Resume", None))
        self.pushButton_6.setText(_translate("Form", "Begin descent", None))
        self.lineEdit_17.setPlaceholderText(_translate("Form", "stage", None))
        self.lineEdit_18.setPlaceholderText(_translate("Form", "activity", None))
        self.progressBar_2.setFormat(_translate("Form", "%v/%m (%p%)", None))
        self.lineEdit_19.setText(_translate("Form", "Bias voltage (V)", None))
        self.lineEdit_20.setText(_translate("Form", "Current (uA)", None))
        self.lineEdit_21.setText(_translate("Form", "Temperature (F)", None))
        self.lineEdit_22.setText(_translate("Form", "Humidity (%)", None))
        self.lineEdit_23.setPlaceholderText(_translate("Form", "bias voltage", None))
        self.lineEdit_24.setPlaceholderText(_translate("Form", "current", None))
        self.lineEdit_25.setPlaceholderText(_translate("Form", "humidity", None))
        self.lineEdit_26.setPlaceholderText(_translate("Form", "temperature", None))
        self.plainTextEdit.setPlainText(_translate("Form", " 0:00:00 test statement\n"
"10:00:00 test statement 2\n"
"22:14:07 test statement 3\n"
"23:59:59 this string is too long for a single line\n"
"         so we will split it and add spaces\n"
"____0____1____2____3____4____5____6____7____8____9____a____b____c____d____e____f____\n"
"\n"
"display only time in console (this)\n"
"save date and time (+unix time?) in data file footer", None))
        self.pushButton_7.setText(_translate("Form", "End routine", None))
        self.plainTextEdit_2.setPlaceholderText(_translate("Form", "write notes here", None))
        self.lineEdit_27.setText(_translate("Form", "Notes (saved with IV data file when routine is ended)", None))

