# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 705)
        self.lwPartList = QtWidgets.QListWidget(Form)
        self.lwPartList.setGeometry(QtCore.QRect(390, 60, 281, 41))
        self.lwPartList.setObjectName("lwPartList")
        self.pbGoToPart = QtWidgets.QPushButton(Form)
        self.pbGoToPart.setGeometry(QtCore.QRect(500, 520, 171, 21))
        self.pbGoToPart.setObjectName("pbGoToPart")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(390, 40, 191, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 191, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setEnabled(False)
        self.lineEdit_8.setGeometry(QtCore.QRect(30, 220, 111, 20))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setEnabled(False)
        self.lineEdit_9.setGeometry(QtCore.QRect(30, 200, 111, 20))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setEnabled(False)
        self.lineEdit_10.setGeometry(QtCore.QRect(30, 180, 111, 20))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pbSearch = QtWidgets.QPushButton(Form)
        self.pbSearch.setGeometry(QtCore.QRect(100, 510, 71, 21))
        self.pbSearch.setObjectName("pbSearch")
        self.pbSearchBType = QtWidgets.QPushButton(Form)
        self.pbSearchBType.setEnabled(False)
        self.pbSearchBType.setGeometry(QtCore.QRect(270, 180, 71, 21))
        self.pbSearchBType.setObjectName("pbSearchBType")
        self.pbSearchSType = QtWidgets.QPushButton(Form)
        self.pbSearchSType.setEnabled(False)
        self.pbSearchSType.setGeometry(QtCore.QRect(270, 200, 71, 21))
        self.pbSearchSType.setObjectName("pbSearchSType")
        self.pbSearchPType = QtWidgets.QPushButton(Form)
        self.pbSearchPType.setEnabled(False)
        self.pbSearchPType.setGeometry(QtCore.QRect(270, 220, 71, 21))
        self.pbSearchPType.setObjectName("pbSearchPType")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setEnabled(False)
        self.lineEdit_12.setGeometry(QtCore.QRect(30, 120, 111, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.dReceived = QtWidgets.QDateEdit(Form)
        self.dReceived.setEnabled(False)
        self.dReceived.setGeometry(QtCore.QRect(140, 120, 131, 21))
        self.dReceived.setObjectName("dReceived")
        self.pbSearchRecDate = QtWidgets.QPushButton(Form)
        self.pbSearchRecDate.setEnabled(False)
        self.pbSearchRecDate.setGeometry(QtCore.QRect(270, 120, 71, 21))
        self.pbSearchRecDate.setObjectName("pbSearchRecDate")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 191, 16))
        self.label_5.setObjectName("label_5")
        self.cbSType = QtWidgets.QComboBox(Form)
        self.cbSType.setEnabled(False)
        self.cbSType.setGeometry(QtCore.QRect(140, 200, 131, 21))
        self.cbSType.setObjectName("cbSType")
        self.cbSType.addItem("")
        self.cbSType.addItem("")
        self.cbSType.addItem("")
        self.cbSType.addItem("")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(450, 490, 221, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.lineEdit_26 = QtWidgets.QLineEdit(Form)
        self.lineEdit_26.setGeometry(QtCore.QRect(390, 490, 61, 20))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.cbBType = QtWidgets.QComboBox(Form)
        self.cbBType.setEnabled(False)
        self.cbBType.setGeometry(QtCore.QRect(140, 180, 131, 21))
        self.cbBType.setObjectName("cbBType")
        self.cbBType.addItem("")
        self.cbBType.addItem("")
        self.cbPType = QtWidgets.QComboBox(Form)
        self.cbPType.setEnabled(False)
        self.cbPType.setGeometry(QtCore.QRect(140, 220, 131, 21))
        self.cbPType.setCurrentText("")
        self.cbPType.setObjectName("cbPType")
        self.cbPType.addItem("")
        self.cbPType.addItem("")
        self.cbPType.addItem("")
        self.cbPType.addItem("")
        self.cbPType.addItem("")
        self.cbPType.addItem("")
        self.cbPType.addItem("")
        self.pbClearResults = QtWidgets.QPushButton(Form)
        self.pbClearResults.setGeometry(QtCore.QRect(390, 520, 101, 21))
        self.pbClearResults.setObjectName("pbClearResults")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(80, 600, 351, 16))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 340, 111, 16))
        self.label_3.setObjectName("label_3")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(150, 360, 131, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(30, 360, 121, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.cbShape = QtWidgets.QComboBox(Form)
        self.cbShape.setGeometry(QtCore.QRect(150, 380, 131, 21))
        self.cbShape.setObjectName("cbShape")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(30, 380, 121, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 280, 111, 16))
        self.label_7.setObjectName("label_7")
        self.cbPartType = QtWidgets.QComboBox(Form)
        self.cbPartType.setGeometry(QtCore.QRect(30, 300, 121, 21))
        self.cbPartType.setObjectName("cbPartType")
        self.cbPartType.addItem("")
        self.cbPartType.addItem("")
        self.cbPartType.addItem("")
        self.cbPartType.addItem("")
        self.cbPartType.addItem("")
        self.cbMaterial = QtWidgets.QComboBox(Form)
        self.cbMaterial.setGeometry(QtCore.QRect(150, 400, 131, 21))
        self.cbMaterial.setObjectName("cbMaterial")
        self.cbMaterial.addItem("")
        self.cbMaterial.addItem("")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(30, 400, 121, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.cbChannelDensity = QtWidgets.QComboBox(Form)
        self.cbChannelDensity.setGeometry(QtCore.QRect(150, 440, 131, 21))
        self.cbChannelDensity.setObjectName("cbChannelDensity")
        self.cbChannelDensity.addItem("")
        self.cbChannelDensity.addItem("")
        self.cbThickness = QtWidgets.QComboBox(Form)
        self.cbThickness.setGeometry(QtCore.QRect(150, 420, 131, 21))
        self.cbThickness.setObjectName("cbThickness")
        self.cbThickness.addItem("")
        self.cbThickness.addItem("")
        self.cbThickness.addItem("")
        self.cbThickness.addItem("")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(30, 420, 121, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(30, 440, 121, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.dCreated = QtWidgets.QDateEdit(Form)
        self.dCreated.setEnabled(True)
        self.dCreated.setGeometry(QtCore.QRect(150, 480, 81, 21))
        self.dCreated.setCalendarPopup(True)
        self.dCreated.setDate(QtCore.QDate(2021, 1, 1))
        self.dCreated.setObjectName("dCreated")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(30, 480, 121, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.cbPCBType = QtWidgets.QComboBox(Form)
        self.cbPCBType.setGeometry(QtCore.QRect(150, 460, 131, 21))
        self.cbPCBType.setCurrentText("")
        self.cbPCBType.setObjectName("cbPCBType")
        self.cbPCBType.addItem("")
        self.cbPCBType.addItem("")
        self.cbPCBType.addItem("")
        self.cbPCBType.addItem("")
        self.cbPCBType.addItem("")
        self.cbPCBType.addItem("")
        self.cbPCBType.addItem("")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(30, 460, 121, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")

        self.retranslateUi(Form)
        self.cbSType.setCurrentIndex(-1)
        self.cbBType.setCurrentIndex(-1)
        self.cbPType.setCurrentIndex(-1)
        self.cbInstitution.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        self.cbPartType.setCurrentIndex(0)
        self.cbMaterial.setCurrentIndex(-1)
        self.cbChannelDensity.setCurrentIndex(-1)
        self.cbThickness.setCurrentIndex(-1)
        self.cbPCBType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbGoToPart.setText(_translate("Form", "go to selected item"))
        self.label.setText(_translate("Form", "Search results:"))
        self.label_2.setText(_translate("Form", "Search by type:"))
        self.lineEdit_8.setText(_translate("Form", "PCB type"))
        self.lineEdit_9.setText(_translate("Form", "Sensor type"))
        self.lineEdit_10.setText(_translate("Form", "Baseplate type"))
        self.pbSearch.setText(_translate("Form", "search"))
        self.pbSearchBType.setText(_translate("Form", "search"))
        self.pbSearchSType.setText(_translate("Form", "search"))
        self.pbSearchPType.setText(_translate("Form", "search"))
        self.lineEdit_12.setText(_translate("Form", "Date received"))
        self.pbSearchRecDate.setText(_translate("Form", "search"))
        self.label_5.setText(_translate("Form", "Search shipments:"))
        self.cbSType.setItemText(0, _translate("Form", "100 um"))
        self.cbSType.setItemText(1, _translate("Form", "200 um"))
        self.cbSType.setItemText(2, _translate("Form", "300 um"))
        self.cbSType.setItemText(3, _translate("Form", "500 um"))
        self.lineEdit_26.setText(_translate("Form", "Status:"))
        self.cbBType.setItemText(0, _translate("Form", "CuW"))
        self.cbBType.setItemText(1, _translate("Form", "PCB"))
        self.cbPType.setItemText(0, _translate("Form", "HGCROCV1"))
        self.cbPType.setItemText(1, _translate("Form", "HGCROCV2"))
        self.cbPType.setItemText(2, _translate("Form", "HGCROCV3"))
        self.cbPType.setItemText(3, _translate("Form", "SKIROCV1"))
        self.cbPType.setItemText(4, _translate("Form", "SKIROCV2"))
        self.cbPType.setItemText(5, _translate("Form", "SKIROCV3"))
        self.cbPType.setItemText(6, _translate("Form", "HGCROC dummy"))
        self.pbClearResults.setText(_translate("Form", "clear results"))
        self.label_6.setText(_translate("Form", "NOTE:  Currently works for locally stored parts only"))
        self.label_3.setText(_translate("Form", "Part attributes:"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "HEPHY"))
        self.cbInstitution.setItemText(5, _translate("Form", "HPK"))
        self.lineEdit_13.setText(_translate("Form", "Institution"))
        self.cbShape.setItemText(0, _translate("Form", "full"))
        self.cbShape.setItemText(1, _translate("Form", "half"))
        self.cbShape.setItemText(2, _translate("Form", "five"))
        self.cbShape.setItemText(3, _translate("Form", "three"))
        self.cbShape.setItemText(4, _translate("Form", "semi"))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)"))
        self.cbShape.setItemText(6, _translate("Form", "choptwo"))
        self.lineEdit_14.setText(_translate("Form", "Geometry"))
        self.label_7.setText(_translate("Form", "Part type:"))
        self.cbPartType.setItemText(0, _translate("Form", "baseplate"))
        self.cbPartType.setItemText(1, _translate("Form", "sensor"))
        self.cbPartType.setItemText(2, _translate("Form", "pcb"))
        self.cbPartType.setItemText(3, _translate("Form", "protomodule"))
        self.cbPartType.setItemText(4, _translate("Form", "module"))
        self.cbMaterial.setItemText(0, _translate("Form", "CuW"))
        self.cbMaterial.setItemText(1, _translate("Form", "PCB"))
        self.lineEdit_15.setText(_translate("Form", "Material"))
        self.cbChannelDensity.setItemText(0, _translate("Form", "HD"))
        self.cbChannelDensity.setItemText(1, _translate("Form", "LD"))
        self.cbThickness.setItemText(0, _translate("Form", "100 um"))
        self.cbThickness.setItemText(1, _translate("Form", "200 um"))
        self.cbThickness.setItemText(2, _translate("Form", "300 um"))
        self.cbThickness.setItemText(3, _translate("Form", "500 um"))
        self.lineEdit_16.setText(_translate("Form", "Thickness"))
        self.lineEdit_17.setText(_translate("Form", "Resolution type"))
        self.lineEdit_18.setText(_translate("Form", "Creation date"))
        self.cbPCBType.setItemText(0, _translate("Form", "HGCROCV1"))
        self.cbPCBType.setItemText(1, _translate("Form", "HGCROCV2"))
        self.cbPCBType.setItemText(2, _translate("Form", "HGCROCV3"))
        self.cbPCBType.setItemText(3, _translate("Form", "SKIROCV1"))
        self.cbPCBType.setItemText(4, _translate("Form", "SKIROCV2"))
        self.cbPCBType.setItemText(5, _translate("Form", "SKIROCV3"))
        self.cbPCBType.setItemText(6, _translate("Form", "HGCROC dummy"))
        self.lineEdit_19.setText(_translate("Form", "PCB type"))

