# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shipment.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 211, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pbSensorSave = QtGui.QPushButton(self.frame_3)
        self.pbSensorSave.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.pbSensorSave.setObjectName(_fromUtf8("pbSensorSave"))
        self.pbSensorEdit = QtGui.QPushButton(self.frame_3)
        self.pbSensorEdit.setGeometry(QtCore.QRect(0, 50, 71, 21))
        self.pbSensorEdit.setObjectName(_fromUtf8("pbSensorEdit"))
        self.pbSensorCancel = QtGui.QPushButton(self.frame_3)
        self.pbSensorCancel.setGeometry(QtCore.QRect(150, 30, 61, 21))
        self.pbSensorCancel.setObjectName(_fromUtf8("pbSensorCancel"))
        self.lineEdit = QtGui.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(1, 1, 80, 19))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pbSensorNew = QtGui.QPushButton(self.frame_3)
        self.pbSensorNew.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.pbSensorNew.setObjectName(_fromUtf8("pbSensorNew"))
        self.sbSensorID = QtGui.QSpinBox(self.frame_3)
        self.sbSensorID.setGeometry(QtCore.QRect(80, 1, 130, 19))
        self.sbSensorID.setMaximum(2147483647)
        self.sbSensorID.setObjectName(_fromUtf8("sbSensorID"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 150, 51, 20))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 170, 51, 20))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.leSender = QtGui.QLineEdit(Form)
        self.leSender.setGeometry(QtCore.QRect(60, 150, 131, 20))
        self.leSender.setObjectName(_fromUtf8("leSender"))
        self.leReceiver = QtGui.QLineEdit(Form)
        self.leReceiver.setGeometry(QtCore.QRect(60, 170, 131, 20))
        self.leReceiver.setObjectName(_fromUtf8("leReceiver"))
        self.dSent = QtGui.QDateEdit(Form)
        self.dSent.setGeometry(QtCore.QRect(340, 150, 111, 21))
        self.dSent.setObjectName(_fromUtf8("dSent"))
        self.pbSentNow = QtGui.QPushButton(Form)
        self.pbSentNow.setGeometry(QtCore.QRect(450, 150, 75, 21))
        self.pbSentNow.setObjectName(_fromUtf8("pbSentNow"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 150, 111, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 170, 111, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pbReceivedNow = QtGui.QPushButton(Form)
        self.pbReceivedNow.setGeometry(QtCore.QRect(450, 170, 75, 21))
        self.pbReceivedNow.setObjectName(_fromUtf8("pbReceivedNow"))
        self.dReceived = QtGui.QDateEdit(Form)
        self.dReceived.setGeometry(QtCore.QRect(340, 170, 111, 21))
        self.dReceived.setObjectName(_fromUtf8("dReceived"))
        self.comboBox = QtGui.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(60, 550, 121, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 120, 81, 20))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.comboBox_2 = QtGui.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 120, 101, 21))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 550, 51, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 550, 21, 20))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.sbPartID = QtGui.QSpinBox(Form)
        self.sbPartID.setGeometry(QtCore.QRect(200, 550, 71, 21))
        self.sbPartID.setMinimum(-1)
        self.sbPartID.setMaximum(2147483647)
        self.sbPartID.setObjectName(_fromUtf8("sbPartID"))
        self.listWidget = QtGui.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 220, 511, 331))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 550, 111, 21))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 200, 191, 16))
        self.label.setObjectName(_fromUtf8("label"))

        self.retranslateUi(Form)
        self.comboBox_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pbSensorSave.setText(_translate("Form", "Save", None))
        self.pbSensorEdit.setText(_translate("Form", "Edit", None))
        self.pbSensorCancel.setText(_translate("Form", "Cancel", None))
        self.lineEdit.setText(_translate("Form", "Shipment ID", None))
        self.pbSensorNew.setText(_translate("Form", "New", None))
        self.lineEdit_2.setText(_translate("Form", "Sender", None))
        self.lineEdit_3.setText(_translate("Form", "Receiver", None))
        self.pbSentNow.setText(_translate("Form", "set to today", None))
        self.lineEdit_4.setText(_translate("Form", "Date sent", None))
        self.lineEdit_5.setText(_translate("Form", "Date Received", None))
        self.pbReceivedNow.setText(_translate("Form", "set to today", None))
        self.comboBox.setItemText(0, _translate("Form", "module", None))
        self.comboBox.setItemText(1, _translate("Form", "baseplate", None))
        self.comboBox.setItemText(2, _translate("Form", "sensor", None))
        self.comboBox.setItemText(3, _translate("Form", "pcb", None))
        self.comboBox.setItemText(4, _translate("Form", "protomodule", None))
        self.lineEdit_7.setText(_translate("Form", "Shipment type", None))
        self.comboBox_2.setItemText(0, _translate("Form", "sending parts", None))
        self.comboBox_2.setItemText(1, _translate("Form", "receiving parts", None))
        self.pushButton.setText(_translate("Form", "add", None))
        self.lineEdit_6.setText(_translate("Form", "ID", None))
        self.pushButton_2.setText(_translate("Form", "delete selected", None))
        self.label.setText(_translate("Form", "parts in shipment", None))

