# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_PCB.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 230, 131, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 370, 131, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 390, 131, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 290, 131, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 270, 131, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 250, 131, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 440, 81, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.sbPCBID = QtGui.QSpinBox(Form)
        self.sbPCBID.setGeometry(QtCore.QRect(90, 10, 131, 21))
        self.sbPCBID.setMaximum(2147483647)
        self.sbPCBID.setObjectName(_fromUtf8("sbPCBID"))
        self.leIdentifier = QtGui.QLineEdit(Form)
        self.leIdentifier.setGeometry(QtCore.QRect(140, 230, 81, 21))
        self.leIdentifier.setText(_fromUtf8(""))
        self.leIdentifier.setReadOnly(True)
        self.leIdentifier.setObjectName(_fromUtf8("leIdentifier"))
        self.leManufacturer = QtGui.QLineEdit(Form)
        self.leManufacturer.setGeometry(QtCore.QRect(140, 250, 81, 21))
        self.leManufacturer.setText(_fromUtf8(""))
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName(_fromUtf8("leManufacturer"))
        self.pbGoModule = QtGui.QPushButton(Form)
        self.pbGoModule.setGeometry(QtCore.QRect(170, 440, 51, 21))
        self.pbGoModule.setObjectName(_fromUtf8("pbGoModule"))
        self.pbPCBCancel = QtGui.QPushButton(Form)
        self.pbPCBCancel.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.pbPCBCancel.setObjectName(_fromUtf8("pbPCBCancel"))
        self.pbPCBEdit = QtGui.QPushButton(Form)
        self.pbPCBEdit.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.pbPCBEdit.setObjectName(_fromUtf8("pbPCBEdit"))
        self.pbPCBNew = QtGui.QPushButton(Form)
        self.pbPCBNew.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.pbPCBNew.setObjectName(_fromUtf8("pbPCBNew"))
        self.pbPCBSave = QtGui.QPushButton(Form)
        self.pbPCBSave.setGeometry(QtCore.QRect(90, 40, 61, 21))
        self.pbPCBSave.setObjectName(_fromUtf8("pbPCBSave"))
        self.dsbThickness = QtGui.QDoubleSpinBox(Form)
        self.dsbThickness.setGeometry(QtCore.QRect(140, 370, 81, 21))
        self.dsbThickness.setReadOnly(True)
        self.dsbThickness.setMinimum(-1.0)
        self.dsbThickness.setMaximum(2147483647.0)
        self.dsbThickness.setSingleStep(0.1)
        self.dsbThickness.setObjectName(_fromUtf8("dsbThickness"))
        self.sbChannels = QtGui.QSpinBox(Form)
        self.sbChannels.setGeometry(QtCore.QRect(140, 270, 81, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName(_fromUtf8("sbChannels"))
        self.dsbFlatness = QtGui.QDoubleSpinBox(Form)
        self.dsbFlatness.setGeometry(QtCore.QRect(140, 390, 81, 21))
        self.dsbFlatness.setReadOnly(True)
        self.dsbFlatness.setMinimum(-1.0)
        self.dsbFlatness.setMaximum(2147483647.0)
        self.dsbFlatness.setSingleStep(0.05)
        self.dsbFlatness.setObjectName(_fromUtf8("dsbFlatness"))
        self.dsbSize = QtGui.QDoubleSpinBox(Form)
        self.dsbSize.setGeometry(QtCore.QRect(140, 290, 81, 21))
        self.dsbSize.setReadOnly(True)
        self.dsbSize.setMinimum(-1.0)
        self.dsbSize.setMaximum(2147483647.0)
        self.dsbSize.setObjectName(_fromUtf8("dsbSize"))
        self.sbModule = QtGui.QSpinBox(Form)
        self.sbModule.setGeometry(QtCore.QRect(90, 440, 81, 21))
        self.sbModule.setReadOnly(True)
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName(_fromUtf8("sbModule"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 310, 131, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 330, 131, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 350, 131, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.sbRotation = QtGui.QSpinBox(Form)
        self.sbRotation.setGeometry(QtCore.QRect(140, 350, 81, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName(_fromUtf8("sbRotation"))
        self.cbShape = QtGui.QComboBox(Form)
        self.cbShape.setGeometry(QtCore.QRect(140, 310, 81, 21))
        self.cbShape.setObjectName(_fromUtf8("cbShape"))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbChirality = QtGui.QComboBox(Form)
        self.cbChirality.setGeometry(QtCore.QRect(140, 330, 81, 21))
        self.cbChirality.setObjectName(_fromUtf8("cbChirality"))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.leIdentifier_2 = QtGui.QLineEdit(Form)
        self.leIdentifier_2.setGeometry(QtCore.QRect(100, 90, 121, 21))
        self.leIdentifier_2.setText(_fromUtf8(""))
        self.leIdentifier_2.setReadOnly(True)
        self.leIdentifier_2.setObjectName(_fromUtf8("leIdentifier_2"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.listWidget = QtGui.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 130, 211, 91))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 110, 121, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 420, 81, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.sbStepPcb = QtGui.QSpinBox(Form)
        self.sbStepPcb.setGeometry(QtCore.QRect(90, 420, 81, 21))
        self.sbStepPcb.setReadOnly(True)
        self.sbStepPcb.setMinimum(-1)
        self.sbStepPcb.setMaximum(2147483647)
        self.sbStepPcb.setObjectName(_fromUtf8("sbStepPcb"))
        self.pbGoStepPcb = QtGui.QPushButton(Form)
        self.pbGoStepPcb.setGeometry(QtCore.QRect(170, 420, 51, 21))
        self.pbGoStepPcb.setObjectName(_fromUtf8("pbGoStepPcb"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(230, 40, 251, 241))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pbAddComment = QtGui.QPushButton(self.frame)
        self.pbAddComment.setGeometry(QtCore.QRect(0, 220, 81, 21))
        self.pbAddComment.setObjectName(_fromUtf8("pbAddComment"))
        self.pteWriteComment = QtGui.QPlainTextEdit(self.frame)
        self.pteWriteComment.setGeometry(QtCore.QRect(0, 150, 251, 71))
        self.pteWriteComment.setObjectName(_fromUtf8("pteWriteComment"))
        self.lineEdit_14 = QtGui.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(0, 0, 121, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.listComments = QtGui.QListWidget(self.frame)
        self.listComments.setGeometry(QtCore.QRect(0, 20, 251, 121))
        self.listComments.setObjectName(_fromUtf8("listComments"))
        self.pbDeleteComment = QtGui.QPushButton(self.frame)
        self.pbDeleteComment.setGeometry(QtCore.QRect(120, 0, 131, 21))
        self.pbDeleteComment.setObjectName(_fromUtf8("pbDeleteComment"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 470, 211, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.listDaqData = QtGui.QListWidget(Form)
        self.listDaqData.setGeometry(QtCore.QRect(10, 490, 211, 131))
        self.listDaqData.setObjectName(_fromUtf8("listDaqData"))
        self.pbAddToPlotter = QtGui.QPushButton(Form)
        self.pbAddToPlotter.setGeometry(QtCore.QRect(10, 620, 121, 21))
        self.pbAddToPlotter.setObjectName(_fromUtf8("pbAddToPlotter"))
        self.pbGoPlotter = QtGui.QPushButton(Form)
        self.pbGoPlotter.setGeometry(QtCore.QRect(140, 620, 81, 21))
        self.pbGoPlotter.setObjectName(_fromUtf8("pbGoPlotter"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "PCB ID", None))
        self.lineEdit_2.setText(_translate("Form", "Identifier", None))
        self.lineEdit_3.setText(_translate("Form", "Thickness (mm)", None))
        self.lineEdit_4.setText(_translate("Form", "Flatness (mm)", None))
        self.lineEdit_5.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_6.setText(_translate("Form", "Channels", None))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer", None))
        self.lineEdit_8.setText(_translate("Form", "On module", None))
        self.pbGoModule.setText(_translate("Form", "Go to", None))
        self.pbPCBCancel.setText(_translate("Form", "Cancel", None))
        self.pbPCBEdit.setText(_translate("Form", "Edit", None))
        self.pbPCBNew.setText(_translate("Form", "New", None))
        self.pbPCBSave.setText(_translate("Form", "Save", None))
        self.lineEdit_15.setText(_translate("Form", "Shape", None))
        self.lineEdit_13.setText(_translate("Form", "Chirality", None))
        self.lineEdit_16.setText(_translate("Form", "Rotation", None))
        self.cbShape.setItemText(0, _translate("Form", "full", None))
        self.cbShape.setItemText(1, _translate("Form", "half", None))
        self.cbShape.setItemText(2, _translate("Form", "...", None))
        self.cbChirality.setItemText(0, _translate("Form", "achiral", None))
        self.cbChirality.setItemText(1, _translate("Form", "left", None))
        self.cbChirality.setItemText(2, _translate("Form", "right", None))
        self.lineEdit_11.setText(_translate("Form", "location", None))
        self.listWidget.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "541 (2019-06-04) (UCSB to CERN)", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form", "go to selected", None))
        self.lineEdit_10.setText(_translate("Form", "shipments", None))
        self.lineEdit_9.setText(_translate("Form", "PCB step", None))
        self.pbGoStepPcb.setText(_translate("Form", "Go to", None))
        self.pbAddComment.setText(_translate("Form", "add comment", None))
        self.pteWriteComment.setPlainText(_translate("Form", "to add:\n"
"daq\n"
"daq_ok\n"
"inspection", None))
        self.lineEdit_14.setText(_translate("Form", "Comments", None))
        self.pbDeleteComment.setText(_translate("Form", "delete selected", None))
        self.lineEdit_12.setText(_translate("Form", "datasets", None))
        self.pbAddToPlotter.setText(_translate("Form", "add selected to plotter", None))
        self.pbGoPlotter.setText(_translate("Form", "go to plotter", None))

