# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_baseplate.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(530, 40, 481, 411))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("pages_ui/baseplate_frame_80.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.dsbC4 = QtGui.QDoubleSpinBox(Form)
        self.dsbC4.setEnabled(False)
        self.dsbC4.setGeometry(QtCore.QRect(650, 400, 62, 22))
        self.dsbC4.setDecimals(2)
        self.dsbC4.setMinimum(-8192.0)
        self.dsbC4.setMaximum(8191.0)
        self.dsbC4.setSingleStep(0.05)
        self.dsbC4.setObjectName(_fromUtf8("dsbC4"))
        self.dsbC5 = QtGui.QDoubleSpinBox(Form)
        self.dsbC5.setEnabled(False)
        self.dsbC5.setGeometry(QtCore.QRect(820, 400, 62, 22))
        self.dsbC5.setDecimals(2)
        self.dsbC5.setMinimum(-8192.0)
        self.dsbC5.setMaximum(8191.0)
        self.dsbC5.setSingleStep(0.05)
        self.dsbC5.setObjectName(_fromUtf8("dsbC5"))
        self.dsbC2 = QtGui.QDoubleSpinBox(Form)
        self.dsbC2.setEnabled(False)
        self.dsbC2.setGeometry(QtCore.QRect(650, 70, 62, 22))
        self.dsbC2.setDecimals(2)
        self.dsbC2.setMinimum(-8192.0)
        self.dsbC2.setMaximum(8191.0)
        self.dsbC2.setSingleStep(0.05)
        self.dsbC2.setObjectName(_fromUtf8("dsbC2"))
        self.dsbC1 = QtGui.QDoubleSpinBox(Form)
        self.dsbC1.setEnabled(False)
        self.dsbC1.setGeometry(QtCore.QRect(820, 70, 62, 22))
        self.dsbC1.setDecimals(2)
        self.dsbC1.setMinimum(-8192.0)
        self.dsbC1.setMaximum(8191.0)
        self.dsbC1.setSingleStep(0.05)
        self.dsbC1.setObjectName(_fromUtf8("dsbC1"))
        self.dsbC0 = QtGui.QDoubleSpinBox(Form)
        self.dsbC0.setEnabled(False)
        self.dsbC0.setGeometry(QtCore.QRect(910, 240, 62, 22))
        self.dsbC0.setDecimals(2)
        self.dsbC0.setMinimum(-8192.0)
        self.dsbC0.setMaximum(8191.0)
        self.dsbC0.setSingleStep(0.05)
        self.dsbC0.setObjectName(_fromUtf8("dsbC0"))
        self.dsbC3 = QtGui.QDoubleSpinBox(Form)
        self.dsbC3.setEnabled(False)
        self.dsbC3.setGeometry(QtCore.QRect(560, 230, 62, 22))
        self.dsbC3.setDecimals(2)
        self.dsbC3.setMinimum(-8192.0)
        self.dsbC3.setMaximum(8191.0)
        self.dsbC3.setSingleStep(0.05)
        self.dsbC3.setObjectName(_fromUtf8("dsbC3"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(700, 240, 131, 20))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.pbEditCornerHeights = QtGui.QPushButton(Form)
        self.pbEditCornerHeights.setGeometry(QtCore.QRect(700, 260, 131, 21))
        self.pbEditCornerHeights.setObjectName(_fromUtf8("pbEditCornerHeights"))
        self.pbSaveCorners = QtGui.QPushButton(Form)
        self.pbSaveCorners.setEnabled(False)
        self.pbSaveCorners.setGeometry(QtCore.QRect(700, 280, 61, 21))
        self.pbSaveCorners.setObjectName(_fromUtf8("pbSaveCorners"))
        self.pbCancelCorners = QtGui.QPushButton(Form)
        self.pbCancelCorners.setEnabled(False)
        self.pbCancelCorners.setGeometry(QtCore.QRect(770, 280, 61, 21))
        self.pbCancelCorners.setObjectName(_fromUtf8("pbCancelCorners"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(230, 40, 251, 241))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pbAddComment = QtGui.QPushButton(self.frame)
        self.pbAddComment.setGeometry(QtCore.QRect(0, 220, 81, 21))
        self.pbAddComment.setObjectName(_fromUtf8("pbAddComment"))
        self.pteWriteComment = QtGui.QPlainTextEdit(self.frame)
        self.pteWriteComment.setGeometry(QtCore.QRect(0, 150, 251, 71))
        self.pteWriteComment.setObjectName(_fromUtf8("pteWriteComment"))
        self.lineEdit_14 = QtGui.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(0, 0, 121, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.listComments = QtGui.QListWidget(self.frame)
        self.listComments.setGeometry(QtCore.QRect(0, 20, 251, 121))
        self.listComments.setObjectName(_fromUtf8("listComments"))
        self.pbDeleteComment = QtGui.QPushButton(self.frame)
        self.pbDeleteComment.setGeometry(QtCore.QRect(120, 0, 131, 21))
        self.pbDeleteComment.setObjectName(_fromUtf8("pbDeleteComment"))
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 211, 71))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pbBaseplateSave = QtGui.QPushButton(self.frame_2)
        self.pbBaseplateSave.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.pbBaseplateSave.setObjectName(_fromUtf8("pbBaseplateSave"))
        self.lineEdit = QtGui.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbBaseplateID = QtGui.QSpinBox(self.frame_2)
        self.sbBaseplateID.setGeometry(QtCore.QRect(80, 0, 131, 21))
        self.sbBaseplateID.setMaximum(65535)
        self.sbBaseplateID.setObjectName(_fromUtf8("sbBaseplateID"))
        self.pbBaseplateCancel = QtGui.QPushButton(self.frame_2)
        self.pbBaseplateCancel.setGeometry(QtCore.QRect(150, 30, 61, 21))
        self.pbBaseplateCancel.setObjectName(_fromUtf8("pbBaseplateCancel"))
        self.pbBaseplateNew = QtGui.QPushButton(self.frame_2)
        self.pbBaseplateNew.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.pbBaseplateNew.setObjectName(_fromUtf8("pbBaseplateNew"))
        self.pbBaseplateEdit = QtGui.QPushButton(self.frame_2)
        self.pbBaseplateEdit.setGeometry(QtCore.QRect(0, 50, 71, 21))
        self.pbBaseplateEdit.setObjectName(_fromUtf8("pbBaseplateEdit"))
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 90, 211, 431))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.cbChirality = QtGui.QComboBox(self.frame_3)
        self.cbChirality.setGeometry(QtCore.QRect(130, 260, 81, 21))
        self.cbChirality.setObjectName(_fromUtf8("cbChirality"))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.pbGoProtomodule = QtGui.QPushButton(self.frame_3)
        self.pbGoProtomodule.setGeometry(QtCore.QRect(170, 350, 41, 21))
        self.pbGoProtomodule.setObjectName(_fromUtf8("pbGoProtomodule"))
        self.lineEdit_18 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(0, 390, 91, 21))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 200, 131, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.sbModule = QtGui.QSpinBox(self.frame_3)
        self.sbModule.setGeometry(QtCore.QRect(90, 370, 81, 21))
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName(_fromUtf8("sbModule"))
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(0, 370, 91, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_19 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_19.setGeometry(QtCore.QRect(0, 410, 91, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.dsbFlatness = QtGui.QDoubleSpinBox(self.frame_3)
        self.dsbFlatness.setGeometry(QtCore.QRect(130, 320, 81, 21))
        self.dsbFlatness.setReadOnly(True)
        self.dsbFlatness.setMinimum(-1.0)
        self.dsbFlatness.setMaximum(2147483647.0)
        self.dsbFlatness.setSingleStep(0.05)
        self.dsbFlatness.setObjectName(_fromUtf8("dsbFlatness"))
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(0, 0, 91, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.cbShape = QtGui.QComboBox(self.frame_3)
        self.cbShape.setGeometry(QtCore.QRect(130, 240, 81, 21))
        self.cbShape.setObjectName(_fromUtf8("cbShape"))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(90, 20, 121, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.leManufacturer = QtGui.QLineEdit(self.frame_3)
        self.leManufacturer.setGeometry(QtCore.QRect(130, 160, 81, 21))
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName(_fromUtf8("leManufacturer"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 140, 131, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.pbGoStepKapton = QtGui.QPushButton(self.frame_3)
        self.pbGoStepKapton.setGeometry(QtCore.QRect(170, 390, 41, 21))
        self.pbGoStepKapton.setObjectName(_fromUtf8("pbGoStepKapton"))
        self.pbGoModule = QtGui.QPushButton(self.frame_3)
        self.pbGoModule.setGeometry(QtCore.QRect(170, 370, 41, 21))
        self.pbGoModule.setObjectName(_fromUtf8("pbGoModule"))
        self.pbGoStepSensor = QtGui.QPushButton(self.frame_3)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(170, 410, 41, 21))
        self.pbGoStepSensor.setObjectName(_fromUtf8("pbGoStepSensor"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 20, 91, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(0, 160, 131, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.sbStepSensor = QtGui.QSpinBox(self.frame_3)
        self.sbStepSensor.setGeometry(QtCore.QRect(90, 410, 81, 21))
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName(_fromUtf8("sbStepSensor"))
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 180, 131, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 320, 131, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.leIdentifier_2 = QtGui.QLineEdit(self.frame_3)
        self.leIdentifier_2.setGeometry(QtCore.QRect(90, 0, 121, 21))
        self.leIdentifier_2.setText(_fromUtf8(""))
        self.leIdentifier_2.setReadOnly(True)
        self.leIdentifier_2.setObjectName(_fromUtf8("leIdentifier_2"))
        self.leMaterial = QtGui.QLineEdit(self.frame_3)
        self.leMaterial.setGeometry(QtCore.QRect(130, 180, 81, 21))
        self.leMaterial.setReadOnly(True)
        self.leMaterial.setObjectName(_fromUtf8("leMaterial"))
        self.dsbSize = QtGui.QDoubleSpinBox(self.frame_3)
        self.dsbSize.setGeometry(QtCore.QRect(130, 220, 81, 21))
        self.dsbSize.setReadOnly(True)
        self.dsbSize.setMinimum(-1.0)
        self.dsbSize.setMaximum(2147483647.0)
        self.dsbSize.setSingleStep(0.05)
        self.dsbSize.setObjectName(_fromUtf8("dsbSize"))
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(0, 300, 131, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.sbProtomodule = QtGui.QSpinBox(self.frame_3)
        self.sbProtomodule.setGeometry(QtCore.QRect(90, 350, 81, 21))
        self.sbProtomodule.setMinimum(-1)
        self.sbProtomodule.setMaximum(2147483647)
        self.sbProtomodule.setObjectName(_fromUtf8("sbProtomodule"))
        self.lineEdit_17 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_17.setGeometry(QtCore.QRect(0, 350, 91, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.listWidget = QtGui.QListWidget(self.frame_3)
        self.listWidget.setGeometry(QtCore.QRect(0, 40, 211, 91))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.lineEdit_13 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(0, 260, 131, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_16 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_16.setGeometry(QtCore.QRect(0, 280, 131, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.cbKaptonType = QtGui.QComboBox(self.frame_3)
        self.cbKaptonType.setGeometry(QtCore.QRect(130, 300, 81, 21))
        self.cbKaptonType.setObjectName(_fromUtf8("cbKaptonType"))
        self.cbKaptonType.addItem(_fromUtf8(""))
        self.cbKaptonType.addItem(_fromUtf8(""))
        self.cbKaptonType.addItem(_fromUtf8(""))
        self.dsbNomThickness = QtGui.QDoubleSpinBox(self.frame_3)
        self.dsbNomThickness.setGeometry(QtCore.QRect(130, 200, 81, 21))
        self.dsbNomThickness.setReadOnly(True)
        self.dsbNomThickness.setMinimum(-1.0)
        self.dsbNomThickness.setMaximum(2147483647.0)
        self.dsbNomThickness.setSingleStep(0.05)
        self.dsbNomThickness.setObjectName(_fromUtf8("dsbNomThickness"))
        self.sbStepKapton = QtGui.QSpinBox(self.frame_3)
        self.sbStepKapton.setGeometry(QtCore.QRect(90, 390, 81, 21))
        self.sbStepKapton.setMinimum(-1)
        self.sbStepKapton.setMaximum(2147483647)
        self.sbStepKapton.setObjectName(_fromUtf8("sbStepKapton"))
        self.leIdentifier = QtGui.QLineEdit(self.frame_3)
        self.leIdentifier.setGeometry(QtCore.QRect(130, 140, 81, 21))
        self.leIdentifier.setReadOnly(True)
        self.leIdentifier.setObjectName(_fromUtf8("leIdentifier"))
        self.lineEdit_15 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(0, 240, 131, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(0, 220, 131, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.sbRotation = QtGui.QSpinBox(self.frame_3)
        self.sbRotation.setGeometry(QtCore.QRect(130, 280, 81, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName(_fromUtf8("sbRotation"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.dsbC4.setToolTip(_translate("Form", "Corner 4", None))
        self.dsbC5.setToolTip(_translate("Form", "Corner 5", None))
        self.dsbC2.setToolTip(_translate("Form", "Corner 2", None))
        self.dsbC1.setToolTip(_translate("Form", "Corner 1", None))
        self.dsbC0.setToolTip(_translate("Form", "Corner 0 (the corner with the oblong hole)", None))
        self.dsbC3.setToolTip(_translate("Form", "Corner 3", None))
        self.lineEdit_9.setText(_translate("Form", "Baseplate corner heights", None))
        self.pbEditCornerHeights.setText(_translate("Form", "Edit corner heights", None))
        self.pbSaveCorners.setText(_translate("Form", "Save", None))
        self.pbCancelCorners.setText(_translate("Form", "Cancel", None))
        self.pbAddComment.setText(_translate("Form", "add comment", None))
        self.pteWriteComment.setPlainText(_translate("Form", "to add:\n"
"kapton_tape_applied\n"
"thickness\n"
"\n"
"check_leakage\n"
"check_surface\n"
"check_edges_firm\n"
"check_glue_spill\n"
"kapton_flatness", None))
        self.lineEdit_14.setText(_translate("Form", "Comments", None))
        self.pbDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbBaseplateSave.setText(_translate("Form", "Save", None))
        self.lineEdit.setText(_translate("Form", "Baseplate ID", None))
        self.pbBaseplateCancel.setText(_translate("Form", "Cancel", None))
        self.pbBaseplateNew.setText(_translate("Form", "New", None))
        self.pbBaseplateEdit.setText(_translate("Form", "Edit", None))
        self.cbChirality.setItemText(0, _translate("Form", "achiral", None))
        self.cbChirality.setItemText(1, _translate("Form", "left", None))
        self.cbChirality.setItemText(2, _translate("Form", "right", None))
        self.pbGoProtomodule.setText(_translate("Form", "Go to", None))
        self.lineEdit_18.setText(_translate("Form", "kapton step", None))
        self.lineEdit_4.setText(_translate("Form", "Nominal Thickness (mm)", None))
        self.lineEdit_8.setText(_translate("Form", "On module", None))
        self.lineEdit_19.setText(_translate("Form", "sensor step", None))
        self.lineEdit_11.setText(_translate("Form", "location", None))
        self.cbShape.setItemText(0, _translate("Form", "full", None))
        self.cbShape.setItemText(1, _translate("Form", "half", None))
        self.cbShape.setItemText(2, _translate("Form", "...", None))
        self.pushButton.setText(_translate("Form", "go to selected", None))
        self.lineEdit_2.setText(_translate("Form", "Identifier", None))
        self.pbGoStepKapton.setText(_translate("Form", "Go to", None))
        self.pbGoModule.setText(_translate("Form", "Go to", None))
        self.pbGoStepSensor.setText(_translate("Form", "Go to", None))
        self.lineEdit_10.setText(_translate("Form", "shipments", None))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer", None))
        self.lineEdit_3.setText(_translate("Form", "Material", None))
        self.lineEdit_5.setToolTip(_translate("Form", "height difference between highest and lowers corners", None))
        self.lineEdit_5.setText(_translate("Form", "Flatness (mm)", None))
        self.lineEdit_12.setText(_translate("Form", "Kapton type", None))
        self.lineEdit_17.setText(_translate("Form", "On protomodule", None))
        self.listWidget.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "541 (2019-06-04) (UCSB to CERN)", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit_13.setText(_translate("Form", "Chirality", None))
        self.lineEdit_16.setText(_translate("Form", "Rotation", None))
        self.cbKaptonType.setItemText(0, _translate("Form", "none", None))
        self.cbKaptonType.setItemText(1, _translate("Form", "single", None))
        self.cbKaptonType.setItemText(2, _translate("Form", "double", None))
        self.lineEdit_15.setText(_translate("Form", "Shape", None))
        self.lineEdit_6.setText(_translate("Form", "Size (inches)", None))

