# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_pcb_step.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.sbModule1 = QtGui.QSpinBox(Form)
        self.sbModule1.setGeometry(QtCore.QRect(440, 140, 71, 22))
        self.sbModule1.setMinimum(-1)
        self.sbModule1.setMaximum(2147483647)
        self.sbModule1.setObjectName(_fromUtf8("sbModule1"))
        self.pbGoModule1 = QtGui.QPushButton(Form)
        self.pbGoModule1.setGeometry(QtCore.QRect(510, 140, 51, 21))
        self.pbGoModule1.setObjectName(_fromUtf8("pbGoModule1"))
        self.pbGoModule2 = QtGui.QPushButton(Form)
        self.pbGoModule2.setGeometry(QtCore.QRect(510, 160, 51, 21))
        self.pbGoModule2.setObjectName(_fromUtf8("pbGoModule2"))
        self.sbModule2 = QtGui.QSpinBox(Form)
        self.sbModule2.setGeometry(QtCore.QRect(440, 160, 71, 22))
        self.sbModule2.setMinimum(-1)
        self.sbModule2.setMaximum(2147483647)
        self.sbModule2.setObjectName(_fromUtf8("sbModule2"))
        self.sbModule3 = QtGui.QSpinBox(Form)
        self.sbModule3.setGeometry(QtCore.QRect(440, 180, 71, 22))
        self.sbModule3.setMinimum(-1)
        self.sbModule3.setMaximum(2147483647)
        self.sbModule3.setObjectName(_fromUtf8("sbModule3"))
        self.pbGoModule3 = QtGui.QPushButton(Form)
        self.pbGoModule3.setGeometry(QtCore.QRect(510, 180, 51, 21))
        self.pbGoModule3.setObjectName(_fromUtf8("pbGoModule3"))
        self.pbGoModule4 = QtGui.QPushButton(Form)
        self.pbGoModule4.setGeometry(QtCore.QRect(510, 240, 51, 21))
        self.pbGoModule4.setObjectName(_fromUtf8("pbGoModule4"))
        self.pbGoModule5 = QtGui.QPushButton(Form)
        self.pbGoModule5.setGeometry(QtCore.QRect(510, 200, 51, 21))
        self.pbGoModule5.setObjectName(_fromUtf8("pbGoModule5"))
        self.sbModule4 = QtGui.QSpinBox(Form)
        self.sbModule4.setGeometry(QtCore.QRect(440, 240, 71, 21))
        self.sbModule4.setMinimum(-1)
        self.sbModule4.setMaximum(2147483647)
        self.sbModule4.setObjectName(_fromUtf8("sbModule4"))
        self.pbGoModule6 = QtGui.QPushButton(Form)
        self.pbGoModule6.setGeometry(QtCore.QRect(510, 220, 51, 21))
        self.pbGoModule6.setObjectName(_fromUtf8("pbGoModule6"))
        self.sbModule5 = QtGui.QSpinBox(Form)
        self.sbModule5.setGeometry(QtCore.QRect(440, 200, 71, 22))
        self.sbModule5.setMinimum(-1)
        self.sbModule5.setMaximum(2147483647)
        self.sbModule5.setObjectName(_fromUtf8("sbModule5"))
        self.sbModule6 = QtGui.QSpinBox(Form)
        self.sbModule6.setGeometry(QtCore.QRect(440, 220, 71, 21))
        self.sbModule6.setMinimum(-1)
        self.sbModule6.setMaximum(2147483647)
        self.sbModule6.setObjectName(_fromUtf8("sbModule6"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 120, 51, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(440, 120, 121, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 140, 51, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 160, 51, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 180, 51, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 200, 51, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 220, 51, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 240, 51, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(600, 220, 91, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(600, 260, 91, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.dtCureStart = QtGui.QDateTimeEdit(Form)
        self.dtCureStart.setGeometry(QtCore.QRect(690, 180, 131, 21))
        self.dtCureStart.setObjectName(_fromUtf8("dtCureStart"))
        self.pbCureStartNow = QtGui.QPushButton(Form)
        self.pbCureStartNow.setGeometry(QtCore.QRect(820, 180, 75, 21))
        self.pbCureStartNow.setObjectName(_fromUtf8("pbCureStartNow"))
        self.leCureTemperature = QtGui.QLineEdit(Form)
        self.leCureTemperature.setGeometry(QtCore.QRect(690, 240, 131, 20))
        self.leCureTemperature.setObjectName(_fromUtf8("leCureTemperature"))
        self.pbEdit = QtGui.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.pbEdit.setObjectName(_fromUtf8("pbEdit"))
        self.leUserPerformed = QtGui.QLineEdit(Form)
        self.leUserPerformed.setGeometry(QtCore.QRect(710, 120, 111, 20))
        self.leUserPerformed.setObjectName(_fromUtf8("leUserPerformed"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(600, 240, 91, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.pbSave = QtGui.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(600, 180, 91, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.sbID = QtGui.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(100, 10, 61, 21))
        self.sbID.setObjectName(_fromUtf8("sbID"))
        self.pbNew = QtGui.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.pbNew.setObjectName(_fromUtf8("pbNew"))
        self.leCureHumidity = QtGui.QLineEdit(Form)
        self.leCureHumidity.setGeometry(QtCore.QRect(690, 260, 131, 21))
        self.leCureHumidity.setObjectName(_fromUtf8("leCureHumidity"))
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 140, 111, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pbDatePerformedNow = QtGui.QPushButton(Form)
        self.pbDatePerformedNow.setGeometry(QtCore.QRect(820, 140, 75, 21))
        self.pbDatePerformedNow.setObjectName(_fromUtf8("pbDatePerformedNow"))
        self.leCureDuration = QtGui.QLineEdit(Form)
        self.leCureDuration.setGeometry(QtCore.QRect(690, 220, 131, 20))
        self.leCureDuration.setObjectName(_fromUtf8("leCureDuration"))
        self.pbCancel = QtGui.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(170, 40, 71, 21))
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.dPerformed = QtGui.QDateEdit(Form)
        self.dPerformed.setGeometry(QtCore.QRect(710, 140, 111, 21))
        self.dPerformed.setObjectName(_fromUtf8("dPerformed"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(600, 120, 111, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.dtCureStop = QtGui.QDateTimeEdit(Form)
        self.dtCureStop.setGeometry(QtCore.QRect(690, 200, 131, 21))
        self.dtCureStop.setObjectName(_fromUtf8("dtCureStop"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(600, 200, 91, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.pbCureStopNow = QtGui.QPushButton(Form)
        self.pbCureStopNow.setGeometry(QtCore.QRect(820, 200, 75, 21))
        self.pbCureStopNow.setObjectName(_fromUtf8("pbCureStopNow"))
        self.sbTool6 = QtGui.QSpinBox(Form)
        self.sbTool6.setGeometry(QtCore.QRect(70, 240, 51, 21))
        self.sbTool6.setMinimum(-1)
        self.sbTool6.setMaximum(2147483647)
        self.sbTool6.setObjectName(_fromUtf8("sbTool6"))
        self.sbTool1 = QtGui.QSpinBox(Form)
        self.sbTool1.setGeometry(QtCore.QRect(70, 140, 51, 22))
        self.sbTool1.setMinimum(-1)
        self.sbTool1.setMaximum(2147483647)
        self.sbTool1.setObjectName(_fromUtf8("sbTool1"))
        self.pbGoTool5 = QtGui.QPushButton(Form)
        self.pbGoTool5.setGeometry(QtCore.QRect(120, 220, 51, 21))
        self.pbGoTool5.setObjectName(_fromUtf8("pbGoTool5"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(70, 120, 101, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.sbTool2 = QtGui.QSpinBox(Form)
        self.sbTool2.setGeometry(QtCore.QRect(70, 160, 51, 22))
        self.sbTool2.setMinimum(-1)
        self.sbTool2.setMaximum(2147483647)
        self.sbTool2.setObjectName(_fromUtf8("sbTool2"))
        self.pbGoTool1 = QtGui.QPushButton(Form)
        self.pbGoTool1.setGeometry(QtCore.QRect(120, 140, 51, 21))
        self.pbGoTool1.setObjectName(_fromUtf8("pbGoTool1"))
        self.pbGoTool4 = QtGui.QPushButton(Form)
        self.pbGoTool4.setGeometry(QtCore.QRect(120, 200, 51, 21))
        self.pbGoTool4.setObjectName(_fromUtf8("pbGoTool4"))
        self.pbGoTool3 = QtGui.QPushButton(Form)
        self.pbGoTool3.setGeometry(QtCore.QRect(120, 180, 51, 21))
        self.pbGoTool3.setObjectName(_fromUtf8("pbGoTool3"))
        self.sbTool3 = QtGui.QSpinBox(Form)
        self.sbTool3.setGeometry(QtCore.QRect(70, 180, 51, 22))
        self.sbTool3.setMinimum(-1)
        self.sbTool3.setMaximum(2147483647)
        self.sbTool3.setObjectName(_fromUtf8("sbTool3"))
        self.pbGoTool6 = QtGui.QPushButton(Form)
        self.pbGoTool6.setGeometry(QtCore.QRect(120, 240, 51, 21))
        self.pbGoTool6.setObjectName(_fromUtf8("pbGoTool6"))
        self.sbTool4 = QtGui.QSpinBox(Form)
        self.sbTool4.setGeometry(QtCore.QRect(70, 200, 51, 22))
        self.sbTool4.setMinimum(-1)
        self.sbTool4.setMaximum(2147483647)
        self.sbTool4.setObjectName(_fromUtf8("sbTool4"))
        self.pbGoTool2 = QtGui.QPushButton(Form)
        self.pbGoTool2.setGeometry(QtCore.QRect(120, 160, 51, 21))
        self.pbGoTool2.setObjectName(_fromUtf8("pbGoTool2"))
        self.sbTool5 = QtGui.QSpinBox(Form)
        self.sbTool5.setGeometry(QtCore.QRect(70, 220, 51, 22))
        self.sbTool5.setMinimum(-1)
        self.sbTool5.setMaximum(2147483647)
        self.sbTool5.setObjectName(_fromUtf8("sbTool5"))
        self.sbPcb1 = QtGui.QSpinBox(Form)
        self.sbPcb1.setGeometry(QtCore.QRect(180, 140, 71, 22))
        self.sbPcb1.setMinimum(-1)
        self.sbPcb1.setMaximum(2147483647)
        self.sbPcb1.setObjectName(_fromUtf8("sbPcb1"))
        self.lineEdit_23 = QtGui.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(180, 120, 121, 20))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.pbGoPcb5 = QtGui.QPushButton(Form)
        self.pbGoPcb5.setGeometry(QtCore.QRect(250, 220, 51, 21))
        self.pbGoPcb5.setObjectName(_fromUtf8("pbGoPcb5"))
        self.sbPcb2 = QtGui.QSpinBox(Form)
        self.sbPcb2.setGeometry(QtCore.QRect(180, 160, 71, 22))
        self.sbPcb2.setMinimum(-1)
        self.sbPcb2.setMaximum(2147483647)
        self.sbPcb2.setObjectName(_fromUtf8("sbPcb2"))
        self.sbProtomodule4 = QtGui.QSpinBox(Form)
        self.sbProtomodule4.setGeometry(QtCore.QRect(310, 200, 71, 22))
        self.sbProtomodule4.setMinimum(-1)
        self.sbProtomodule4.setMaximum(2147483647)
        self.sbProtomodule4.setObjectName(_fromUtf8("sbProtomodule4"))
        self.sbProtomodule2 = QtGui.QSpinBox(Form)
        self.sbProtomodule2.setGeometry(QtCore.QRect(310, 160, 71, 22))
        self.sbProtomodule2.setMinimum(-1)
        self.sbProtomodule2.setMaximum(2147483647)
        self.sbProtomodule2.setObjectName(_fromUtf8("sbProtomodule2"))
        self.sbPcb5 = QtGui.QSpinBox(Form)
        self.sbPcb5.setGeometry(QtCore.QRect(180, 220, 71, 21))
        self.sbPcb5.setMinimum(-1)
        self.sbPcb5.setMaximum(2147483647)
        self.sbPcb5.setObjectName(_fromUtf8("sbPcb5"))
        self.pbGoProtomodule1 = QtGui.QPushButton(Form)
        self.pbGoProtomodule1.setGeometry(QtCore.QRect(380, 140, 51, 21))
        self.pbGoProtomodule1.setObjectName(_fromUtf8("pbGoProtomodule1"))
        self.sbPcb6 = QtGui.QSpinBox(Form)
        self.sbPcb6.setGeometry(QtCore.QRect(180, 240, 71, 21))
        self.sbPcb6.setMinimum(-1)
        self.sbPcb6.setMaximum(2147483647)
        self.sbPcb6.setObjectName(_fromUtf8("sbPcb6"))
        self.pbGoPcb1 = QtGui.QPushButton(Form)
        self.pbGoPcb1.setGeometry(QtCore.QRect(250, 140, 51, 21))
        self.pbGoPcb1.setObjectName(_fromUtf8("pbGoPcb1"))
        self.sbProtomodule5 = QtGui.QSpinBox(Form)
        self.sbProtomodule5.setGeometry(QtCore.QRect(310, 220, 71, 21))
        self.sbProtomodule5.setMinimum(-1)
        self.sbProtomodule5.setMaximum(2147483647)
        self.sbProtomodule5.setObjectName(_fromUtf8("sbProtomodule5"))
        self.pbGoProtomodule6 = QtGui.QPushButton(Form)
        self.pbGoProtomodule6.setGeometry(QtCore.QRect(380, 240, 51, 21))
        self.pbGoProtomodule6.setObjectName(_fromUtf8("pbGoProtomodule6"))
        self.pbGoProtomodule2 = QtGui.QPushButton(Form)
        self.pbGoProtomodule2.setGeometry(QtCore.QRect(380, 160, 51, 21))
        self.pbGoProtomodule2.setObjectName(_fromUtf8("pbGoProtomodule2"))
        self.pbGoProtomodule5 = QtGui.QPushButton(Form)
        self.pbGoProtomodule5.setGeometry(QtCore.QRect(380, 220, 51, 21))
        self.pbGoProtomodule5.setObjectName(_fromUtf8("pbGoProtomodule5"))
        self.pbGoProtomodule3 = QtGui.QPushButton(Form)
        self.pbGoProtomodule3.setGeometry(QtCore.QRect(380, 180, 51, 21))
        self.pbGoProtomodule3.setObjectName(_fromUtf8("pbGoProtomodule3"))
        self.pbGoPcb4 = QtGui.QPushButton(Form)
        self.pbGoPcb4.setGeometry(QtCore.QRect(250, 200, 51, 21))
        self.pbGoPcb4.setObjectName(_fromUtf8("pbGoPcb4"))
        self.pbGoPcb2 = QtGui.QPushButton(Form)
        self.pbGoPcb2.setGeometry(QtCore.QRect(250, 160, 51, 21))
        self.pbGoPcb2.setObjectName(_fromUtf8("pbGoPcb2"))
        self.pbGoPcb3 = QtGui.QPushButton(Form)
        self.pbGoPcb3.setGeometry(QtCore.QRect(250, 180, 51, 21))
        self.pbGoPcb3.setObjectName(_fromUtf8("pbGoPcb3"))
        self.sbProtomodule1 = QtGui.QSpinBox(Form)
        self.sbProtomodule1.setGeometry(QtCore.QRect(310, 140, 71, 22))
        self.sbProtomodule1.setMinimum(-1)
        self.sbProtomodule1.setMaximum(2147483647)
        self.sbProtomodule1.setObjectName(_fromUtf8("sbProtomodule1"))
        self.sbPcb4 = QtGui.QSpinBox(Form)
        self.sbPcb4.setGeometry(QtCore.QRect(180, 200, 71, 22))
        self.sbPcb4.setMinimum(-1)
        self.sbPcb4.setMaximum(2147483647)
        self.sbPcb4.setObjectName(_fromUtf8("sbPcb4"))
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(310, 120, 121, 20))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.sbProtomodule3 = QtGui.QSpinBox(Form)
        self.sbProtomodule3.setGeometry(QtCore.QRect(310, 180, 71, 22))
        self.sbProtomodule3.setMinimum(-1)
        self.sbProtomodule3.setMaximum(2147483647)
        self.sbProtomodule3.setObjectName(_fromUtf8("sbProtomodule3"))
        self.sbPcb3 = QtGui.QSpinBox(Form)
        self.sbPcb3.setGeometry(QtCore.QRect(180, 180, 71, 22))
        self.sbPcb3.setMinimum(-1)
        self.sbPcb3.setMaximum(2147483647)
        self.sbPcb3.setObjectName(_fromUtf8("sbPcb3"))
        self.sbProtomodule6 = QtGui.QSpinBox(Form)
        self.sbProtomodule6.setGeometry(QtCore.QRect(310, 240, 71, 21))
        self.sbProtomodule6.setMinimum(-1)
        self.sbProtomodule6.setMaximum(2147483647)
        self.sbProtomodule6.setObjectName(_fromUtf8("sbProtomodule6"))
        self.pbGoProtomodule4 = QtGui.QPushButton(Form)
        self.pbGoProtomodule4.setGeometry(QtCore.QRect(380, 200, 51, 21))
        self.pbGoProtomodule4.setObjectName(_fromUtf8("pbGoProtomodule4"))
        self.pbGoPcb6 = QtGui.QPushButton(Form)
        self.pbGoPcb6.setGeometry(QtCore.QRect(250, 240, 51, 21))
        self.pbGoPcb6.setObjectName(_fromUtf8("pbGoPcb6"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 310, 121, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.pbGoTrayAssembly = QtGui.QPushButton(Form)
        self.pbGoTrayAssembly.setGeometry(QtCore.QRect(200, 290, 51, 21))
        self.pbGoTrayAssembly.setObjectName(_fromUtf8("pbGoTrayAssembly"))
        self.sbBatchAraldite = QtGui.QSpinBox(Form)
        self.sbBatchAraldite.setGeometry(QtCore.QRect(130, 310, 71, 21))
        self.sbBatchAraldite.setMinimum(-1)
        self.sbBatchAraldite.setMaximum(999999)
        self.sbBatchAraldite.setObjectName(_fromUtf8("sbBatchAraldite"))
        self.pbGoTrayComponent = QtGui.QPushButton(Form)
        self.pbGoTrayComponent.setGeometry(QtCore.QRect(200, 270, 51, 21))
        self.pbGoTrayComponent.setObjectName(_fromUtf8("pbGoTrayComponent"))
        self.sbTrayComponent = QtGui.QSpinBox(Form)
        self.sbTrayComponent.setGeometry(QtCore.QRect(130, 270, 71, 21))
        self.sbTrayComponent.setMinimum(-1)
        self.sbTrayComponent.setMaximum(999999)
        self.sbTrayComponent.setObjectName(_fromUtf8("sbTrayComponent"))
        self.pbGoBatchAraldite = QtGui.QPushButton(Form)
        self.pbGoBatchAraldite.setGeometry(QtCore.QRect(200, 310, 51, 21))
        self.pbGoBatchAraldite.setObjectName(_fromUtf8("pbGoBatchAraldite"))
        self.lineEdit_24 = QtGui.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 270, 121, 21))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 290, 121, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.sbTrayAssembly = QtGui.QSpinBox(Form)
        self.sbTrayAssembly.setGeometry(QtCore.QRect(130, 290, 71, 21))
        self.sbTrayAssembly.setMinimum(-1)
        self.sbTrayAssembly.setMaximum(999999)
        self.sbTrayAssembly.setObjectName(_fromUtf8("sbTrayAssembly"))
        self.lineEdit_26 = QtGui.QLineEdit(Form)
        self.lineEdit_26.setGeometry(QtCore.QRect(10, 520, 51, 20))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.listIssues = QtGui.QListWidget(Form)
        self.listIssues.setGeometry(QtCore.QRect(10, 350, 721, 171))
        self.listIssues.setObjectName(_fromUtf8("listIssues"))
        self.leStatus = QtGui.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(60, 520, 171, 20))
        self.leStatus.setText(_fromUtf8(""))
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName(_fromUtf8("leStatus"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pbGoModule1.setText(_translate("Form", "go to", None))
        self.pbGoModule2.setText(_translate("Form", "go to", None))
        self.pbGoModule3.setText(_translate("Form", "go to", None))
        self.pbGoModule4.setText(_translate("Form", "go to", None))
        self.pbGoModule5.setText(_translate("Form", "go to", None))
        self.pbGoModule6.setText(_translate("Form", "go to", None))
        self.lineEdit_12.setText(_translate("Form", "position", None))
        self.lineEdit_14.setText(_translate("Form", "Module ID assigned", None))
        self.lineEdit_15.setText(_translate("Form", "1", None))
        self.lineEdit_16.setText(_translate("Form", "2", None))
        self.lineEdit_17.setText(_translate("Form", "3", None))
        self.lineEdit_18.setText(_translate("Form", "4", None))
        self.lineEdit_19.setText(_translate("Form", "5", None))
        self.lineEdit_20.setText(_translate("Form", "6", None))
        self.lineEdit_7.setText(_translate("Form", "cure duration", None))
        self.lineEdit_9.setText(_translate("Form", "cure humidity", None))
        self.pbCureStartNow.setText(_translate("Form", "set to now", None))
        self.pbEdit.setText(_translate("Form", "Edit", None))
        self.lineEdit_8.setText(_translate("Form", "cure temperature", None))
        self.pbSave.setText(_translate("Form", "Save", None))
        self.lineEdit_5.setText(_translate("Form", "cure start", None))
        self.pbNew.setText(_translate("Form", "New", None))
        self.lineEdit.setText(_translate("Form", "PCB step ID", None))
        self.lineEdit_3.setText(_translate("Form", "date performed", None))
        self.pbDatePerformedNow.setText(_translate("Form", "set to today", None))
        self.pbCancel.setText(_translate("Form", "Cancel", None))
        self.lineEdit_2.setText(_translate("Form", "who performed step", None))
        self.lineEdit_6.setText(_translate("Form", "cure stop", None))
        self.pbCureStopNow.setText(_translate("Form", "set to now", None))
        self.pbGoTool5.setText(_translate("Form", "go to", None))
        self.lineEdit_13.setText(_translate("Form", "PCB tool ID", None))
        self.pbGoTool1.setText(_translate("Form", "go to", None))
        self.pbGoTool4.setText(_translate("Form", "go to", None))
        self.pbGoTool3.setText(_translate("Form", "go to", None))
        self.pbGoTool6.setText(_translate("Form", "go to", None))
        self.pbGoTool2.setText(_translate("Form", "go to", None))
        self.lineEdit_23.setText(_translate("Form", "PCB ID", None))
        self.pbGoPcb5.setText(_translate("Form", "go to", None))
        self.pbGoProtomodule1.setText(_translate("Form", "go to", None))
        self.pbGoPcb1.setText(_translate("Form", "go to", None))
        self.pbGoProtomodule6.setText(_translate("Form", "go to", None))
        self.pbGoProtomodule2.setText(_translate("Form", "go to", None))
        self.pbGoProtomodule5.setText(_translate("Form", "go to", None))
        self.pbGoProtomodule3.setText(_translate("Form", "go to", None))
        self.pbGoPcb4.setText(_translate("Form", "go to", None))
        self.pbGoPcb2.setText(_translate("Form", "go to", None))
        self.pbGoPcb3.setText(_translate("Form", "go to", None))
        self.lineEdit_22.setText(_translate("Form", "Protomodule ID", None))
        self.pbGoProtomodule4.setText(_translate("Form", "go to", None))
        self.pbGoPcb6.setText(_translate("Form", "go to", None))
        self.lineEdit_11.setText(_translate("Form", "araldite batch", None))
        self.pbGoTrayAssembly.setText(_translate("Form", "go to", None))
        self.pbGoTrayComponent.setText(_translate("Form", "go to", None))
        self.pbGoBatchAraldite.setText(_translate("Form", "go to", None))
        self.lineEdit_24.setText(_translate("Form", "component tray (PCB)", None))
        self.lineEdit_21.setText(_translate("Form", "assembly tray", None))
        self.lineEdit_26.setText(_translate("Form", "Status:", None))
        self.listIssues.setToolTip(_translate("Form", "list of issues", None))

