# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_supplies.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbAralditeID = QtGui.QSpinBox(Form)
        self.sbAralditeID.setGeometry(QtCore.QRect(90, 10, 91, 21))
        self.sbAralditeID.setMaximum(2147483647)
        self.sbAralditeID.setObjectName(_fromUtf8("sbAralditeID"))
        self.listAralditeComments = QtGui.QListWidget(Form)
        self.listAralditeComments.setGeometry(QtCore.QRect(10, 100, 251, 121))
        self.listAralditeComments.setObjectName(_fromUtf8("listAralditeComments"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pbAralditeDeleteComment = QtGui.QPushButton(Form)
        self.pbAralditeDeleteComment.setGeometry(QtCore.QRect(130, 80, 131, 21))
        self.pbAralditeDeleteComment.setObjectName(_fromUtf8("pbAralditeDeleteComment"))
        self.pteAralditeWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteAralditeWriteComment.setGeometry(QtCore.QRect(10, 230, 251, 71))
        self.pteAralditeWriteComment.setObjectName(_fromUtf8("pteAralditeWriteComment"))
        self.pbAralditeAddComment = QtGui.QPushButton(Form)
        self.pbAralditeAddComment.setGeometry(QtCore.QRect(10, 300, 81, 23))
        self.pbAralditeAddComment.setObjectName(_fromUtf8("pbAralditeAddComment"))
        self.pbAralditeEditNew = QtGui.QPushButton(Form)
        self.pbAralditeEditNew.setGeometry(QtCore.QRect(200, 10, 61, 21))
        self.pbAralditeEditNew.setObjectName(_fromUtf8("pbAralditeEditNew"))
        self.pbAralditeSave = QtGui.QPushButton(Form)
        self.pbAralditeSave.setGeometry(QtCore.QRect(200, 30, 61, 21))
        self.pbAralditeSave.setObjectName(_fromUtf8("pbAralditeSave"))
        self.pbAralditeCancel = QtGui.QPushButton(Form)
        self.pbAralditeCancel.setGeometry(QtCore.QRect(200, 50, 61, 21))
        self.pbAralditeCancel.setObjectName(_fromUtf8("pbAralditeCancel"))
        self.dAralditeReceived = QtGui.QDateEdit(Form)
        self.dAralditeReceived.setGeometry(QtCore.QRect(90, 30, 91, 21))
        self.dAralditeReceived.setObjectName(_fromUtf8("dAralditeReceived"))
        self.dAralditeExpires = QtGui.QDateEdit(Form)
        self.dAralditeExpires.setGeometry(QtCore.QRect(90, 50, 91, 21))
        self.dAralditeExpires.setObjectName(_fromUtf8("dAralditeExpires"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 410, 81, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 390, 81, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.listLoctiteComments = QtGui.QListWidget(Form)
        self.listLoctiteComments.setGeometry(QtCore.QRect(10, 460, 251, 121))
        self.listLoctiteComments.setObjectName(_fromUtf8("listLoctiteComments"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 440, 121, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.pbLoctiteDeleteComment = QtGui.QPushButton(Form)
        self.pbLoctiteDeleteComment.setGeometry(QtCore.QRect(130, 440, 131, 21))
        self.pbLoctiteDeleteComment.setObjectName(_fromUtf8("pbLoctiteDeleteComment"))
        self.pbLoctiteCancel = QtGui.QPushButton(Form)
        self.pbLoctiteCancel.setGeometry(QtCore.QRect(200, 410, 61, 21))
        self.pbLoctiteCancel.setObjectName(_fromUtf8("pbLoctiteCancel"))
        self.pbLoctiteAddComment = QtGui.QPushButton(Form)
        self.pbLoctiteAddComment.setGeometry(QtCore.QRect(10, 660, 81, 23))
        self.pbLoctiteAddComment.setObjectName(_fromUtf8("pbLoctiteAddComment"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 370, 81, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.dLoctiteReceived = QtGui.QDateEdit(Form)
        self.dLoctiteReceived.setGeometry(QtCore.QRect(90, 390, 91, 21))
        self.dLoctiteReceived.setObjectName(_fromUtf8("dLoctiteReceived"))
        self.pteLoctiteWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteLoctiteWriteComment.setGeometry(QtCore.QRect(10, 590, 251, 71))
        self.pteLoctiteWriteComment.setObjectName(_fromUtf8("pteLoctiteWriteComment"))
        self.pbLoctiteSave = QtGui.QPushButton(Form)
        self.pbLoctiteSave.setGeometry(QtCore.QRect(200, 390, 61, 21))
        self.pbLoctiteSave.setObjectName(_fromUtf8("pbLoctiteSave"))
        self.dLoctiteExpires = QtGui.QDateEdit(Form)
        self.dLoctiteExpires.setGeometry(QtCore.QRect(90, 410, 91, 21))
        self.dLoctiteExpires.setObjectName(_fromUtf8("dLoctiteExpires"))
        self.pbLoctiteEditNew = QtGui.QPushButton(Form)
        self.pbLoctiteEditNew.setGeometry(QtCore.QRect(200, 370, 61, 21))
        self.pbLoctiteEditNew.setObjectName(_fromUtf8("pbLoctiteEditNew"))
        self.sbLoctiteID = QtGui.QSpinBox(Form)
        self.sbLoctiteID.setGeometry(QtCore.QRect(90, 370, 91, 21))
        self.sbLoctiteID.setMaximum(2147483647)
        self.sbLoctiteID.setObjectName(_fromUtf8("sbLoctiteID"))
        self.sbSylgardThinID = QtGui.QSpinBox(Form)
        self.sbSylgardThinID.setGeometry(QtCore.QRect(420, 370, 61, 21))
        self.sbSylgardThinID.setMaximum(2147483647)
        self.sbSylgardThinID.setObjectName(_fromUtf8("sbSylgardThinID"))
        self.pbSylgardThinAddComment = QtGui.QPushButton(Form)
        self.pbSylgardThinAddComment.setGeometry(QtCore.QRect(310, 660, 81, 23))
        self.pbSylgardThinAddComment.setObjectName(_fromUtf8("pbSylgardThinAddComment"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 410, 81, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(310, 440, 121, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(310, 390, 81, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.pbSylgardThinSave = QtGui.QPushButton(Form)
        self.pbSylgardThinSave.setGeometry(QtCore.QRect(500, 390, 61, 21))
        self.pbSylgardThinSave.setObjectName(_fromUtf8("pbSylgardThinSave"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 370, 111, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.listSylgardThinComments = QtGui.QListWidget(Form)
        self.listSylgardThinComments.setGeometry(QtCore.QRect(310, 460, 251, 121))
        self.listSylgardThinComments.setObjectName(_fromUtf8("listSylgardThinComments"))
        self.pbSylgardThinDeleteComment = QtGui.QPushButton(Form)
        self.pbSylgardThinDeleteComment.setGeometry(QtCore.QRect(430, 440, 131, 21))
        self.pbSylgardThinDeleteComment.setObjectName(_fromUtf8("pbSylgardThinDeleteComment"))
        self.pteSylgardThinWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteSylgardThinWriteComment.setGeometry(QtCore.QRect(310, 590, 251, 71))
        self.pteSylgardThinWriteComment.setObjectName(_fromUtf8("pteSylgardThinWriteComment"))
        self.pbSylgardThinCancel = QtGui.QPushButton(Form)
        self.pbSylgardThinCancel.setGeometry(QtCore.QRect(500, 410, 61, 21))
        self.pbSylgardThinCancel.setObjectName(_fromUtf8("pbSylgardThinCancel"))
        self.dSylgardThinExpires = QtGui.QDateEdit(Form)
        self.dSylgardThinExpires.setGeometry(QtCore.QRect(390, 410, 91, 21))
        self.dSylgardThinExpires.setObjectName(_fromUtf8("dSylgardThinExpires"))
        self.dSylgardThinReceived = QtGui.QDateEdit(Form)
        self.dSylgardThinReceived.setGeometry(QtCore.QRect(390, 390, 91, 21))
        self.dSylgardThinReceived.setObjectName(_fromUtf8("dSylgardThinReceived"))
        self.pbSylgardThinEditNew = QtGui.QPushButton(Form)
        self.pbSylgardThinEditNew.setGeometry(QtCore.QRect(500, 370, 61, 21))
        self.pbSylgardThinEditNew.setObjectName(_fromUtf8("pbSylgardThinEditNew"))
        self.pbSylgardThickEditNew = QtGui.QPushButton(Form)
        self.pbSylgardThickEditNew.setGeometry(QtCore.QRect(500, 10, 61, 21))
        self.pbSylgardThickEditNew.setObjectName(_fromUtf8("pbSylgardThickEditNew"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(310, 50, 81, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(310, 80, 121, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.sbSylgardThickID = QtGui.QSpinBox(Form)
        self.sbSylgardThickID.setGeometry(QtCore.QRect(420, 10, 61, 21))
        self.sbSylgardThickID.setMaximum(2147483647)
        self.sbSylgardThickID.setObjectName(_fromUtf8("sbSylgardThickID"))
        self.pbSylgardThickCancel = QtGui.QPushButton(Form)
        self.pbSylgardThickCancel.setGeometry(QtCore.QRect(500, 50, 61, 21))
        self.pbSylgardThickCancel.setObjectName(_fromUtf8("pbSylgardThickCancel"))
        self.listSylgardThickComments = QtGui.QListWidget(Form)
        self.listSylgardThickComments.setGeometry(QtCore.QRect(310, 100, 251, 121))
        self.listSylgardThickComments.setObjectName(_fromUtf8("listSylgardThickComments"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(310, 10, 111, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.pbSylgardThickDeleteComment = QtGui.QPushButton(Form)
        self.pbSylgardThickDeleteComment.setGeometry(QtCore.QRect(430, 80, 131, 21))
        self.pbSylgardThickDeleteComment.setObjectName(_fromUtf8("pbSylgardThickDeleteComment"))
        self.pteSylgardThickWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteSylgardThickWriteComment.setGeometry(QtCore.QRect(310, 230, 251, 71))
        self.pteSylgardThickWriteComment.setObjectName(_fromUtf8("pteSylgardThickWriteComment"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(310, 30, 81, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.pbSylgardThickAddComment = QtGui.QPushButton(Form)
        self.pbSylgardThickAddComment.setGeometry(QtCore.QRect(310, 300, 81, 23))
        self.pbSylgardThickAddComment.setObjectName(_fromUtf8("pbSylgardThickAddComment"))
        self.pbSylgardThickSave = QtGui.QPushButton(Form)
        self.pbSylgardThickSave.setGeometry(QtCore.QRect(500, 30, 61, 21))
        self.pbSylgardThickSave.setObjectName(_fromUtf8("pbSylgardThickSave"))
        self.dSylgardThickExpires = QtGui.QDateEdit(Form)
        self.dSylgardThickExpires.setGeometry(QtCore.QRect(390, 50, 91, 21))
        self.dSylgardThickExpires.setObjectName(_fromUtf8("dSylgardThickExpires"))
        self.dSylgardThickReceived = QtGui.QDateEdit(Form)
        self.dSylgardThickReceived.setGeometry(QtCore.QRect(390, 30, 91, 21))
        self.dSylgardThickReceived.setObjectName(_fromUtf8("dSylgardThickReceived"))
        self.dBondWireReceived = QtGui.QDateEdit(Form)
        self.dBondWireReceived.setGeometry(QtCore.QRect(690, 30, 91, 21))
        self.dBondWireReceived.setObjectName(_fromUtf8("dBondWireReceived"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(610, 50, 81, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.listBondWireComments = QtGui.QListWidget(Form)
        self.listBondWireComments.setGeometry(QtCore.QRect(610, 100, 251, 121))
        self.listBondWireComments.setObjectName(_fromUtf8("listBondWireComments"))
        self.pbBondWireEditNew = QtGui.QPushButton(Form)
        self.pbBondWireEditNew.setGeometry(QtCore.QRect(800, 10, 61, 21))
        self.pbBondWireEditNew.setObjectName(_fromUtf8("pbBondWireEditNew"))
        self.pbBondWireDeleteComment = QtGui.QPushButton(Form)
        self.pbBondWireDeleteComment.setGeometry(QtCore.QRect(730, 80, 131, 21))
        self.pbBondWireDeleteComment.setObjectName(_fromUtf8("pbBondWireDeleteComment"))
        self.pbBondWireCancel = QtGui.QPushButton(Form)
        self.pbBondWireCancel.setGeometry(QtCore.QRect(800, 50, 61, 21))
        self.pbBondWireCancel.setObjectName(_fromUtf8("pbBondWireCancel"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(610, 80, 121, 21))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.sbBondWireID = QtGui.QSpinBox(Form)
        self.sbBondWireID.setGeometry(QtCore.QRect(700, 10, 81, 21))
        self.sbBondWireID.setMaximum(2147483647)
        self.sbBondWireID.setObjectName(_fromUtf8("sbBondWireID"))
        self.pteBondWireWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteBondWireWriteComment.setGeometry(QtCore.QRect(610, 230, 251, 71))
        self.pteBondWireWriteComment.setObjectName(_fromUtf8("pteBondWireWriteComment"))
        self.pbBondWireSave = QtGui.QPushButton(Form)
        self.pbBondWireSave.setGeometry(QtCore.QRect(800, 30, 61, 21))
        self.pbBondWireSave.setObjectName(_fromUtf8("pbBondWireSave"))
        self.dBondWireExpires = QtGui.QDateEdit(Form)
        self.dBondWireExpires.setGeometry(QtCore.QRect(690, 50, 91, 21))
        self.dBondWireExpires.setObjectName(_fromUtf8("dBondWireExpires"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(610, 30, 81, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(610, 10, 91, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.pbBondWireAddComment = QtGui.QPushButton(Form)
        self.pbBondWireAddComment.setGeometry(QtCore.QRect(610, 300, 81, 23))
        self.pbBondWireAddComment.setObjectName(_fromUtf8("pbBondWireAddComment"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "Araldite batch", None))
        self.lineEdit_3.setText(_translate("Form", "Comments", None))
        self.pbAralditeDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbAralditeAddComment.setText(_translate("Form", "add comment", None))
        self.pbAralditeEditNew.setText(_translate("Form", "edit/new", None))
        self.pbAralditeSave.setText(_translate("Form", "save", None))
        self.pbAralditeCancel.setText(_translate("Form", "cancel", None))
        self.lineEdit_2.setText(_translate("Form", "Received", None))
        self.lineEdit_4.setText(_translate("Form", "Expires", None))
        self.lineEdit_5.setText(_translate("Form", "Expires", None))
        self.lineEdit_6.setText(_translate("Form", "Received", None))
        self.lineEdit_7.setText(_translate("Form", "Comments", None))
        self.pbLoctiteDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbLoctiteCancel.setText(_translate("Form", "cancel", None))
        self.pbLoctiteAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_8.setToolTip(_translate("Form", "Loctite = silver epoxy", None))
        self.lineEdit_8.setText(_translate("Form", "Loctite batch", None))
        self.pbLoctiteSave.setText(_translate("Form", "save", None))
        self.pbLoctiteEditNew.setText(_translate("Form", "edit/new", None))
        self.pbSylgardThinAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_9.setText(_translate("Form", "Expires", None))
        self.lineEdit_10.setText(_translate("Form", "Comments", None))
        self.lineEdit_11.setText(_translate("Form", "Received", None))
        self.pbSylgardThinSave.setText(_translate("Form", "save", None))
        self.lineEdit_12.setText(_translate("Form", "Sylgard (thin) batch", None))
        self.pbSylgardThinDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbSylgardThinCancel.setText(_translate("Form", "cancel", None))
        self.pbSylgardThinEditNew.setText(_translate("Form", "edit/new", None))
        self.pbSylgardThickEditNew.setText(_translate("Form", "edit/new", None))
        self.lineEdit_13.setText(_translate("Form", "Expires", None))
        self.lineEdit_14.setText(_translate("Form", "Comments", None))
        self.pbSylgardThickCancel.setText(_translate("Form", "cancel", None))
        self.lineEdit_15.setText(_translate("Form", "Sylgard (thick) batch", None))
        self.pbSylgardThickDeleteComment.setText(_translate("Form", "delete selected", None))
        self.lineEdit_16.setText(_translate("Form", "Received", None))
        self.pbSylgardThickAddComment.setText(_translate("Form", "add comment", None))
        self.pbSylgardThickSave.setText(_translate("Form", "save", None))
        self.lineEdit_17.setText(_translate("Form", "Expires", None))
        self.pbBondWireEditNew.setText(_translate("Form", "edit/new", None))
        self.pbBondWireDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbBondWireCancel.setText(_translate("Form", "cancel", None))
        self.lineEdit_18.setText(_translate("Form", "Comments", None))
        self.pbBondWireSave.setText(_translate("Form", "save", None))
        self.lineEdit_19.setText(_translate("Form", "Received", None))
        self.lineEdit_20.setText(_translate("Form", "Bond wire batch", None))
        self.pbBondWireAddComment.setText(_translate("Form", "add comment", None))

