# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_module.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(976, 663)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbModuleID = QtGui.QSpinBox(Form)
        self.sbModuleID.setGeometry(QtCore.QRect(80, 10, 91, 21))
        self.sbModuleID.setMaximum(65535)
        self.sbModuleID.setProperty("value", 0)
        self.sbModuleID.setObjectName(_fromUtf8("sbModuleID"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.leBaseplateID = QtGui.QLineEdit(Form)
        self.leBaseplateID.setGeometry(QtCore.QRect(80, 30, 51, 21))
        self.leBaseplateID.setReadOnly(True)
        self.leBaseplateID.setObjectName(_fromUtf8("leBaseplateID"))
        self.leSensorID = QtGui.QLineEdit(Form)
        self.leSensorID.setGeometry(QtCore.QRect(80, 50, 51, 21))
        self.leSensorID.setReadOnly(True)
        self.leSensorID.setObjectName(_fromUtf8("leSensorID"))
        self.lePCBID = QtGui.QLineEdit(Form)
        self.lePCBID.setGeometry(QtCore.QRect(80, 70, 51, 21))
        self.lePCBID.setReadOnly(True)
        self.lePCBID.setObjectName(_fromUtf8("lePCBID"))
        self.pbGoBaseplate = QtGui.QPushButton(Form)
        self.pbGoBaseplate.setGeometry(QtCore.QRect(130, 30, 41, 21))
        self.pbGoBaseplate.setObjectName(_fromUtf8("pbGoBaseplate"))
        self.pbGoSensor = QtGui.QPushButton(Form)
        self.pbGoSensor.setGeometry(QtCore.QRect(130, 50, 41, 21))
        self.pbGoSensor.setObjectName(_fromUtf8("pbGoSensor"))
        self.pbGoPCB = QtGui.QPushButton(Form)
        self.pbGoPCB.setGeometry(QtCore.QRect(130, 70, 41, 21))
        self.pbGoPCB.setObjectName(_fromUtf8("pbGoPCB"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.leThickness = QtGui.QLineEdit(Form)
        self.leThickness.setGeometry(QtCore.QRect(80, 100, 91, 21))
        self.leThickness.setReadOnly(True)
        self.leThickness.setObjectName(_fromUtf8("leThickness"))
        self.cbIVCurves = QtGui.QComboBox(Form)
        self.cbIVCurves.setGeometry(QtCore.QRect(60, 210, 501, 21))
        self.cbIVCurves.setObjectName(_fromUtf8("cbIVCurves"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 210, 51, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.tabBinsRaw = QtGui.QTabWidget(Form)
        self.tabBinsRaw.setGeometry(QtCore.QRect(10, 140, 551, 71))
        self.tabBinsRaw.setObjectName(_fromUtf8("tabBinsRaw"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.ckPlotAsc = QtGui.QCheckBox(self.tab)
        self.ckPlotAsc.setGeometry(QtCore.QRect(110, 0, 91, 17))
        self.ckPlotAsc.setObjectName(_fromUtf8("ckPlotAsc"))
        self.ckPlotDesc = QtGui.QCheckBox(self.tab)
        self.ckPlotDesc.setGeometry(QtCore.QRect(110, 20, 101, 17))
        self.ckPlotDesc.setChecked(True)
        self.ckPlotDesc.setObjectName(_fromUtf8("ckPlotDesc"))
        self.cbBinsXAxis = QtGui.QComboBox(self.tab)
        self.cbBinsXAxis.setGeometry(QtCore.QRect(40, 0, 61, 21))
        self.cbBinsXAxis.setObjectName(_fromUtf8("cbBinsXAxis"))
        self.cbBinsXAxis.addItem(_fromUtf8(""))
        self.cbBinsXAxis.addItem(_fromUtf8(""))
        self.cbBinsXAxis.addItem(_fromUtf8(""))
        self.cbBinsXAxis.addItem(_fromUtf8(""))
        self.lineEdit_9 = QtGui.QLineEdit(self.tab)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 20, 41, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.cbBinsYAxis = QtGui.QComboBox(self.tab)
        self.cbBinsYAxis.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.cbBinsYAxis.setObjectName(_fromUtf8("cbBinsYAxis"))
        self.cbBinsYAxis.addItem(_fromUtf8(""))
        self.cbBinsYAxis.addItem(_fromUtf8(""))
        self.cbBinsYAxis.addItem(_fromUtf8(""))
        self.cbBinsYAxis.addItem(_fromUtf8(""))
        self.lineEdit_10 = QtGui.QLineEdit(self.tab)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.tabBinsRaw.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(0, 20, 41, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.cbRawXAxis = QtGui.QComboBox(self.tab_2)
        self.cbRawXAxis.setGeometry(QtCore.QRect(40, 0, 61, 21))
        self.cbRawXAxis.setObjectName(_fromUtf8("cbRawXAxis"))
        self.cbRawXAxis.addItem(_fromUtf8(""))
        self.cbRawXAxis.addItem(_fromUtf8(""))
        self.cbRawXAxis.addItem(_fromUtf8(""))
        self.cbRawXAxis.addItem(_fromUtf8(""))
        self.cbRawYAxis = QtGui.QComboBox(self.tab_2)
        self.cbRawYAxis.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.cbRawYAxis.setObjectName(_fromUtf8("cbRawYAxis"))
        self.cbRawYAxis.addItem(_fromUtf8(""))
        self.cbRawYAxis.addItem(_fromUtf8(""))
        self.cbRawYAxis.addItem(_fromUtf8(""))
        self.cbRawYAxis.addItem(_fromUtf8(""))
        self.tabBinsRaw.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 230, 551, 421))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.vlPlotIV = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.vlPlotIV.setObjectName(_fromUtf8("vlPlotIV"))

        self.retranslateUi(Form)
        self.tabBinsRaw.setCurrentIndex(0)
        self.cbBinsXAxis.setCurrentIndex(1)
        self.cbBinsYAxis.setCurrentIndex(2)
        self.cbRawXAxis.setCurrentIndex(1)
        self.cbRawYAxis.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "Module ID", None))
        self.lineEdit_2.setText(_translate("Form", "Baseplate ID", None))
        self.lineEdit_3.setText(_translate("Form", "Sensor ID", None))
        self.lineEdit_4.setText(_translate("Form", "PCB ID", None))
        self.pbGoBaseplate.setText(_translate("Form", "Go to", None))
        self.pbGoSensor.setText(_translate("Form", "Go to", None))
        self.pbGoPCB.setText(_translate("Form", "Go to", None))
        self.lineEdit_5.setText(_translate("Form", "Thickness", None))
        self.lineEdit_6.setText(_translate("Form", "IV curve", None))
        self.ckPlotAsc.setText(_translate("Form", "Plot ascending", None))
        self.ckPlotDesc.setText(_translate("Form", "Plot descending", None))
        self.cbBinsXAxis.setItemText(0, _translate("Form", "Time", None))
        self.cbBinsXAxis.setItemText(1, _translate("Form", "Voltage", None))
        self.cbBinsXAxis.setItemText(2, _translate("Form", "Current", None))
        self.cbBinsXAxis.setItemText(3, _translate("Form", "Vsource", None))
        self.lineEdit_9.setText(_translate("Form", "Y axis", None))
        self.cbBinsYAxis.setItemText(0, _translate("Form", "Time", None))
        self.cbBinsYAxis.setItemText(1, _translate("Form", "Voltage", None))
        self.cbBinsYAxis.setItemText(2, _translate("Form", "Current", None))
        self.cbBinsYAxis.setItemText(3, _translate("Form", "Vsource", None))
        self.lineEdit_10.setText(_translate("Form", "X axis", None))
        self.tabBinsRaw.setTabText(self.tabBinsRaw.indexOf(self.tab), _translate("Form", "Bins", None))
        self.lineEdit_7.setText(_translate("Form", "X axis", None))
        self.lineEdit_8.setText(_translate("Form", "Y axis", None))
        self.cbRawXAxis.setItemText(0, _translate("Form", "Time", None))
        self.cbRawXAxis.setItemText(1, _translate("Form", "Voltage", None))
        self.cbRawXAxis.setItemText(2, _translate("Form", "Current", None))
        self.cbRawXAxis.setItemText(3, _translate("Form", "Vsource", None))
        self.cbRawYAxis.setItemText(0, _translate("Form", "Time", None))
        self.cbRawYAxis.setItemText(1, _translate("Form", "Voltage", None))
        self.cbRawYAxis.setItemText(2, _translate("Form", "Current", None))
        self.cbRawYAxis.setItemText(3, _translate("Form", "Vsource", None))
        self.tabBinsRaw.setTabText(self.tabBinsRaw.indexOf(self.tab_2), _translate("Form", "Raw data", None))

