# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_protomodule.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 90, 211, 551))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pbGoShipment = QtGui.QPushButton(self.frame_2)
        self.pbGoShipment.setGeometry(QtCore.QRect(90, 20, 121, 21))
        self.pbGoShipment.setObjectName(_fromUtf8("pbGoShipment"))
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(1, 1, 90, 20))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(1, 20, 90, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.leLocation = QtGui.QLineEdit(self.frame_2)
        self.leLocation.setGeometry(QtCore.QRect(90, 1, 120, 20))
        self.leLocation.setText(_fromUtf8(""))
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName(_fromUtf8("leLocation"))
        self.listShipments = QtGui.QListWidget(self.frame_2)
        self.listShipments.setGeometry(QtCore.QRect(0, 40, 211, 91))
        self.listShipments.setObjectName(_fromUtf8("listShipments"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(1, 230, 130, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(1, 210, 130, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(1, 250, 130, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.sbRotation = QtGui.QSpinBox(self.frame_2)
        self.sbRotation.setGeometry(QtCore.QRect(130, 250, 80, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName(_fromUtf8("sbRotation"))
        self.sbChannels = QtGui.QSpinBox(self.frame_2)
        self.sbChannels.setGeometry(QtCore.QRect(130, 190, 80, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName(_fromUtf8("sbChannels"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(1, 190, 130, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.pbAddComment = QtGui.QPushButton(self.frame_2)
        self.pbAddComment.setGeometry(QtCore.QRect(0, 530, 81, 21))
        self.pbAddComment.setObjectName(_fromUtf8("pbAddComment"))
        self.lineEdit_14 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(1, 310, 100, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.pbDeleteComment = QtGui.QPushButton(self.frame_2)
        self.pbDeleteComment.setGeometry(QtCore.QRect(100, 310, 111, 21))
        self.pbDeleteComment.setObjectName(_fromUtf8("pbDeleteComment"))
        self.pteWriteComment = QtGui.QPlainTextEdit(self.frame_2)
        self.pteWriteComment.setGeometry(QtCore.QRect(1, 460, 209, 71))
        self.pteWriteComment.setObjectName(_fromUtf8("pteWriteComment"))
        self.listComments = QtGui.QListWidget(self.frame_2)
        self.listComments.setGeometry(QtCore.QRect(0, 330, 211, 121))
        self.listComments.setObjectName(_fromUtf8("listComments"))
        self.cbSize = QtGui.QComboBox(self.frame_2)
        self.cbSize.setGeometry(QtCore.QRect(130, 210, 81, 21))
        self.cbSize.setObjectName(_fromUtf8("cbSize"))
        self.cbSize.addItem(_fromUtf8(""))
        self.cbSize.addItem(_fromUtf8(""))
        self.lineEdit_15 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(1, 270, 130, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.cbChirality = QtGui.QComboBox(self.frame_2)
        self.cbChirality.setGeometry(QtCore.QRect(130, 270, 81, 21))
        self.cbChirality.setObjectName(_fromUtf8("cbChirality"))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(1, 170, 130, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.dsbThickness = QtGui.QDoubleSpinBox(self.frame_2)
        self.dsbThickness.setGeometry(QtCore.QRect(130, 170, 81, 21))
        self.dsbThickness.setReadOnly(True)
        self.dsbThickness.setMinimum(-1.0)
        self.dsbThickness.setMaximum(2147483647.0)
        self.dsbThickness.setSingleStep(0.1)
        self.dsbThickness.setObjectName(_fromUtf8("dsbThickness"))
        self.lineEdit_16 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(1, 150, 130, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.leNumKaptons = QtGui.QLineEdit(self.frame_2)
        self.leNumKaptons.setGeometry(QtCore.QRect(129, 150, 80, 21))
        self.leNumKaptons.setReadOnly(True)
        self.leNumKaptons.setObjectName(_fromUtf8("leNumKaptons"))
        self.cbShape = QtGui.QComboBox(self.frame_2)
        self.cbShape.setGeometry(QtCore.QRect(130, 230, 80, 20))
        self.cbShape.setObjectName(_fromUtf8("cbShape"))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 211, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pbSave = QtGui.QPushButton(self.frame_3)
        self.pbSave.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.pbEdit = QtGui.QPushButton(self.frame_3)
        self.pbEdit.setGeometry(QtCore.QRect(0, 50, 71, 21))
        self.pbEdit.setObjectName(_fromUtf8("pbEdit"))
        self.pbCancel = QtGui.QPushButton(self.frame_3)
        self.pbCancel.setGeometry(QtCore.QRect(150, 30, 61, 21))
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.lineEdit = QtGui.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(1, 1, 80, 19))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pbNew = QtGui.QPushButton(self.frame_3)
        self.pbNew.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.pbNew.setObjectName(_fromUtf8("pbNew"))
        self.sbID = QtGui.QSpinBox(self.frame_3)
        self.sbID.setGeometry(QtCore.QRect(80, 1, 130, 19))
        self.sbID.setMaximum(2147483647)
        self.sbID.setObjectName(_fromUtf8("sbID"))
        self.pbGoStepSensor = QtGui.QPushButton(Form)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(430, 90, 41, 21))
        self.pbGoStepSensor.setObjectName(_fromUtf8("pbGoStepSensor"))
        self.pbGoModule = QtGui.QPushButton(Form)
        self.pbGoModule.setGeometry(QtCore.QRect(430, 370, 41, 21))
        self.pbGoModule.setObjectName(_fromUtf8("pbGoModule"))
        self.sbSensor = QtGui.QSpinBox(Form)
        self.sbSensor.setGeometry(QtCore.QRect(350, 110, 81, 21))
        self.sbSensor.setReadOnly(True)
        self.sbSensor.setMinimum(-1)
        self.sbSensor.setMaximum(2147483647)
        self.sbSensor.setObjectName(_fromUtf8("sbSensor"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(260, 110, 91, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(260, 370, 91, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.sbModule = QtGui.QSpinBox(Form)
        self.sbModule.setGeometry(QtCore.QRect(350, 370, 81, 21))
        self.sbModule.setReadOnly(True)
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName(_fromUtf8("sbModule"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(260, 90, 91, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.pbGoSensor = QtGui.QPushButton(Form)
        self.pbGoSensor.setGeometry(QtCore.QRect(430, 110, 41, 21))
        self.pbGoSensor.setObjectName(_fromUtf8("pbGoSensor"))
        self.sbStepSensor = QtGui.QSpinBox(Form)
        self.sbStepSensor.setGeometry(QtCore.QRect(350, 90, 81, 21))
        self.sbStepSensor.setReadOnly(True)
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName(_fromUtf8("sbStepSensor"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 330, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 70, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(260, 130, 91, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.pbGoBaseplate = QtGui.QPushButton(Form)
        self.pbGoBaseplate.setGeometry(QtCore.QRect(430, 130, 41, 21))
        self.pbGoBaseplate.setObjectName(_fromUtf8("pbGoBaseplate"))
        self.sbBaseplate = QtGui.QSpinBox(Form)
        self.sbBaseplate.setGeometry(QtCore.QRect(350, 130, 81, 21))
        self.sbBaseplate.setReadOnly(True)
        self.sbBaseplate.setMinimum(-1)
        self.sbBaseplate.setMaximum(2147483647)
        self.sbBaseplate.setObjectName(_fromUtf8("sbBaseplate"))
        self.sbStepPcb = QtGui.QSpinBox(Form)
        self.sbStepPcb.setGeometry(QtCore.QRect(350, 350, 81, 21))
        self.sbStepPcb.setReadOnly(True)
        self.sbStepPcb.setMinimum(-1)
        self.sbStepPcb.setMaximum(2147483647)
        self.sbStepPcb.setObjectName(_fromUtf8("sbStepPcb"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(260, 350, 91, 21))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.pbGoStepPcb = QtGui.QPushButton(Form)
        self.pbGoStepPcb.setGeometry(QtCore.QRect(430, 350, 41, 21))
        self.pbGoStepPcb.setObjectName(_fromUtf8("pbGoStepPcb"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(260, 200, 151, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(260, 220, 151, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(260, 240, 151, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(260, 260, 151, 21))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(260, 280, 151, 21))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(260, 180, 141, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dsbOffsetTranslation = QtGui.QDoubleSpinBox(Form)
        self.dsbOffsetTranslation.setGeometry(QtCore.QRect(410, 200, 81, 21))
        self.dsbOffsetTranslation.setReadOnly(True)
        self.dsbOffsetTranslation.setMinimum(-1.0)
        self.dsbOffsetTranslation.setMaximum(2147483647.0)
        self.dsbOffsetTranslation.setSingleStep(0.1)
        self.dsbOffsetTranslation.setObjectName(_fromUtf8("dsbOffsetTranslation"))
        self.dsbOffsetRotation = QtGui.QDoubleSpinBox(Form)
        self.dsbOffsetRotation.setGeometry(QtCore.QRect(410, 220, 81, 21))
        self.dsbOffsetRotation.setReadOnly(True)
        self.dsbOffsetRotation.setMinimum(-1.0)
        self.dsbOffsetRotation.setMaximum(2147483647.0)
        self.dsbOffsetRotation.setSingleStep(0.1)
        self.dsbOffsetRotation.setObjectName(_fromUtf8("dsbOffsetRotation"))
        self.dsbFlatness = QtGui.QDoubleSpinBox(Form)
        self.dsbFlatness.setGeometry(QtCore.QRect(410, 240, 81, 21))
        self.dsbFlatness.setReadOnly(True)
        self.dsbFlatness.setMinimum(-1.0)
        self.dsbFlatness.setMaximum(2147483647.0)
        self.dsbFlatness.setSingleStep(0.1)
        self.dsbFlatness.setObjectName(_fromUtf8("dsbFlatness"))
        self.cbCheckCracks = QtGui.QComboBox(Form)
        self.cbCheckCracks.setGeometry(QtCore.QRect(410, 260, 81, 20))
        self.cbCheckCracks.setObjectName(_fromUtf8("cbCheckCracks"))
        self.cbCheckCracks.addItem(_fromUtf8(""))
        self.cbCheckCracks.addItem(_fromUtf8(""))
        self.cbCheckGlueSpill = QtGui.QComboBox(Form)
        self.cbCheckGlueSpill.setGeometry(QtCore.QRect(410, 280, 81, 20))
        self.cbCheckGlueSpill.setObjectName(_fromUtf8("cbCheckGlueSpill"))
        self.cbCheckGlueSpill.addItem(_fromUtf8(""))
        self.cbCheckGlueSpill.addItem(_fromUtf8(""))

        self.retranslateUi(Form)
        self.cbSize.setCurrentIndex(-1)
        self.cbChirality.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        self.cbCheckCracks.setCurrentIndex(-1)
        self.cbCheckGlueSpill.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pbGoShipment.setText(_translate("Form", "go to selected", None))
        self.lineEdit_9.setText(_translate("Form", "location", None))
        self.lineEdit_3.setText(_translate("Form", "shipments", None))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)", None))
        self.lineEdit_10.setText(_translate("Form", "Shape", None))
        self.lineEdit_5.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_11.setText(_translate("Form", "Rotation", None))
        self.lineEdit_6.setText(_translate("Form", "Channels", None))
        self.pbAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_14.setText(_translate("Form", "Comments", None))
        self.pbDeleteComment.setText(_translate("Form", "delete selected", None))
        self.cbSize.setItemText(0, _translate("Form", "8", None))
        self.cbSize.setItemText(1, _translate("Form", "6", None))
        self.lineEdit_15.setText(_translate("Form", "Chirality", None))
        self.cbChirality.setItemText(0, _translate("Form", "achiral", None))
        self.cbChirality.setItemText(1, _translate("Form", "left", None))
        self.cbChirality.setItemText(2, _translate("Form", "right", None))
        self.lineEdit_4.setText(_translate("Form", "Thickness (mm)", None))
        self.lineEdit_16.setText(_translate("Form", "number of kapton layers", None))
        self.cbShape.setItemText(0, _translate("Form", "full", None))
        self.cbShape.setItemText(1, _translate("Form", "half", None))
        self.cbShape.setItemText(2, _translate("Form", "five", None))
        self.cbShape.setItemText(3, _translate("Form", "three", None))
        self.cbShape.setItemText(4, _translate("Form", "semi", None))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)", None))
        self.cbShape.setItemText(6, _translate("Form", "choptwo", None))
        self.pbSave.setText(_translate("Form", "Save", None))
        self.pbEdit.setText(_translate("Form", "Edit", None))
        self.pbCancel.setText(_translate("Form", "Cancel", None))
        self.lineEdit.setText(_translate("Form", "Protomodule ID", None))
        self.pbNew.setText(_translate("Form", "New", None))
        self.pbGoStepSensor.setText(_translate("Form", "Go to", None))
        self.pbGoModule.setText(_translate("Form", "Go to", None))
        self.lineEdit_12.setText(_translate("Form", "sensor", None))
        self.lineEdit_8.setText(_translate("Form", "On module", None))
        self.lineEdit_13.setText(_translate("Form", "Placement step", None))
        self.pbGoSensor.setText(_translate("Form", "Go to", None))
        self.label.setText(_translate("Form", "PCB platement", None))
        self.label_2.setText(_translate("Form", "sensor placement", None))
        self.lineEdit_17.setText(_translate("Form", "baseplate", None))
        self.pbGoBaseplate.setText(_translate("Form", "Go to", None))
        self.lineEdit_18.setText(_translate("Form", "PCB step", None))
        self.pbGoStepPcb.setText(_translate("Form", "Go to", None))
        self.lineEdit_19.setText(_translate("Form", "translational offset (microns)", None))
        self.lineEdit_20.setText(_translate("Form", "rotational offset (degrees)", None))
        self.lineEdit_21.setText(_translate("Form", "flatness (mm)", None))
        self.lineEdit_22.setText(_translate("Form", "check for cracks", None))
        self.lineEdit_23.setText(_translate("Form", "check glue spillage", None))
        self.label_3.setText(_translate("Form", "protomodule qualification", None))
        self.cbCheckCracks.setItemText(0, _translate("Form", "pass", None))
        self.cbCheckCracks.setItemText(1, _translate("Form", "fail", None))
        self.cbCheckGlueSpill.setItemText(0, _translate("Form", "pass", None))
        self.cbCheckGlueSpill.setItemText(1, _translate("Form", "fail", None))

