# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_PCB.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 240, 131, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 110, 131, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 90, 131, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 300, 131, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 280, 131, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 260, 131, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(260, 260, 81, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.sbID = QtGui.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(90, 10, 131, 21))
        self.sbID.setMaximum(2147483647)
        self.sbID.setObjectName(_fromUtf8("sbID"))
        self.leIdentifier = QtGui.QLineEdit(Form)
        self.leIdentifier.setGeometry(QtCore.QRect(140, 240, 81, 21))
        self.leIdentifier.setText(_fromUtf8(""))
        self.leIdentifier.setReadOnly(True)
        self.leIdentifier.setObjectName(_fromUtf8("leIdentifier"))
        self.leManufacturer = QtGui.QLineEdit(Form)
        self.leManufacturer.setGeometry(QtCore.QRect(140, 260, 81, 21))
        self.leManufacturer.setText(_fromUtf8(""))
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName(_fromUtf8("leManufacturer"))
        self.pbGoModule = QtGui.QPushButton(Form)
        self.pbGoModule.setGeometry(QtCore.QRect(420, 260, 51, 21))
        self.pbGoModule.setObjectName(_fromUtf8("pbGoModule"))
        self.pbCancel = QtGui.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(160, 40, 61, 21))
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.pbEdit = QtGui.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.pbEdit.setObjectName(_fromUtf8("pbEdit"))
        self.pbNew = QtGui.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.pbNew.setObjectName(_fromUtf8("pbNew"))
        self.pbSave = QtGui.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(90, 40, 61, 21))
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.dsbThickness = QtGui.QDoubleSpinBox(Form)
        self.dsbThickness.setGeometry(QtCore.QRect(390, 110, 81, 21))
        self.dsbThickness.setReadOnly(True)
        self.dsbThickness.setMinimum(-1.0)
        self.dsbThickness.setMaximum(2147483647.0)
        self.dsbThickness.setSingleStep(0.1)
        self.dsbThickness.setObjectName(_fromUtf8("dsbThickness"))
        self.sbChannels = QtGui.QSpinBox(Form)
        self.sbChannels.setGeometry(QtCore.QRect(140, 280, 81, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName(_fromUtf8("sbChannels"))
        self.dsbFlatness = QtGui.QDoubleSpinBox(Form)
        self.dsbFlatness.setGeometry(QtCore.QRect(390, 90, 81, 21))
        self.dsbFlatness.setReadOnly(True)
        self.dsbFlatness.setMinimum(-1.0)
        self.dsbFlatness.setMaximum(2147483647.0)
        self.dsbFlatness.setSingleStep(0.05)
        self.dsbFlatness.setObjectName(_fromUtf8("dsbFlatness"))
        self.sbModule = QtGui.QSpinBox(Form)
        self.sbModule.setGeometry(QtCore.QRect(340, 260, 81, 21))
        self.sbModule.setReadOnly(True)
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName(_fromUtf8("sbModule"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 320, 131, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 340, 131, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 360, 131, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.sbRotation = QtGui.QSpinBox(Form)
        self.sbRotation.setGeometry(QtCore.QRect(140, 360, 81, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName(_fromUtf8("sbRotation"))
        self.cbChirality = QtGui.QComboBox(Form)
        self.cbChirality.setGeometry(QtCore.QRect(140, 340, 81, 21))
        self.cbChirality.setObjectName(_fromUtf8("cbChirality"))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.leLocation = QtGui.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(100, 90, 121, 21))
        self.leLocation.setText(_fromUtf8(""))
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName(_fromUtf8("leLocation"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.listShipments = QtGui.QListWidget(Form)
        self.listShipments.setGeometry(QtCore.QRect(10, 130, 211, 91))
        self.listShipments.setObjectName(_fromUtf8("listShipments"))
        self.pbGoShipment = QtGui.QPushButton(Form)
        self.pbGoShipment.setGeometry(QtCore.QRect(100, 110, 121, 21))
        self.pbGoShipment.setObjectName(_fromUtf8("pbGoShipment"))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(260, 240, 81, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.sbStepPcb = QtGui.QSpinBox(Form)
        self.sbStepPcb.setGeometry(QtCore.QRect(340, 240, 81, 21))
        self.sbStepPcb.setReadOnly(True)
        self.sbStepPcb.setMinimum(-1)
        self.sbStepPcb.setMaximum(2147483647)
        self.sbStepPcb.setObjectName(_fromUtf8("sbStepPcb"))
        self.pbGoStepPcb = QtGui.QPushButton(Form)
        self.pbGoStepPcb.setGeometry(QtCore.QRect(420, 240, 51, 21))
        self.pbGoStepPcb.setObjectName(_fromUtf8("pbGoStepPcb"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(260, 400, 211, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.listDaqData = QtGui.QListWidget(Form)
        self.listDaqData.setGeometry(QtCore.QRect(260, 420, 211, 131))
        self.listDaqData.setObjectName(_fromUtf8("listDaqData"))
        self.pbAddToPlotter = QtGui.QPushButton(Form)
        self.pbAddToPlotter.setGeometry(QtCore.QRect(260, 550, 121, 21))
        self.pbAddToPlotter.setObjectName(_fromUtf8("pbAddToPlotter"))
        self.pbGoPlotter = QtGui.QPushButton(Form)
        self.pbGoPlotter.setGeometry(QtCore.QRect(390, 550, 81, 21))
        self.pbGoPlotter.setObjectName(_fromUtf8("pbGoPlotter"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(260, 130, 131, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(260, 150, 131, 21))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(260, 170, 131, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.pteWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteWriteComment.setGeometry(QtCore.QRect(10, 550, 211, 71))
        self.pteWriteComment.setPlainText(_fromUtf8(""))
        self.pteWriteComment.setObjectName(_fromUtf8("pteWriteComment"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 400, 101, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.pbDeleteComment = QtGui.QPushButton(Form)
        self.pbDeleteComment.setGeometry(QtCore.QRect(110, 400, 111, 21))
        self.pbDeleteComment.setObjectName(_fromUtf8("pbDeleteComment"))
        self.listComments = QtGui.QListWidget(Form)
        self.listComments.setGeometry(QtCore.QRect(10, 420, 211, 121))
        self.listComments.setObjectName(_fromUtf8("listComments"))
        self.pbAddComment = QtGui.QPushButton(Form)
        self.pbAddComment.setGeometry(QtCore.QRect(10, 620, 81, 21))
        self.pbAddComment.setObjectName(_fromUtf8("pbAddComment"))
        self.cbInspection = QtGui.QComboBox(Form)
        self.cbInspection.setGeometry(QtCore.QRect(390, 130, 81, 21))
        self.cbInspection.setObjectName(_fromUtf8("cbInspection"))
        self.cbInspection.addItem(_fromUtf8(""))
        self.cbInspection.addItem(_fromUtf8(""))
        self.cbDaqOK = QtGui.QComboBox(Form)
        self.cbDaqOK.setGeometry(QtCore.QRect(390, 170, 81, 21))
        self.cbDaqOK.setObjectName(_fromUtf8("cbDaqOK"))
        self.cbDaqOK.addItem(_fromUtf8(""))
        self.cbDaqOK.addItem(_fromUtf8(""))
        self.leDaq = QtGui.QLineEdit(Form)
        self.leDaq.setGeometry(QtCore.QRect(390, 150, 81, 20))
        self.leDaq.setText(_fromUtf8(""))
        self.leDaq.setReadOnly(True)
        self.leDaq.setObjectName(_fromUtf8("leDaq"))
        self.cbSize = QtGui.QComboBox(Form)
        self.cbSize.setGeometry(QtCore.QRect(140, 300, 81, 21))
        self.cbSize.setObjectName(_fromUtf8("cbSize"))
        self.cbSize.addItem(_fromUtf8(""))
        self.cbSize.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 70, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 220, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cbShape = QtGui.QComboBox(Form)
        self.cbShape.setGeometry(QtCore.QRect(140, 320, 80, 20))
        self.cbShape.setObjectName(_fromUtf8("cbShape"))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))

        self.retranslateUi(Form)
        self.cbChirality.setCurrentIndex(-1)
        self.cbInspection.setCurrentIndex(-1)
        self.cbDaqOK.setCurrentIndex(-1)
        self.cbSize.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "PCB ID", None))
        self.lineEdit_2.setText(_translate("Form", "Identifier", None))
        self.lineEdit_3.setText(_translate("Form", "Thickness (mm)", None))
        self.lineEdit_4.setText(_translate("Form", "Flatness (mm)", None))
        self.lineEdit_5.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_6.setText(_translate("Form", "Channels", None))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer", None))
        self.lineEdit_8.setText(_translate("Form", "On module", None))
        self.pbGoModule.setText(_translate("Form", "Go to", None))
        self.pbCancel.setText(_translate("Form", "Cancel", None))
        self.pbEdit.setText(_translate("Form", "Edit", None))
        self.pbNew.setText(_translate("Form", "New", None))
        self.pbSave.setText(_translate("Form", "Save", None))
        self.lineEdit_15.setText(_translate("Form", "Shape", None))
        self.lineEdit_13.setText(_translate("Form", "Chirality", None))
        self.lineEdit_16.setText(_translate("Form", "Rotation", None))
        self.cbChirality.setItemText(0, _translate("Form", "achiral", None))
        self.cbChirality.setItemText(1, _translate("Form", "left", None))
        self.cbChirality.setItemText(2, _translate("Form", "right", None))
        self.lineEdit_11.setText(_translate("Form", "location", None))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)", None))
        self.pbGoShipment.setText(_translate("Form", "go to selected", None))
        self.lineEdit_10.setText(_translate("Form", "shipments", None))
        self.lineEdit_9.setText(_translate("Form", "PCB step", None))
        self.pbGoStepPcb.setText(_translate("Form", "Go to", None))
        self.lineEdit_12.setText(_translate("Form", "datasets", None))
        self.pbAddToPlotter.setText(_translate("Form", "add selected to plotter", None))
        self.pbGoPlotter.setText(_translate("Form", "go to plotter", None))
        self.lineEdit_17.setText(_translate("Form", "Inspection", None))
        self.lineEdit_18.setText(_translate("Form", "Data Acquisition dataset", None))
        self.lineEdit_19.setText(_translate("Form", "Data Acquisition OK?", None))
        self.lineEdit_14.setText(_translate("Form", "Comments", None))
        self.pbDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbAddComment.setText(_translate("Form", "add comment", None))
        self.cbInspection.setItemText(0, _translate("Form", "pass", None))
        self.cbInspection.setItemText(1, _translate("Form", "fail", None))
        self.cbDaqOK.setItemText(0, _translate("Form", "yes", None))
        self.cbDaqOK.setItemText(1, _translate("Form", "no", None))
        self.cbSize.setItemText(0, _translate("Form", "8", None))
        self.cbSize.setItemText(1, _translate("Form", "6", None))
        self.label.setText(_translate("Form", "PCB qualification", None))
        self.label_2.setText(_translate("Form", "PCB placement step", None))
        self.cbShape.setItemText(0, _translate("Form", "full", None))
        self.cbShape.setItemText(1, _translate("Form", "half", None))
        self.cbShape.setItemText(2, _translate("Form", "five", None))
        self.cbShape.setItemText(3, _translate("Form", "three", None))
        self.cbShape.setItemText(4, _translate("Form", "semi", None))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)", None))
        self.cbShape.setItemText(6, _translate("Form", "choptwo", None))

