# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_pcb_step.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 705)
        self.sbModule1 = QtWidgets.QSpinBox(Form)
        self.sbModule1.setGeometry(QtCore.QRect(460, 160, 91, 22))
        self.sbModule1.setMinimum(-1)
        self.sbModule1.setMaximum(2147483647)
        self.sbModule1.setObjectName("sbModule1")
        self.pbGoModule1 = QtWidgets.QPushButton(Form)
        self.pbGoModule1.setGeometry(QtCore.QRect(550, 160, 51, 21))
        self.pbGoModule1.setObjectName("pbGoModule1")
        self.pbGoModule2 = QtWidgets.QPushButton(Form)
        self.pbGoModule2.setGeometry(QtCore.QRect(550, 180, 51, 21))
        self.pbGoModule2.setObjectName("pbGoModule2")
        self.sbModule2 = QtWidgets.QSpinBox(Form)
        self.sbModule2.setGeometry(QtCore.QRect(460, 180, 91, 22))
        self.sbModule2.setMinimum(-1)
        self.sbModule2.setMaximum(2147483647)
        self.sbModule2.setObjectName("sbModule2")
        self.sbModule3 = QtWidgets.QSpinBox(Form)
        self.sbModule3.setGeometry(QtCore.QRect(460, 200, 91, 22))
        self.sbModule3.setMinimum(-1)
        self.sbModule3.setMaximum(2147483647)
        self.sbModule3.setObjectName("sbModule3")
        self.pbGoModule3 = QtWidgets.QPushButton(Form)
        self.pbGoModule3.setGeometry(QtCore.QRect(550, 200, 51, 21))
        self.pbGoModule3.setObjectName("pbGoModule3")
        self.pbGoModule4 = QtWidgets.QPushButton(Form)
        self.pbGoModule4.setGeometry(QtCore.QRect(550, 260, 51, 21))
        self.pbGoModule4.setObjectName("pbGoModule4")
        self.pbGoModule5 = QtWidgets.QPushButton(Form)
        self.pbGoModule5.setGeometry(QtCore.QRect(550, 220, 51, 21))
        self.pbGoModule5.setObjectName("pbGoModule5")
        self.sbModule4 = QtWidgets.QSpinBox(Form)
        self.sbModule4.setGeometry(QtCore.QRect(460, 260, 91, 21))
        self.sbModule4.setMinimum(-1)
        self.sbModule4.setMaximum(2147483647)
        self.sbModule4.setObjectName("sbModule4")
        self.pbGoModule6 = QtWidgets.QPushButton(Form)
        self.pbGoModule6.setGeometry(QtCore.QRect(550, 240, 51, 21))
        self.pbGoModule6.setObjectName("pbGoModule6")
        self.sbModule5 = QtWidgets.QSpinBox(Form)
        self.sbModule5.setGeometry(QtCore.QRect(460, 220, 91, 22))
        self.sbModule5.setMinimum(-1)
        self.sbModule5.setMaximum(2147483647)
        self.sbModule5.setObjectName("sbModule5")
        self.sbModule6 = QtWidgets.QSpinBox(Form)
        self.sbModule6.setGeometry(QtCore.QRect(460, 240, 91, 21))
        self.sbModule6.setMinimum(-1)
        self.sbModule6.setMaximum(2147483647)
        self.sbModule6.setObjectName("sbModule6")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 140, 71, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(460, 140, 141, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 160, 71, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 180, 71, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 200, 71, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 220, 71, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 240, 71, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(610, 260, 131, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.leCureTemperature = QtWidgets.QLineEdit(Form)
        self.leCureTemperature.setGeometry(QtCore.QRect(740, 240, 141, 20))
        self.leCureTemperature.setObjectName("leCureTemperature")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.leUserPerformed = QtWidgets.QLineEdit(Form)
        self.leUserPerformed.setGeometry(QtCore.QRect(760, 140, 131, 20))
        self.leUserPerformed.setObjectName("leUserPerformed")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(610, 240, 131, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.pbSave.setObjectName("pbSave")
        self.sbID = QtWidgets.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(100, 10, 71, 21))
        self.sbID.setObjectName("sbID")
        self.pbNew = QtWidgets.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.pbNew.setObjectName("pbNew")
        self.leCureHumidity = QtWidgets.QLineEdit(Form)
        self.leCureHumidity.setGeometry(QtCore.QRect(740, 260, 141, 21))
        self.leCureHumidity.setObjectName("leCureHumidity")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(170, 40, 71, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 140, 151, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.sbTool6 = QtWidgets.QSpinBox(Form)
        self.sbTool6.setGeometry(QtCore.QRect(90, 260, 51, 21))
        self.sbTool6.setMinimum(-1)
        self.sbTool6.setMaximum(2147483647)
        self.sbTool6.setObjectName("sbTool6")
        self.sbTool1 = QtWidgets.QSpinBox(Form)
        self.sbTool1.setGeometry(QtCore.QRect(90, 160, 51, 22))
        self.sbTool1.setMinimum(-1)
        self.sbTool1.setMaximum(2147483647)
        self.sbTool1.setObjectName("sbTool1")
        self.pbGoTool5 = QtWidgets.QPushButton(Form)
        self.pbGoTool5.setGeometry(QtCore.QRect(140, 240, 51, 21))
        self.pbGoTool5.setObjectName("pbGoTool5")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 140, 101, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.sbTool2 = QtWidgets.QSpinBox(Form)
        self.sbTool2.setGeometry(QtCore.QRect(90, 180, 51, 22))
        self.sbTool2.setMinimum(-1)
        self.sbTool2.setMaximum(2147483647)
        self.sbTool2.setObjectName("sbTool2")
        self.pbGoTool1 = QtWidgets.QPushButton(Form)
        self.pbGoTool1.setGeometry(QtCore.QRect(140, 160, 51, 21))
        self.pbGoTool1.setObjectName("pbGoTool1")
        self.pbGoTool4 = QtWidgets.QPushButton(Form)
        self.pbGoTool4.setGeometry(QtCore.QRect(140, 220, 51, 21))
        self.pbGoTool4.setObjectName("pbGoTool4")
        self.pbGoTool3 = QtWidgets.QPushButton(Form)
        self.pbGoTool3.setGeometry(QtCore.QRect(140, 200, 51, 21))
        self.pbGoTool3.setObjectName("pbGoTool3")
        self.sbTool3 = QtWidgets.QSpinBox(Form)
        self.sbTool3.setGeometry(QtCore.QRect(90, 200, 51, 22))
        self.sbTool3.setMinimum(-1)
        self.sbTool3.setMaximum(2147483647)
        self.sbTool3.setObjectName("sbTool3")
        self.pbGoTool6 = QtWidgets.QPushButton(Form)
        self.pbGoTool6.setGeometry(QtCore.QRect(140, 260, 51, 21))
        self.pbGoTool6.setObjectName("pbGoTool6")
        self.sbTool4 = QtWidgets.QSpinBox(Form)
        self.sbTool4.setGeometry(QtCore.QRect(90, 220, 51, 22))
        self.sbTool4.setMinimum(-1)
        self.sbTool4.setMaximum(2147483647)
        self.sbTool4.setObjectName("sbTool4")
        self.pbGoTool2 = QtWidgets.QPushButton(Form)
        self.pbGoTool2.setGeometry(QtCore.QRect(140, 180, 51, 21))
        self.pbGoTool2.setObjectName("pbGoTool2")
        self.sbTool5 = QtWidgets.QSpinBox(Form)
        self.sbTool5.setGeometry(QtCore.QRect(90, 240, 51, 22))
        self.sbTool5.setMinimum(-1)
        self.sbTool5.setMaximum(2147483647)
        self.sbTool5.setObjectName("sbTool5")
        self.sbPcb1 = QtWidgets.QSpinBox(Form)
        self.sbPcb1.setGeometry(QtCore.QRect(200, 160, 71, 22))
        self.sbPcb1.setMinimum(-1)
        self.sbPcb1.setMaximum(2147483647)
        self.sbPcb1.setObjectName("sbPcb1")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(200, 140, 121, 20))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pbGoPcb5 = QtWidgets.QPushButton(Form)
        self.pbGoPcb5.setGeometry(QtCore.QRect(270, 240, 51, 21))
        self.pbGoPcb5.setObjectName("pbGoPcb5")
        self.sbPcb2 = QtWidgets.QSpinBox(Form)
        self.sbPcb2.setGeometry(QtCore.QRect(200, 180, 71, 22))
        self.sbPcb2.setMinimum(-1)
        self.sbPcb2.setMaximum(2147483647)
        self.sbPcb2.setObjectName("sbPcb2")
        self.sbProtomodule4 = QtWidgets.QSpinBox(Form)
        self.sbProtomodule4.setGeometry(QtCore.QRect(330, 220, 71, 22))
        self.sbProtomodule4.setMinimum(-1)
        self.sbProtomodule4.setMaximum(2147483647)
        self.sbProtomodule4.setObjectName("sbProtomodule4")
        self.sbProtomodule2 = QtWidgets.QSpinBox(Form)
        self.sbProtomodule2.setGeometry(QtCore.QRect(330, 180, 71, 22))
        self.sbProtomodule2.setMinimum(-1)
        self.sbProtomodule2.setMaximum(2147483647)
        self.sbProtomodule2.setObjectName("sbProtomodule2")
        self.sbPcb5 = QtWidgets.QSpinBox(Form)
        self.sbPcb5.setGeometry(QtCore.QRect(200, 240, 71, 21))
        self.sbPcb5.setMinimum(-1)
        self.sbPcb5.setMaximum(2147483647)
        self.sbPcb5.setObjectName("sbPcb5")
        self.pbGoProtomodule1 = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule1.setGeometry(QtCore.QRect(400, 160, 51, 21))
        self.pbGoProtomodule1.setObjectName("pbGoProtomodule1")
        self.sbPcb6 = QtWidgets.QSpinBox(Form)
        self.sbPcb6.setGeometry(QtCore.QRect(200, 260, 71, 21))
        self.sbPcb6.setMinimum(-1)
        self.sbPcb6.setMaximum(2147483647)
        self.sbPcb6.setObjectName("sbPcb6")
        self.pbGoPcb1 = QtWidgets.QPushButton(Form)
        self.pbGoPcb1.setGeometry(QtCore.QRect(270, 160, 51, 21))
        self.pbGoPcb1.setObjectName("pbGoPcb1")
        self.sbProtomodule5 = QtWidgets.QSpinBox(Form)
        self.sbProtomodule5.setGeometry(QtCore.QRect(330, 240, 71, 21))
        self.sbProtomodule5.setMinimum(-1)
        self.sbProtomodule5.setMaximum(2147483647)
        self.sbProtomodule5.setObjectName("sbProtomodule5")
        self.pbGoProtomodule6 = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule6.setGeometry(QtCore.QRect(400, 260, 51, 21))
        self.pbGoProtomodule6.setObjectName("pbGoProtomodule6")
        self.pbGoProtomodule2 = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule2.setGeometry(QtCore.QRect(400, 180, 51, 21))
        self.pbGoProtomodule2.setObjectName("pbGoProtomodule2")
        self.pbGoProtomodule5 = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule5.setGeometry(QtCore.QRect(400, 240, 51, 21))
        self.pbGoProtomodule5.setObjectName("pbGoProtomodule5")
        self.pbGoProtomodule3 = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule3.setGeometry(QtCore.QRect(400, 200, 51, 21))
        self.pbGoProtomodule3.setObjectName("pbGoProtomodule3")
        self.pbGoPcb4 = QtWidgets.QPushButton(Form)
        self.pbGoPcb4.setGeometry(QtCore.QRect(270, 220, 51, 21))
        self.pbGoPcb4.setObjectName("pbGoPcb4")
        self.pbGoPcb2 = QtWidgets.QPushButton(Form)
        self.pbGoPcb2.setGeometry(QtCore.QRect(270, 180, 51, 21))
        self.pbGoPcb2.setObjectName("pbGoPcb2")
        self.pbGoPcb3 = QtWidgets.QPushButton(Form)
        self.pbGoPcb3.setGeometry(QtCore.QRect(270, 200, 51, 21))
        self.pbGoPcb3.setObjectName("pbGoPcb3")
        self.sbProtomodule1 = QtWidgets.QSpinBox(Form)
        self.sbProtomodule1.setGeometry(QtCore.QRect(330, 160, 71, 22))
        self.sbProtomodule1.setMinimum(-1)
        self.sbProtomodule1.setMaximum(2147483647)
        self.sbProtomodule1.setObjectName("sbProtomodule1")
        self.sbPcb4 = QtWidgets.QSpinBox(Form)
        self.sbPcb4.setGeometry(QtCore.QRect(200, 220, 71, 22))
        self.sbPcb4.setMinimum(-1)
        self.sbPcb4.setMaximum(2147483647)
        self.sbPcb4.setObjectName("sbPcb4")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(330, 140, 121, 20))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.sbProtomodule3 = QtWidgets.QSpinBox(Form)
        self.sbProtomodule3.setGeometry(QtCore.QRect(330, 200, 71, 22))
        self.sbProtomodule3.setMinimum(-1)
        self.sbProtomodule3.setMaximum(2147483647)
        self.sbProtomodule3.setObjectName("sbProtomodule3")
        self.sbPcb3 = QtWidgets.QSpinBox(Form)
        self.sbPcb3.setGeometry(QtCore.QRect(200, 200, 71, 22))
        self.sbPcb3.setMinimum(-1)
        self.sbPcb3.setMaximum(2147483647)
        self.sbPcb3.setObjectName("sbPcb3")
        self.sbProtomodule6 = QtWidgets.QSpinBox(Form)
        self.sbProtomodule6.setGeometry(QtCore.QRect(330, 260, 71, 21))
        self.sbProtomodule6.setMinimum(-1)
        self.sbProtomodule6.setMaximum(2147483647)
        self.sbProtomodule6.setObjectName("sbProtomodule6")
        self.pbGoProtomodule4 = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule4.setGeometry(QtCore.QRect(400, 220, 51, 21))
        self.pbGoProtomodule4.setObjectName("pbGoProtomodule4")
        self.pbGoPcb6 = QtWidgets.QPushButton(Form)
        self.pbGoPcb6.setGeometry(QtCore.QRect(270, 260, 51, 21))
        self.pbGoPcb6.setObjectName("pbGoPcb6")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 330, 161, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pbGoTrayAssembly = QtWidgets.QPushButton(Form)
        self.pbGoTrayAssembly.setGeometry(QtCore.QRect(240, 310, 51, 21))
        self.pbGoTrayAssembly.setObjectName("pbGoTrayAssembly")
        self.sbBatchAraldite = QtWidgets.QSpinBox(Form)
        self.sbBatchAraldite.setGeometry(QtCore.QRect(170, 330, 71, 21))
        self.sbBatchAraldite.setMinimum(-1)
        self.sbBatchAraldite.setMaximum(999999)
        self.sbBatchAraldite.setObjectName("sbBatchAraldite")
        self.pbGoTrayComponent = QtWidgets.QPushButton(Form)
        self.pbGoTrayComponent.setGeometry(QtCore.QRect(240, 290, 51, 21))
        self.pbGoTrayComponent.setObjectName("pbGoTrayComponent")
        self.sbTrayComponent = QtWidgets.QSpinBox(Form)
        self.sbTrayComponent.setGeometry(QtCore.QRect(170, 290, 71, 21))
        self.sbTrayComponent.setMinimum(-1)
        self.sbTrayComponent.setMaximum(999999)
        self.sbTrayComponent.setObjectName("sbTrayComponent")
        self.pbGoBatchAraldite = QtWidgets.QPushButton(Form)
        self.pbGoBatchAraldite.setGeometry(QtCore.QRect(240, 330, 51, 21))
        self.pbGoBatchAraldite.setObjectName("pbGoBatchAraldite")
        self.lineEdit_24 = QtWidgets.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 290, 161, 21))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 310, 161, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.sbTrayAssembly = QtWidgets.QSpinBox(Form)
        self.sbTrayAssembly.setGeometry(QtCore.QRect(170, 310, 71, 21))
        self.sbTrayAssembly.setMinimum(-1)
        self.sbTrayAssembly.setMaximum(999999)
        self.sbTrayAssembly.setObjectName("sbTrayAssembly")
        self.lineEdit_26 = QtWidgets.QLineEdit(Form)
        self.lineEdit_26.setGeometry(QtCore.QRect(10, 540, 61, 20))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.listIssues = QtWidgets.QListWidget(Form)
        self.listIssues.setGeometry(QtCore.QRect(10, 370, 721, 171))
        self.listIssues.setObjectName("listIssues")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(70, 540, 171, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(610, 200, 131, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pbRunStartNow = QtWidgets.QPushButton(Form)
        self.pbRunStartNow.setGeometry(QtCore.QRect(890, 200, 91, 21))
        self.pbRunStartNow.setObjectName("pbRunStartNow")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(610, 160, 151, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.leLocation = QtWidgets.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(760, 160, 131, 20))
        self.leLocation.setObjectName("leLocation")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(160, 110, 81, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lineEdit_25 = QtWidgets.QLineEdit(Form)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 110, 151, 20))
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.dtRunStart = QtWidgets.QDateTimeEdit(Form)
        self.dtRunStart.setGeometry(QtCore.QRect(740, 200, 151, 21))
        self.dtRunStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dtRunStart.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.dtRunStart.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dtRunStart.setCalendarPopup(True)
        self.dtRunStart.setObjectName("dtRunStart")

        self.retranslateUi(Form)
        self.cbInstitution.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbGoModule1.setText(_translate("Form", "go to"))
        self.pbGoModule2.setText(_translate("Form", "go to"))
        self.pbGoModule3.setText(_translate("Form", "go to"))
        self.pbGoModule4.setText(_translate("Form", "go to"))
        self.pbGoModule5.setText(_translate("Form", "go to"))
        self.pbGoModule6.setText(_translate("Form", "go to"))
        self.lineEdit_12.setText(_translate("Form", "position"))
        self.lineEdit_14.setText(_translate("Form", "Module ID assigned"))
        self.lineEdit_15.setText(_translate("Form", "1 (1, 1)"))
        self.lineEdit_16.setText(_translate("Form", "2 (1, 2)"))
        self.lineEdit_17.setText(_translate("Form", "3 (2, 1)"))
        self.lineEdit_18.setText(_translate("Form", "4 (2, 2)"))
        self.lineEdit_19.setText(_translate("Form", "5 (3, 1)"))
        self.lineEdit_20.setText(_translate("Form", "6 (3, 2)"))
        self.lineEdit_9.setText(_translate("Form", "cure humidity (%)"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.lineEdit_8.setText(_translate("Form", "cure temp (C)"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.pbNew.setText(_translate("Form", "New"))
        self.lineEdit.setText(_translate("Form", "PCB step ID"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.lineEdit_2.setText(_translate("Form", "who performed step"))
        self.pbGoTool5.setText(_translate("Form", "go to"))
        self.lineEdit_13.setText(_translate("Form", "PCB tool ID"))
        self.pbGoTool1.setText(_translate("Form", "go to"))
        self.pbGoTool4.setText(_translate("Form", "go to"))
        self.pbGoTool3.setText(_translate("Form", "go to"))
        self.pbGoTool6.setText(_translate("Form", "go to"))
        self.pbGoTool2.setText(_translate("Form", "go to"))
        self.lineEdit_23.setText(_translate("Form", "PCB ID"))
        self.pbGoPcb5.setText(_translate("Form", "go to"))
        self.pbGoProtomodule1.setText(_translate("Form", "go to"))
        self.pbGoPcb1.setText(_translate("Form", "go to"))
        self.pbGoProtomodule6.setText(_translate("Form", "go to"))
        self.pbGoProtomodule2.setText(_translate("Form", "go to"))
        self.pbGoProtomodule5.setText(_translate("Form", "go to"))
        self.pbGoProtomodule3.setText(_translate("Form", "go to"))
        self.pbGoPcb4.setText(_translate("Form", "go to"))
        self.pbGoPcb2.setText(_translate("Form", "go to"))
        self.pbGoPcb3.setText(_translate("Form", "go to"))
        self.lineEdit_22.setText(_translate("Form", "Protomodule ID"))
        self.pbGoProtomodule4.setText(_translate("Form", "go to"))
        self.pbGoPcb6.setText(_translate("Form", "go to"))
        self.lineEdit_11.setText(_translate("Form", "araldite batch"))
        self.pbGoTrayAssembly.setText(_translate("Form", "go to"))
        self.pbGoTrayComponent.setText(_translate("Form", "go to"))
        self.pbGoBatchAraldite.setText(_translate("Form", "go to"))
        self.lineEdit_24.setText(_translate("Form", "component tray (PCB)"))
        self.lineEdit_21.setText(_translate("Form", "assembly tray"))
        self.lineEdit_26.setText(_translate("Form", "Status:"))
        self.listIssues.setToolTip(_translate("Form", "list of issues"))
        self.lineEdit_10.setText(_translate("Form", "run start"))
        self.pbRunStartNow.setText(_translate("Form", "set to now"))
        self.lineEdit_3.setText(_translate("Form", "location"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "NTU"))
        self.lineEdit_25.setText(_translate("Form", "Institution (for tools)"))

