# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_baseplate.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 720)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(570, 150, 481, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pages_ui/baseplate_frame_80.png"))
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 261, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.pbSave = QtWidgets.QPushButton(self.frame_2)
        self.pbSave.setGeometry(QtCore.QRect(90, 50, 71, 21))
        self.pbSave.setObjectName("pbSave")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(1, 1, 151, 20))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pbCancel = QtWidgets.QPushButton(self.frame_2)
        self.pbCancel.setGeometry(QtCore.QRect(170, 50, 71, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbNew = QtWidgets.QPushButton(self.frame_2)
        self.pbNew.setGeometry(QtCore.QRect(0, 50, 71, 21))
        self.pbNew.setObjectName("pbNew")
        self.pbEdit = QtWidgets.QPushButton(self.frame_2)
        self.pbEdit.setGeometry(QtCore.QRect(0, 70, 81, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.leID = QtWidgets.QLineEdit(self.frame_2)
        self.leID.setGeometry(QtCore.QRect(150, 0, 111, 20))
        self.leID.setText("")
        self.leID.setReadOnly(True)
        self.leID.setObjectName("leID")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 70, 61, 20))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.leStatus = QtWidgets.QLineEdit(self.frame_2)
        self.leStatus.setGeometry(QtCore.QRect(150, 70, 111, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.pbLoad = QtWidgets.QPushButton(self.frame_2)
        self.pbLoad.setGeometry(QtCore.QRect(60, 20, 131, 21))
        self.pbLoad.setObjectName("pbLoad")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(20, 120, 261, 561))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.cbChirality = QtWidgets.QComboBox(self.frame_3)
        self.cbChirality.setGeometry(QtCore.QRect(180, 280, 80, 20))
        self.cbChirality.setObjectName("cbChirality")
        self.cbChirality.addItem("")
        self.cbChirality.addItem("")
        self.cbChirality.addItem("")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(1, 239, 181, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(1, 41, 121, 20))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.cbShape = QtWidgets.QComboBox(self.frame_3)
        self.cbShape.setGeometry(QtCore.QRect(180, 260, 80, 20))
        self.cbShape.setObjectName("cbShape")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.pbGoShipment = QtWidgets.QPushButton(self.frame_3)
        self.pbGoShipment.setGeometry(QtCore.QRect(120, 60, 141, 21))
        self.pbGoShipment.setObjectName("pbGoShipment")
        self.leManufacturer = QtWidgets.QLineEdit(self.frame_3)
        self.leManufacturer.setGeometry(QtCore.QRect(180, 200, 80, 20))
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName("leManufacturer")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(1, 60, 121, 20))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(1, 199, 181, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(1, 219, 181, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.leLocation = QtWidgets.QLineEdit(self.frame_3)
        self.leLocation.setGeometry(QtCore.QRect(119, 41, 141, 20))
        self.leLocation.setText("")
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName("leLocation")
        self.listShipments = QtWidgets.QListWidget(self.frame_3)
        self.listShipments.setGeometry(QtCore.QRect(0, 80, 261, 91))
        self.listShipments.setObjectName("listShipments")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(1, 280, 181, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.dsbNomThickness = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.dsbNomThickness.setGeometry(QtCore.QRect(180, 239, 80, 21))
        self.dsbNomThickness.setReadOnly(True)
        self.dsbNomThickness.setDecimals(3)
        self.dsbNomThickness.setMinimum(-1.0)
        self.dsbNomThickness.setMaximum(2147483647.0)
        self.dsbNomThickness.setSingleStep(0.05)
        self.dsbNomThickness.setObjectName("dsbNomThickness")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_15.setGeometry(QtCore.QRect(1, 260, 181, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(0, 300, 261, 261))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.pbAddComment = QtWidgets.QPushButton(self.frame)
        self.pbAddComment.setGeometry(QtCore.QRect(0, 240, 111, 21))
        self.pbAddComment.setObjectName("pbAddComment")
        self.pteWriteComment = QtWidgets.QPlainTextEdit(self.frame)
        self.pteWriteComment.setGeometry(QtCore.QRect(0, 170, 261, 71))
        self.pteWriteComment.setPlainText("")
        self.pteWriteComment.setObjectName("pteWriteComment")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(1, 20, 141, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.listComments = QtWidgets.QListWidget(self.frame)
        self.listComments.setGeometry(QtCore.QRect(0, 40, 261, 121))
        self.listComments.setObjectName("listComments")
        self.pbDeleteComment = QtWidgets.QPushButton(self.frame)
        self.pbDeleteComment.setGeometry(QtCore.QRect(140, 20, 121, 21))
        self.pbDeleteComment.setObjectName("pbDeleteComment")
        self.cbMaterial = QtWidgets.QComboBox(self.frame_3)
        self.cbMaterial.setGeometry(QtCore.QRect(180, 219, 81, 21))
        self.cbMaterial.setObjectName("cbMaterial")
        self.cbMaterial.addItem("")
        self.cbMaterial.addItem("")
        self.cbMaterial.addItem("")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_39.setGeometry(QtCore.QRect(1, 21, 121, 20))
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_38.setGeometry(QtCore.QRect(1, 1, 121, 20))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.leInsertUser = QtWidgets.QLineEdit(self.frame_3)
        self.leInsertUser.setGeometry(QtCore.QRect(120, 1, 141, 20))
        self.leInsertUser.setText("")
        self.leInsertUser.setReadOnly(True)
        self.leInsertUser.setObjectName("leInsertUser")
        self.leBarcode = QtWidgets.QLineEdit(self.frame_3)
        self.leBarcode.setGeometry(QtCore.QRect(180, 180, 80, 20))
        self.leBarcode.setText("")
        self.leBarcode.setReadOnly(True)
        self.leBarcode.setObjectName("leBarcode")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(1, 180, 181, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.cbInstitution = QtWidgets.QComboBox(self.frame_3)
        self.cbInstitution.setGeometry(QtCore.QRect(120, 20, 141, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lineEdit_4.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_3.raise_()
        self.leLocation.raise_()
        self.listShipments.raise_()
        self.lineEdit_13.raise_()
        self.dsbNomThickness.raise_()
        self.lineEdit_15.raise_()
        self.frame.raise_()
        self.cbMaterial.raise_()
        self.pbGoShipment.raise_()
        self.leManufacturer.raise_()
        self.cbShape.raise_()
        self.cbChirality.raise_()
        self.lineEdit_39.raise_()
        self.lineEdit_38.raise_()
        self.leInsertUser.raise_()
        self.lineEdit_9.raise_()
        self.leBarcode.raise_()
        self.cbInstitution.raise_()
        self.pbGoProtomodule = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule.setGeometry(QtCore.QRect(510, 330, 51, 21))
        self.pbGoProtomodule.setObjectName("pbGoProtomodule")
        self.pbGoStepSensor = QtWidgets.QPushButton(Form)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(510, 310, 51, 21))
        self.pbGoStepSensor.setObjectName("pbGoStepSensor")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(310, 330, 121, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(310, 400, 121, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(310, 310, 121, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.sbStepSensor = QtWidgets.QSpinBox(Form)
        self.sbStepSensor.setGeometry(QtCore.QRect(430, 310, 81, 21))
        self.sbStepSensor.setReadOnly(True)
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName("sbStepSensor")
        self.pbGoModule = QtWidgets.QPushButton(Form)
        self.pbGoModule.setGeometry(QtCore.QRect(510, 400, 51, 21))
        self.pbGoModule.setObjectName("pbGoModule")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(305, 219, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(310, 290, 211, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(310, 380, 211, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(720, 350, 201, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(990, 350, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(900, 180, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(710, 180, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(655, 350, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(700, 510, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(900, 510, 16, 16))
        self.label_16.setObjectName("label_16")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setEnabled(False)
        self.frame_7.setGeometry(QtCore.QRect(305, 239, 241, 21))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.pbGoStepKapton = QtWidgets.QPushButton(self.frame_7)
        self.pbGoStepKapton.setEnabled(False)
        self.pbGoStepKapton.setGeometry(QtCore.QRect(190, 0, 51, 21))
        self.pbGoStepKapton.setObjectName("pbGoStepKapton")
        self.sbStepKapton = QtWidgets.QSpinBox(self.frame_7)
        self.sbStepKapton.setEnabled(False)
        self.sbStepKapton.setGeometry(QtCore.QRect(110, 1, 81, 19))
        self.sbStepKapton.setReadOnly(True)
        self.sbStepKapton.setMinimum(-1)
        self.sbStepKapton.setMaximum(2147483647)
        self.sbStepKapton.setObjectName("sbStepKapton")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_18.setEnabled(False)
        self.lineEdit_18.setGeometry(QtCore.QRect(1, 1, 111, 19))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.leProtomodule = QtWidgets.QLineEdit(Form)
        self.leProtomodule.setGeometry(QtCore.QRect(430, 330, 80, 20))
        self.leProtomodule.setReadOnly(True)
        self.leProtomodule.setObjectName("leProtomodule")
        self.leModule = QtWidgets.QLineEdit(Form)
        self.leModule.setGeometry(QtCore.QRect(430, 400, 80, 20))
        self.leModule.setReadOnly(True)
        self.leModule.setObjectName("leModule")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(310, 30, 261, 16))
        self.label_5.setObjectName("label_5")
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(310, 50, 241, 141))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(1, 120, 161, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_36.setGeometry(QtCore.QRect(1, 40, 161, 20))
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_37.setGeometry(QtCore.QRect(1, 80, 161, 20))
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_40.setGeometry(QtCore.QRect(1, 100, 161, 20))
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.dsbC2 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.dsbC2.setEnabled(True)
        self.dsbC2.setGeometry(QtCore.QRect(160, 40, 79, 20))
        self.dsbC2.setDecimals(3)
        self.dsbC2.setMinimum(-8192.0)
        self.dsbC2.setMaximum(8191.0)
        self.dsbC2.setSingleStep(0.05)
        self.dsbC2.setObjectName("dsbC2")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_41.setGeometry(QtCore.QRect(1, 0, 161, 20))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_42.setGeometry(QtCore.QRect(1, 20, 161, 20))
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.dsbC5 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.dsbC5.setEnabled(True)
        self.dsbC5.setGeometry(QtCore.QRect(160, 100, 79, 20))
        self.dsbC5.setDecimals(3)
        self.dsbC5.setMinimum(-8192.0)
        self.dsbC5.setMaximum(8191.0)
        self.dsbC5.setSingleStep(0.05)
        self.dsbC5.setObjectName("dsbC5")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_43.setGeometry(QtCore.QRect(1, 60, 161, 20))
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.dsbC1 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.dsbC1.setEnabled(True)
        self.dsbC1.setGeometry(QtCore.QRect(160, 20, 79, 20))
        self.dsbC1.setDecimals(3)
        self.dsbC1.setMinimum(-8192.0)
        self.dsbC1.setMaximum(8191.0)
        self.dsbC1.setSingleStep(0.05)
        self.dsbC1.setObjectName("dsbC1")
        self.dsbC0 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.dsbC0.setEnabled(True)
        self.dsbC0.setGeometry(QtCore.QRect(160, 0, 79, 20))
        self.dsbC0.setDecimals(3)
        self.dsbC0.setMinimum(-8192.0)
        self.dsbC0.setMaximum(8191.0)
        self.dsbC0.setSingleStep(0.05)
        self.dsbC0.setObjectName("dsbC0")
        self.dsbC3 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.dsbC3.setEnabled(True)
        self.dsbC3.setGeometry(QtCore.QRect(160, 60, 79, 21))
        self.dsbC3.setDecimals(3)
        self.dsbC3.setMinimum(-8192.0)
        self.dsbC3.setMaximum(8191.0)
        self.dsbC3.setSingleStep(0.05)
        self.dsbC3.setObjectName("dsbC3")
        self.dsbC4 = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.dsbC4.setEnabled(True)
        self.dsbC4.setGeometry(QtCore.QRect(160, 80, 79, 21))
        self.dsbC4.setDecimals(3)
        self.dsbC4.setMinimum(-8192.0)
        self.dsbC4.setMaximum(8191.0)
        self.dsbC4.setSingleStep(0.05)
        self.dsbC4.setObjectName("dsbC4")
        self.leFlatness = QtWidgets.QLineEdit(self.frame_4)
        self.leFlatness.setGeometry(QtCore.QRect(160, 120, 80, 20))
        self.leFlatness.setReadOnly(True)
        self.leFlatness.setObjectName("leFlatness")

        self.retranslateUi(Form)
        self.cbChirality.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        self.cbMaterial.setCurrentIndex(-1)
        self.cbInstitution.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit.setText(_translate("Form", "Baseplate ID"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbNew.setText(_translate("Form", "New"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.lineEdit_6.setText(_translate("Form", "Status:"))
        self.pbLoad.setText(_translate("Form", "Load / check DB"))
        self.cbChirality.setItemText(0, _translate("Form", "achiral"))
        self.cbChirality.setItemText(1, _translate("Form", "left"))
        self.cbChirality.setItemText(2, _translate("Form", "right"))
        self.lineEdit_4.setText(_translate("Form", "Nominal thickness (mm)"))
        self.lineEdit_11.setText(_translate("Form", "Location"))
        self.cbShape.setItemText(0, _translate("Form", "full"))
        self.cbShape.setItemText(1, _translate("Form", "half"))
        self.cbShape.setItemText(2, _translate("Form", "five"))
        self.cbShape.setItemText(3, _translate("Form", "three"))
        self.cbShape.setItemText(4, _translate("Form", "semi"))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)"))
        self.cbShape.setItemText(6, _translate("Form", "choptwo"))
        self.pbGoShipment.setText(_translate("Form", "Go to selected"))
        self.lineEdit_10.setText(_translate("Form", "Shipments"))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer"))
        self.lineEdit_3.setText(_translate("Form", "Type (material)"))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)"))
        self.lineEdit_13.setText(_translate("Form", "Chirality"))
        self.lineEdit_15.setText(_translate("Form", "Shape"))
        self.pbAddComment.setText(_translate("Form", "Add comment"))
        self.lineEdit_14.setText(_translate("Form", "Comments"))
        self.pbDeleteComment.setText(_translate("Form", "Delete selected"))
        self.cbMaterial.setItemText(0, _translate("Form", "Cu"))
        self.cbMaterial.setItemText(1, _translate("Form", "CuW"))
        self.cbMaterial.setItemText(2, _translate("Form", "PCB"))
        self.lineEdit_39.setText(_translate("Form", "Institution"))
        self.lineEdit_38.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_38.setText(_translate("Form", "User name"))
        self.lineEdit_9.setText(_translate("Form", "Barcode"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "HEPHY"))
        self.cbInstitution.setItemText(5, _translate("Form", "HPK"))
        self.pbGoProtomodule.setText(_translate("Form", "Go to"))
        self.pbGoStepSensor.setText(_translate("Form", "Go to"))
        self.lineEdit_17.setText(_translate("Form", "On protomodule"))
        self.lineEdit_8.setText(_translate("Form", "On module"))
        self.lineEdit_19.setText(_translate("Form", "Sensor step"))
        self.pbGoModule.setText(_translate("Form", "Go to"))
        self.label_3.setText(_translate("Form", "Kapton application"))
        self.label_8.setText(_translate("Form", "Sensor application"))
        self.label_9.setText(_translate("Form", "Module"))
        self.label_10.setText(_translate("Form", "corner numbering reference"))
        self.label_11.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "1"))
        self.label_13.setText(_translate("Form", "2"))
        self.label_14.setText(_translate("Form", "3"))
        self.label_15.setText(_translate("Form", "4"))
        self.label_16.setText(_translate("Form", "5"))
        self.pbGoStepKapton.setText(_translate("Form", "Go to"))
        self.lineEdit_18.setText(_translate("Form", "Kapton step"))
        self.label_5.setText(_translate("Form", "Baseplate qualification & preparation"))
        self.lineEdit_12.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_12.setText(_translate("Form", "Flatness (mm)"))
        self.lineEdit_36.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_36.setText(_translate("Form", "Corner height 2"))
        self.lineEdit_37.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_37.setText(_translate("Form", "Corner height 4"))
        self.lineEdit_40.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_40.setText(_translate("Form", "Corner height 5"))
        self.dsbC2.setToolTip(_translate("Form", "Corner 2"))
        self.lineEdit_41.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_41.setText(_translate("Form", "Corner height 0 (mm)"))
        self.lineEdit_42.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_42.setText(_translate("Form", "Corner height 1"))
        self.dsbC5.setToolTip(_translate("Form", "Corner 5"))
        self.lineEdit_43.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_43.setText(_translate("Form", "Corner height 3"))
        self.dsbC1.setToolTip(_translate("Form", "Corner 1"))
        self.dsbC0.setToolTip(_translate("Form", "Corner 0 (the corner with the oblong hole)"))
        self.dsbC3.setToolTip(_translate("Form", "Corner 3"))
        self.dsbC4.setToolTip(_translate("Form", "Corner 4"))

