# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_tooling.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbSensorToolID = QtGui.QSpinBox(Form)
        self.sbSensorToolID.setGeometry(QtCore.QRect(90, 10, 51, 21))
        self.sbSensorToolID.setMaximum(2147483647)
        self.sbSensorToolID.setObjectName(_fromUtf8("sbSensorToolID"))
        self.listSensorToolComments = QtGui.QListWidget(Form)
        self.listSensorToolComments.setGeometry(QtCore.QRect(10, 100, 251, 121))
        self.listSensorToolComments.setObjectName(_fromUtf8("listSensorToolComments"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.dsbSensorToolSize = QtGui.QDoubleSpinBox(Form)
        self.dsbSensorToolSize.setGeometry(QtCore.QRect(90, 30, 51, 21))
        self.dsbSensorToolSize.setMaximum(100.0)
        self.dsbSensorToolSize.setObjectName(_fromUtf8("dsbSensorToolSize"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pbSensorToolDeleteComment = QtGui.QPushButton(Form)
        self.pbSensorToolDeleteComment.setGeometry(QtCore.QRect(130, 80, 131, 21))
        self.pbSensorToolDeleteComment.setObjectName(_fromUtf8("pbSensorToolDeleteComment"))
        self.pteSensorToolWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteSensorToolWriteComment.setGeometry(QtCore.QRect(10, 230, 251, 71))
        self.pteSensorToolWriteComment.setObjectName(_fromUtf8("pteSensorToolWriteComment"))
        self.pbSensorToolAddComment = QtGui.QPushButton(Form)
        self.pbSensorToolAddComment.setGeometry(QtCore.QRect(10, 300, 81, 23))
        self.pbSensorToolAddComment.setObjectName(_fromUtf8("pbSensorToolAddComment"))
        self.pbPcbToolAddComment = QtGui.QPushButton(Form)
        self.pbPcbToolAddComment.setGeometry(QtCore.QRect(10, 660, 81, 21))
        self.pbPcbToolAddComment.setObjectName(_fromUtf8("pbPcbToolAddComment"))
        self.dsbPcbToolSize = QtGui.QDoubleSpinBox(Form)
        self.dsbPcbToolSize.setGeometry(QtCore.QRect(90, 390, 51, 21))
        self.dsbPcbToolSize.setMaximum(100.0)
        self.dsbPcbToolSize.setObjectName(_fromUtf8("dsbPcbToolSize"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 440, 121, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.ptePcbToolWriteComment = QtGui.QPlainTextEdit(Form)
        self.ptePcbToolWriteComment.setGeometry(QtCore.QRect(10, 590, 251, 71))
        self.ptePcbToolWriteComment.setObjectName(_fromUtf8("ptePcbToolWriteComment"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 370, 81, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.sbPcbToolID = QtGui.QSpinBox(Form)
        self.sbPcbToolID.setGeometry(QtCore.QRect(90, 370, 51, 21))
        self.sbPcbToolID.setMaximum(2147483647)
        self.sbPcbToolID.setObjectName(_fromUtf8("sbPcbToolID"))
        self.pbPcbToolDeleteComment = QtGui.QPushButton(Form)
        self.pbPcbToolDeleteComment.setGeometry(QtCore.QRect(130, 440, 131, 21))
        self.pbPcbToolDeleteComment.setObjectName(_fromUtf8("pbPcbToolDeleteComment"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 390, 81, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.listPcbToolComments = QtGui.QListWidget(Form)
        self.listPcbToolComments.setGeometry(QtCore.QRect(10, 460, 251, 121))
        self.listPcbToolComments.setObjectName(_fromUtf8("listPcbToolComments"))
        self.listPcbTrayComments = QtGui.QListWidget(Form)
        self.listPcbTrayComments.setGeometry(QtCore.QRect(310, 460, 251, 121))
        self.listPcbTrayComments.setObjectName(_fromUtf8("listPcbTrayComments"))
        self.pbSensorTrayAddComment = QtGui.QPushButton(Form)
        self.pbSensorTrayAddComment.setGeometry(QtCore.QRect(310, 300, 81, 23))
        self.pbSensorTrayAddComment.setObjectName(_fromUtf8("pbSensorTrayAddComment"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(310, 390, 131, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(310, 440, 121, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.pteSensorTrayWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteSensorTrayWriteComment.setGeometry(QtCore.QRect(310, 230, 251, 71))
        self.pteSensorTrayWriteComment.setObjectName(_fromUtf8("pteSensorTrayWriteComment"))
        self.sbSensorTrayID = QtGui.QSpinBox(Form)
        self.sbSensorTrayID.setGeometry(QtCore.QRect(440, 10, 51, 21))
        self.sbSensorTrayID.setMaximum(2147483647)
        self.sbSensorTrayID.setObjectName(_fromUtf8("sbSensorTrayID"))
        self.pbPcbTrayAddComment = QtGui.QPushButton(Form)
        self.pbPcbTrayAddComment.setGeometry(QtCore.QRect(310, 660, 81, 21))
        self.pbPcbTrayAddComment.setObjectName(_fromUtf8("pbPcbTrayAddComment"))
        self.dsbPcbTraySize = QtGui.QDoubleSpinBox(Form)
        self.dsbPcbTraySize.setGeometry(QtCore.QRect(440, 390, 51, 21))
        self.dsbPcbTraySize.setMaximum(100.0)
        self.dsbPcbTraySize.setObjectName(_fromUtf8("dsbPcbTraySize"))
        self.sbPcbTrayID = QtGui.QSpinBox(Form)
        self.sbPcbTrayID.setGeometry(QtCore.QRect(440, 370, 51, 21))
        self.sbPcbTrayID.setMaximum(2147483647)
        self.sbPcbTrayID.setObjectName(_fromUtf8("sbPcbTrayID"))
        self.listSensorTrayComments = QtGui.QListWidget(Form)
        self.listSensorTrayComments.setGeometry(QtCore.QRect(310, 100, 251, 121))
        self.listSensorTrayComments.setObjectName(_fromUtf8("listSensorTrayComments"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 80, 121, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_10 = QtGui.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(310, 10, 131, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pbSensorTrayDeleteComment = QtGui.QPushButton(Form)
        self.pbSensorTrayDeleteComment.setGeometry(QtCore.QRect(430, 80, 131, 21))
        self.pbSensorTrayDeleteComment.setObjectName(_fromUtf8("pbSensorTrayDeleteComment"))
        self.pbPcbTrayDeleteComment = QtGui.QPushButton(Form)
        self.pbPcbTrayDeleteComment.setGeometry(QtCore.QRect(430, 440, 131, 21))
        self.pbPcbTrayDeleteComment.setObjectName(_fromUtf8("pbPcbTrayDeleteComment"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(310, 30, 131, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.ptePcbTrayWriteComment = QtGui.QPlainTextEdit(Form)
        self.ptePcbTrayWriteComment.setGeometry(QtCore.QRect(310, 590, 251, 71))
        self.ptePcbTrayWriteComment.setObjectName(_fromUtf8("ptePcbTrayWriteComment"))
        self.dsbSensorTraySize = QtGui.QDoubleSpinBox(Form)
        self.dsbSensorTraySize.setGeometry(QtCore.QRect(440, 30, 51, 21))
        self.dsbSensorTraySize.setMaximum(100.0)
        self.dsbSensorTraySize.setObjectName(_fromUtf8("dsbSensorTraySize"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 370, 131, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.dsbAssemblyTraySize = QtGui.QDoubleSpinBox(Form)
        self.dsbAssemblyTraySize.setGeometry(QtCore.QRect(690, 30, 51, 21))
        self.dsbAssemblyTraySize.setMaximum(100.0)
        self.dsbAssemblyTraySize.setObjectName(_fromUtf8("dsbAssemblyTraySize"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(610, 80, 121, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.listAssemblyTrayComments = QtGui.QListWidget(Form)
        self.listAssemblyTrayComments.setGeometry(QtCore.QRect(610, 100, 251, 121))
        self.listAssemblyTrayComments.setObjectName(_fromUtf8("listAssemblyTrayComments"))
        self.pbAssemblyTrayAddComment = QtGui.QPushButton(Form)
        self.pbAssemblyTrayAddComment.setGeometry(QtCore.QRect(610, 300, 81, 23))
        self.pbAssemblyTrayAddComment.setObjectName(_fromUtf8("pbAssemblyTrayAddComment"))
        self.sbAssemblyTrayID = QtGui.QSpinBox(Form)
        self.sbAssemblyTrayID.setGeometry(QtCore.QRect(690, 10, 51, 21))
        self.sbAssemblyTrayID.setMaximum(2147483647)
        self.sbAssemblyTrayID.setObjectName(_fromUtf8("sbAssemblyTrayID"))
        self.pbAssemblyTrayDeleteComment = QtGui.QPushButton(Form)
        self.pbAssemblyTrayDeleteComment.setGeometry(QtCore.QRect(730, 80, 131, 21))
        self.pbAssemblyTrayDeleteComment.setObjectName(_fromUtf8("pbAssemblyTrayDeleteComment"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(610, 30, 81, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.pteAssemblyTrayWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteAssemblyTrayWriteComment.setGeometry(QtCore.QRect(610, 230, 251, 71))
        self.pteAssemblyTrayWriteComment.setObjectName(_fromUtf8("pteAssemblyTrayWriteComment"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(610, 10, 81, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.pbSensorToolEditNew = QtGui.QPushButton(Form)
        self.pbSensorToolEditNew.setGeometry(QtCore.QRect(200, 10, 61, 21))
        self.pbSensorToolEditNew.setObjectName(_fromUtf8("pbSensorToolEditNew"))
        self.pbSensorToolSave = QtGui.QPushButton(Form)
        self.pbSensorToolSave.setGeometry(QtCore.QRect(200, 30, 61, 21))
        self.pbSensorToolSave.setObjectName(_fromUtf8("pbSensorToolSave"))
        self.pbSensorToolCancel = QtGui.QPushButton(Form)
        self.pbSensorToolCancel.setGeometry(QtCore.QRect(200, 50, 61, 21))
        self.pbSensorToolCancel.setObjectName(_fromUtf8("pbSensorToolCancel"))
        self.pbPcbToolCancel = QtGui.QPushButton(Form)
        self.pbPcbToolCancel.setGeometry(QtCore.QRect(200, 410, 61, 21))
        self.pbPcbToolCancel.setObjectName(_fromUtf8("pbPcbToolCancel"))
        self.pbPcbToolSave = QtGui.QPushButton(Form)
        self.pbPcbToolSave.setGeometry(QtCore.QRect(200, 390, 61, 21))
        self.pbPcbToolSave.setObjectName(_fromUtf8("pbPcbToolSave"))
        self.pbPcbToolEditNew = QtGui.QPushButton(Form)
        self.pbPcbToolEditNew.setGeometry(QtCore.QRect(200, 370, 61, 21))
        self.pbPcbToolEditNew.setObjectName(_fromUtf8("pbPcbToolEditNew"))
        self.pbPcbTrayEditNew = QtGui.QPushButton(Form)
        self.pbPcbTrayEditNew.setGeometry(QtCore.QRect(500, 370, 61, 21))
        self.pbPcbTrayEditNew.setObjectName(_fromUtf8("pbPcbTrayEditNew"))
        self.pbPcbTraySave = QtGui.QPushButton(Form)
        self.pbPcbTraySave.setGeometry(QtCore.QRect(500, 390, 61, 21))
        self.pbPcbTraySave.setObjectName(_fromUtf8("pbPcbTraySave"))
        self.pbPcbTrayCancel = QtGui.QPushButton(Form)
        self.pbPcbTrayCancel.setGeometry(QtCore.QRect(500, 410, 61, 21))
        self.pbPcbTrayCancel.setObjectName(_fromUtf8("pbPcbTrayCancel"))
        self.pbSensorTrayCancel = QtGui.QPushButton(Form)
        self.pbSensorTrayCancel.setGeometry(QtCore.QRect(500, 50, 61, 21))
        self.pbSensorTrayCancel.setObjectName(_fromUtf8("pbSensorTrayCancel"))
        self.pbSensorTraySave = QtGui.QPushButton(Form)
        self.pbSensorTraySave.setGeometry(QtCore.QRect(500, 30, 61, 21))
        self.pbSensorTraySave.setObjectName(_fromUtf8("pbSensorTraySave"))
        self.pbSensorTrayEditNew = QtGui.QPushButton(Form)
        self.pbSensorTrayEditNew.setGeometry(QtCore.QRect(500, 10, 61, 21))
        self.pbSensorTrayEditNew.setObjectName(_fromUtf8("pbSensorTrayEditNew"))
        self.pbAssemblyTrayEditNew = QtGui.QPushButton(Form)
        self.pbAssemblyTrayEditNew.setGeometry(QtCore.QRect(800, 10, 61, 21))
        self.pbAssemblyTrayEditNew.setObjectName(_fromUtf8("pbAssemblyTrayEditNew"))
        self.pbAssemblyTrayCancel = QtGui.QPushButton(Form)
        self.pbAssemblyTrayCancel.setGeometry(QtCore.QRect(800, 50, 61, 21))
        self.pbAssemblyTrayCancel.setObjectName(_fromUtf8("pbAssemblyTrayCancel"))
        self.pbAssemblyTraySave = QtGui.QPushButton(Form)
        self.pbAssemblyTraySave.setGeometry(QtCore.QRect(800, 30, 61, 21))
        self.pbAssemblyTraySave.setObjectName(_fromUtf8("pbAssemblyTraySave"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "Sensor tool", None))
        self.lineEdit_2.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_3.setText(_translate("Form", "Comments", None))
        self.pbSensorToolDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbSensorToolAddComment.setText(_translate("Form", "add comment", None))
        self.pbPcbToolAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_4.setText(_translate("Form", "Comments", None))
        self.lineEdit_5.setText(_translate("Form", "PCB tool", None))
        self.pbPcbToolDeleteComment.setText(_translate("Form", "delete selected", None))
        self.lineEdit_6.setText(_translate("Form", "Size (inches)", None))
        self.pbSensorTrayAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_7.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_8.setText(_translate("Form", "Comments", None))
        self.pbPcbTrayAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_9.setText(_translate("Form", "Comments", None))
        self.lineEdit_10.setText(_translate("Form", "Sensor Component Tray", None))
        self.pbSensorTrayDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbPcbTrayDeleteComment.setText(_translate("Form", "delete selected", None))
        self.lineEdit_11.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_12.setText(_translate("Form", "PCB Component Tray", None))
        self.lineEdit_13.setText(_translate("Form", "Comments", None))
        self.pbAssemblyTrayAddComment.setText(_translate("Form", "add comment", None))
        self.pbAssemblyTrayDeleteComment.setText(_translate("Form", "delete selected", None))
        self.lineEdit_14.setText(_translate("Form", "Size (inches)", None))
        self.lineEdit_15.setText(_translate("Form", "Assembly Tray", None))
        self.pbSensorToolEditNew.setText(_translate("Form", "edit/new", None))
        self.pbSensorToolSave.setText(_translate("Form", "save", None))
        self.pbSensorToolCancel.setText(_translate("Form", "cancel", None))
        self.pbPcbToolCancel.setText(_translate("Form", "cancel", None))
        self.pbPcbToolSave.setText(_translate("Form", "save", None))
        self.pbPcbToolEditNew.setText(_translate("Form", "edit/new", None))
        self.pbPcbTrayEditNew.setText(_translate("Form", "edit/new", None))
        self.pbPcbTraySave.setText(_translate("Form", "save", None))
        self.pbPcbTrayCancel.setText(_translate("Form", "cancel", None))
        self.pbSensorTrayCancel.setText(_translate("Form", "cancel", None))
        self.pbSensorTraySave.setText(_translate("Form", "save", None))
        self.pbSensorTrayEditNew.setText(_translate("Form", "edit/new", None))
        self.pbAssemblyTrayEditNew.setText(_translate("Form", "edit/new", None))
        self.pbAssemblyTrayCancel.setText(_translate("Form", "cancel", None))
        self.pbAssemblyTraySave.setText(_translate("Form", "save", None))

