# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_wirebonding.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1199, 756)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(190, 30, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(100, 30, 81, 21))
        self.pbSave.setObjectName("pbSave")
        self.leLocation = QtWidgets.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(150, 119, 141, 21))
        self.leLocation.setText("")
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName("leLocation")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 119, 141, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pteWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteWriteComment.setGeometry(QtCore.QRect(650, 510, 281, 61))
        self.pteWriteComment.setPlainText("")
        self.pteWriteComment.setObjectName("pteWriteComment")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(650, 390, 161, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pbDeleteComment = QtWidgets.QPushButton(Form)
        self.pbDeleteComment.setGeometry(QtCore.QRect(810, 390, 121, 21))
        self.pbDeleteComment.setObjectName("pbDeleteComment")
        self.listComments = QtWidgets.QListWidget(Form)
        self.listComments.setGeometry(QtCore.QRect(650, 410, 281, 91))
        self.listComments.setObjectName("listComments")
        self.pbAddComment = QtWidgets.QPushButton(Form)
        self.pbAddComment.setGeometry(QtCore.QRect(650, 570, 111, 21))
        self.pbAddComment.setObjectName("pbAddComment")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 150, 211, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 171, 21))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 220, 281, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pteWirebondsDamagedBack = QtWidgets.QPlainTextEdit(self.frame)
        self.pteWirebondsDamagedBack.setGeometry(QtCore.QRect(0, 180, 281, 51))
        self.pteWirebondsDamagedBack.setObjectName("pteWirebondsDamagedBack")
        self.leWirebondsRepairedUserBack = QtWidgets.QLineEdit(self.frame)
        self.leWirebondsRepairedUserBack.setGeometry(QtCore.QRect(180, 310, 101, 20))
        self.leWirebondsRepairedUserBack.setText("")
        self.leWirebondsRepairedUserBack.setReadOnly(True)
        self.leWirebondsRepairedUserBack.setObjectName("leWirebondsRepairedUserBack")
        self.ckWirebondsInspectedBack = QtWidgets.QCheckBox(self.frame)
        self.ckWirebondsInspectedBack.setGeometry(QtCore.QRect(1, 140, 241, 17))
        self.ckWirebondsInspectedBack.setObjectName("ckWirebondsInspectedBack")
        self.ckWirebondsRepairedBack = QtWidgets.QCheckBox(self.frame)
        self.ckWirebondsRepairedBack.setGeometry(QtCore.QRect(1, 240, 241, 17))
        self.ckWirebondsRepairedBack.setObjectName("ckWirebondsRepairedBack")
        self.leWirebondingUserBack = QtWidgets.QLineEdit(self.frame)
        self.leWirebondingUserBack.setGeometry(QtCore.QRect(190, 20, 91, 20))
        self.leWirebondingUserBack.setText("")
        self.leWirebondingUserBack.setReadOnly(True)
        self.leWirebondingUserBack.setObjectName("leWirebondingUserBack")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_31.setGeometry(QtCore.QRect(1, 20, 191, 21))
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(2, 60, 141, 16))
        self.label_3.setObjectName("label_3")
        self.ckWirebondingBack = QtWidgets.QCheckBox(self.frame)
        self.ckWirebondingBack.setGeometry(QtCore.QRect(1, 0, 231, 17))
        self.ckWirebondingBack.setObjectName("ckWirebondingBack")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_36.setGeometry(QtCore.QRect(1, 310, 181, 20))
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.pteUnbondedChannelsBack = QtWidgets.QPlainTextEdit(self.frame)
        self.pteUnbondedChannelsBack.setGeometry(QtCore.QRect(0, 80, 281, 51))
        self.pteUnbondedChannelsBack.setObjectName("pteUnbondedChannelsBack")
        self.pteWirebondsRepairedListBack = QtWidgets.QPlainTextEdit(self.frame)
        self.pteWirebondsRepairedListBack.setGeometry(QtCore.QRect(0, 260, 281, 51))
        self.pteWirebondsRepairedListBack.setObjectName("pteWirebondsRepairedListBack")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 211, 21))
        self.label_7.setObjectName("label_7")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 170, 282, 21))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(1, 0, 191, 20))
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.cbCheckGlueSpill = QtWidgets.QComboBox(self.frame_2)
        self.cbCheckGlueSpill.setGeometry(QtCore.QRect(190, 0, 92, 20))
        self.cbCheckGlueSpill.setObjectName("cbCheckGlueSpill")
        self.cbCheckGlueSpill.addItem("")
        self.cbCheckGlueSpill.addItem("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(650, 270, 181, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 570, 171, 16))
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(650, 290, 241, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.cbWirebondingFinalInspectionOK = QtWidgets.QComboBox(self.frame_3)
        self.cbWirebondingFinalInspectionOK.setGeometry(QtCore.QRect(150, 40, 91, 21))
        self.cbWirebondingFinalInspectionOK.setObjectName("cbWirebondingFinalInspectionOK")
        self.cbWirebondingFinalInspectionOK.addItem("")
        self.cbWirebondingFinalInspectionOK.addItem("")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_37.setGeometry(QtCore.QRect(1, 40, 151, 20))
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.ckWirebondingFinalInspection = QtWidgets.QCheckBox(self.frame_3)
        self.ckWirebondingFinalInspection.setGeometry(QtCore.QRect(1, 0, 171, 17))
        self.ckWirebondingFinalInspection.setObjectName("ckWirebondingFinalInspection")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_40.setGeometry(QtCore.QRect(1, 20, 151, 21))
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.leWirebondingFinalInspectionUser = QtWidgets.QLineEdit(self.frame_3)
        self.leWirebondingFinalInspectionUser.setGeometry(QtCore.QRect(150, 20, 91, 20))
        self.leWirebondingFinalInspectionUser.setText("")
        self.leWirebondingFinalInspectionUser.setReadOnly(True)
        self.leWirebondingFinalInspectionUser.setObjectName("leWirebondingFinalInspectionUser")
        self.lineEdit_37.raise_()
        self.ckWirebondingFinalInspection.raise_()
        self.lineEdit_40.raise_()
        self.leWirebondingFinalInspectionUser.raise_()
        self.cbWirebondingFinalInspectionOK.raise_()
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(10, 590, 291, 101))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.ckEncapsulationBack = QtWidgets.QCheckBox(self.frame_4)
        self.ckEncapsulationBack.setGeometry(QtCore.QRect(0, 0, 191, 17))
        self.ckEncapsulationBack.setObjectName("ckEncapsulationBack")
        self.leEncapsulationUserBack = QtWidgets.QLineEdit(self.frame_4)
        self.leEncapsulationUserBack.setGeometry(QtCore.QRect(140, 20, 151, 20))
        self.leEncapsulationUserBack.setText("")
        self.leEncapsulationUserBack.setReadOnly(True)
        self.leEncapsulationUserBack.setObjectName("leEncapsulationUserBack")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_38.setGeometry(QtCore.QRect(1, 20, 141, 21))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.dtCureStartBack = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dtCureStartBack.setGeometry(QtCore.QRect(80, 40, 131, 21))
        self.dtCureStartBack.setDate(QtCore.QDate(2020, 1, 1))
        self.dtCureStartBack.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStartBack.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStartBack.setCalendarPopup(True)
        self.dtCureStartBack.setObjectName("dtCureStartBack")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(1, 60, 81, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pbCureStopNowBack = QtWidgets.QPushButton(self.frame_4)
        self.pbCureStopNowBack.setGeometry(QtCore.QRect(210, 60, 81, 21))
        self.pbCureStopNowBack.setObjectName("pbCureStopNowBack")
        self.pbCureStartNowBack = QtWidgets.QPushButton(self.frame_4)
        self.pbCureStartNowBack.setGeometry(QtCore.QRect(210, 40, 81, 21))
        self.pbCureStartNowBack.setObjectName("pbCureStartNowBack")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(1, 40, 81, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_39.setGeometry(QtCore.QRect(1, 80, 161, 20))
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.cbEncapsulationInspectionBack = QtWidgets.QComboBox(self.frame_4)
        self.cbEncapsulationInspectionBack.setGeometry(QtCore.QRect(160, 80, 131, 20))
        self.cbEncapsulationInspectionBack.setObjectName("cbEncapsulationInspectionBack")
        self.cbEncapsulationInspectionBack.addItem("")
        self.cbEncapsulationInspectionBack.addItem("")
        self.dtCureStopBack = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dtCureStopBack.setGeometry(QtCore.QRect(80, 60, 131, 21))
        self.dtCureStopBack.setDate(QtCore.QDate(2020, 1, 1))
        self.dtCureStopBack.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStopBack.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStopBack.setCalendarPopup(True)
        self.dtCureStopBack.setObjectName("dtCureStopBack")
        self.ckEncapsulationBack.raise_()
        self.lineEdit_38.raise_()
        self.dtCureStartBack.raise_()
        self.lineEdit_6.raise_()
        self.pbCureStopNowBack.raise_()
        self.pbCureStartNowBack.raise_()
        self.lineEdit_7.raise_()
        self.lineEdit_39.raise_()
        self.cbEncapsulationInspectionBack.raise_()
        self.leEncapsulationUserBack.raise_()
        self.dtCureStopBack.raise_()
        self.lineEdit_52 = QtWidgets.QLineEdit(Form)
        self.lineEdit_52.setGeometry(QtCore.QRect(10, 99, 141, 21))
        self.lineEdit_52.setReadOnly(True)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(Form)
        self.lineEdit_53.setGeometry(QtCore.QRect(11, 80, 141, 20))
        self.lineEdit_53.setReadOnly(True)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.leInsertUser = QtWidgets.QLineEdit(Form)
        self.leInsertUser.setGeometry(QtCore.QRect(150, 80, 141, 20))
        self.leInsertUser.setText("")
        self.leInsertUser.setReadOnly(True)
        self.leInsertUser.setObjectName("leInsertUser")
        self.leID = QtWidgets.QLineEdit(Form)
        self.leID.setGeometry(QtCore.QRect(160, 10, 111, 20))
        self.leID.setText("")
        self.leID.setReadOnly(True)
        self.leID.setObjectName("leID")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(330, 80, 282, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.leTestBondsPulledUser = QtWidgets.QLineEdit(self.frame_5)
        self.leTestBondsPulledUser.setGeometry(QtCore.QRect(190, 40, 91, 20))
        self.leTestBondsPulledUser.setText("")
        self.leTestBondsPulledUser.setReadOnly(True)
        self.leTestBondsPulledUser.setObjectName("leTestBondsPulledUser")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_35.setGeometry(QtCore.QRect(1, 60, 191, 21))
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_32.setGeometry(QtCore.QRect(1, 40, 191, 21))
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.ckTestBondsPulled = QtWidgets.QCheckBox(self.frame_5)
        self.ckTestBondsPulled.setGeometry(QtCore.QRect(1, 20, 161, 17))
        self.ckTestBondsPulled.setObjectName("ckTestBondsPulled")
        self.cbTestBondsPulledOK = QtWidgets.QComboBox(self.frame_5)
        self.cbTestBondsPulledOK.setGeometry(QtCore.QRect(190, 60, 91, 21))
        self.cbTestBondsPulledOK.setObjectName("cbTestBondsPulledOK")
        self.cbTestBondsPulledOK.addItem("")
        self.cbTestBondsPulledOK.addItem("")
        self.ckTestBonds = QtWidgets.QCheckBox(self.frame_5)
        self.ckTestBonds.setGeometry(QtCore.QRect(1, 0, 161, 17))
        self.ckTestBonds.setObjectName("ckTestBonds")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(330, 60, 211, 21))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(330, 190, 171, 21))
        self.label_12.setObjectName("label_12")
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(330, 210, 281, 471))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.pteWirebondsDamagedFront = QtWidgets.QPlainTextEdit(self.frame_6)
        self.pteWirebondsDamagedFront.setGeometry(QtCore.QRect(0, 260, 281, 51))
        self.pteWirebondsDamagedFront.setObjectName("pteWirebondsDamagedFront")
        self.leWirebondsRepairedUserFront = QtWidgets.QLineEdit(self.frame_6)
        self.leWirebondsRepairedUserFront.setGeometry(QtCore.QRect(180, 390, 101, 20))
        self.leWirebondsRepairedUserFront.setText("")
        self.leWirebondsRepairedUserFront.setReadOnly(True)
        self.leWirebondsRepairedUserFront.setObjectName("leWirebondsRepairedUserFront")
        self.ckWirebondsInspectedFront = QtWidgets.QCheckBox(self.frame_6)
        self.ckWirebondsInspectedFront.setGeometry(QtCore.QRect(0, 220, 241, 17))
        self.ckWirebondsInspectedFront.setObjectName("ckWirebondsInspectedFront")
        self.ckWirebondsRepairedFront = QtWidgets.QCheckBox(self.frame_6)
        self.ckWirebondsRepairedFront.setGeometry(QtCore.QRect(0, 320, 241, 17))
        self.ckWirebondsRepairedFront.setObjectName("ckWirebondsRepairedFront")
        self.leWirebondingUserFront = QtWidgets.QLineEdit(self.frame_6)
        self.leWirebondingUserFront.setGeometry(QtCore.QRect(190, 20, 91, 20))
        self.leWirebondingUserFront.setText("")
        self.leWirebondingUserFront.setReadOnly(True)
        self.leWirebondingUserFront.setObjectName("leWirebondingUserFront")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_41.setGeometry(QtCore.QRect(1, 20, 191, 21))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(2, 140, 141, 16))
        self.label_9.setObjectName("label_9")
        self.ckWirebondingFront = QtWidgets.QCheckBox(self.frame_6)
        self.ckWirebondingFront.setGeometry(QtCore.QRect(0, 0, 231, 17))
        self.ckWirebondingFront.setObjectName("ckWirebondingFront")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_42.setGeometry(QtCore.QRect(1, 390, 181, 20))
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.pteUnbondedChannelsFront = QtWidgets.QPlainTextEdit(self.frame_6)
        self.pteUnbondedChannelsFront.setGeometry(QtCore.QRect(0, 160, 281, 51))
        self.pteUnbondedChannelsFront.setObjectName("pteUnbondedChannelsFront")
        self.pteWirebondsRepairedListFront = QtWidgets.QPlainTextEdit(self.frame_6)
        self.pteWirebondsRepairedListFront.setGeometry(QtCore.QRect(0, 340, 281, 51))
        self.pteWirebondsRepairedListFront.setObjectName("pteWirebondsRepairedListFront")
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 211, 21))
        self.label_10.setObjectName("label_10")
        self.pteWirebondingChannelsSkipFront = QtWidgets.QPlainTextEdit(self.frame_6)
        self.pteWirebondingChannelsSkipFront.setGeometry(QtCore.QRect(0, 80, 281, 51))
        self.pteWirebondingChannelsSkipFront.setReadOnly(True)
        self.pteWirebondingChannelsSkipFront.setObjectName("pteWirebondingChannelsSkipFront")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(0, 60, 251, 16))
        self.label_13.setObjectName("label_13")
        self.ckGuardLayerBonds = QtWidgets.QCheckBox(self.frame_6)
        self.ckGuardLayerBonds.setGeometry(QtCore.QRect(0, 450, 241, 17))
        self.ckGuardLayerBonds.setObjectName("ckGuardLayerBonds")
        self.ckShieldLayerBonds = QtWidgets.QCheckBox(self.frame_6)
        self.ckShieldLayerBonds.setGeometry(QtCore.QRect(0, 420, 241, 21))
        self.ckShieldLayerBonds.setObjectName("ckShieldLayerBonds")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(650, 140, 291, 101))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.ckEncapsulationFront = QtWidgets.QCheckBox(self.frame_7)
        self.ckEncapsulationFront.setGeometry(QtCore.QRect(0, 0, 201, 17))
        self.ckEncapsulationFront.setObjectName("ckEncapsulationFront")
        self.leEncapsulationUserFront = QtWidgets.QLineEdit(self.frame_7)
        self.leEncapsulationUserFront.setGeometry(QtCore.QRect(140, 20, 151, 20))
        self.leEncapsulationUserFront.setText("")
        self.leEncapsulationUserFront.setReadOnly(True)
        self.leEncapsulationUserFront.setObjectName("leEncapsulationUserFront")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_45.setGeometry(QtCore.QRect(1, 20, 141, 21))
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.dtCureStartFront = QtWidgets.QDateTimeEdit(self.frame_7)
        self.dtCureStartFront.setGeometry(QtCore.QRect(80, 40, 131, 21))
        self.dtCureStartFront.setDate(QtCore.QDate(2020, 1, 1))
        self.dtCureStartFront.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStartFront.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStartFront.setCalendarPopup(True)
        self.dtCureStartFront.setObjectName("dtCureStartFront")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(1, 60, 81, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pbCureStopNowFront = QtWidgets.QPushButton(self.frame_7)
        self.pbCureStopNowFront.setGeometry(QtCore.QRect(210, 60, 81, 21))
        self.pbCureStopNowFront.setObjectName("pbCureStopNowFront")
        self.pbCureStartNowFront = QtWidgets.QPushButton(self.frame_7)
        self.pbCureStartNowFront.setGeometry(QtCore.QRect(210, 40, 81, 21))
        self.pbCureStartNowFront.setObjectName("pbCureStartNowFront")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(1, 40, 81, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_46.setGeometry(QtCore.QRect(1, 80, 161, 20))
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.cbEncapsulationInspectionFront = QtWidgets.QComboBox(self.frame_7)
        self.cbEncapsulationInspectionFront.setGeometry(QtCore.QRect(160, 80, 131, 20))
        self.cbEncapsulationInspectionFront.setObjectName("cbEncapsulationInspectionFront")
        self.cbEncapsulationInspectionFront.addItem("")
        self.cbEncapsulationInspectionFront.addItem("")
        self.dtCureStopFront = QtWidgets.QDateTimeEdit(self.frame_7)
        self.dtCureStopFront.setGeometry(QtCore.QRect(80, 60, 131, 21))
        self.dtCureStopFront.setDate(QtCore.QDate(2020, 1, 1))
        self.dtCureStopFront.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStopFront.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStopFront.setCalendarPopup(True)
        self.dtCureStopFront.setObjectName("dtCureStopFront")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(650, 120, 181, 16))
        self.label_14.setObjectName("label_14")
        self.leErrors = QtWidgets.QLineEdit(Form)
        self.leErrors.setGeometry(QtCore.QRect(650, 30, 301, 21))
        self.leErrors.setText("")
        self.leErrors.setReadOnly(True)
        self.leErrors.setObjectName("leErrors")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(650, 50, 321, 51))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(650, 10, 181, 16))
        self.label_15.setObjectName("label_15")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(150, 100, 141, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")

        self.retranslateUi(Form)
        self.cbCheckGlueSpill.setCurrentIndex(-1)
        self.cbWirebondingFinalInspectionOK.setCurrentIndex(-1)
        self.cbEncapsulationInspectionBack.setCurrentIndex(-1)
        self.cbTestBondsPulledOK.setCurrentIndex(-1)
        self.cbEncapsulationInspectionFront.setCurrentIndex(-1)
        self.cbInstitution.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Module to wirebond"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit_14.setText(_translate("Form", "location"))
        self.lineEdit_16.setText(_translate("Form", "wirebonding notes"))
        self.pbDeleteComment.setText(_translate("Form", "Delete selected"))
        self.pbAddComment.setText(_translate("Form", "Add comment"))
        self.label.setText(_translate("Form", "Pre-wirebonding qualification"))
        self.label_2.setText(_translate("Form", "Wirebonding:  Back side"))
        self.ckWirebondsInspectedBack.setText(_translate("Form", "Wirebonds inspected"))
        self.ckWirebondsRepairedBack.setText(_translate("Form", "Wirebonds repaired (list below)"))
        self.lineEdit_31.setText(_translate("Form", "Back wirebonding user"))
        self.label_3.setText(_translate("Form", "Unbonded channels"))
        self.ckWirebondingBack.setText(_translate("Form", "Back wirebonding performed"))
        self.lineEdit_36.setText(_translate("Form", "Wirebonds repaired user"))
        self.label_7.setText(_translate("Form", "(list damaged below)"))
        self.lineEdit_29.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_29.setText(_translate("Form", "Check glue spillage"))
        self.cbCheckGlueSpill.setItemText(0, _translate("Form", "pass"))
        self.cbCheckGlueSpill.setItemText(1, _translate("Form", "fail"))
        self.label_4.setText(_translate("Form", "Wirebonding qualification"))
        self.label_5.setText(_translate("Form", "Encapsulation:  Back side"))
        self.cbWirebondingFinalInspectionOK.setItemText(0, _translate("Form", "pass"))
        self.cbWirebondingFinalInspectionOK.setItemText(1, _translate("Form", "fail"))
        self.lineEdit_37.setText(_translate("Form", "Final inspection OK?"))
        self.ckWirebondingFinalInspection.setText(_translate("Form", "Final inspection done"))
        self.lineEdit_40.setText(_translate("Form", "Final inspection user"))
        self.ckEncapsulationBack.setText(_translate("Form", "Back encapsulation done"))
        self.lineEdit_38.setText(_translate("Form", "Encpasulation user"))
        self.lineEdit_6.setText(_translate("Form", "cure stop"))
        self.pbCureStopNowBack.setText(_translate("Form", "set to now"))
        self.pbCureStartNowBack.setText(_translate("Form", "set to now"))
        self.lineEdit_7.setText(_translate("Form", "cure start"))
        self.lineEdit_39.setText(_translate("Form", "Post-curing inspection"))
        self.cbEncapsulationInspectionBack.setItemText(0, _translate("Form", "pass"))
        self.cbEncapsulationInspectionBack.setItemText(1, _translate("Form", "fail"))
        self.lineEdit_52.setText(_translate("Form", "institution"))
        self.lineEdit_53.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_53.setText(_translate("Form", "User name"))
        self.lineEdit_35.setText(_translate("Form", "Test bonds pulled OK?"))
        self.lineEdit_32.setText(_translate("Form", "Test bond pull user"))
        self.ckTestBondsPulled.setText(_translate("Form", "Test bonds pulled"))
        self.cbTestBondsPulledOK.setItemText(0, _translate("Form", "yes"))
        self.cbTestBondsPulledOK.setItemText(1, _translate("Form", "no"))
        self.ckTestBonds.setText(_translate("Form", "Is test bond module"))
        self.label_8.setText(_translate("Form", "Test bonds"))
        self.label_12.setText(_translate("Form", "Wirebonding:  Front side"))
        self.ckWirebondsInspectedFront.setText(_translate("Form", "Wirebonds inspected"))
        self.ckWirebondsRepairedFront.setText(_translate("Form", "Wirebonds repaired (list below)"))
        self.lineEdit_41.setText(_translate("Form", "Front wirebonding user"))
        self.label_9.setText(_translate("Form", "Unbonded channels"))
        self.ckWirebondingFront.setText(_translate("Form", "Front wirebonding performed"))
        self.lineEdit_42.setText(_translate("Form", "Wirebonds repaired user"))
        self.label_10.setText(_translate("Form", "(list damaged below)"))
        self.label_13.setText(_translate("Form", "Channels to skip (currently disabled)"))
        self.ckGuardLayerBonds.setText(_translate("Form", "Guard layer bonds performed"))
        self.ckShieldLayerBonds.setText(_translate("Form", "Shield layer bonds performed"))
        self.ckEncapsulationFront.setText(_translate("Form", "Front encapsulation done"))
        self.lineEdit_45.setText(_translate("Form", "Encpasulation user"))
        self.lineEdit_10.setText(_translate("Form", "cure stop"))
        self.pbCureStopNowFront.setText(_translate("Form", "set to now"))
        self.pbCureStartNowFront.setText(_translate("Form", "set to now"))
        self.lineEdit_11.setText(_translate("Form", "cure start"))
        self.lineEdit_46.setText(_translate("Form", "Post-curing inspection"))
        self.cbEncapsulationInspectionFront.setItemText(0, _translate("Form", "pass"))
        self.cbEncapsulationInspectionFront.setItemText(1, _translate("Form", "fail"))
        self.label_14.setText(_translate("Form", "Encapsulation:  Front side"))
        self.label_6.setText(_translate("Form", "Note:  Format of all text box input should be a comma-separated list of values.  ex. 1, 3, 4, ..."))
        self.label_15.setText(_translate("Form", "Text formatting errors:"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "HEPHY"))
        self.cbInstitution.setItemText(5, _translate("Form", "HPK"))

