# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_sensor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 726)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 90, 261, 611))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.leManufacturer = QtWidgets.QLineEdit(self.frame_2)
        self.leManufacturer.setGeometry(QtCore.QRect(180, 210, 80, 21))
        self.leManufacturer.setText("")
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName("leManufacturer")
        self.pbGoShipment = QtWidgets.QPushButton(self.frame_2)
        self.pbGoShipment.setGeometry(QtCore.QRect(120, 60, 141, 21))
        self.pbGoShipment.setObjectName("pbGoShipment")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(1, 41, 121, 20))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(1, 190, 181, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(1, 60, 121, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.leIdentifier = QtWidgets.QLineEdit(self.frame_2)
        self.leIdentifier.setGeometry(QtCore.QRect(180, 190, 80, 20))
        self.leIdentifier.setText("")
        self.leIdentifier.setReadOnly(True)
        self.leIdentifier.setObjectName("leIdentifier")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(1, 210, 181, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.leLocation = QtWidgets.QLineEdit(self.frame_2)
        self.leLocation.setGeometry(QtCore.QRect(120, 41, 141, 20))
        self.leLocation.setText("")
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName("leLocation")
        self.listShipments = QtWidgets.QListWidget(self.frame_2)
        self.listShipments.setGeometry(QtCore.QRect(0, 80, 261, 91))
        self.listShipments.setObjectName("listShipments")
        self.cbShape = QtWidgets.QComboBox(self.frame_2)
        self.cbShape.setGeometry(QtCore.QRect(180, 270, 81, 20))
        self.cbShape.setObjectName("cbShape")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(1, 270, 181, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(1, 250, 181, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(1, 290, 181, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.sbRotation = QtWidgets.QSpinBox(self.frame_2)
        self.sbRotation.setGeometry(QtCore.QRect(180, 290, 80, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName("sbRotation")
        self.sbChannels = QtWidgets.QSpinBox(self.frame_2)
        self.sbChannels.setGeometry(QtCore.QRect(180, 310, 80, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName("sbChannels")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(1, 310, 181, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(1, 230, 181, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pbAddComment = QtWidgets.QPushButton(self.frame_2)
        self.pbAddComment.setGeometry(QtCore.QRect(0, 590, 111, 21))
        self.pbAddComment.setObjectName("pbAddComment")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_14.setGeometry(QtCore.QRect(1, 370, 141, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pbDeleteComment = QtWidgets.QPushButton(self.frame_2)
        self.pbDeleteComment.setGeometry(QtCore.QRect(140, 370, 121, 21))
        self.pbDeleteComment.setObjectName("pbDeleteComment")
        self.pteWriteComment = QtWidgets.QPlainTextEdit(self.frame_2)
        self.pteWriteComment.setGeometry(QtCore.QRect(0, 520, 261, 71))
        self.pteWriteComment.setObjectName("pteWriteComment")
        self.listComments = QtWidgets.QListWidget(self.frame_2)
        self.listComments.setGeometry(QtCore.QRect(0, 390, 261, 121))
        self.listComments.setObjectName("listComments")
        self.cbSize = QtWidgets.QComboBox(self.frame_2)
        self.cbSize.setGeometry(QtCore.QRect(180, 250, 81, 21))
        self.cbSize.setObjectName("cbSize")
        self.cbSize.addItem("")
        self.cbSize.addItem("")
        self.cbSemiType = QtWidgets.QComboBox(self.frame_2)
        self.cbSemiType.setGeometry(QtCore.QRect(180, 330, 81, 21))
        self.cbSemiType.setObjectName("cbSemiType")
        self.cbSemiType.addItem("")
        self.cbSemiType.addItem("")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_16.setGeometry(QtCore.QRect(0, 330, 181, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(1, 21, 121, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.cbInstitution = QtWidgets.QComboBox(self.frame_2)
        self.cbInstitution.setGeometry(QtCore.QRect(120, 21, 141, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.leInsertUser = QtWidgets.QLineEdit(self.frame_2)
        self.leInsertUser.setGeometry(QtCore.QRect(120, 1, 141, 20))
        self.leInsertUser.setText("")
        self.leInsertUser.setReadOnly(True)
        self.leInsertUser.setObjectName("leInsertUser")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(1, 1, 121, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.cbType = QtWidgets.QComboBox(self.frame_2)
        self.cbType.setGeometry(QtCore.QRect(180, 230, 81, 21))
        self.cbType.setObjectName("cbType")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.lineEdit_9.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.leIdentifier.raise_()
        self.lineEdit_7.raise_()
        self.leLocation.raise_()
        self.listShipments.raise_()
        self.lineEdit_10.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_11.raise_()
        self.sbRotation.raise_()
        self.lineEdit_6.raise_()
        self.lineEdit_4.raise_()
        self.pbAddComment.raise_()
        self.lineEdit_14.raise_()
        self.pbDeleteComment.raise_()
        self.pteWriteComment.raise_()
        self.listComments.raise_()
        self.cbSize.raise_()
        self.pbGoShipment.raise_()
        self.cbShape.raise_()
        self.sbChannels.raise_()
        self.leManufacturer.raise_()
        self.cbSemiType.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.cbInstitution.raise_()
        self.leInsertUser.raise_()
        self.lineEdit_18.raise_()
        self.cbType.raise_()
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 261, 71))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.pbSave = QtWidgets.QPushButton(self.frame_3)
        self.pbSave.setGeometry(QtCore.QRect(90, 30, 71, 21))
        self.pbSave.setObjectName("pbSave")
        self.pbEdit = QtWidgets.QPushButton(self.frame_3)
        self.pbEdit.setGeometry(QtCore.QRect(0, 50, 81, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbCancel = QtWidgets.QPushButton(self.frame_3)
        self.pbCancel.setGeometry(QtCore.QRect(170, 30, 71, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(1, 1, 171, 19))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pbNew = QtWidgets.QPushButton(self.frame_3)
        self.pbNew.setGeometry(QtCore.QRect(0, 30, 81, 21))
        self.pbNew.setObjectName("pbNew")
        self.sbID = QtWidgets.QSpinBox(self.frame_3)
        self.sbID.setGeometry(QtCore.QRect(169, 1, 91, 20))
        self.sbID.setMaximum(2147483647)
        self.sbID.setObjectName("sbID")
        self.pbGoStepSensor = QtWidgets.QPushButton(Form)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(510, 150, 51, 21))
        self.pbGoStepSensor.setObjectName("pbGoStepSensor")
        self.pbGoModule = QtWidgets.QPushButton(Form)
        self.pbGoModule.setGeometry(QtCore.QRect(510, 240, 51, 21))
        self.pbGoModule.setObjectName("pbGoModule")
        self.sbProtomodule = QtWidgets.QSpinBox(Form)
        self.sbProtomodule.setGeometry(QtCore.QRect(430, 170, 81, 21))
        self.sbProtomodule.setReadOnly(True)
        self.sbProtomodule.setMinimum(-1)
        self.sbProtomodule.setMaximum(2147483647)
        self.sbProtomodule.setObjectName("sbProtomodule")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 170, 121, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(310, 240, 121, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.sbModule = QtWidgets.QSpinBox(Form)
        self.sbModule.setGeometry(QtCore.QRect(430, 240, 81, 21))
        self.sbModule.setReadOnly(True)
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName("sbModule")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(310, 150, 121, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pbGoProtomodule = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule.setGeometry(QtCore.QRect(510, 170, 51, 21))
        self.pbGoProtomodule.setObjectName("pbGoProtomodule")
        self.sbStepSensor = QtWidgets.QSpinBox(Form)
        self.sbStepSensor.setGeometry(QtCore.QRect(430, 150, 81, 21))
        self.sbStepSensor.setReadOnly(True)
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName("sbStepSensor")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(310, 220, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(310, 130, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 70, 141, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(310, 90, 131, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.cbInspection = QtWidgets.QComboBox(Form)
        self.cbInspection.setGeometry(QtCore.QRect(440, 90, 121, 21))
        self.cbInspection.setObjectName("cbInspection")
        self.cbInspection.addItem("")
        self.cbInspection.addItem("")

        self.retranslateUi(Form)
        self.cbShape.setCurrentIndex(-1)
        self.cbSize.setCurrentIndex(-1)
        self.cbSemiType.setCurrentIndex(0)
        self.cbInstitution.setCurrentIndex(0)
        self.cbType.setCurrentIndex(0)
        self.cbInspection.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pbGoShipment.setText(_translate("Form", "Go to selected"))
        self.lineEdit_9.setText(_translate("Form", "Location"))
        self.lineEdit_2.setText(_translate("Form", "Identifier"))
        self.lineEdit_3.setText(_translate("Form", "Shipments"))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer"))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)"))
        self.cbShape.setItemText(0, _translate("Form", "full"))
        self.cbShape.setItemText(1, _translate("Form", "half"))
        self.cbShape.setItemText(2, _translate("Form", "five"))
        self.cbShape.setItemText(3, _translate("Form", "three"))
        self.cbShape.setItemText(4, _translate("Form", "semi"))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)"))
        self.cbShape.setItemText(6, _translate("Form", "choptwo"))
        self.lineEdit_10.setText(_translate("Form", "Shape"))
        self.lineEdit_5.setText(_translate("Form", "Size (inches)"))
        self.lineEdit_11.setText(_translate("Form", "Rotation"))
        self.lineEdit_6.setText(_translate("Form", "Channels"))
        self.lineEdit_4.setText(_translate("Form", "Type (Si thickness)"))
        self.pbAddComment.setText(_translate("Form", "Add comment"))
        self.lineEdit_14.setText(_translate("Form", "Comments"))
        self.pbDeleteComment.setText(_translate("Form", "Delete selected"))
        self.cbSize.setItemText(0, _translate("Form", "8"))
        self.cbSize.setItemText(1, _translate("Form", "6"))
        self.cbSemiType.setItemText(0, _translate("Form", "P-type"))
        self.cbSemiType.setItemText(1, _translate("Form", "N-type"))
        self.lineEdit_16.setText(_translate("Form", "Semiconductor type"))
        self.lineEdit_17.setText(_translate("Form", "Institution"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.lineEdit_18.setText(_translate("Form", "User name"))
        self.cbType.setItemText(0, _translate("Form", "100 um"))
        self.cbType.setItemText(1, _translate("Form", "200 um"))
        self.cbType.setItemText(2, _translate("Form", "300 um"))
        self.cbType.setItemText(3, _translate("Form", "500 um"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.lineEdit.setText(_translate("Form", "Sensor ID"))
        self.pbNew.setText(_translate("Form", "New"))
        self.pbGoStepSensor.setText(_translate("Form", "Go to"))
        self.pbGoModule.setText(_translate("Form", "Go to"))
        self.lineEdit_12.setText(_translate("Form", "On protomodule"))
        self.lineEdit_8.setText(_translate("Form", "On module"))
        self.lineEdit_13.setText(_translate("Form", "Placement step"))
        self.pbGoProtomodule.setText(_translate("Form", "Go to"))
        self.label.setText(_translate("Form", "module"))
        self.label_2.setText(_translate("Form", "sensor placement"))
        self.label_3.setText(_translate("Form", "sensor qualification"))
        self.lineEdit_15.setText(_translate("Form", "Visual inspection"))
        self.cbInspection.setItemText(0, _translate("Form", "pass"))
        self.cbInspection.setItemText(1, _translate("Form", "fail"))

