# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_module.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1199, 756)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 379, 141, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 399, 141, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 419, 141, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pbGoBaseplate = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate.setGeometry(QtCore.QRect(250, 379, 41, 21))
        self.pbGoBaseplate.setObjectName("pbGoBaseplate")
        self.pbGoSensor = QtWidgets.QPushButton(Form)
        self.pbGoSensor.setGeometry(QtCore.QRect(250, 399, 41, 21))
        self.pbGoSensor.setObjectName("pbGoSensor")
        self.pbGoPcb = QtWidgets.QPushButton(Form)
        self.pbGoPcb.setGeometry(QtCore.QRect(250, 419, 41, 21))
        self.pbGoPcb.setObjectName("pbGoPcb")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 249, 181, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(190, 30, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(100, 30, 81, 21))
        self.pbSave.setObjectName("pbSave")
        self.dsbThickness = QtWidgets.QDoubleSpinBox(Form)
        self.dsbThickness.setGeometry(QtCore.QRect(190, 249, 101, 21))
        self.dsbThickness.setMinimum(-1.0)
        self.dsbThickness.setMaximum(2147483647.0)
        self.dsbThickness.setObjectName("dsbThickness")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 359, 181, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 319, 181, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 339, 181, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.sbStepPcb = QtWidgets.QSpinBox(Form)
        self.sbStepPcb.setGeometry(QtCore.QRect(190, 359, 61, 21))
        self.sbStepPcb.setReadOnly(True)
        self.sbStepPcb.setMinimum(-1)
        self.sbStepPcb.setMaximum(2147483647)
        self.sbStepPcb.setObjectName("sbStepPcb")
        self.sbStepSensor = QtWidgets.QSpinBox(Form)
        self.sbStepSensor.setGeometry(QtCore.QRect(190, 339, 61, 21))
        self.sbStepSensor.setReadOnly(True)
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName("sbStepSensor")
        self.sbStepKapton = QtWidgets.QSpinBox(Form)
        self.sbStepKapton.setGeometry(QtCore.QRect(190, 319, 61, 21))
        self.sbStepKapton.setReadOnly(True)
        self.sbStepKapton.setMinimum(-1)
        self.sbStepKapton.setMaximum(2147483647)
        self.sbStepKapton.setObjectName("sbStepKapton")
        self.pbGoStepPcb = QtWidgets.QPushButton(Form)
        self.pbGoStepPcb.setGeometry(QtCore.QRect(250, 359, 41, 21))
        self.pbGoStepPcb.setObjectName("pbGoStepPcb")
        self.pbGoStepKapton = QtWidgets.QPushButton(Form)
        self.pbGoStepKapton.setGeometry(QtCore.QRect(250, 319, 41, 21))
        self.pbGoStepKapton.setObjectName("pbGoStepKapton")
        self.pbGoStepSensor = QtWidgets.QPushButton(Form)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(250, 339, 41, 21))
        self.pbGoStepSensor.setObjectName("pbGoStepSensor")
        self.leLocation = QtWidgets.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(150, 119, 141, 21))
        self.leLocation.setText("")
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName("leLocation")
        self.pbGoShipment = QtWidgets.QPushButton(Form)
        self.pbGoShipment.setGeometry(QtCore.QRect(150, 139, 141, 21))
        self.pbGoShipment.setObjectName("pbGoShipment")
        self.listShipments = QtWidgets.QListWidget(Form)
        self.listShipments.setGeometry(QtCore.QRect(10, 159, 281, 61))
        self.listShipments.setObjectName("listShipments")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 119, 141, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 139, 141, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pteWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteWriteComment.setGeometry(QtCore.QRect(10, 589, 281, 61))
        self.pteWriteComment.setPlainText("")
        self.pteWriteComment.setObjectName("pteWriteComment")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 469, 161, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pbDeleteComment = QtWidgets.QPushButton(Form)
        self.pbDeleteComment.setGeometry(QtCore.QRect(170, 469, 121, 21))
        self.pbDeleteComment.setObjectName("pbDeleteComment")
        self.listComments = QtWidgets.QListWidget(Form)
        self.listComments.setGeometry(QtCore.QRect(10, 489, 281, 91))
        self.listComments.setObjectName("listComments")
        self.pbAddComment = QtWidgets.QPushButton(Form)
        self.pbAddComment.setGeometry(QtCore.QRect(10, 649, 111, 21))
        self.pbAddComment.setObjectName("pbAddComment")
        self.cbChirality = QtWidgets.QComboBox(Form)
        self.cbChirality.setGeometry(QtCore.QRect(190, 289, 101, 21))
        self.cbChirality.setObjectName("cbChirality")
        self.cbChirality.addItem("")
        self.cbChirality.addItem("")
        self.cbChirality.addItem("")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 269, 181, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 289, 181, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.sbChannels = QtWidgets.QSpinBox(Form)
        self.sbChannels.setGeometry(QtCore.QRect(190, 229, 101, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName("sbChannels")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 229, 181, 21))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 439, 141, 21))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pbGoProtomodule = QtWidgets.QPushButton(Form)
        self.pbGoProtomodule.setGeometry(QtCore.QRect(250, 439, 41, 21))
        self.pbGoProtomodule.setObjectName("pbGoProtomodule")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(340, 60, 221, 16))
        self.label_6.setObjectName("label_6")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(340, 80, 291, 251))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.ckHvCablesAttached = QtWidgets.QCheckBox(self.frame_5)
        self.ckHvCablesAttached.setGeometry(QtCore.QRect(0, 0, 171, 17))
        self.ckHvCablesAttached.setObjectName("ckHvCablesAttached")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_42.setGeometry(QtCore.QRect(1, 20, 181, 21))
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.leHvCablesAttachedUser = QtWidgets.QLineEdit(self.frame_5)
        self.leHvCablesAttachedUser.setGeometry(QtCore.QRect(180, 20, 111, 20))
        self.leHvCablesAttachedUser.setText("")
        self.leHvCablesAttachedUser.setReadOnly(True)
        self.leHvCablesAttachedUser.setObjectName("leHvCablesAttachedUser")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_43.setGeometry(QtCore.QRect(1, 50, 181, 21))
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_44.setGeometry(QtCore.QRect(1, 90, 181, 20))
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_45.setGeometry(QtCore.QRect(1, 70, 181, 21))
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.leUnbiasedDaq = QtWidgets.QLineEdit(self.frame_5)
        self.leUnbiasedDaq.setGeometry(QtCore.QRect(180, 50, 111, 20))
        self.leUnbiasedDaq.setText("")
        self.leUnbiasedDaq.setReadOnly(True)
        self.leUnbiasedDaq.setObjectName("leUnbiasedDaq")
        self.cbUnbiasedDaqOK = QtWidgets.QComboBox(self.frame_5)
        self.cbUnbiasedDaqOK.setGeometry(QtCore.QRect(180, 90, 111, 21))
        self.cbUnbiasedDaqOK.setObjectName("cbUnbiasedDaqOK")
        self.cbUnbiasedDaqOK.addItem("")
        self.cbUnbiasedDaqOK.addItem("")
        self.leUnbiasedDaqUser = QtWidgets.QLineEdit(self.frame_5)
        self.leUnbiasedDaqUser.setGeometry(QtCore.QRect(180, 70, 111, 20))
        self.leUnbiasedDaqUser.setText("")
        self.leUnbiasedDaqUser.setReadOnly(True)
        self.leUnbiasedDaqUser.setObjectName("leUnbiasedDaqUser")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_46.setGeometry(QtCore.QRect(1, 120, 171, 21))
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.cbIvOK = QtWidgets.QComboBox(self.frame_5)
        self.cbIvOK.setGeometry(QtCore.QRect(170, 160, 121, 21))
        self.cbIvOK.setObjectName("cbIvOK")
        self.cbIvOK.addItem("")
        self.cbIvOK.addItem("")
        self.leIvUser = QtWidgets.QLineEdit(self.frame_5)
        self.leIvUser.setGeometry(QtCore.QRect(170, 140, 121, 20))
        self.leIvUser.setText("")
        self.leIvUser.setReadOnly(True)
        self.leIvUser.setObjectName("leIvUser")
        self.leIv = QtWidgets.QLineEdit(self.frame_5)
        self.leIv.setGeometry(QtCore.QRect(170, 120, 121, 20))
        self.leIv.setText("")
        self.leIv.setReadOnly(True)
        self.leIv.setObjectName("leIv")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_47.setGeometry(QtCore.QRect(1, 160, 171, 20))
        self.lineEdit_47.setReadOnly(True)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_48.setGeometry(QtCore.QRect(1, 140, 171, 21))
        self.lineEdit_48.setReadOnly(True)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_49.setGeometry(QtCore.QRect(1, 190, 171, 21))
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.cbBiasedDaqOK = QtWidgets.QComboBox(self.frame_5)
        self.cbBiasedDaqOK.setGeometry(QtCore.QRect(170, 230, 121, 21))
        self.cbBiasedDaqOK.setObjectName("cbBiasedDaqOK")
        self.cbBiasedDaqOK.addItem("")
        self.cbBiasedDaqOK.addItem("")
        self.leBiasedDaqVoltage = QtWidgets.QLineEdit(self.frame_5)
        self.leBiasedDaqVoltage.setGeometry(QtCore.QRect(170, 210, 121, 20))
        self.leBiasedDaqVoltage.setText("")
        self.leBiasedDaqVoltage.setReadOnly(True)
        self.leBiasedDaqVoltage.setObjectName("leBiasedDaqVoltage")
        self.leBiasedDaq = QtWidgets.QLineEdit(self.frame_5)
        self.leBiasedDaq.setGeometry(QtCore.QRect(170, 190, 121, 20))
        self.leBiasedDaq.setText("")
        self.leBiasedDaq.setReadOnly(True)
        self.leBiasedDaq.setObjectName("leBiasedDaq")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_50.setGeometry(QtCore.QRect(1, 230, 171, 20))
        self.lineEdit_50.setReadOnly(True)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_51.setGeometry(QtCore.QRect(1, 210, 171, 21))
        self.lineEdit_51.setReadOnly(True)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.ckHvCablesAttached.raise_()
        self.lineEdit_42.raise_()
        self.leHvCablesAttachedUser.raise_()
        self.lineEdit_43.raise_()
        self.lineEdit_44.raise_()
        self.lineEdit_45.raise_()
        self.leUnbiasedDaq.raise_()
        self.cbUnbiasedDaqOK.raise_()
        self.leUnbiasedDaqUser.raise_()
        self.lineEdit_46.raise_()
        self.cbIvOK.raise_()
        self.leIv.raise_()
        self.lineEdit_47.raise_()
        self.lineEdit_48.raise_()
        self.lineEdit_49.raise_()
        self.leBiasedDaq.raise_()
        self.lineEdit_50.raise_()
        self.lineEdit_51.raise_()
        self.leIvUser.raise_()
        self.leBiasedDaqVoltage.raise_()
        self.cbBiasedDaqOK.raise_()
        self.lineEdit_28 = QtWidgets.QLineEdit(Form)
        self.lineEdit_28.setGeometry(QtCore.QRect(680, 290, 211, 21))
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.listDaqData = QtWidgets.QListWidget(Form)
        self.listDaqData.setGeometry(QtCore.QRect(680, 310, 211, 131))
        self.listDaqData.setObjectName("listDaqData")
        self.pbDaqAddToPlotter = QtWidgets.QPushButton(Form)
        self.pbDaqAddToPlotter.setGeometry(QtCore.QRect(680, 440, 171, 21))
        self.pbDaqAddToPlotter.setObjectName("pbDaqAddToPlotter")
        self.pbDaqGoPlotter = QtWidgets.QPushButton(Form)
        self.pbDaqGoPlotter.setGeometry(QtCore.QRect(680, 460, 101, 21))
        self.pbDaqGoPlotter.setObjectName("pbDaqGoPlotter")
        self.pbIvGoPlotter = QtWidgets.QPushButton(Form)
        self.pbIvGoPlotter.setGeometry(QtCore.QRect(680, 250, 101, 21))
        self.pbIvGoPlotter.setObjectName("pbIvGoPlotter")
        self.pbIvAddToPlotter = QtWidgets.QPushButton(Form)
        self.pbIvAddToPlotter.setGeometry(QtCore.QRect(680, 230, 171, 21))
        self.pbIvAddToPlotter.setObjectName("pbIvAddToPlotter")
        self.lineEdit_41 = QtWidgets.QLineEdit(Form)
        self.lineEdit_41.setGeometry(QtCore.QRect(680, 80, 211, 21))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.listIvData = QtWidgets.QListWidget(Form)
        self.listIvData.setGeometry(QtCore.QRect(680, 100, 211, 131))
        self.listIvData.setObjectName("listIvData")
        self.cbShape = QtWidgets.QComboBox(Form)
        self.cbShape.setGeometry(QtCore.QRect(190, 269, 101, 20))
        self.cbShape.setObjectName("cbShape")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.lineEdit_52 = QtWidgets.QLineEdit(Form)
        self.lineEdit_52.setGeometry(QtCore.QRect(10, 99, 141, 21))
        self.lineEdit_52.setReadOnly(True)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(150, 99, 141, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lineEdit_53 = QtWidgets.QLineEdit(Form)
        self.lineEdit_53.setGeometry(QtCore.QRect(11, 80, 141, 20))
        self.lineEdit_53.setReadOnly(True)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.leInsertUser = QtWidgets.QLineEdit(Form)
        self.leInsertUser.setGeometry(QtCore.QRect(150, 80, 141, 20))
        self.leInsertUser.setText("")
        self.leInsertUser.setReadOnly(True)
        self.leInsertUser.setObjectName("leInsertUser")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(300, 0, 271, 51))
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.leID = QtWidgets.QLineEdit(Form)
        self.leID.setGeometry(QtCore.QRect(130, 10, 111, 20))
        self.leID.setText("")
        self.leID.setReadOnly(True)
        self.leID.setObjectName("leID")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.leBaseplate = QtWidgets.QLineEdit(Form)
        self.leBaseplate.setGeometry(QtCore.QRect(150, 380, 101, 20))
        self.leBaseplate.setReadOnly(True)
        self.leBaseplate.setObjectName("leBaseplate")
        self.lePcb = QtWidgets.QLineEdit(Form)
        self.lePcb.setGeometry(QtCore.QRect(150, 420, 101, 20))
        self.lePcb.setReadOnly(True)
        self.lePcb.setObjectName("lePcb")
        self.leSensor = QtWidgets.QLineEdit(Form)
        self.leSensor.setGeometry(QtCore.QRect(150, 400, 101, 20))
        self.leSensor.setReadOnly(True)
        self.leSensor.setObjectName("leSensor")
        self.leProtomodule = QtWidgets.QLineEdit(Form)
        self.leProtomodule.setGeometry(QtCore.QRect(150, 440, 101, 20))
        self.leProtomodule.setReadOnly(True)
        self.leProtomodule.setObjectName("leProtomodule")

        self.retranslateUi(Form)
        self.cbChirality.setCurrentIndex(-1)
        self.cbUnbiasedDaqOK.setCurrentIndex(-1)
        self.cbIvOK.setCurrentIndex(-1)
        self.cbBiasedDaqOK.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        self.cbInstitution.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Module ID"))
        self.lineEdit_2.setText(_translate("Form", "Baseplate ID"))
        self.lineEdit_3.setText(_translate("Form", "Sensor ID"))
        self.lineEdit_4.setText(_translate("Form", "PCB ID"))
        self.pbGoBaseplate.setText(_translate("Form", "Go to"))
        self.pbGoSensor.setText(_translate("Form", "Go to"))
        self.pbGoPcb.setText(_translate("Form", "Go to"))
        self.lineEdit_5.setText(_translate("Form", "Thickness (mm)"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit_11.setText(_translate("Form", "PCB placement step"))
        self.lineEdit_12.setText(_translate("Form", "Kapton placement step"))
        self.lineEdit_13.setText(_translate("Form", "Sensor placement step"))
        self.pbGoStepPcb.setText(_translate("Form", "Go to"))
        self.pbGoStepKapton.setText(_translate("Form", "Go to"))
        self.pbGoStepSensor.setText(_translate("Form", "Go to"))
        self.pbGoShipment.setText(_translate("Form", "Go to selected"))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)"))
        self.lineEdit_14.setText(_translate("Form", "location"))
        self.lineEdit_15.setText(_translate("Form", "shipments"))
        self.lineEdit_16.setText(_translate("Form", "Comments"))
        self.pbDeleteComment.setText(_translate("Form", "Delete selected"))
        self.pbAddComment.setText(_translate("Form", "Add comment"))
        self.cbChirality.setItemText(0, _translate("Form", "achiral"))
        self.cbChirality.setItemText(1, _translate("Form", "left"))
        self.cbChirality.setItemText(2, _translate("Form", "right"))
        self.lineEdit_20.setText(_translate("Form", "Shape"))
        self.lineEdit_21.setText(_translate("Form", "Chirality"))
        self.lineEdit_22.setText(_translate("Form", "Channels"))
        self.lineEdit_23.setText(_translate("Form", "Protomodule ID"))
        self.pbGoProtomodule.setText(_translate("Form", "Go to"))
        self.label_6.setText(_translate("Form", "Finished module qualification"))
        self.ckHvCablesAttached.setText(_translate("Form", "HV cables attached"))
        self.lineEdit_42.setText(_translate("Form", "HV cable attachment user"))
        self.lineEdit_43.setText(_translate("Form", "Unbiased DAQ dataset"))
        self.lineEdit_44.setText(_translate("Form", "Unbiased DAQ OK?"))
        self.lineEdit_45.setText(_translate("Form", "Unbiased DAQ user"))
        self.cbUnbiasedDaqOK.setItemText(0, _translate("Form", "yes"))
        self.cbUnbiasedDaqOK.setItemText(1, _translate("Form", "no"))
        self.lineEdit_46.setText(_translate("Form", "IV dataset"))
        self.cbIvOK.setItemText(0, _translate("Form", "yes"))
        self.cbIvOK.setItemText(1, _translate("Form", "no"))
        self.lineEdit_47.setText(_translate("Form", "IV OK?"))
        self.lineEdit_48.setText(_translate("Form", "IV user"))
        self.lineEdit_49.setText(_translate("Form", "Biased DAQ dataset"))
        self.cbBiasedDaqOK.setItemText(0, _translate("Form", "yes"))
        self.cbBiasedDaqOK.setItemText(1, _translate("Form", "no"))
        self.lineEdit_50.setText(_translate("Form", "Biased DAQ OK?"))
        self.lineEdit_51.setText(_translate("Form", "Biased DAQ voltage"))
        self.lineEdit_28.setText(_translate("Form", "DAQ datasets"))
        self.pbDaqAddToPlotter.setText(_translate("Form", "Add selected to plotter"))
        self.pbDaqGoPlotter.setText(_translate("Form", "Go to plotter"))
        self.pbIvGoPlotter.setText(_translate("Form", "Go to plotter"))
        self.pbIvAddToPlotter.setText(_translate("Form", "Add selected to plotter"))
        self.lineEdit_41.setText(_translate("Form", "IV datasets"))
        self.cbShape.setItemText(0, _translate("Form", "full"))
        self.cbShape.setItemText(1, _translate("Form", "half"))
        self.cbShape.setItemText(2, _translate("Form", "five"))
        self.cbShape.setItemText(3, _translate("Form", "three"))
        self.cbShape.setItemText(4, _translate("Form", "semi"))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)"))
        self.cbShape.setItemText(6, _translate("Form", "choptwo"))
        self.lineEdit_52.setText(_translate("Form", "institution"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "NTU"))
        self.lineEdit_53.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_53.setText(_translate("Form", "User name"))
        self.label_8.setText(_translate("Form", "Note:  modules are automatically created upon completion of a pcb step."))

