# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_sensor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(230, 90, 251, 241))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pbAddComment = QtGui.QPushButton(self.frame)
        self.pbAddComment.setGeometry(QtCore.QRect(0, 220, 81, 21))
        self.pbAddComment.setObjectName(_fromUtf8("pbAddComment"))
        self.pteWriteComment = QtGui.QPlainTextEdit(self.frame)
        self.pteWriteComment.setGeometry(QtCore.QRect(0, 150, 251, 71))
        self.pteWriteComment.setObjectName(_fromUtf8("pteWriteComment"))
        self.lineEdit_14 = QtGui.QLineEdit(self.frame)
        self.lineEdit_14.setGeometry(QtCore.QRect(0, 0, 121, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.listComments = QtGui.QListWidget(self.frame)
        self.listComments.setGeometry(QtCore.QRect(0, 20, 251, 121))
        self.listComments.setObjectName(_fromUtf8("listComments"))
        self.pbDeleteComment = QtGui.QPushButton(self.frame)
        self.pbDeleteComment.setGeometry(QtCore.QRect(120, 0, 131, 21))
        self.pbDeleteComment.setObjectName(_fromUtf8("pbDeleteComment"))
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 90, 211, 351))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setMidLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.sbStepSensor = QtGui.QSpinBox(self.frame_2)
        self.sbStepSensor.setGeometry(QtCore.QRect(90, 290, 81, 21))
        self.sbStepSensor.setReadOnly(True)
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName(_fromUtf8("sbStepSensor"))
        self.pbGoProtomodule = QtGui.QPushButton(self.frame_2)
        self.pbGoProtomodule.setGeometry(QtCore.QRect(170, 310, 41, 21))
        self.pbGoProtomodule.setObjectName(_fromUtf8("pbGoProtomodule"))
        self.lineEdit_10 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(0, 240, 81, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.pbGoModule = QtGui.QPushButton(self.frame_2)
        self.pbGoModule.setGeometry(QtCore.QRect(170, 330, 41, 21))
        self.pbGoModule.setObjectName(_fromUtf8("pbGoModule"))
        self.cbShape = QtGui.QComboBox(self.frame_2)
        self.cbShape.setGeometry(QtCore.QRect(80, 240, 81, 21))
        self.cbShape.setObjectName(_fromUtf8("cbShape"))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.lineEdit_13 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(0, 290, 91, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.sbProtomodule = QtGui.QSpinBox(self.frame_2)
        self.sbProtomodule.setGeometry(QtCore.QRect(90, 310, 81, 21))
        self.sbProtomodule.setReadOnly(True)
        self.sbProtomodule.setMinimum(-1)
        self.sbProtomodule.setMaximum(2147483647)
        self.sbProtomodule.setObjectName(_fromUtf8("sbProtomodule"))
        self.leManufacturer = QtGui.QLineEdit(self.frame_2)
        self.leManufacturer.setGeometry(QtCore.QRect(80, 160, 81, 21))
        self.leManufacturer.setText(_fromUtf8(""))
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName(_fromUtf8("leManufacturer"))
        self.dsbSize = QtGui.QDoubleSpinBox(self.frame_2)
        self.dsbSize.setGeometry(QtCore.QRect(80, 200, 81, 21))
        self.dsbSize.setReadOnly(True)
        self.dsbSize.setMinimum(-1.0)
        self.dsbSize.setMaximum(2147483647.0)
        self.dsbSize.setObjectName(_fromUtf8("dsbSize"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(0, 220, 81, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_12 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(0, 310, 91, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.pushButton = QtGui.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(90, 20, 121, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pbGoStepSensor = QtGui.QPushButton(self.frame_2)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(170, 290, 41, 21))
        self.pbGoStepSensor.setObjectName(_fromUtf8("pbGoStepSensor"))
        self.lineEdit_11 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(0, 260, 81, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_9 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(0, 0, 91, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.lineEdit_2 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 140, 81, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.sbRotation = QtGui.QSpinBox(self.frame_2)
        self.sbRotation.setGeometry(QtCore.QRect(80, 260, 81, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName(_fromUtf8("sbRotation"))
        self.lineEdit_4 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 180, 81, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 20, 91, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_8 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(0, 330, 91, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.sbModule = QtGui.QSpinBox(self.frame_2)
        self.sbModule.setGeometry(QtCore.QRect(90, 330, 81, 21))
        self.sbModule.setReadOnly(True)
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName(_fromUtf8("sbModule"))
        self.leIdentifier = QtGui.QLineEdit(self.frame_2)
        self.leIdentifier.setGeometry(QtCore.QRect(80, 140, 81, 21))
        self.leIdentifier.setText(_fromUtf8(""))
        self.leIdentifier.setReadOnly(True)
        self.leIdentifier.setObjectName(_fromUtf8("leIdentifier"))
        self.sbChannels = QtGui.QSpinBox(self.frame_2)
        self.sbChannels.setGeometry(QtCore.QRect(80, 220, 81, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName(_fromUtf8("sbChannels"))
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(0, 160, 81, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.leIdentifier_2 = QtGui.QLineEdit(self.frame_2)
        self.leIdentifier_2.setGeometry(QtCore.QRect(90, 0, 121, 21))
        self.leIdentifier_2.setText(_fromUtf8(""))
        self.leIdentifier_2.setReadOnly(True)
        self.leIdentifier_2.setObjectName(_fromUtf8("leIdentifier_2"))
        self.lineEdit_5 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(0, 200, 81, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.listWidget = QtGui.QListWidget(self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(0, 40, 211, 91))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.leType = QtGui.QLineEdit(self.frame_2)
        self.leType.setGeometry(QtCore.QRect(80, 180, 81, 21))
        self.leType.setText(_fromUtf8(""))
        self.leType.setReadOnly(True)
        self.leType.setObjectName(_fromUtf8("leType"))
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 211, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pbSensorSave = QtGui.QPushButton(self.frame_3)
        self.pbSensorSave.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.pbSensorSave.setObjectName(_fromUtf8("pbSensorSave"))
        self.pbSensorEdit = QtGui.QPushButton(self.frame_3)
        self.pbSensorEdit.setGeometry(QtCore.QRect(0, 50, 71, 21))
        self.pbSensorEdit.setObjectName(_fromUtf8("pbSensorEdit"))
        self.pbSensorCancel = QtGui.QPushButton(self.frame_3)
        self.pbSensorCancel.setGeometry(QtCore.QRect(150, 30, 61, 21))
        self.pbSensorCancel.setObjectName(_fromUtf8("pbSensorCancel"))
        self.lineEdit = QtGui.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pbSensorNew = QtGui.QPushButton(self.frame_3)
        self.pbSensorNew.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.pbSensorNew.setObjectName(_fromUtf8("pbSensorNew"))
        self.sbSensorID = QtGui.QSpinBox(self.frame_3)
        self.sbSensorID.setGeometry(QtCore.QRect(80, 0, 131, 21))
        self.sbSensorID.setMaximum(2147483647)
        self.sbSensorID.setObjectName(_fromUtf8("sbSensorID"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pbAddComment.setText(_translate("Form", "add comment", None))
        self.lineEdit_14.setText(_translate("Form", "Comments", None))
        self.pbDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbGoProtomodule.setText(_translate("Form", "Go to", None))
        self.lineEdit_10.setText(_translate("Form", "Shape", None))
        self.pbGoModule.setText(_translate("Form", "Go to", None))
        self.cbShape.setItemText(0, _translate("Form", "full", None))
        self.cbShape.setItemText(1, _translate("Form", "half", None))
        self.cbShape.setItemText(2, _translate("Form", "...", None))
        self.lineEdit_13.setText(_translate("Form", "Placement step", None))
        self.lineEdit_6.setText(_translate("Form", "Channels", None))
        self.lineEdit_12.setText(_translate("Form", "On protomodule", None))
        self.pushButton.setText(_translate("Form", "go to selected", None))
        self.pbGoStepSensor.setText(_translate("Form", "Go to", None))
        self.lineEdit_11.setText(_translate("Form", "Rotation", None))
        self.lineEdit_9.setText(_translate("Form", "location", None))
        self.lineEdit_2.setText(_translate("Form", "Identifier", None))
        self.lineEdit_4.setText(_translate("Form", "Type", None))
        self.lineEdit_3.setText(_translate("Form", "shipments", None))
        self.lineEdit_8.setText(_translate("Form", "On module", None))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer", None))
        self.lineEdit_5.setText(_translate("Form", "Size", None))
        self.listWidget.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "541 (2019-06-04) (UCSB to CERN)", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pbSensorSave.setText(_translate("Form", "Save", None))
        self.pbSensorEdit.setText(_translate("Form", "Edit", None))
        self.pbSensorCancel.setText(_translate("Form", "Cancel", None))
        self.lineEdit.setText(_translate("Form", "Sensor ID", None))
        self.pbSensorNew.setText(_translate("Form", "New", None))

