# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_kapton_step.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 705)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbID = QtGui.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(90, 10, 71, 21))
        self.sbID.setObjectName(_fromUtf8("sbID"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 100, 91, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 120, 91, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 140, 91, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 160, 91, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 180, 91, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.sbBaseplate1 = QtGui.QSpinBox(Form)
        self.sbBaseplate1.setGeometry(QtCore.QRect(180, 230, 71, 22))
        self.sbBaseplate1.setMinimum(-1)
        self.sbBaseplate1.setMaximum(2147483647)
        self.sbBaseplate1.setObjectName(_fromUtf8("sbBaseplate1"))
        self.pbGoBaseplate1 = QtGui.QPushButton(Form)
        self.pbGoBaseplate1.setGeometry(QtCore.QRect(250, 230, 51, 21))
        self.pbGoBaseplate1.setObjectName(_fromUtf8("pbGoBaseplate1"))
        self.pbGoBaseplate2 = QtGui.QPushButton(Form)
        self.pbGoBaseplate2.setGeometry(QtCore.QRect(250, 250, 51, 21))
        self.pbGoBaseplate2.setObjectName(_fromUtf8("pbGoBaseplate2"))
        self.sbBaseplate2 = QtGui.QSpinBox(Form)
        self.sbBaseplate2.setGeometry(QtCore.QRect(180, 250, 71, 22))
        self.sbBaseplate2.setMinimum(-1)
        self.sbBaseplate2.setMaximum(2147483647)
        self.sbBaseplate2.setObjectName(_fromUtf8("sbBaseplate2"))
        self.sbBaseplate3 = QtGui.QSpinBox(Form)
        self.sbBaseplate3.setGeometry(QtCore.QRect(180, 270, 71, 22))
        self.sbBaseplate3.setMinimum(-1)
        self.sbBaseplate3.setMaximum(2147483647)
        self.sbBaseplate3.setObjectName(_fromUtf8("sbBaseplate3"))
        self.pbGoBaseplate3 = QtGui.QPushButton(Form)
        self.pbGoBaseplate3.setGeometry(QtCore.QRect(250, 270, 51, 21))
        self.pbGoBaseplate3.setObjectName(_fromUtf8("pbGoBaseplate3"))
        self.pbGoBaseplate6 = QtGui.QPushButton(Form)
        self.pbGoBaseplate6.setGeometry(QtCore.QRect(250, 330, 51, 21))
        self.pbGoBaseplate6.setObjectName(_fromUtf8("pbGoBaseplate6"))
        self.pbGoBaseplate4 = QtGui.QPushButton(Form)
        self.pbGoBaseplate4.setGeometry(QtCore.QRect(250, 290, 51, 21))
        self.pbGoBaseplate4.setObjectName(_fromUtf8("pbGoBaseplate4"))
        self.sbBaseplate6 = QtGui.QSpinBox(Form)
        self.sbBaseplate6.setGeometry(QtCore.QRect(180, 330, 71, 21))
        self.sbBaseplate6.setMinimum(-1)
        self.sbBaseplate6.setMaximum(2147483647)
        self.sbBaseplate6.setObjectName(_fromUtf8("sbBaseplate6"))
        self.pbGoBaseplate5 = QtGui.QPushButton(Form)
        self.pbGoBaseplate5.setGeometry(QtCore.QRect(250, 310, 51, 21))
        self.pbGoBaseplate5.setObjectName(_fromUtf8("pbGoBaseplate5"))
        self.sbBaseplate4 = QtGui.QSpinBox(Form)
        self.sbBaseplate4.setGeometry(QtCore.QRect(180, 290, 71, 22))
        self.sbBaseplate4.setMinimum(-1)
        self.sbBaseplate4.setMaximum(2147483647)
        self.sbBaseplate4.setObjectName(_fromUtf8("sbBaseplate4"))
        self.sbBaseplate5 = QtGui.QSpinBox(Form)
        self.sbBaseplate5.setGeometry(QtCore.QRect(180, 310, 71, 21))
        self.sbBaseplate5.setMinimum(-1)
        self.sbBaseplate5.setMaximum(2147483647)
        self.sbBaseplate5.setObjectName(_fromUtf8("sbBaseplate5"))
        self.leUserPerformed = QtGui.QLineEdit(Form)
        self.leUserPerformed.setGeometry(QtCore.QRect(120, 40, 111, 20))
        self.leUserPerformed.setObjectName(_fromUtf8("leUserPerformed"))
        self.leCureDuration = QtGui.QLineEdit(Form)
        self.leCureDuration.setGeometry(QtCore.QRect(100, 140, 131, 20))
        self.leCureDuration.setReadOnly(True)
        self.leCureDuration.setObjectName(_fromUtf8("leCureDuration"))
        self.leCureTemperature = QtGui.QLineEdit(Form)
        self.leCureTemperature.setGeometry(QtCore.QRect(100, 160, 131, 20))
        self.leCureTemperature.setObjectName(_fromUtf8("leCureTemperature"))
        self.leCureHumidity = QtGui.QLineEdit(Form)
        self.leCureHumidity.setGeometry(QtCore.QRect(100, 180, 131, 21))
        self.leCureHumidity.setObjectName(_fromUtf8("leCureHumidity"))
        self.pbNew = QtGui.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(310, 2, 71, 21))
        self.pbNew.setObjectName(_fromUtf8("pbNew"))
        self.pbEdit = QtGui.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(390, 0, 71, 21))
        self.pbEdit.setObjectName(_fromUtf8("pbEdit"))
        self.pbCancel = QtGui.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(390, 30, 71, 21))
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.pbSave = QtGui.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(310, 30, 71, 21))
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 400, 131, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 210, 51, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(70, 210, 101, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(180, 210, 121, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 230, 51, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 250, 51, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 270, 51, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 290, 51, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 310, 51, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 330, 51, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.sbTool5 = QtGui.QSpinBox(Form)
        self.sbTool5.setGeometry(QtCore.QRect(70, 310, 51, 22))
        self.sbTool5.setMinimum(-1)
        self.sbTool5.setMaximum(2147483647)
        self.sbTool5.setObjectName(_fromUtf8("sbTool5"))
        self.sbTool1 = QtGui.QSpinBox(Form)
        self.sbTool1.setGeometry(QtCore.QRect(70, 230, 51, 22))
        self.sbTool1.setMinimum(-1)
        self.sbTool1.setMaximum(2147483647)
        self.sbTool1.setObjectName(_fromUtf8("sbTool1"))
        self.sbTool3 = QtGui.QSpinBox(Form)
        self.sbTool3.setGeometry(QtCore.QRect(70, 270, 51, 22))
        self.sbTool3.setMinimum(-1)
        self.sbTool3.setMaximum(2147483647)
        self.sbTool3.setObjectName(_fromUtf8("sbTool3"))
        self.sbTool4 = QtGui.QSpinBox(Form)
        self.sbTool4.setGeometry(QtCore.QRect(70, 290, 51, 22))
        self.sbTool4.setMinimum(-1)
        self.sbTool4.setMaximum(2147483647)
        self.sbTool4.setObjectName(_fromUtf8("sbTool4"))
        self.sbTool2 = QtGui.QSpinBox(Form)
        self.sbTool2.setGeometry(QtCore.QRect(70, 250, 51, 22))
        self.sbTool2.setMinimum(-1)
        self.sbTool2.setMaximum(2147483647)
        self.sbTool2.setObjectName(_fromUtf8("sbTool2"))
        self.sbTool6 = QtGui.QSpinBox(Form)
        self.sbTool6.setGeometry(QtCore.QRect(70, 330, 51, 21))
        self.sbTool6.setMinimum(-1)
        self.sbTool6.setMaximum(2147483647)
        self.sbTool6.setObjectName(_fromUtf8("sbTool6"))
        self.sbBatchAraldite = QtGui.QSpinBox(Form)
        self.sbBatchAraldite.setGeometry(QtCore.QRect(140, 400, 71, 21))
        self.sbBatchAraldite.setMinimum(-1)
        self.sbBatchAraldite.setMaximum(999999)
        self.sbBatchAraldite.setObjectName(_fromUtf8("sbBatchAraldite"))
        self.dtCureStart = QtGui.QDateTimeEdit(Form)
        self.dtCureStart.setGeometry(QtCore.QRect(100, 100, 131, 21))
        self.dtCureStart.setObjectName(_fromUtf8("dtCureStart"))
        self.dtCureStop = QtGui.QDateTimeEdit(Form)
        self.dtCureStop.setGeometry(QtCore.QRect(100, 120, 131, 21))
        self.dtCureStop.setObjectName(_fromUtf8("dtCureStop"))
        self.dPerformed = QtGui.QDateEdit(Form)
        self.dPerformed.setGeometry(QtCore.QRect(120, 60, 111, 21))
        self.dPerformed.setObjectName(_fromUtf8("dPerformed"))
        self.pbGoTool5 = QtGui.QPushButton(Form)
        self.pbGoTool5.setGeometry(QtCore.QRect(120, 310, 51, 21))
        self.pbGoTool5.setObjectName(_fromUtf8("pbGoTool5"))
        self.pbGoTool4 = QtGui.QPushButton(Form)
        self.pbGoTool4.setGeometry(QtCore.QRect(120, 290, 51, 21))
        self.pbGoTool4.setObjectName(_fromUtf8("pbGoTool4"))
        self.pbGoTool1 = QtGui.QPushButton(Form)
        self.pbGoTool1.setGeometry(QtCore.QRect(120, 230, 51, 21))
        self.pbGoTool1.setObjectName(_fromUtf8("pbGoTool1"))
        self.pbGoTool2 = QtGui.QPushButton(Form)
        self.pbGoTool2.setGeometry(QtCore.QRect(120, 250, 51, 21))
        self.pbGoTool2.setObjectName(_fromUtf8("pbGoTool2"))
        self.pbGoTool6 = QtGui.QPushButton(Form)
        self.pbGoTool6.setGeometry(QtCore.QRect(120, 330, 51, 21))
        self.pbGoTool6.setObjectName(_fromUtf8("pbGoTool6"))
        self.pbGoTool3 = QtGui.QPushButton(Form)
        self.pbGoTool3.setGeometry(QtCore.QRect(120, 270, 51, 21))
        self.pbGoTool3.setObjectName(_fromUtf8("pbGoTool3"))
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 380, 131, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 360, 131, 21))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.sbTrayAssembly = QtGui.QSpinBox(Form)
        self.sbTrayAssembly.setGeometry(QtCore.QRect(140, 380, 71, 21))
        self.sbTrayAssembly.setMinimum(-1)
        self.sbTrayAssembly.setMaximum(999999)
        self.sbTrayAssembly.setObjectName(_fromUtf8("sbTrayAssembly"))
        self.sbTrayComponent = QtGui.QSpinBox(Form)
        self.sbTrayComponent.setGeometry(QtCore.QRect(140, 360, 71, 21))
        self.sbTrayComponent.setMinimum(-1)
        self.sbTrayComponent.setMaximum(999999)
        self.sbTrayComponent.setObjectName(_fromUtf8("sbTrayComponent"))
        self.pbGoTrayAssembly = QtGui.QPushButton(Form)
        self.pbGoTrayAssembly.setGeometry(QtCore.QRect(210, 380, 51, 21))
        self.pbGoTrayAssembly.setObjectName(_fromUtf8("pbGoTrayAssembly"))
        self.pbGoTrayComponent = QtGui.QPushButton(Form)
        self.pbGoTrayComponent.setGeometry(QtCore.QRect(210, 360, 51, 21))
        self.pbGoTrayComponent.setObjectName(_fromUtf8("pbGoTrayComponent"))
        self.pbGoBatchAraldite = QtGui.QPushButton(Form)
        self.pbGoBatchAraldite.setGeometry(QtCore.QRect(210, 400, 51, 21))
        self.pbGoBatchAraldite.setObjectName(_fromUtf8("pbGoBatchAraldite"))
        self.pbDatePerformedNow = QtGui.QPushButton(Form)
        self.pbDatePerformedNow.setGeometry(QtCore.QRect(230, 60, 75, 21))
        self.pbDatePerformedNow.setObjectName(_fromUtf8("pbDatePerformedNow"))
        self.pbCureStartNow = QtGui.QPushButton(Form)
        self.pbCureStartNow.setGeometry(QtCore.QRect(230, 100, 75, 21))
        self.pbCureStartNow.setObjectName(_fromUtf8("pbCureStartNow"))
        self.pbCureStopNow = QtGui.QPushButton(Form)
        self.pbCureStopNow.setGeometry(QtCore.QRect(230, 120, 75, 21))
        self.pbCureStopNow.setObjectName(_fromUtf8("pbCureStopNow"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "Kapton step ID", None))
        self.lineEdit_2.setText(_translate("Form", "who performed step", None))
        self.lineEdit_3.setText(_translate("Form", "date performed", None))
        self.lineEdit_5.setText(_translate("Form", "cure start", None))
        self.lineEdit_6.setText(_translate("Form", "cure stop", None))
        self.lineEdit_7.setText(_translate("Form", "cure duration", None))
        self.lineEdit_8.setText(_translate("Form", "cure temperature", None))
        self.lineEdit_9.setText(_translate("Form", "cure humidity", None))
        self.pbGoBaseplate1.setText(_translate("Form", "go to", None))
        self.pbGoBaseplate2.setText(_translate("Form", "go to", None))
        self.pbGoBaseplate3.setText(_translate("Form", "go to", None))
        self.pbGoBaseplate6.setText(_translate("Form", "go to", None))
        self.pbGoBaseplate4.setText(_translate("Form", "go to", None))
        self.pbGoBaseplate5.setText(_translate("Form", "go to", None))
        self.pbNew.setText(_translate("Form", "New", None))
        self.pbEdit.setText(_translate("Form", "Edit", None))
        self.pbCancel.setText(_translate("Form", "Cancel", None))
        self.pbSave.setText(_translate("Form", "Save", None))
        self.lineEdit_11.setText(_translate("Form", "araldite batch", None))
        self.lineEdit_12.setText(_translate("Form", "position", None))
        self.lineEdit_13.setText(_translate("Form", "sensor tool ID", None))
        self.lineEdit_14.setText(_translate("Form", "baseplate ID", None))
        self.lineEdit_15.setText(_translate("Form", "1", None))
        self.lineEdit_16.setText(_translate("Form", "2", None))
        self.lineEdit_17.setText(_translate("Form", "3", None))
        self.lineEdit_18.setText(_translate("Form", "4", None))
        self.lineEdit_19.setText(_translate("Form", "5", None))
        self.lineEdit_20.setText(_translate("Form", "6", None))
        self.pbGoTool5.setText(_translate("Form", "go to", None))
        self.pbGoTool4.setText(_translate("Form", "go to", None))
        self.pbGoTool1.setText(_translate("Form", "go to", None))
        self.pbGoTool2.setText(_translate("Form", "go to", None))
        self.pbGoTool6.setText(_translate("Form", "go to", None))
        self.pbGoTool3.setText(_translate("Form", "go to", None))
        self.lineEdit_21.setText(_translate("Form", "assembly tray", None))
        self.lineEdit_22.setText(_translate("Form", "component tray (sensor)", None))
        self.pbGoTrayAssembly.setText(_translate("Form", "go to", None))
        self.pbGoTrayComponent.setText(_translate("Form", "go to", None))
        self.pbGoBatchAraldite.setText(_translate("Form", "go to", None))
        self.pbDatePerformedNow.setText(_translate("Form", "set to today", None))
        self.pbCureStartNow.setText(_translate("Form", "set to now", None))
        self.pbCureStopNow.setText(_translate("Form", "set to now", None))

