# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_wirebonding.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1199, 756)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(190, 30, 81, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(100, 30, 81, 21))
        self.pbSave.setObjectName("pbSave")
        self.pteWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteWriteComment.setGeometry(QtCore.QRect(670, 310, 281, 61))
        self.pteWriteComment.setPlainText("")
        self.pteWriteComment.setObjectName("pteWriteComment")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(670, 190, 161, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pbDeleteComment = QtWidgets.QPushButton(Form)
        self.pbDeleteComment.setGeometry(QtCore.QRect(830, 190, 121, 21))
        self.pbDeleteComment.setObjectName("pbDeleteComment")
        self.listComments = QtWidgets.QListWidget(Form)
        self.listComments.setGeometry(QtCore.QRect(670, 210, 281, 91))
        self.listComments.setObjectName("listComments")
        self.pbAddComment = QtWidgets.QPushButton(Form)
        self.pbAddComment.setGeometry(QtCore.QRect(670, 370, 111, 21))
        self.pbAddComment.setObjectName("pbAddComment")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 120, 211, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 280, 171, 21))
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 300, 281, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.ckWirebondsInspectedBack = QtWidgets.QCheckBox(self.frame)
        self.ckWirebondsInspectedBack.setGeometry(QtCore.QRect(1, 140, 241, 17))
        self.ckWirebondsInspectedBack.setObjectName("ckWirebondsInspectedBack")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_31.setGeometry(QtCore.QRect(1, 20, 171, 21))
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(2, 60, 141, 16))
        self.label_3.setObjectName("label_3")
        self.ckWirebondingBack = QtWidgets.QCheckBox(self.frame)
        self.ckWirebondingBack.setGeometry(QtCore.QRect(1, 0, 231, 17))
        self.ckWirebondingBack.setObjectName("ckWirebondingBack")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_36.setGeometry(QtCore.QRect(1, 170, 181, 20))
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.pteUnbondedChannelsBack = QtWidgets.QPlainTextEdit(self.frame)
        self.pteUnbondedChannelsBack.setGeometry(QtCore.QRect(0, 80, 281, 51))
        self.pteUnbondedChannelsBack.setObjectName("pteUnbondedChannelsBack")
        self.cbWirebondingUserBack = QtWidgets.QComboBox(self.frame)
        self.cbWirebondingUserBack.setGeometry(QtCore.QRect(170, 20, 111, 21))
        self.cbWirebondingUserBack.setObjectName("cbWirebondingUserBack")
        self.cbWirebondsRepairedUserBack = QtWidgets.QComboBox(self.frame)
        self.cbWirebondsRepairedUserBack.setGeometry(QtCore.QRect(180, 170, 101, 21))
        self.cbWirebondsRepairedUserBack.setObjectName("cbWirebondsRepairedUserBack")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 140, 282, 21))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(1, 0, 191, 20))
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.cbPreinspection = QtWidgets.QComboBox(self.frame_2)
        self.cbPreinspection.setGeometry(QtCore.QRect(190, 0, 92, 20))
        self.cbPreinspection.setObjectName("cbPreinspection")
        self.cbPreinspection.addItem("")
        self.cbPreinspection.addItem("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(670, 110, 181, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 510, 171, 16))
        self.label_5.setObjectName("label_5")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(670, 130, 241, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.cbWirebondingFinalInspectionOK = QtWidgets.QComboBox(self.frame_3)
        self.cbWirebondingFinalInspectionOK.setGeometry(QtCore.QRect(150, 20, 91, 21))
        self.cbWirebondingFinalInspectionOK.setObjectName("cbWirebondingFinalInspectionOK")
        self.cbWirebondingFinalInspectionOK.addItem("")
        self.cbWirebondingFinalInspectionOK.addItem("")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_37.setGeometry(QtCore.QRect(1, 20, 151, 20))
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_40.setGeometry(QtCore.QRect(1, 0, 151, 21))
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.cbWirebondingFinalInspectionUser = QtWidgets.QComboBox(self.frame_3)
        self.cbWirebondingFinalInspectionUser.setGeometry(QtCore.QRect(150, 0, 91, 21))
        self.cbWirebondingFinalInspectionUser.setObjectName("cbWirebondingFinalInspectionUser")
        self.lineEdit_37.raise_()
        self.lineEdit_40.raise_()
        self.cbWirebondingFinalInspectionOK.raise_()
        self.cbWirebondingFinalInspectionUser.raise_()
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(10, 530, 291, 141))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.ckEncapsulationBack = QtWidgets.QCheckBox(self.frame_4)
        self.ckEncapsulationBack.setGeometry(QtCore.QRect(0, 0, 191, 17))
        self.ckEncapsulationBack.setObjectName("ckEncapsulationBack")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_38.setGeometry(QtCore.QRect(1, 20, 141, 21))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.dtCureStartBack = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dtCureStartBack.setGeometry(QtCore.QRect(140, 60, 151, 21))
        self.dtCureStartBack.setDate(QtCore.QDate(2021, 1, 1))
        self.dtCureStartBack.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStartBack.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStartBack.setCalendarPopup(True)
        self.dtCureStartBack.setObjectName("dtCureStartBack")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(1, 80, 141, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pbCureStopNowBack = QtWidgets.QPushButton(self.frame_4)
        self.pbCureStopNowBack.setGeometry(QtCore.QRect(140, 80, 151, 21))
        self.pbCureStopNowBack.setObjectName("pbCureStopNowBack")
        self.pbCureStartNowBack = QtWidgets.QPushButton(self.frame_4)
        self.pbCureStartNowBack.setGeometry(QtCore.QRect(140, 40, 151, 21))
        self.pbCureStartNowBack.setObjectName("pbCureStartNowBack")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(1, 40, 141, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_39.setGeometry(QtCore.QRect(1, 120, 161, 20))
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.cbEncapsulationInspectionBack = QtWidgets.QComboBox(self.frame_4)
        self.cbEncapsulationInspectionBack.setGeometry(QtCore.QRect(160, 120, 131, 20))
        self.cbEncapsulationInspectionBack.setObjectName("cbEncapsulationInspectionBack")
        self.cbEncapsulationInspectionBack.addItem("")
        self.cbEncapsulationInspectionBack.addItem("")
        self.dtCureStopBack = QtWidgets.QDateTimeEdit(self.frame_4)
        self.dtCureStopBack.setGeometry(QtCore.QRect(140, 100, 151, 21))
        self.dtCureStopBack.setDate(QtCore.QDate(2021, 1, 1))
        self.dtCureStopBack.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStopBack.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStopBack.setCalendarPopup(True)
        self.dtCureStopBack.setObjectName("dtCureStopBack")
        self.cbEncapsulationUserBack = QtWidgets.QComboBox(self.frame_4)
        self.cbEncapsulationUserBack.setGeometry(QtCore.QRect(140, 20, 151, 21))
        self.cbEncapsulationUserBack.setObjectName("cbEncapsulationUserBack")
        self.leID = QtWidgets.QLineEdit(Form)
        self.leID.setGeometry(QtCore.QRect(160, 10, 111, 20))
        self.leID.setText("")
        self.leID.setReadOnly(True)
        self.leID.setObjectName("leID")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(10, 50, 111, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(340, 90, 282, 81))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_32.setGeometry(QtCore.QRect(1, 20, 191, 21))
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.ckTestBonds = QtWidgets.QCheckBox(self.frame_5)
        self.ckTestBonds.setGeometry(QtCore.QRect(1, 0, 161, 17))
        self.ckTestBonds.setObjectName("ckTestBonds")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_43.setGeometry(QtCore.QRect(0, 40, 191, 21))
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_44.setGeometry(QtCore.QRect(0, 60, 191, 21))
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.dsbBondPullAvg = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.dsbBondPullAvg.setGeometry(QtCore.QRect(190, 40, 91, 21))
        self.dsbBondPullAvg.setObjectName("dsbBondPullAvg")
        self.dsbBondPullStd = QtWidgets.QDoubleSpinBox(self.frame_5)
        self.dsbBondPullStd.setGeometry(QtCore.QRect(190, 60, 91, 21))
        self.dsbBondPullStd.setObjectName("dsbBondPullStd")
        self.cbTestBondsPulledUser = QtWidgets.QComboBox(self.frame_5)
        self.cbTestBondsPulledUser.setGeometry(QtCore.QRect(190, 20, 91, 21))
        self.cbTestBondsPulledUser.setObjectName("cbTestBondsPulledUser")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(340, 70, 211, 21))
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(340, 190, 171, 21))
        self.label_12.setObjectName("label_12")
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(340, 210, 281, 271))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.ckWirebondsInspectedFront = QtWidgets.QCheckBox(self.frame_6)
        self.ckWirebondsInspectedFront.setGeometry(QtCore.QRect(0, 220, 241, 17))
        self.ckWirebondsInspectedFront.setObjectName("ckWirebondsInspectedFront")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_41.setGeometry(QtCore.QRect(1, 20, 181, 21))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(2, 140, 141, 16))
        self.label_9.setObjectName("label_9")
        self.ckWirebondingFront = QtWidgets.QCheckBox(self.frame_6)
        self.ckWirebondingFront.setGeometry(QtCore.QRect(0, 0, 231, 17))
        self.ckWirebondingFront.setObjectName("ckWirebondingFront")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_42.setGeometry(QtCore.QRect(1, 250, 181, 20))
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.pteUnbondedChannelsFront = QtWidgets.QPlainTextEdit(self.frame_6)
        self.pteUnbondedChannelsFront.setGeometry(QtCore.QRect(0, 160, 281, 51))
        self.pteUnbondedChannelsFront.setObjectName("pteUnbondedChannelsFront")
        self.pteWirebondingChannelsSkipFront = QtWidgets.QPlainTextEdit(self.frame_6)
        self.pteWirebondingChannelsSkipFront.setGeometry(QtCore.QRect(0, 80, 281, 51))
        self.pteWirebondingChannelsSkipFront.setReadOnly(True)
        self.pteWirebondingChannelsSkipFront.setObjectName("pteWirebondingChannelsSkipFront")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(0, 60, 251, 16))
        self.label_13.setObjectName("label_13")
        self.cbWirebondingUserFront = QtWidgets.QComboBox(self.frame_6)
        self.cbWirebondingUserFront.setGeometry(QtCore.QRect(180, 20, 101, 21))
        self.cbWirebondingUserFront.setObjectName("cbWirebondingUserFront")
        self.cbWirebondsRepairedUserFront = QtWidgets.QComboBox(self.frame_6)
        self.cbWirebondsRepairedUserFront.setGeometry(QtCore.QRect(180, 250, 101, 21))
        self.cbWirebondsRepairedUserFront.setObjectName("cbWirebondsRepairedUserFront")
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(340, 520, 281, 141))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.ckEncapsulationFront = QtWidgets.QCheckBox(self.frame_7)
        self.ckEncapsulationFront.setGeometry(QtCore.QRect(0, 0, 201, 17))
        self.ckEncapsulationFront.setObjectName("ckEncapsulationFront")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_45.setGeometry(QtCore.QRect(1, 20, 141, 21))
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.dtCureStartFront = QtWidgets.QDateTimeEdit(self.frame_7)
        self.dtCureStartFront.setGeometry(QtCore.QRect(140, 60, 141, 21))
        self.dtCureStartFront.setDate(QtCore.QDate(2021, 1, 1))
        self.dtCureStartFront.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStartFront.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStartFront.setCalendarPopup(True)
        self.dtCureStartFront.setObjectName("dtCureStartFront")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(1, 80, 141, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pbCureStopNowFront = QtWidgets.QPushButton(self.frame_7)
        self.pbCureStopNowFront.setGeometry(QtCore.QRect(140, 80, 141, 21))
        self.pbCureStopNowFront.setObjectName("pbCureStopNowFront")
        self.pbCureStartNowFront = QtWidgets.QPushButton(self.frame_7)
        self.pbCureStartNowFront.setGeometry(QtCore.QRect(140, 40, 141, 21))
        self.pbCureStartNowFront.setObjectName("pbCureStartNowFront")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_11.setGeometry(QtCore.QRect(1, 40, 141, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_46.setGeometry(QtCore.QRect(1, 120, 161, 20))
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.cbEncapsulationInspectionFront = QtWidgets.QComboBox(self.frame_7)
        self.cbEncapsulationInspectionFront.setGeometry(QtCore.QRect(160, 120, 121, 20))
        self.cbEncapsulationInspectionFront.setObjectName("cbEncapsulationInspectionFront")
        self.cbEncapsulationInspectionFront.addItem("")
        self.cbEncapsulationInspectionFront.addItem("")
        self.dtCureStopFront = QtWidgets.QDateTimeEdit(self.frame_7)
        self.dtCureStopFront.setGeometry(QtCore.QRect(140, 100, 141, 21))
        self.dtCureStopFront.setDate(QtCore.QDate(2021, 1, 1))
        self.dtCureStopFront.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.dtCureStopFront.setMinimumDate(QtCore.QDate(2000, 9, 1))
        self.dtCureStopFront.setCalendarPopup(True)
        self.dtCureStopFront.setObjectName("dtCureStopFront")
        self.cbEncapsulationUserFront = QtWidgets.QComboBox(self.frame_7)
        self.cbEncapsulationUserFront.setGeometry(QtCore.QRect(140, 20, 141, 21))
        self.cbEncapsulationUserFront.setObjectName("cbEncapsulationUserFront")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(340, 500, 181, 16))
        self.label_14.setObjectName("label_14")
        self.leErrors = QtWidgets.QLineEdit(Form)
        self.leErrors.setGeometry(QtCore.QRect(330, 30, 631, 21))
        self.leErrors.setText("")
        self.leErrors.setReadOnly(True)
        self.leErrors.setObjectName("leErrors")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(660, 50, 321, 51))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(330, 10, 181, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 90, 141, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.dWirebonding = QtWidgets.QDateEdit(Form)
        self.dWirebonding.setGeometry(QtCore.QRect(150, 90, 141, 21))
        self.dWirebonding.setCalendarPopup(True)
        self.dWirebonding.setDate(QtCore.QDate(2021, 1, 1))
        self.dWirebonding.setObjectName("dWirebonding")
        self.pteWriteCommentEncap = QtWidgets.QPlainTextEdit(Form)
        self.pteWriteCommentEncap.setGeometry(QtCore.QRect(670, 550, 281, 61))
        self.pteWriteCommentEncap.setPlainText("")
        self.pteWriteCommentEncap.setObjectName("pteWriteCommentEncap")
        self.pbAddCommentEncap = QtWidgets.QPushButton(Form)
        self.pbAddCommentEncap.setGeometry(QtCore.QRect(670, 610, 111, 21))
        self.pbAddCommentEncap.setObjectName("pbAddCommentEncap")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(670, 430, 161, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.listCommentsEncap = QtWidgets.QListWidget(Form)
        self.listCommentsEncap.setGeometry(QtCore.QRect(670, 450, 281, 91))
        self.listCommentsEncap.setObjectName("listCommentsEncap")
        self.pbDeleteCommentEncap = QtWidgets.QPushButton(Form)
        self.pbDeleteCommentEncap.setGeometry(QtCore.QRect(830, 430, 121, 21))
        self.pbDeleteCommentEncap.setObjectName("pbDeleteCommentEncap")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 180, 171, 21))
        self.label_7.setObjectName("label_7")
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setGeometry(QtCore.QRect(10, 200, 281, 61))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_33.setGeometry(QtCore.QRect(0, 0, 181, 21))
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_34.setGeometry(QtCore.QRect(0, 20, 181, 21))
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_35.setGeometry(QtCore.QRect(0, 40, 181, 21))
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.sbBatchSylgard = QtWidgets.QSpinBox(self.frame_8)
        self.sbBatchSylgard.setGeometry(QtCore.QRect(180, 0, 101, 21))
        self.sbBatchSylgard.setMinimum(-1)
        self.sbBatchSylgard.setMaximum(999999)
        self.sbBatchSylgard.setObjectName("sbBatchSylgard")
        self.sbBatchBondWire = QtWidgets.QSpinBox(self.frame_8)
        self.sbBatchBondWire.setGeometry(QtCore.QRect(180, 20, 101, 21))
        self.sbBatchBondWire.setMinimum(-1)
        self.sbBatchBondWire.setMaximum(999999)
        self.sbBatchBondWire.setObjectName("sbBatchBondWire")
        self.sbBatchWedge = QtWidgets.QSpinBox(self.frame_8)
        self.sbBatchWedge.setGeometry(QtCore.QRect(180, 40, 101, 21))
        self.sbBatchWedge.setMinimum(-1)
        self.sbBatchWedge.setMaximum(999999)
        self.sbBatchWedge.setObjectName("sbBatchWedge")

        self.retranslateUi(Form)
        self.cbWirebondingUserBack.setCurrentIndex(-1)
        self.cbWirebondsRepairedUserBack.setCurrentIndex(-1)
        self.cbPreinspection.setCurrentIndex(-1)
        self.cbWirebondingFinalInspectionOK.setCurrentIndex(-1)
        self.cbWirebondingFinalInspectionUser.setCurrentIndex(-1)
        self.cbEncapsulationInspectionBack.setCurrentIndex(-1)
        self.cbEncapsulationUserBack.setCurrentIndex(-1)
        self.cbTestBondsPulledUser.setCurrentIndex(-1)
        self.cbWirebondingUserFront.setCurrentIndex(-1)
        self.cbWirebondsRepairedUserFront.setCurrentIndex(-1)
        self.cbEncapsulationInspectionFront.setCurrentIndex(-1)
        self.cbEncapsulationUserFront.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Module to wirebond"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit_16.setText(_translate("Form", "wirebonding notes"))
        self.pbDeleteComment.setText(_translate("Form", "Delete selected"))
        self.pbAddComment.setText(_translate("Form", "Add comment"))
        self.label.setText(_translate("Form", "Pre-wirebonding qualification"))
        self.label_2.setText(_translate("Form", "Wirebonding:  Back side"))
        self.ckWirebondsInspectedBack.setText(_translate("Form", "Wirebonds inspected"))
        self.lineEdit_31.setText(_translate("Form", "Back wirebonding user"))
        self.label_3.setText(_translate("Form", "Unbonded areas"))
        self.ckWirebondingBack.setText(_translate("Form", "Back wirebonding performed"))
        self.lineEdit_36.setText(_translate("Form", "Wirebonds repaired user"))
        self.lineEdit_29.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_29.setText(_translate("Form", "Visual inspection"))
        self.cbPreinspection.setItemText(0, _translate("Form", "pass"))
        self.cbPreinspection.setItemText(1, _translate("Form", "fail"))
        self.label_4.setText(_translate("Form", "Wirebonding qualification"))
        self.label_5.setText(_translate("Form", "Encapsulation:  Back side"))
        self.cbWirebondingFinalInspectionOK.setItemText(0, _translate("Form", "pass"))
        self.cbWirebondingFinalInspectionOK.setItemText(1, _translate("Form", "fail"))
        self.lineEdit_37.setText(_translate("Form", "Final inspection OK?"))
        self.lineEdit_40.setText(_translate("Form", "Final inspection user"))
        self.ckEncapsulationBack.setText(_translate("Form", "Back encapsulation done"))
        self.lineEdit_38.setText(_translate("Form", "Encpasulation user"))
        self.lineEdit_6.setText(_translate("Form", "oven cure stop"))
        self.pbCureStopNowBack.setText(_translate("Form", "set to now"))
        self.pbCureStartNowBack.setText(_translate("Form", "set to now"))
        self.lineEdit_7.setText(_translate("Form", "oven cure start"))
        self.lineEdit_39.setText(_translate("Form", "Post-curing inspection"))
        self.cbEncapsulationInspectionBack.setItemText(0, _translate("Form", "pass"))
        self.cbEncapsulationInspectionBack.setItemText(1, _translate("Form", "fail"))
        self.lineEdit_32.setText(_translate("Form", "Test bond pull user"))
        self.ckTestBonds.setText(_translate("Form", "Is test bond module"))
        self.lineEdit_43.setText(_translate("Form", "Pull strength average (g)"))
        self.lineEdit_44.setText(_translate("Form", "Pull strength stddev (g)"))
        self.label_8.setText(_translate("Form", "Test bonds"))
        self.label_12.setText(_translate("Form", "Wirebonding:  Front side"))
        self.ckWirebondsInspectedFront.setText(_translate("Form", "Wirebonds inspected"))
        self.lineEdit_41.setText(_translate("Form", "Front wirebonding user"))
        self.label_9.setText(_translate("Form", "Unbonded channels"))
        self.ckWirebondingFront.setText(_translate("Form", "Front wirebonding performed"))
        self.lineEdit_42.setText(_translate("Form", "Wirebonds repaired user"))
        self.label_13.setText(_translate("Form", "Channels to skip (currently disabled)"))
        self.ckEncapsulationFront.setText(_translate("Form", "Front encapsulation done"))
        self.lineEdit_45.setText(_translate("Form", "Encpasulation user"))
        self.lineEdit_10.setText(_translate("Form", "oven cure stop"))
        self.pbCureStopNowFront.setText(_translate("Form", "set to now"))
        self.pbCureStartNowFront.setText(_translate("Form", "set to now"))
        self.lineEdit_11.setText(_translate("Form", "oven cure start"))
        self.lineEdit_46.setText(_translate("Form", "Post-curing inspection"))
        self.cbEncapsulationInspectionFront.setItemText(0, _translate("Form", "pass"))
        self.cbEncapsulationInspectionFront.setItemText(1, _translate("Form", "fail"))
        self.label_14.setText(_translate("Form", "Encapsulation:  Front side"))
        self.label_6.setText(_translate("Form", "Note:  Format of all text box input should be a comma-separated list of values.  ex. 1, 3, 4, ..."))
        self.label_15.setText(_translate("Form", "Errors:"))
        self.lineEdit_15.setText(_translate("Form", "wirebonding date"))
        self.pbAddCommentEncap.setText(_translate("Form", "Add comment"))
        self.lineEdit_17.setText(_translate("Form", "encapsulation notes"))
        self.pbDeleteCommentEncap.setText(_translate("Form", "Delete selected"))
        self.label_7.setText(_translate("Form", "Supply batches"))
        self.lineEdit_33.setText(_translate("Form", "Sylgard batch ID"))
        self.lineEdit_34.setText(_translate("Form", "Bond wire batch ID"))
        self.lineEdit_35.setText(_translate("Form", "Wedge batch ID"))

