# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_sensor_step.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 705)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.sbID = QtWidgets.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(120, 10, 61, 21))
        self.sbID.setObjectName("sbID")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(650, 140, 151, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(650, 240, 131, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(650, 260, 131, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.sbProtoModule1 = QtWidgets.QSpinBox(Form)
        self.sbProtoModule1.setGeometry(QtCore.QRect(460, 160, 131, 22))
        self.sbProtoModule1.setMinimum(-1)
        self.sbProtoModule1.setMaximum(2147483647)
        self.sbProtoModule1.setObjectName("sbProtoModule1")
        self.pbGoProtoModule1 = QtWidgets.QPushButton(Form)
        self.pbGoProtoModule1.setGeometry(QtCore.QRect(590, 160, 51, 21))
        self.pbGoProtoModule1.setObjectName("pbGoProtoModule1")
        self.pbGoProtoModule2 = QtWidgets.QPushButton(Form)
        self.pbGoProtoModule2.setGeometry(QtCore.QRect(590, 180, 51, 21))
        self.pbGoProtoModule2.setObjectName("pbGoProtoModule2")
        self.sbProtoModule2 = QtWidgets.QSpinBox(Form)
        self.sbProtoModule2.setGeometry(QtCore.QRect(460, 180, 131, 22))
        self.sbProtoModule2.setMinimum(-1)
        self.sbProtoModule2.setMaximum(2147483647)
        self.sbProtoModule2.setObjectName("sbProtoModule2")
        self.sbProtoModule3 = QtWidgets.QSpinBox(Form)
        self.sbProtoModule3.setGeometry(QtCore.QRect(460, 200, 131, 22))
        self.sbProtoModule3.setMinimum(-1)
        self.sbProtoModule3.setMaximum(2147483647)
        self.sbProtoModule3.setObjectName("sbProtoModule3")
        self.pbGoProtoModule3 = QtWidgets.QPushButton(Form)
        self.pbGoProtoModule3.setGeometry(QtCore.QRect(590, 200, 51, 21))
        self.pbGoProtoModule3.setObjectName("pbGoProtoModule3")
        self.pbGoProtoModule6 = QtWidgets.QPushButton(Form)
        self.pbGoProtoModule6.setGeometry(QtCore.QRect(590, 260, 51, 21))
        self.pbGoProtoModule6.setObjectName("pbGoProtoModule6")
        self.pbGoProtoModule4 = QtWidgets.QPushButton(Form)
        self.pbGoProtoModule4.setGeometry(QtCore.QRect(590, 220, 51, 21))
        self.pbGoProtoModule4.setObjectName("pbGoProtoModule4")
        self.sbProtoModule6 = QtWidgets.QSpinBox(Form)
        self.sbProtoModule6.setGeometry(QtCore.QRect(460, 260, 131, 21))
        self.sbProtoModule6.setMinimum(-1)
        self.sbProtoModule6.setMaximum(2147483647)
        self.sbProtoModule6.setObjectName("sbProtoModule6")
        self.pbGoProtoModule5 = QtWidgets.QPushButton(Form)
        self.pbGoProtoModule5.setGeometry(QtCore.QRect(590, 240, 51, 21))
        self.pbGoProtoModule5.setObjectName("pbGoProtoModule5")
        self.sbProtoModule4 = QtWidgets.QSpinBox(Form)
        self.sbProtoModule4.setGeometry(QtCore.QRect(460, 220, 131, 22))
        self.sbProtoModule4.setMinimum(-1)
        self.sbProtoModule4.setMaximum(2147483647)
        self.sbProtoModule4.setObjectName("sbProtoModule4")
        self.sbProtoModule5 = QtWidgets.QSpinBox(Form)
        self.sbProtoModule5.setGeometry(QtCore.QRect(460, 240, 131, 21))
        self.sbProtoModule5.setMinimum(-1)
        self.sbProtoModule5.setMaximum(2147483647)
        self.sbProtoModule5.setObjectName("sbProtoModule5")
        self.leUserPerformed = QtWidgets.QLineEdit(Form)
        self.leUserPerformed.setGeometry(QtCore.QRect(800, 140, 121, 20))
        self.leUserPerformed.setObjectName("leUserPerformed")
        self.leCureTemperature = QtWidgets.QLineEdit(Form)
        self.leCureTemperature.setGeometry(QtCore.QRect(780, 240, 151, 20))
        self.leCureTemperature.setObjectName("leCureTemperature")
        self.leCureHumidity = QtWidgets.QLineEdit(Form)
        self.leCureHumidity.setGeometry(QtCore.QRect(780, 260, 151, 21))
        self.leCureHumidity.setObjectName("leCureHumidity")
        self.pbNew = QtWidgets.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.pbNew.setObjectName("pbNew")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(170, 40, 71, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.pbSave.setObjectName("pbSave")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 140, 71, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(460, 140, 181, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 160, 71, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 180, 71, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 200, 71, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 220, 71, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 240, 71, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pbGoBaseplate4 = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate4.setGeometry(QtCore.QRect(400, 220, 51, 21))
        self.pbGoBaseplate4.setObjectName("pbGoBaseplate4")
        self.sbTool4 = QtWidgets.QSpinBox(Form)
        self.sbTool4.setGeometry(QtCore.QRect(90, 220, 51, 22))
        self.sbTool4.setMinimum(-1)
        self.sbTool4.setMaximum(2147483647)
        self.sbTool4.setObjectName("sbTool4")
        self.pbGoTool3 = QtWidgets.QPushButton(Form)
        self.pbGoTool3.setGeometry(QtCore.QRect(140, 200, 51, 21))
        self.pbGoTool3.setObjectName("pbGoTool3")
        self.pbGoBaseplate2 = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate2.setGeometry(QtCore.QRect(400, 180, 51, 21))
        self.pbGoBaseplate2.setObjectName("pbGoBaseplate2")
        self.sbTool3 = QtWidgets.QSpinBox(Form)
        self.sbTool3.setGeometry(QtCore.QRect(90, 200, 51, 22))
        self.sbTool3.setMinimum(-1)
        self.sbTool3.setMaximum(2147483647)
        self.sbTool3.setObjectName("sbTool3")
        self.pbGoTool4 = QtWidgets.QPushButton(Form)
        self.pbGoTool4.setGeometry(QtCore.QRect(140, 220, 51, 21))
        self.pbGoTool4.setObjectName("pbGoTool4")
        self.pbGoBaseplate6 = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate6.setGeometry(QtCore.QRect(400, 260, 51, 21))
        self.pbGoBaseplate6.setObjectName("pbGoBaseplate6")
        self.pbGoBaseplate3 = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate3.setGeometry(QtCore.QRect(400, 200, 51, 21))
        self.pbGoBaseplate3.setObjectName("pbGoBaseplate3")
        self.pbGoBaseplate5 = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate5.setGeometry(QtCore.QRect(400, 240, 51, 21))
        self.pbGoBaseplate5.setObjectName("pbGoBaseplate5")
        self.pbGoBaseplate1 = QtWidgets.QPushButton(Form)
        self.pbGoBaseplate1.setGeometry(QtCore.QRect(400, 160, 51, 21))
        self.pbGoBaseplate1.setObjectName("pbGoBaseplate1")
        self.sbTool1 = QtWidgets.QSpinBox(Form)
        self.sbTool1.setGeometry(QtCore.QRect(90, 160, 51, 22))
        self.sbTool1.setMinimum(-1)
        self.sbTool1.setMaximum(2147483647)
        self.sbTool1.setObjectName("sbTool1")
        self.sbBaseplate3 = QtWidgets.QSpinBox(Form)
        self.sbBaseplate3.setGeometry(QtCore.QRect(330, 200, 71, 22))
        self.sbBaseplate3.setMinimum(-1)
        self.sbBaseplate3.setMaximum(2147483647)
        self.sbBaseplate3.setObjectName("sbBaseplate3")
        self.pbGoTool2 = QtWidgets.QPushButton(Form)
        self.pbGoTool2.setGeometry(QtCore.QRect(140, 180, 51, 21))
        self.pbGoTool2.setObjectName("pbGoTool2")
        self.pbGoTool6 = QtWidgets.QPushButton(Form)
        self.pbGoTool6.setGeometry(QtCore.QRect(140, 260, 51, 21))
        self.pbGoTool6.setObjectName("pbGoTool6")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(330, 140, 121, 20))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.sbBaseplate1 = QtWidgets.QSpinBox(Form)
        self.sbBaseplate1.setGeometry(QtCore.QRect(330, 160, 71, 22))
        self.sbBaseplate1.setMinimum(-1)
        self.sbBaseplate1.setMaximum(2147483647)
        self.sbBaseplate1.setObjectName("sbBaseplate1")
        self.sbBaseplate6 = QtWidgets.QSpinBox(Form)
        self.sbBaseplate6.setGeometry(QtCore.QRect(330, 260, 71, 21))
        self.sbBaseplate6.setMinimum(-1)
        self.sbBaseplate6.setMaximum(2147483647)
        self.sbBaseplate6.setObjectName("sbBaseplate6")
        self.sbTool5 = QtWidgets.QSpinBox(Form)
        self.sbTool5.setGeometry(QtCore.QRect(90, 240, 51, 22))
        self.sbTool5.setMinimum(-1)
        self.sbTool5.setMaximum(2147483647)
        self.sbTool5.setObjectName("sbTool5")
        self.sbBaseplate2 = QtWidgets.QSpinBox(Form)
        self.sbBaseplate2.setGeometry(QtCore.QRect(330, 180, 71, 22))
        self.sbBaseplate2.setMinimum(-1)
        self.sbBaseplate2.setMaximum(2147483647)
        self.sbBaseplate2.setObjectName("sbBaseplate2")
        self.sbBaseplate5 = QtWidgets.QSpinBox(Form)
        self.sbBaseplate5.setGeometry(QtCore.QRect(330, 240, 71, 21))
        self.sbBaseplate5.setMinimum(-1)
        self.sbBaseplate5.setMaximum(2147483647)
        self.sbBaseplate5.setObjectName("sbBaseplate5")
        self.sbTool6 = QtWidgets.QSpinBox(Form)
        self.sbTool6.setGeometry(QtCore.QRect(90, 260, 51, 21))
        self.sbTool6.setMinimum(-1)
        self.sbTool6.setMaximum(2147483647)
        self.sbTool6.setObjectName("sbTool6")
        self.pbGoTool5 = QtWidgets.QPushButton(Form)
        self.pbGoTool5.setGeometry(QtCore.QRect(140, 240, 51, 21))
        self.pbGoTool5.setObjectName("pbGoTool5")
        self.sbTool2 = QtWidgets.QSpinBox(Form)
        self.sbTool2.setGeometry(QtCore.QRect(90, 180, 51, 22))
        self.sbTool2.setMinimum(-1)
        self.sbTool2.setMaximum(2147483647)
        self.sbTool2.setObjectName("sbTool2")
        self.sbBaseplate4 = QtWidgets.QSpinBox(Form)
        self.sbBaseplate4.setGeometry(QtCore.QRect(330, 220, 71, 22))
        self.sbBaseplate4.setMinimum(-1)
        self.sbBaseplate4.setMaximum(2147483647)
        self.sbBaseplate4.setObjectName("sbBaseplate4")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 140, 101, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.pbGoTool1 = QtWidgets.QPushButton(Form)
        self.pbGoTool1.setGeometry(QtCore.QRect(140, 160, 51, 21))
        self.pbGoTool1.setObjectName("pbGoTool1")
        self.sbSensor4 = QtWidgets.QSpinBox(Form)
        self.sbSensor4.setGeometry(QtCore.QRect(200, 220, 71, 22))
        self.sbSensor4.setMinimum(-1)
        self.sbSensor4.setMaximum(2147483647)
        self.sbSensor4.setObjectName("sbSensor4")
        self.pbGoSensor5 = QtWidgets.QPushButton(Form)
        self.pbGoSensor5.setGeometry(QtCore.QRect(270, 240, 51, 21))
        self.pbGoSensor5.setObjectName("pbGoSensor5")
        self.pbGoSensor3 = QtWidgets.QPushButton(Form)
        self.pbGoSensor3.setGeometry(QtCore.QRect(270, 200, 51, 21))
        self.pbGoSensor3.setObjectName("pbGoSensor3")
        self.sbSensor5 = QtWidgets.QSpinBox(Form)
        self.sbSensor5.setGeometry(QtCore.QRect(200, 240, 71, 21))
        self.sbSensor5.setMinimum(-1)
        self.sbSensor5.setMaximum(2147483647)
        self.sbSensor5.setObjectName("sbSensor5")
        self.pbGoSensor6 = QtWidgets.QPushButton(Form)
        self.pbGoSensor6.setGeometry(QtCore.QRect(270, 260, 51, 21))
        self.pbGoSensor6.setObjectName("pbGoSensor6")
        self.pbGoSensor1 = QtWidgets.QPushButton(Form)
        self.pbGoSensor1.setGeometry(QtCore.QRect(270, 160, 51, 21))
        self.pbGoSensor1.setObjectName("pbGoSensor1")
        self.sbSensor1 = QtWidgets.QSpinBox(Form)
        self.sbSensor1.setGeometry(QtCore.QRect(200, 160, 71, 22))
        self.sbSensor1.setMinimum(-1)
        self.sbSensor1.setMaximum(2147483647)
        self.sbSensor1.setObjectName("sbSensor1")
        self.sbSensor3 = QtWidgets.QSpinBox(Form)
        self.sbSensor3.setGeometry(QtCore.QRect(200, 200, 71, 22))
        self.sbSensor3.setMinimum(-1)
        self.sbSensor3.setMaximum(2147483647)
        self.sbSensor3.setObjectName("sbSensor3")
        self.sbSensor6 = QtWidgets.QSpinBox(Form)
        self.sbSensor6.setGeometry(QtCore.QRect(200, 260, 71, 21))
        self.sbSensor6.setMinimum(-1)
        self.sbSensor6.setMaximum(2147483647)
        self.sbSensor6.setObjectName("sbSensor6")
        self.pbGoSensor2 = QtWidgets.QPushButton(Form)
        self.pbGoSensor2.setGeometry(QtCore.QRect(270, 180, 51, 21))
        self.pbGoSensor2.setObjectName("pbGoSensor2")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(200, 140, 121, 20))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.pbGoSensor4 = QtWidgets.QPushButton(Form)
        self.pbGoSensor4.setGeometry(QtCore.QRect(270, 220, 51, 21))
        self.pbGoSensor4.setObjectName("pbGoSensor4")
        self.sbSensor2 = QtWidgets.QSpinBox(Form)
        self.sbSensor2.setGeometry(QtCore.QRect(200, 180, 71, 22))
        self.sbSensor2.setMinimum(-1)
        self.sbSensor2.setMaximum(2147483647)
        self.sbSensor2.setObjectName("sbSensor2")
        self.pbGoTrayAssembly = QtWidgets.QPushButton(Form)
        self.pbGoTrayAssembly.setGeometry(QtCore.QRect(260, 310, 51, 21))
        self.pbGoTrayAssembly.setObjectName("pbGoTrayAssembly")
        self.pbGoTrayComponent = QtWidgets.QPushButton(Form)
        self.pbGoTrayComponent.setGeometry(QtCore.QRect(260, 290, 51, 21))
        self.pbGoTrayComponent.setObjectName("pbGoTrayComponent")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 310, 181, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.sbTrayComponent = QtWidgets.QSpinBox(Form)
        self.sbTrayComponent.setGeometry(QtCore.QRect(190, 290, 71, 21))
        self.sbTrayComponent.setMinimum(-1)
        self.sbTrayComponent.setMaximum(999999)
        self.sbTrayComponent.setObjectName("sbTrayComponent")
        self.sbBatchAraldite = QtWidgets.QSpinBox(Form)
        self.sbBatchAraldite.setGeometry(QtCore.QRect(190, 330, 71, 21))
        self.sbBatchAraldite.setMinimum(-1)
        self.sbBatchAraldite.setMaximum(999999)
        self.sbBatchAraldite.setObjectName("sbBatchAraldite")
        self.sbTrayAssembly = QtWidgets.QSpinBox(Form)
        self.sbTrayAssembly.setGeometry(QtCore.QRect(190, 310, 71, 21))
        self.sbTrayAssembly.setMinimum(-1)
        self.sbTrayAssembly.setMaximum(999999)
        self.sbTrayAssembly.setObjectName("sbTrayAssembly")
        self.pbGoBatchAraldite = QtWidgets.QPushButton(Form)
        self.pbGoBatchAraldite.setGeometry(QtCore.QRect(260, 330, 51, 21))
        self.pbGoBatchAraldite.setObjectName("pbGoBatchAraldite")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 330, 181, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_24 = QtWidgets.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 290, 181, 21))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(Form)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 350, 181, 21))
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.sbBatchLoctite = QtWidgets.QSpinBox(Form)
        self.sbBatchLoctite.setGeometry(QtCore.QRect(190, 350, 71, 21))
        self.sbBatchLoctite.setMinimum(-1)
        self.sbBatchLoctite.setMaximum(999999)
        self.sbBatchLoctite.setObjectName("sbBatchLoctite")
        self.pbGoBatchLoctite = QtWidgets.QPushButton(Form)
        self.pbGoBatchLoctite.setGeometry(QtCore.QRect(260, 350, 51, 21))
        self.pbGoBatchLoctite.setObjectName("pbGoBatchLoctite")
        self.listIssues = QtWidgets.QListWidget(Form)
        self.listIssues.setGeometry(QtCore.QRect(10, 390, 721, 171))
        self.listIssues.setObjectName("listIssues")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(60, 560, 171, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.lineEdit_26 = QtWidgets.QLineEdit(Form)
        self.lineEdit_26.setGeometry(QtCore.QRect(10, 560, 51, 20))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(650, 200, 131, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pbRunStartNow = QtWidgets.QPushButton(Form)
        self.pbRunStartNow.setGeometry(QtCore.QRect(930, 200, 91, 21))
        self.pbRunStartNow.setObjectName("pbRunStartNow")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(650, 160, 151, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.leLocation = QtWidgets.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(800, 160, 121, 20))
        self.leLocation.setObjectName("leLocation")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(160, 110, 81, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lineEdit_27 = QtWidgets.QLineEdit(Form)
        self.lineEdit_27.setGeometry(QtCore.QRect(10, 110, 151, 20))
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.dtRunStart = QtWidgets.QDateTimeEdit(Form)
        self.dtRunStart.setGeometry(QtCore.QRect(780, 200, 151, 21))
        self.dtRunStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dtRunStart.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.dtRunStart.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dtRunStart.setCalendarPopup(True)
        self.dtRunStart.setObjectName("dtRunStart")

        self.retranslateUi(Form)
        self.cbInstitution.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Sensor step ID"))
        self.lineEdit_2.setText(_translate("Form", "who performed step"))
        self.lineEdit_8.setText(_translate("Form", "cure temp (C)"))
        self.lineEdit_9.setText(_translate("Form", "cure humidity (%)"))
        self.pbGoProtoModule1.setText(_translate("Form", "go to"))
        self.pbGoProtoModule2.setText(_translate("Form", "go to"))
        self.pbGoProtoModule3.setText(_translate("Form", "go to"))
        self.pbGoProtoModule6.setText(_translate("Form", "go to"))
        self.pbGoProtoModule4.setText(_translate("Form", "go to"))
        self.pbGoProtoModule5.setText(_translate("Form", "go to"))
        self.pbNew.setText(_translate("Form", "New"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit_12.setText(_translate("Form", "position"))
        self.lineEdit_14.setText(_translate("Form", "protomodule ID assigned"))
        self.lineEdit_15.setText(_translate("Form", "1 (1, 1)"))
        self.lineEdit_16.setText(_translate("Form", "2 (1, 2)"))
        self.lineEdit_17.setText(_translate("Form", "3 (2, 1)"))
        self.lineEdit_18.setText(_translate("Form", "4 (2, 2)"))
        self.lineEdit_19.setText(_translate("Form", "5 (3, 1)"))
        self.lineEdit_20.setText(_translate("Form", "6 (3, 2)"))
        self.pbGoBaseplate4.setText(_translate("Form", "go to"))
        self.pbGoTool3.setText(_translate("Form", "go to"))
        self.pbGoBaseplate2.setText(_translate("Form", "go to"))
        self.pbGoTool4.setText(_translate("Form", "go to"))
        self.pbGoBaseplate6.setText(_translate("Form", "go to"))
        self.pbGoBaseplate3.setText(_translate("Form", "go to"))
        self.pbGoBaseplate5.setText(_translate("Form", "go to"))
        self.pbGoBaseplate1.setText(_translate("Form", "go to"))
        self.pbGoTool2.setText(_translate("Form", "go to"))
        self.pbGoTool6.setText(_translate("Form", "go to"))
        self.lineEdit_22.setText(_translate("Form", "baseplate ID"))
        self.pbGoTool5.setText(_translate("Form", "go to"))
        self.lineEdit_13.setText(_translate("Form", "sensor tool ID"))
        self.pbGoTool1.setText(_translate("Form", "go to"))
        self.pbGoSensor5.setText(_translate("Form", "go to"))
        self.pbGoSensor3.setText(_translate("Form", "go to"))
        self.pbGoSensor6.setText(_translate("Form", "go to"))
        self.pbGoSensor1.setText(_translate("Form", "go to"))
        self.pbGoSensor2.setText(_translate("Form", "go to"))
        self.lineEdit_23.setText(_translate("Form", "sensor ID"))
        self.pbGoSensor4.setText(_translate("Form", "go to"))
        self.pbGoTrayAssembly.setText(_translate("Form", "go to"))
        self.pbGoTrayComponent.setText(_translate("Form", "go to"))
        self.lineEdit_21.setText(_translate("Form", "assembly tray"))
        self.pbGoBatchAraldite.setText(_translate("Form", "go to"))
        self.lineEdit_11.setText(_translate("Form", "araldite batch"))
        self.lineEdit_24.setText(_translate("Form", "component tray (sensor)"))
        self.lineEdit_25.setText(_translate("Form", "loctite batch"))
        self.pbGoBatchLoctite.setText(_translate("Form", "go to"))
        self.listIssues.setToolTip(_translate("Form", "list of issues"))
        self.lineEdit_26.setText(_translate("Form", "Status:"))
        self.lineEdit_10.setText(_translate("Form", "run start"))
        self.pbRunStartNow.setText(_translate("Form", "set to now"))
        self.lineEdit_4.setText(_translate("Form", "location"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "NTU"))
        self.lineEdit_27.setText(_translate("Form", "Institution (for tools)"))

