# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_tooling.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 705)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.sbSensorToolID = QtWidgets.QSpinBox(Form)
        self.sbSensorToolID.setGeometry(QtCore.QRect(110, 10, 51, 21))
        self.sbSensorToolID.setMaximum(2147483647)
        self.sbSensorToolID.setObjectName("sbSensorToolID")
        self.listSensorToolComments = QtWidgets.QListWidget(Form)
        self.listSensorToolComments.setGeometry(QtCore.QRect(10, 100, 251, 121))
        self.listSensorToolComments.setObjectName("listSensorToolComments")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dsbSensorToolSize = QtWidgets.QDoubleSpinBox(Form)
        self.dsbSensorToolSize.setGeometry(QtCore.QRect(110, 30, 51, 21))
        self.dsbSensorToolSize.setMaximum(100.0)
        self.dsbSensorToolSize.setObjectName("dsbSensorToolSize")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 80, 121, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pbSensorToolDeleteComment = QtWidgets.QPushButton(Form)
        self.pbSensorToolDeleteComment.setGeometry(QtCore.QRect(130, 80, 131, 21))
        self.pbSensorToolDeleteComment.setObjectName("pbSensorToolDeleteComment")
        self.pteSensorToolWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteSensorToolWriteComment.setGeometry(QtCore.QRect(10, 230, 251, 71))
        self.pteSensorToolWriteComment.setObjectName("pteSensorToolWriteComment")
        self.pbSensorToolAddComment = QtWidgets.QPushButton(Form)
        self.pbSensorToolAddComment.setGeometry(QtCore.QRect(10, 300, 111, 23))
        self.pbSensorToolAddComment.setObjectName("pbSensorToolAddComment")
        self.pbPcbToolAddComment = QtWidgets.QPushButton(Form)
        self.pbPcbToolAddComment.setGeometry(QtCore.QRect(10, 660, 111, 21))
        self.pbPcbToolAddComment.setObjectName("pbPcbToolAddComment")
        self.dsbPcbToolSize = QtWidgets.QDoubleSpinBox(Form)
        self.dsbPcbToolSize.setGeometry(QtCore.QRect(100, 390, 51, 21))
        self.dsbPcbToolSize.setMaximum(100.0)
        self.dsbPcbToolSize.setObjectName("dsbPcbToolSize")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 440, 121, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.ptePcbToolWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.ptePcbToolWriteComment.setGeometry(QtCore.QRect(10, 590, 251, 71))
        self.ptePcbToolWriteComment.setObjectName("ptePcbToolWriteComment")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 370, 91, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.sbPcbToolID = QtWidgets.QSpinBox(Form)
        self.sbPcbToolID.setGeometry(QtCore.QRect(100, 370, 51, 21))
        self.sbPcbToolID.setMaximum(2147483647)
        self.sbPcbToolID.setObjectName("sbPcbToolID")
        self.pbPcbToolDeleteComment = QtWidgets.QPushButton(Form)
        self.pbPcbToolDeleteComment.setGeometry(QtCore.QRect(130, 440, 131, 21))
        self.pbPcbToolDeleteComment.setObjectName("pbPcbToolDeleteComment")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 390, 91, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.listPcbToolComments = QtWidgets.QListWidget(Form)
        self.listPcbToolComments.setGeometry(QtCore.QRect(10, 460, 251, 121))
        self.listPcbToolComments.setObjectName("listPcbToolComments")
        self.listPcbTrayComments = QtWidgets.QListWidget(Form)
        self.listPcbTrayComments.setGeometry(QtCore.QRect(310, 460, 291, 121))
        self.listPcbTrayComments.setObjectName("listPcbTrayComments")
        self.pbSensorTrayAddComment = QtWidgets.QPushButton(Form)
        self.pbSensorTrayAddComment.setGeometry(QtCore.QRect(310, 300, 111, 23))
        self.pbSensorTrayAddComment.setObjectName("pbSensorTrayAddComment")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(310, 390, 171, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(310, 440, 161, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pteSensorTrayWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteSensorTrayWriteComment.setGeometry(QtCore.QRect(310, 230, 291, 71))
        self.pteSensorTrayWriteComment.setObjectName("pteSensorTrayWriteComment")
        self.sbSensorTrayID = QtWidgets.QSpinBox(Form)
        self.sbSensorTrayID.setGeometry(QtCore.QRect(480, 10, 51, 21))
        self.sbSensorTrayID.setMaximum(2147483647)
        self.sbSensorTrayID.setObjectName("sbSensorTrayID")
        self.pbPcbTrayAddComment = QtWidgets.QPushButton(Form)
        self.pbPcbTrayAddComment.setGeometry(QtCore.QRect(310, 660, 111, 21))
        self.pbPcbTrayAddComment.setObjectName("pbPcbTrayAddComment")
        self.dsbPcbTraySize = QtWidgets.QDoubleSpinBox(Form)
        self.dsbPcbTraySize.setGeometry(QtCore.QRect(480, 390, 51, 21))
        self.dsbPcbTraySize.setMaximum(100.0)
        self.dsbPcbTraySize.setObjectName("dsbPcbTraySize")
        self.sbPcbTrayID = QtWidgets.QSpinBox(Form)
        self.sbPcbTrayID.setGeometry(QtCore.QRect(480, 370, 51, 21))
        self.sbPcbTrayID.setMaximum(2147483647)
        self.sbPcbTrayID.setObjectName("sbPcbTrayID")
        self.listSensorTrayComments = QtWidgets.QListWidget(Form)
        self.listSensorTrayComments.setGeometry(QtCore.QRect(310, 100, 291, 121))
        self.listSensorTrayComments.setObjectName("listSensorTrayComments")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 80, 161, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(310, 10, 171, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pbSensorTrayDeleteComment = QtWidgets.QPushButton(Form)
        self.pbSensorTrayDeleteComment.setGeometry(QtCore.QRect(470, 80, 131, 21))
        self.pbSensorTrayDeleteComment.setObjectName("pbSensorTrayDeleteComment")
        self.pbPcbTrayDeleteComment = QtWidgets.QPushButton(Form)
        self.pbPcbTrayDeleteComment.setGeometry(QtCore.QRect(470, 440, 131, 21))
        self.pbPcbTrayDeleteComment.setObjectName("pbPcbTrayDeleteComment")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(310, 30, 171, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.ptePcbTrayWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.ptePcbTrayWriteComment.setGeometry(QtCore.QRect(310, 590, 291, 71))
        self.ptePcbTrayWriteComment.setObjectName("ptePcbTrayWriteComment")
        self.dsbSensorTraySize = QtWidgets.QDoubleSpinBox(Form)
        self.dsbSensorTraySize.setGeometry(QtCore.QRect(480, 30, 51, 21))
        self.dsbSensorTraySize.setMaximum(100.0)
        self.dsbSensorTraySize.setObjectName("dsbSensorTraySize")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 370, 171, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.dsbAssemblyTraySize = QtWidgets.QDoubleSpinBox(Form)
        self.dsbAssemblyTraySize.setGeometry(QtCore.QRect(760, 30, 51, 21))
        self.dsbAssemblyTraySize.setMaximum(100.0)
        self.dsbAssemblyTraySize.setObjectName("dsbAssemblyTraySize")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(650, 80, 121, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.listAssemblyTrayComments = QtWidgets.QListWidget(Form)
        self.listAssemblyTrayComments.setGeometry(QtCore.QRect(650, 100, 251, 121))
        self.listAssemblyTrayComments.setObjectName("listAssemblyTrayComments")
        self.pbAssemblyTrayAddComment = QtWidgets.QPushButton(Form)
        self.pbAssemblyTrayAddComment.setGeometry(QtCore.QRect(650, 300, 111, 23))
        self.pbAssemblyTrayAddComment.setObjectName("pbAssemblyTrayAddComment")
        self.sbAssemblyTrayID = QtWidgets.QSpinBox(Form)
        self.sbAssemblyTrayID.setGeometry(QtCore.QRect(760, 10, 51, 21))
        self.sbAssemblyTrayID.setMaximum(2147483647)
        self.sbAssemblyTrayID.setObjectName("sbAssemblyTrayID")
        self.pbAssemblyTrayDeleteComment = QtWidgets.QPushButton(Form)
        self.pbAssemblyTrayDeleteComment.setGeometry(QtCore.QRect(770, 80, 131, 21))
        self.pbAssemblyTrayDeleteComment.setObjectName("pbAssemblyTrayDeleteComment")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(650, 30, 111, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pteAssemblyTrayWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteAssemblyTrayWriteComment.setGeometry(QtCore.QRect(650, 230, 251, 71))
        self.pteAssemblyTrayWriteComment.setObjectName("pteAssemblyTrayWriteComment")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(650, 10, 111, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pbSensorToolEditNew = QtWidgets.QPushButton(Form)
        self.pbSensorToolEditNew.setGeometry(QtCore.QRect(190, 10, 71, 21))
        self.pbSensorToolEditNew.setObjectName("pbSensorToolEditNew")
        self.pbSensorToolSave = QtWidgets.QPushButton(Form)
        self.pbSensorToolSave.setGeometry(QtCore.QRect(190, 30, 71, 21))
        self.pbSensorToolSave.setObjectName("pbSensorToolSave")
        self.pbSensorToolCancel = QtWidgets.QPushButton(Form)
        self.pbSensorToolCancel.setGeometry(QtCore.QRect(190, 50, 71, 21))
        self.pbSensorToolCancel.setObjectName("pbSensorToolCancel")
        self.pbPcbToolCancel = QtWidgets.QPushButton(Form)
        self.pbPcbToolCancel.setGeometry(QtCore.QRect(190, 410, 71, 21))
        self.pbPcbToolCancel.setObjectName("pbPcbToolCancel")
        self.pbPcbToolSave = QtWidgets.QPushButton(Form)
        self.pbPcbToolSave.setGeometry(QtCore.QRect(190, 390, 71, 21))
        self.pbPcbToolSave.setObjectName("pbPcbToolSave")
        self.pbPcbToolEditNew = QtWidgets.QPushButton(Form)
        self.pbPcbToolEditNew.setGeometry(QtCore.QRect(190, 370, 71, 21))
        self.pbPcbToolEditNew.setObjectName("pbPcbToolEditNew")
        self.pbPcbTrayEditNew = QtWidgets.QPushButton(Form)
        self.pbPcbTrayEditNew.setGeometry(QtCore.QRect(530, 370, 71, 21))
        self.pbPcbTrayEditNew.setObjectName("pbPcbTrayEditNew")
        self.pbPcbTraySave = QtWidgets.QPushButton(Form)
        self.pbPcbTraySave.setGeometry(QtCore.QRect(530, 390, 71, 21))
        self.pbPcbTraySave.setObjectName("pbPcbTraySave")
        self.pbPcbTrayCancel = QtWidgets.QPushButton(Form)
        self.pbPcbTrayCancel.setGeometry(QtCore.QRect(530, 410, 71, 21))
        self.pbPcbTrayCancel.setObjectName("pbPcbTrayCancel")
        self.pbSensorTrayCancel = QtWidgets.QPushButton(Form)
        self.pbSensorTrayCancel.setGeometry(QtCore.QRect(530, 50, 71, 21))
        self.pbSensorTrayCancel.setObjectName("pbSensorTrayCancel")
        self.pbSensorTraySave = QtWidgets.QPushButton(Form)
        self.pbSensorTraySave.setGeometry(QtCore.QRect(530, 30, 71, 21))
        self.pbSensorTraySave.setObjectName("pbSensorTraySave")
        self.pbSensorTrayEditNew = QtWidgets.QPushButton(Form)
        self.pbSensorTrayEditNew.setGeometry(QtCore.QRect(530, 10, 71, 21))
        self.pbSensorTrayEditNew.setObjectName("pbSensorTrayEditNew")
        self.pbAssemblyTrayEditNew = QtWidgets.QPushButton(Form)
        self.pbAssemblyTrayEditNew.setGeometry(QtCore.QRect(830, 10, 71, 21))
        self.pbAssemblyTrayEditNew.setObjectName("pbAssemblyTrayEditNew")
        self.pbAssemblyTrayCancel = QtWidgets.QPushButton(Form)
        self.pbAssemblyTrayCancel.setGeometry(QtCore.QRect(830, 50, 71, 21))
        self.pbAssemblyTrayCancel.setObjectName("pbAssemblyTrayCancel")
        self.pbAssemblyTraySave = QtWidgets.QPushButton(Form)
        self.pbAssemblyTraySave.setGeometry(QtCore.QRect(830, 30, 71, 21))
        self.pbAssemblyTraySave.setObjectName("pbAssemblyTraySave")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Sensor tool"))
        self.lineEdit_2.setText(_translate("Form", "Size (inches)"))
        self.lineEdit_3.setText(_translate("Form", "Comments"))
        self.pbSensorToolDeleteComment.setText(_translate("Form", "delete selected"))
        self.pbSensorToolAddComment.setText(_translate("Form", "add comment"))
        self.pbPcbToolAddComment.setText(_translate("Form", "add comment"))
        self.lineEdit_4.setText(_translate("Form", "Comments"))
        self.lineEdit_5.setText(_translate("Form", "PCB tool"))
        self.pbPcbToolDeleteComment.setText(_translate("Form", "delete selected"))
        self.lineEdit_6.setText(_translate("Form", "Size (inches)"))
        self.pbSensorTrayAddComment.setText(_translate("Form", "add comment"))
        self.lineEdit_7.setText(_translate("Form", "Size (inches)"))
        self.lineEdit_8.setText(_translate("Form", "Comments"))
        self.pbPcbTrayAddComment.setText(_translate("Form", "add comment"))
        self.lineEdit_9.setText(_translate("Form", "Comments"))
        self.lineEdit_10.setText(_translate("Form", "Sensor Component Tray"))
        self.pbSensorTrayDeleteComment.setText(_translate("Form", "delete selected"))
        self.pbPcbTrayDeleteComment.setText(_translate("Form", "delete selected"))
        self.lineEdit_11.setText(_translate("Form", "Size (inches)"))
        self.lineEdit_12.setText(_translate("Form", "PCB Component Tray"))
        self.lineEdit_13.setText(_translate("Form", "Comments"))
        self.pbAssemblyTrayAddComment.setText(_translate("Form", "add comment"))
        self.pbAssemblyTrayDeleteComment.setText(_translate("Form", "delete selected"))
        self.lineEdit_14.setText(_translate("Form", "Size (inches)"))
        self.lineEdit_15.setText(_translate("Form", "Assembly Tray"))
        self.pbSensorToolEditNew.setText(_translate("Form", "edit/new"))
        self.pbSensorToolSave.setText(_translate("Form", "save"))
        self.pbSensorToolCancel.setText(_translate("Form", "cancel"))
        self.pbPcbToolCancel.setText(_translate("Form", "cancel"))
        self.pbPcbToolSave.setText(_translate("Form", "save"))
        self.pbPcbToolEditNew.setText(_translate("Form", "edit/new"))
        self.pbPcbTrayEditNew.setText(_translate("Form", "edit/new"))
        self.pbPcbTraySave.setText(_translate("Form", "save"))
        self.pbPcbTrayCancel.setText(_translate("Form", "cancel"))
        self.pbSensorTrayCancel.setText(_translate("Form", "cancel"))
        self.pbSensorTraySave.setText(_translate("Form", "save"))
        self.pbSensorTrayEditNew.setText(_translate("Form", "edit/new"))
        self.pbAssemblyTrayEditNew.setText(_translate("Form", "edit/new"))
        self.pbAssemblyTrayCancel.setText(_translate("Form", "cancel"))
        self.pbAssemblyTraySave.setText(_translate("Form", "save"))

