# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_supplies.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 749)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.sbAralditeID = QtWidgets.QSpinBox(Form)
        self.sbAralditeID.setGeometry(QtCore.QRect(110, 10, 91, 21))
        self.sbAralditeID.setMaximum(2147483647)
        self.sbAralditeID.setObjectName("sbAralditeID")
        self.listAralditeComments = QtWidgets.QListWidget(Form)
        self.listAralditeComments.setGeometry(QtCore.QRect(10, 120, 261, 121))
        self.listAralditeComments.setObjectName("listAralditeComments")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 100, 121, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pbAralditeDeleteComment = QtWidgets.QPushButton(Form)
        self.pbAralditeDeleteComment.setGeometry(QtCore.QRect(130, 100, 131, 21))
        self.pbAralditeDeleteComment.setObjectName("pbAralditeDeleteComment")
        self.pteAralditeWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteAralditeWriteComment.setGeometry(QtCore.QRect(10, 250, 261, 71))
        self.pteAralditeWriteComment.setObjectName("pteAralditeWriteComment")
        self.pbAralditeAddComment = QtWidgets.QPushButton(Form)
        self.pbAralditeAddComment.setGeometry(QtCore.QRect(10, 320, 111, 23))
        self.pbAralditeAddComment.setObjectName("pbAralditeAddComment")
        self.pbAralditeEditNew = QtWidgets.QPushButton(Form)
        self.pbAralditeEditNew.setGeometry(QtCore.QRect(200, 10, 71, 21))
        self.pbAralditeEditNew.setObjectName("pbAralditeEditNew")
        self.pbAralditeSave = QtWidgets.QPushButton(Form)
        self.pbAralditeSave.setGeometry(QtCore.QRect(200, 30, 71, 21))
        self.pbAralditeSave.setObjectName("pbAralditeSave")
        self.pbAralditeCancel = QtWidgets.QPushButton(Form)
        self.pbAralditeCancel.setGeometry(QtCore.QRect(200, 50, 71, 21))
        self.pbAralditeCancel.setObjectName("pbAralditeCancel")
        self.dAralditeReceived = QtWidgets.QDateEdit(Form)
        self.dAralditeReceived.setGeometry(QtCore.QRect(110, 30, 91, 21))
        self.dAralditeReceived.setObjectName("dAralditeReceived")
        self.dAralditeExpires = QtWidgets.QDateEdit(Form)
        self.dAralditeExpires.setGeometry(QtCore.QRect(110, 50, 91, 21))
        self.dAralditeExpires.setObjectName("dAralditeExpires")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 430, 101, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 410, 101, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.listLoctiteComments = QtWidgets.QListWidget(Form)
        self.listLoctiteComments.setGeometry(QtCore.QRect(10, 500, 261, 121))
        self.listLoctiteComments.setObjectName("listLoctiteComments")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 480, 131, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pbLoctiteDeleteComment = QtWidgets.QPushButton(Form)
        self.pbLoctiteDeleteComment.setGeometry(QtCore.QRect(140, 480, 131, 21))
        self.pbLoctiteDeleteComment.setObjectName("pbLoctiteDeleteComment")
        self.pbLoctiteCancel = QtWidgets.QPushButton(Form)
        self.pbLoctiteCancel.setGeometry(QtCore.QRect(200, 430, 71, 21))
        self.pbLoctiteCancel.setObjectName("pbLoctiteCancel")
        self.pbLoctiteAddComment = QtWidgets.QPushButton(Form)
        self.pbLoctiteAddComment.setGeometry(QtCore.QRect(10, 680, 111, 23))
        self.pbLoctiteAddComment.setObjectName("pbLoctiteAddComment")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 390, 101, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.dLoctiteReceived = QtWidgets.QDateEdit(Form)
        self.dLoctiteReceived.setGeometry(QtCore.QRect(110, 410, 91, 21))
        self.dLoctiteReceived.setObjectName("dLoctiteReceived")
        self.pteLoctiteWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteLoctiteWriteComment.setGeometry(QtCore.QRect(10, 630, 261, 71))
        self.pteLoctiteWriteComment.setObjectName("pteLoctiteWriteComment")
        self.pbLoctiteSave = QtWidgets.QPushButton(Form)
        self.pbLoctiteSave.setGeometry(QtCore.QRect(200, 410, 71, 21))
        self.pbLoctiteSave.setObjectName("pbLoctiteSave")
        self.dLoctiteExpires = QtWidgets.QDateEdit(Form)
        self.dLoctiteExpires.setGeometry(QtCore.QRect(110, 430, 91, 21))
        self.dLoctiteExpires.setObjectName("dLoctiteExpires")
        self.pbLoctiteEditNew = QtWidgets.QPushButton(Form)
        self.pbLoctiteEditNew.setGeometry(QtCore.QRect(200, 390, 71, 21))
        self.pbLoctiteEditNew.setObjectName("pbLoctiteEditNew")
        self.sbLoctiteID = QtWidgets.QSpinBox(Form)
        self.sbLoctiteID.setGeometry(QtCore.QRect(110, 390, 91, 21))
        self.sbLoctiteID.setMaximum(2147483647)
        self.sbLoctiteID.setObjectName("sbLoctiteID")
        self.sbSylgardThinID = QtWidgets.QSpinBox(Form)
        self.sbSylgardThinID.setGeometry(QtCore.QRect(470, 390, 61, 21))
        self.sbSylgardThinID.setMaximum(2147483647)
        self.sbSylgardThinID.setObjectName("sbSylgardThinID")
        self.pbSylgardThinAddComment = QtWidgets.QPushButton(Form)
        self.pbSylgardThinAddComment.setGeometry(QtCore.QRect(320, 700, 111, 23))
        self.pbSylgardThinAddComment.setObjectName("pbSylgardThinAddComment")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(320, 430, 121, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(320, 480, 151, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(320, 410, 121, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.pbSylgardThinSave = QtWidgets.QPushButton(Form)
        self.pbSylgardThinSave.setGeometry(QtCore.QRect(530, 410, 71, 21))
        self.pbSylgardThinSave.setObjectName("pbSylgardThinSave")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(320, 390, 151, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.listSylgardThinComments = QtWidgets.QListWidget(Form)
        self.listSylgardThinComments.setGeometry(QtCore.QRect(320, 500, 281, 121))
        self.listSylgardThinComments.setObjectName("listSylgardThinComments")
        self.pbSylgardThinDeleteComment = QtWidgets.QPushButton(Form)
        self.pbSylgardThinDeleteComment.setGeometry(QtCore.QRect(470, 480, 131, 21))
        self.pbSylgardThinDeleteComment.setObjectName("pbSylgardThinDeleteComment")
        self.pteSylgardThinWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteSylgardThinWriteComment.setGeometry(QtCore.QRect(320, 630, 281, 71))
        self.pteSylgardThinWriteComment.setObjectName("pteSylgardThinWriteComment")
        self.pbSylgardThinCancel = QtWidgets.QPushButton(Form)
        self.pbSylgardThinCancel.setGeometry(QtCore.QRect(530, 430, 71, 21))
        self.pbSylgardThinCancel.setObjectName("pbSylgardThinCancel")
        self.dSylgardThinExpires = QtWidgets.QDateEdit(Form)
        self.dSylgardThinExpires.setGeometry(QtCore.QRect(440, 430, 91, 21))
        self.dSylgardThinExpires.setObjectName("dSylgardThinExpires")
        self.dSylgardThinReceived = QtWidgets.QDateEdit(Form)
        self.dSylgardThinReceived.setGeometry(QtCore.QRect(440, 410, 91, 21))
        self.dSylgardThinReceived.setObjectName("dSylgardThinReceived")
        self.pbSylgardThinEditNew = QtWidgets.QPushButton(Form)
        self.pbSylgardThinEditNew.setGeometry(QtCore.QRect(530, 390, 71, 21))
        self.pbSylgardThinEditNew.setObjectName("pbSylgardThinEditNew")
        self.pbSylgardThickEditNew = QtWidgets.QPushButton(Form)
        self.pbSylgardThickEditNew.setGeometry(QtCore.QRect(530, 10, 71, 21))
        self.pbSylgardThickEditNew.setObjectName("pbSylgardThickEditNew")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(320, 50, 121, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(320, 100, 151, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.sbSylgardThickID = QtWidgets.QSpinBox(Form)
        self.sbSylgardThickID.setGeometry(QtCore.QRect(470, 10, 61, 21))
        self.sbSylgardThickID.setMaximum(2147483647)
        self.sbSylgardThickID.setObjectName("sbSylgardThickID")
        self.pbSylgardThickCancel = QtWidgets.QPushButton(Form)
        self.pbSylgardThickCancel.setGeometry(QtCore.QRect(530, 50, 71, 21))
        self.pbSylgardThickCancel.setObjectName("pbSylgardThickCancel")
        self.listSylgardThickComments = QtWidgets.QListWidget(Form)
        self.listSylgardThickComments.setGeometry(QtCore.QRect(320, 120, 281, 121))
        self.listSylgardThickComments.setObjectName("listSylgardThickComments")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(320, 10, 151, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.pbSylgardThickDeleteComment = QtWidgets.QPushButton(Form)
        self.pbSylgardThickDeleteComment.setGeometry(QtCore.QRect(470, 100, 131, 21))
        self.pbSylgardThickDeleteComment.setObjectName("pbSylgardThickDeleteComment")
        self.pteSylgardThickWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteSylgardThickWriteComment.setGeometry(QtCore.QRect(320, 250, 281, 71))
        self.pteSylgardThickWriteComment.setObjectName("pteSylgardThickWriteComment")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(320, 30, 121, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pbSylgardThickAddComment = QtWidgets.QPushButton(Form)
        self.pbSylgardThickAddComment.setGeometry(QtCore.QRect(320, 320, 111, 23))
        self.pbSylgardThickAddComment.setObjectName("pbSylgardThickAddComment")
        self.pbSylgardThickSave = QtWidgets.QPushButton(Form)
        self.pbSylgardThickSave.setGeometry(QtCore.QRect(530, 30, 71, 21))
        self.pbSylgardThickSave.setObjectName("pbSylgardThickSave")
        self.dSylgardThickExpires = QtWidgets.QDateEdit(Form)
        self.dSylgardThickExpires.setGeometry(QtCore.QRect(440, 50, 91, 21))
        self.dSylgardThickExpires.setObjectName("dSylgardThickExpires")
        self.dSylgardThickReceived = QtWidgets.QDateEdit(Form)
        self.dSylgardThickReceived.setGeometry(QtCore.QRect(440, 30, 91, 21))
        self.dSylgardThickReceived.setObjectName("dSylgardThickReceived")
        self.dBondWireReceived = QtWidgets.QDateEdit(Form)
        self.dBondWireReceived.setGeometry(QtCore.QRect(760, 30, 91, 21))
        self.dBondWireReceived.setObjectName("dBondWireReceived")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(650, 50, 111, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.listBondWireComments = QtWidgets.QListWidget(Form)
        self.listBondWireComments.setGeometry(QtCore.QRect(650, 120, 271, 121))
        self.listBondWireComments.setObjectName("listBondWireComments")
        self.pbBondWireEditNew = QtWidgets.QPushButton(Form)
        self.pbBondWireEditNew.setGeometry(QtCore.QRect(850, 10, 71, 21))
        self.pbBondWireEditNew.setObjectName("pbBondWireEditNew")
        self.pbBondWireDeleteComment = QtWidgets.QPushButton(Form)
        self.pbBondWireDeleteComment.setGeometry(QtCore.QRect(790, 100, 131, 21))
        self.pbBondWireDeleteComment.setObjectName("pbBondWireDeleteComment")
        self.pbBondWireCancel = QtWidgets.QPushButton(Form)
        self.pbBondWireCancel.setGeometry(QtCore.QRect(850, 50, 71, 21))
        self.pbBondWireCancel.setObjectName("pbBondWireCancel")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(650, 100, 141, 21))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.sbBondWireID = QtWidgets.QSpinBox(Form)
        self.sbBondWireID.setGeometry(QtCore.QRect(770, 10, 81, 21))
        self.sbBondWireID.setMaximum(2147483647)
        self.sbBondWireID.setObjectName("sbBondWireID")
        self.pteBondWireWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteBondWireWriteComment.setGeometry(QtCore.QRect(650, 250, 271, 71))
        self.pteBondWireWriteComment.setObjectName("pteBondWireWriteComment")
        self.pbBondWireSave = QtWidgets.QPushButton(Form)
        self.pbBondWireSave.setGeometry(QtCore.QRect(850, 30, 71, 21))
        self.pbBondWireSave.setObjectName("pbBondWireSave")
        self.dBondWireExpires = QtWidgets.QDateEdit(Form)
        self.dBondWireExpires.setGeometry(QtCore.QRect(760, 50, 91, 21))
        self.dBondWireExpires.setObjectName("dBondWireExpires")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(650, 30, 111, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(650, 10, 121, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.pbBondWireAddComment = QtWidgets.QPushButton(Form)
        self.pbBondWireAddComment.setGeometry(QtCore.QRect(650, 320, 111, 23))
        self.pbBondWireAddComment.setObjectName("pbBondWireAddComment")
        self.ckIsAralditeEmpty = QtWidgets.QCheckBox(Form)
        self.ckIsAralditeEmpty.setGeometry(QtCore.QRect(10, 75, 161, 17))
        self.ckIsAralditeEmpty.setObjectName("ckIsAralditeEmpty")
        self.ckIsSylgardThickEmpty = QtWidgets.QCheckBox(Form)
        self.ckIsSylgardThickEmpty.setGeometry(QtCore.QRect(320, 75, 161, 17))
        self.ckIsSylgardThickEmpty.setObjectName("ckIsSylgardThickEmpty")
        self.ckIsBondWireEmpty = QtWidgets.QCheckBox(Form)
        self.ckIsBondWireEmpty.setGeometry(QtCore.QRect(650, 75, 161, 17))
        self.ckIsBondWireEmpty.setObjectName("ckIsBondWireEmpty")
        self.ckIsLoctiteEmpty = QtWidgets.QCheckBox(Form)
        self.ckIsLoctiteEmpty.setGeometry(QtCore.QRect(10, 455, 161, 17))
        self.ckIsLoctiteEmpty.setObjectName("ckIsLoctiteEmpty")
        self.ckIsSylgardThinEmpty = QtWidgets.QCheckBox(Form)
        self.ckIsSylgardThinEmpty.setGeometry(QtCore.QRect(320, 455, 161, 17))
        self.ckIsSylgardThinEmpty.setObjectName("ckIsSylgardThinEmpty")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Araldite batch"))
        self.lineEdit_3.setText(_translate("Form", "Comments"))
        self.pbAralditeDeleteComment.setText(_translate("Form", "delete selected"))
        self.pbAralditeAddComment.setText(_translate("Form", "add comment"))
        self.pbAralditeEditNew.setText(_translate("Form", "edit/new"))
        self.pbAralditeSave.setText(_translate("Form", "save"))
        self.pbAralditeCancel.setText(_translate("Form", "cancel"))
        self.lineEdit_2.setText(_translate("Form", "Received"))
        self.lineEdit_4.setText(_translate("Form", "Expires"))
        self.lineEdit_5.setText(_translate("Form", "Expires"))
        self.lineEdit_6.setText(_translate("Form", "Received"))
        self.lineEdit_7.setText(_translate("Form", "Comments"))
        self.pbLoctiteDeleteComment.setText(_translate("Form", "delete selected"))
        self.pbLoctiteCancel.setText(_translate("Form", "cancel"))
        self.pbLoctiteAddComment.setText(_translate("Form", "add comment"))
        self.lineEdit_8.setToolTip(_translate("Form", "Loctite = silver epoxy"))
        self.lineEdit_8.setText(_translate("Form", "Loctite batch"))
        self.pbLoctiteSave.setText(_translate("Form", "save"))
        self.pbLoctiteEditNew.setText(_translate("Form", "edit/new"))
        self.pbSylgardThinAddComment.setText(_translate("Form", "add comment"))
        self.lineEdit_9.setText(_translate("Form", "Expires"))
        self.lineEdit_10.setText(_translate("Form", "Comments"))
        self.lineEdit_11.setText(_translate("Form", "Received"))
        self.pbSylgardThinSave.setText(_translate("Form", "save"))
        self.lineEdit_12.setText(_translate("Form", "Sylgard (thin) batch"))
        self.pbSylgardThinDeleteComment.setText(_translate("Form", "delete selected"))
        self.pbSylgardThinCancel.setText(_translate("Form", "cancel"))
        self.pbSylgardThinEditNew.setText(_translate("Form", "edit/new"))
        self.pbSylgardThickEditNew.setText(_translate("Form", "edit/new"))
        self.lineEdit_13.setText(_translate("Form", "Expires"))
        self.lineEdit_14.setText(_translate("Form", "Comments"))
        self.pbSylgardThickCancel.setText(_translate("Form", "cancel"))
        self.lineEdit_15.setText(_translate("Form", "Sylgard (thick) batch"))
        self.pbSylgardThickDeleteComment.setText(_translate("Form", "delete selected"))
        self.lineEdit_16.setText(_translate("Form", "Received"))
        self.pbSylgardThickAddComment.setText(_translate("Form", "add comment"))
        self.pbSylgardThickSave.setText(_translate("Form", "save"))
        self.lineEdit_17.setText(_translate("Form", "Expires"))
        self.pbBondWireEditNew.setText(_translate("Form", "edit/new"))
        self.pbBondWireDeleteComment.setText(_translate("Form", "delete selected"))
        self.pbBondWireCancel.setText(_translate("Form", "cancel"))
        self.lineEdit_18.setText(_translate("Form", "Comments"))
        self.pbBondWireSave.setText(_translate("Form", "save"))
        self.lineEdit_19.setText(_translate("Form", "Received"))
        self.lineEdit_20.setText(_translate("Form", "Bond wire batch"))
        self.pbBondWireAddComment.setText(_translate("Form", "add comment"))
        self.ckIsAralditeEmpty.setText(_translate("Form", "Batch is empty"))
        self.ckIsSylgardThickEmpty.setText(_translate("Form", "Batch is empty"))
        self.ckIsBondWireEmpty.setText(_translate("Form", "Batch is empty"))
        self.ckIsLoctiteEmpty.setText(_translate("Form", "Batch is empty"))
        self.ckIsSylgardThinEmpty.setText(_translate("Form", "Batch is empty"))

