# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_PCB.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 719)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 110, 181, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 90, 181, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 380, 181, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 360, 181, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 320, 181, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(310, 260, 131, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.sbID = QtWidgets.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(140, 10, 131, 21))
        self.sbID.setMaximum(2147483647)
        self.sbID.setObjectName("sbID")
        self.leManufacturer = QtWidgets.QLineEdit(Form)
        self.leManufacturer.setGeometry(QtCore.QRect(190, 320, 81, 21))
        self.leManufacturer.setText("")
        self.leManufacturer.setReadOnly(True)
        self.leManufacturer.setObjectName("leManufacturer")
        self.pbGoModule = QtWidgets.QPushButton(Form)
        self.pbGoModule.setGeometry(QtCore.QRect(520, 260, 51, 21))
        self.pbGoModule.setObjectName("pbGoModule")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(180, 40, 71, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbNew = QtWidgets.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.pbNew.setObjectName("pbNew")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(100, 40, 71, 21))
        self.pbSave.setObjectName("pbSave")
        self.dsbThickness = QtWidgets.QDoubleSpinBox(Form)
        self.dsbThickness.setGeometry(QtCore.QRect(490, 110, 81, 21))
        self.dsbThickness.setReadOnly(True)
        self.dsbThickness.setMinimum(-1.0)
        self.dsbThickness.setMaximum(2147483647.0)
        self.dsbThickness.setSingleStep(0.1)
        self.dsbThickness.setObjectName("dsbThickness")
        self.sbChannels = QtWidgets.QSpinBox(Form)
        self.sbChannels.setGeometry(QtCore.QRect(190, 360, 81, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName("sbChannels")
        self.dsbFlatness = QtWidgets.QDoubleSpinBox(Form)
        self.dsbFlatness.setGeometry(QtCore.QRect(490, 90, 81, 21))
        self.dsbFlatness.setReadOnly(True)
        self.dsbFlatness.setMinimum(-1.0)
        self.dsbFlatness.setMaximum(2147483647.0)
        self.dsbFlatness.setSingleStep(0.05)
        self.dsbFlatness.setObjectName("dsbFlatness")
        self.sbModule = QtWidgets.QSpinBox(Form)
        self.sbModule.setGeometry(QtCore.QRect(440, 260, 81, 21))
        self.sbModule.setReadOnly(True)
        self.sbModule.setMinimum(-1)
        self.sbModule.setMaximum(2147483647)
        self.sbModule.setObjectName("sbModule")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 400, 181, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 420, 181, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 440, 181, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.sbRotation = QtWidgets.QSpinBox(Form)
        self.sbRotation.setGeometry(QtCore.QRect(190, 440, 81, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName("sbRotation")
        self.cbChirality = QtWidgets.QComboBox(Form)
        self.cbChirality.setGeometry(QtCore.QRect(190, 420, 81, 21))
        self.cbChirality.setObjectName("cbChirality")
        self.cbChirality.addItem("")
        self.cbChirality.addItem("")
        self.cbChirality.addItem("")
        self.leLocation = QtWidgets.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(130, 130, 141, 21))
        self.leLocation.setText("")
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName("leLocation")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 130, 121, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.listShipments = QtWidgets.QListWidget(Form)
        self.listShipments.setGeometry(QtCore.QRect(10, 170, 261, 91))
        self.listShipments.setObjectName("listShipments")
        self.pbGoShipment = QtWidgets.QPushButton(Form)
        self.pbGoShipment.setGeometry(QtCore.QRect(130, 150, 141, 21))
        self.pbGoShipment.setObjectName("pbGoShipment")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 150, 121, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(310, 240, 131, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.sbStepPcb = QtWidgets.QSpinBox(Form)
        self.sbStepPcb.setGeometry(QtCore.QRect(440, 240, 81, 21))
        self.sbStepPcb.setReadOnly(True)
        self.sbStepPcb.setMinimum(-1)
        self.sbStepPcb.setMaximum(2147483647)
        self.sbStepPcb.setObjectName("sbStepPcb")
        self.pbGoStepPcb = QtWidgets.QPushButton(Form)
        self.pbGoStepPcb.setGeometry(QtCore.QRect(520, 240, 51, 21))
        self.pbGoStepPcb.setObjectName("pbGoStepPcb")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(310, 400, 271, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.listDaqData = QtWidgets.QListWidget(Form)
        self.listDaqData.setGeometry(QtCore.QRect(310, 420, 271, 131))
        self.listDaqData.setObjectName("listDaqData")
        self.pbAddToPlotter = QtWidgets.QPushButton(Form)
        self.pbAddToPlotter.setGeometry(QtCore.QRect(310, 550, 171, 21))
        self.pbAddToPlotter.setObjectName("pbAddToPlotter")
        self.pbGoPlotter = QtWidgets.QPushButton(Form)
        self.pbGoPlotter.setGeometry(QtCore.QRect(480, 550, 101, 21))
        self.pbGoPlotter.setObjectName("pbGoPlotter")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(310, 130, 181, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(310, 150, 181, 21))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(310, 170, 181, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pteWriteComment = QtWidgets.QPlainTextEdit(Form)
        self.pteWriteComment.setGeometry(QtCore.QRect(10, 620, 261, 71))
        self.pteWriteComment.setPlainText("")
        self.pteWriteComment.setObjectName("pteWriteComment")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 480, 141, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pbDeleteComment = QtWidgets.QPushButton(Form)
        self.pbDeleteComment.setGeometry(QtCore.QRect(150, 480, 121, 21))
        self.pbDeleteComment.setObjectName("pbDeleteComment")
        self.listComments = QtWidgets.QListWidget(Form)
        self.listComments.setGeometry(QtCore.QRect(10, 500, 261, 111))
        self.listComments.setObjectName("listComments")
        self.pbAddComment = QtWidgets.QPushButton(Form)
        self.pbAddComment.setGeometry(QtCore.QRect(10, 690, 111, 21))
        self.pbAddComment.setObjectName("pbAddComment")
        self.cbInspection = QtWidgets.QComboBox(Form)
        self.cbInspection.setGeometry(QtCore.QRect(490, 130, 81, 21))
        self.cbInspection.setObjectName("cbInspection")
        self.cbInspection.addItem("")
        self.cbInspection.addItem("")
        self.cbDaqOK = QtWidgets.QComboBox(Form)
        self.cbDaqOK.setGeometry(QtCore.QRect(490, 170, 81, 21))
        self.cbDaqOK.setObjectName("cbDaqOK")
        self.cbDaqOK.addItem("")
        self.cbDaqOK.addItem("")
        self.leDaq = QtWidgets.QLineEdit(Form)
        self.leDaq.setGeometry(QtCore.QRect(490, 150, 81, 20))
        self.leDaq.setText("")
        self.leDaq.setReadOnly(True)
        self.leDaq.setObjectName("leDaq")
        self.cbSize = QtWidgets.QComboBox(Form)
        self.cbSize.setGeometry(QtCore.QRect(190, 380, 81, 21))
        self.cbSize.setObjectName("cbSize")
        self.cbSize.addItem("")
        self.cbSize.addItem("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(310, 70, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(310, 220, 141, 16))
        self.label_2.setObjectName("label_2")
        self.cbShape = QtWidgets.QComboBox(Form)
        self.cbShape.setGeometry(QtCore.QRect(190, 400, 81, 20))
        self.cbShape.setObjectName("cbShape")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbShape.addItem("")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(130, 110, 141, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 110, 121, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_38 = QtWidgets.QLineEdit(Form)
        self.lineEdit_38.setGeometry(QtCore.QRect(10, 91, 121, 20))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.leInsertUser = QtWidgets.QLineEdit(Form)
        self.leInsertUser.setGeometry(QtCore.QRect(130, 91, 141, 20))
        self.leInsertUser.setText("")
        self.leInsertUser.setReadOnly(True)
        self.leInsertUser.setObjectName("leInsertUser")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 340, 131, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.cbType = QtWidgets.QComboBox(Form)
        self.cbType.setGeometry(QtCore.QRect(140, 340, 131, 21))
        self.cbType.setCurrentText("")
        self.cbType.setObjectName("cbType")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.cbType.addItem("")
        self.leSerial = QtWidgets.QLineEdit(Form)
        self.leSerial.setGeometry(QtCore.QRect(190, 280, 80, 20))
        self.leSerial.setReadOnly(True)
        self.leSerial.setObjectName("leSerial")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(11, 280, 181, 21))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(11, 300, 181, 21))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.leBarcode = QtWidgets.QLineEdit(Form)
        self.leBarcode.setGeometry(QtCore.QRect(190, 300, 80, 20))
        self.leBarcode.setText("")
        self.leBarcode.setReadOnly(True)
        self.leBarcode.setObjectName("leBarcode")

        self.retranslateUi(Form)
        self.cbChirality.setCurrentIndex(-1)
        self.cbInspection.setCurrentIndex(-1)
        self.cbDaqOK.setCurrentIndex(-1)
        self.cbSize.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        self.cbInstitution.setCurrentIndex(-1)
        self.cbType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "PCB ID"))
        self.lineEdit_3.setText(_translate("Form", "Thickness (mm)"))
        self.lineEdit_4.setText(_translate("Form", "Flatness (mm)"))
        self.lineEdit_5.setText(_translate("Form", "Size (inches)"))
        self.lineEdit_6.setText(_translate("Form", "Channels"))
        self.lineEdit_7.setText(_translate("Form", "Manufacturer"))
        self.lineEdit_8.setText(_translate("Form", "On module"))
        self.pbGoModule.setText(_translate("Form", "Go to"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbNew.setText(_translate("Form", "New"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit_15.setText(_translate("Form", "Shape"))
        self.lineEdit_13.setText(_translate("Form", "Chirality"))
        self.lineEdit_16.setText(_translate("Form", "Rotation"))
        self.cbChirality.setItemText(0, _translate("Form", "achiral"))
        self.cbChirality.setItemText(1, _translate("Form", "left"))
        self.cbChirality.setItemText(2, _translate("Form", "right"))
        self.lineEdit_11.setText(_translate("Form", "Location"))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)"))
        self.pbGoShipment.setText(_translate("Form", "Go to selected"))
        self.lineEdit_10.setText(_translate("Form", "Shipments"))
        self.lineEdit_9.setText(_translate("Form", "PCB step"))
        self.pbGoStepPcb.setText(_translate("Form", "Go to"))
        self.lineEdit_12.setText(_translate("Form", "Datasets"))
        self.pbAddToPlotter.setText(_translate("Form", "Add selected to plotter"))
        self.pbGoPlotter.setText(_translate("Form", "Go to plotter"))
        self.lineEdit_17.setText(_translate("Form", "Inspection"))
        self.lineEdit_18.setText(_translate("Form", "Data Acquisition dataset"))
        self.lineEdit_19.setText(_translate("Form", "Data Acquisition OK?"))
        self.lineEdit_14.setText(_translate("Form", "Comments"))
        self.pbDeleteComment.setText(_translate("Form", "Delete selected"))
        self.pbAddComment.setText(_translate("Form", "Add comment"))
        self.cbInspection.setItemText(0, _translate("Form", "pass"))
        self.cbInspection.setItemText(1, _translate("Form", "fail"))
        self.cbDaqOK.setItemText(0, _translate("Form", "yes"))
        self.cbDaqOK.setItemText(1, _translate("Form", "no"))
        self.cbSize.setItemText(0, _translate("Form", "8"))
        self.cbSize.setItemText(1, _translate("Form", "6"))
        self.label.setText(_translate("Form", "PCB qualification"))
        self.label_2.setText(_translate("Form", "PCB placement step"))
        self.cbShape.setItemText(0, _translate("Form", "full"))
        self.cbShape.setItemText(1, _translate("Form", "half"))
        self.cbShape.setItemText(2, _translate("Form", "five"))
        self.cbShape.setItemText(3, _translate("Form", "three"))
        self.cbShape.setItemText(4, _translate("Form", "semi"))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)"))
        self.cbShape.setItemText(6, _translate("Form", "choptwo"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.lineEdit_20.setText(_translate("Form", "Institution"))
        self.lineEdit_38.setToolTip(_translate("Form", "height difference between highest and lowers corners"))
        self.lineEdit_38.setText(_translate("Form", "User name"))
        self.lineEdit_21.setText(_translate("Form", "Type"))
        self.cbType.setItemText(0, _translate("Form", "HGCROCV1"))
        self.cbType.setItemText(1, _translate("Form", "HGCROCV2"))
        self.cbType.setItemText(2, _translate("Form", "HGCROCV3"))
        self.cbType.setItemText(3, _translate("Form", "SKIROCV1"))
        self.cbType.setItemText(4, _translate("Form", "SKIROCV2"))
        self.cbType.setItemText(5, _translate("Form", "SKIROCV3"))
        self.cbType.setItemText(6, _translate("Form", "HGCROC dummy"))
        self.lineEdit_22.setText(_translate("Form", "Serial number"))
        self.lineEdit_23.setText(_translate("Form", "Barcode"))

