# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_kapton_step.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 705)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.sbID = QtWidgets.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(120, 10, 71, 21))
        self.sbID.setObjectName("sbID")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 140, 151, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(500, 240, 131, 21))
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(500, 260, 131, 21))
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pbGoSensor1 = QtWidgets.QPushButton(Form)
        self.pbGoSensor1.setGeometry(QtCore.QRect(300, 160, 51, 21))
        self.pbGoSensor1.setObjectName("pbGoSensor1")
        self.pbGoSensor2 = QtWidgets.QPushButton(Form)
        self.pbGoSensor2.setGeometry(QtCore.QRect(300, 180, 51, 21))
        self.pbGoSensor2.setObjectName("pbGoSensor2")
        self.pbGoSensor3 = QtWidgets.QPushButton(Form)
        self.pbGoSensor3.setGeometry(QtCore.QRect(300, 200, 51, 21))
        self.pbGoSensor3.setObjectName("pbGoSensor3")
        self.pbGoSensor6 = QtWidgets.QPushButton(Form)
        self.pbGoSensor6.setGeometry(QtCore.QRect(300, 260, 51, 21))
        self.pbGoSensor6.setObjectName("pbGoSensor6")
        self.pbGoSensor4 = QtWidgets.QPushButton(Form)
        self.pbGoSensor4.setGeometry(QtCore.QRect(300, 220, 51, 21))
        self.pbGoSensor4.setObjectName("pbGoSensor4")
        self.pbGoSensor5 = QtWidgets.QPushButton(Form)
        self.pbGoSensor5.setGeometry(QtCore.QRect(300, 240, 51, 21))
        self.pbGoSensor5.setObjectName("pbGoSensor5")
        self.leUserPerformed = QtWidgets.QLineEdit(Form)
        self.leUserPerformed.setGeometry(QtCore.QRect(650, 140, 121, 20))
        self.leUserPerformed.setObjectName("leUserPerformed")
        self.leCureTemperature = QtWidgets.QLineEdit(Form)
        self.leCureTemperature.setGeometry(QtCore.QRect(630, 240, 151, 20))
        self.leCureTemperature.setObjectName("leCureTemperature")
        self.leCureHumidity = QtWidgets.QLineEdit(Form)
        self.leCureHumidity.setGeometry(QtCore.QRect(630, 260, 151, 21))
        self.leCureHumidity.setObjectName("leCureHumidity")
        self.pbNew = QtWidgets.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.pbNew.setObjectName("pbNew")
        self.pbEdit = QtWidgets.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.pbEdit.setObjectName("pbEdit")
        self.pbCancel = QtWidgets.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(170, 40, 71, 21))
        self.pbCancel.setObjectName("pbCancel")
        self.pbSave = QtWidgets.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.pbSave.setObjectName("pbSave")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 340, 181, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 140, 70, 20))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(90, 140, 101, 20))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(210, 140, 141, 20))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 160, 70, 20))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 180, 70, 20))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 200, 70, 20))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 220, 70, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 240, 70, 20))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 260, 70, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.sbTool5 = QtWidgets.QSpinBox(Form)
        self.sbTool5.setGeometry(QtCore.QRect(90, 240, 51, 22))
        self.sbTool5.setMinimum(-1)
        self.sbTool5.setMaximum(2147483647)
        self.sbTool5.setObjectName("sbTool5")
        self.sbTool1 = QtWidgets.QSpinBox(Form)
        self.sbTool1.setGeometry(QtCore.QRect(90, 160, 51, 22))
        self.sbTool1.setMinimum(-1)
        self.sbTool1.setMaximum(2147483647)
        self.sbTool1.setObjectName("sbTool1")
        self.sbTool3 = QtWidgets.QSpinBox(Form)
        self.sbTool3.setGeometry(QtCore.QRect(90, 200, 51, 22))
        self.sbTool3.setMinimum(-1)
        self.sbTool3.setMaximum(2147483647)
        self.sbTool3.setObjectName("sbTool3")
        self.sbTool4 = QtWidgets.QSpinBox(Form)
        self.sbTool4.setGeometry(QtCore.QRect(90, 220, 51, 22))
        self.sbTool4.setMinimum(-1)
        self.sbTool4.setMaximum(2147483647)
        self.sbTool4.setObjectName("sbTool4")
        self.sbTool2 = QtWidgets.QSpinBox(Form)
        self.sbTool2.setGeometry(QtCore.QRect(90, 180, 51, 22))
        self.sbTool2.setMinimum(-1)
        self.sbTool2.setMaximum(2147483647)
        self.sbTool2.setObjectName("sbTool2")
        self.sbTool6 = QtWidgets.QSpinBox(Form)
        self.sbTool6.setGeometry(QtCore.QRect(90, 260, 51, 21))
        self.sbTool6.setMinimum(-1)
        self.sbTool6.setMaximum(2147483647)
        self.sbTool6.setObjectName("sbTool6")
        self.sbBatchAraldite = QtWidgets.QSpinBox(Form)
        self.sbBatchAraldite.setGeometry(QtCore.QRect(190, 340, 71, 21))
        self.sbBatchAraldite.setMinimum(-1)
        self.sbBatchAraldite.setMaximum(999999)
        self.sbBatchAraldite.setObjectName("sbBatchAraldite")
        self.pbGoTool5 = QtWidgets.QPushButton(Form)
        self.pbGoTool5.setGeometry(QtCore.QRect(140, 240, 51, 21))
        self.pbGoTool5.setObjectName("pbGoTool5")
        self.pbGoTool4 = QtWidgets.QPushButton(Form)
        self.pbGoTool4.setGeometry(QtCore.QRect(140, 220, 51, 21))
        self.pbGoTool4.setObjectName("pbGoTool4")
        self.pbGoTool1 = QtWidgets.QPushButton(Form)
        self.pbGoTool1.setGeometry(QtCore.QRect(140, 160, 51, 21))
        self.pbGoTool1.setObjectName("pbGoTool1")
        self.pbGoTool2 = QtWidgets.QPushButton(Form)
        self.pbGoTool2.setGeometry(QtCore.QRect(140, 180, 51, 21))
        self.pbGoTool2.setObjectName("pbGoTool2")
        self.pbGoTool6 = QtWidgets.QPushButton(Form)
        self.pbGoTool6.setGeometry(QtCore.QRect(140, 260, 51, 21))
        self.pbGoTool6.setObjectName("pbGoTool6")
        self.pbGoTool3 = QtWidgets.QPushButton(Form)
        self.pbGoTool3.setGeometry(QtCore.QRect(140, 200, 51, 21))
        self.pbGoTool3.setObjectName("pbGoTool3")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 320, 181, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 300, 181, 21))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.sbTrayAssembly = QtWidgets.QSpinBox(Form)
        self.sbTrayAssembly.setGeometry(QtCore.QRect(190, 320, 71, 21))
        self.sbTrayAssembly.setMinimum(-1)
        self.sbTrayAssembly.setMaximum(999999)
        self.sbTrayAssembly.setObjectName("sbTrayAssembly")
        self.sbTrayComponent = QtWidgets.QSpinBox(Form)
        self.sbTrayComponent.setGeometry(QtCore.QRect(190, 300, 71, 21))
        self.sbTrayComponent.setMinimum(-1)
        self.sbTrayComponent.setMaximum(999999)
        self.sbTrayComponent.setObjectName("sbTrayComponent")
        self.pbGoTrayAssembly = QtWidgets.QPushButton(Form)
        self.pbGoTrayAssembly.setGeometry(QtCore.QRect(260, 320, 51, 21))
        self.pbGoTrayAssembly.setObjectName("pbGoTrayAssembly")
        self.pbGoTrayComponent = QtWidgets.QPushButton(Form)
        self.pbGoTrayComponent.setGeometry(QtCore.QRect(260, 300, 51, 21))
        self.pbGoTrayComponent.setObjectName("pbGoTrayComponent")
        self.pbGoBatchAraldite = QtWidgets.QPushButton(Form)
        self.pbGoBatchAraldite.setGeometry(QtCore.QRect(260, 340, 51, 21))
        self.pbGoBatchAraldite.setObjectName("pbGoBatchAraldite")
        self.listIssues = QtWidgets.QListWidget(Form)
        self.listIssues.setGeometry(QtCore.QRect(10, 390, 721, 171))
        self.listIssues.setObjectName("listIssues")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 560, 61, 20))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.leStatus = QtWidgets.QLineEdit(Form)
        self.leStatus.setGeometry(QtCore.QRect(70, 560, 171, 20))
        self.leStatus.setText("")
        self.leStatus.setReadOnly(True)
        self.leStatus.setObjectName("leStatus")
        self.lineEdit_24 = QtWidgets.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(360, 140, 130, 20))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.ckKaptonInspected1 = QtWidgets.QCheckBox(Form)
        self.ckKaptonInspected1.setGeometry(QtCore.QRect(360, 160, 70, 17))
        self.ckKaptonInspected1.setObjectName("ckKaptonInspected1")
        self.ckKaptonInspected2 = QtWidgets.QCheckBox(Form)
        self.ckKaptonInspected2.setGeometry(QtCore.QRect(360, 180, 70, 17))
        self.ckKaptonInspected2.setObjectName("ckKaptonInspected2")
        self.ckKaptonInspected4 = QtWidgets.QCheckBox(Form)
        self.ckKaptonInspected4.setGeometry(QtCore.QRect(360, 220, 70, 17))
        self.ckKaptonInspected4.setObjectName("ckKaptonInspected4")
        self.ckKaptonInspected3 = QtWidgets.QCheckBox(Form)
        self.ckKaptonInspected3.setGeometry(QtCore.QRect(360, 200, 70, 17))
        self.ckKaptonInspected3.setObjectName("ckKaptonInspected3")
        self.ckKaptonInspected5 = QtWidgets.QCheckBox(Form)
        self.ckKaptonInspected5.setGeometry(QtCore.QRect(360, 240, 70, 17))
        self.ckKaptonInspected5.setObjectName("ckKaptonInspected5")
        self.ckKaptonInspected6 = QtWidgets.QCheckBox(Form)
        self.ckKaptonInspected6.setGeometry(QtCore.QRect(360, 260, 70, 17))
        self.ckKaptonInspected6.setObjectName("ckKaptonInspected6")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(500, 160, 151, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.leLocation = QtWidgets.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(650, 160, 121, 20))
        self.leLocation.setObjectName("leLocation")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(500, 200, 131, 21))
        self.lineEdit_10.setReadOnly(True)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.dtRunStart = QtWidgets.QDateTimeEdit(Form)
        self.dtRunStart.setGeometry(QtCore.QRect(630, 200, 151, 21))
        self.dtRunStart.setMaximumDate(QtCore.QDate(2030, 12, 31))
        self.dtRunStart.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dtRunStart.setCalendarPopup(True)
        self.dtRunStart.setObjectName("dtRunStart")
        self.pbRunStartNow = QtWidgets.QPushButton(Form)
        self.pbRunStartNow.setGeometry(QtCore.QRect(780, 200, 91, 21))
        self.pbRunStartNow.setObjectName("pbRunStartNow")
        self.lineEdit_25 = QtWidgets.QLineEdit(Form)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 110, 151, 20))
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.leSensor1 = QtWidgets.QLineEdit(Form)
        self.leSensor1.setGeometry(QtCore.QRect(210, 160, 91, 20))
        self.leSensor1.setObjectName("leSensor1")
        self.leSensor2 = QtWidgets.QLineEdit(Form)
        self.leSensor2.setGeometry(QtCore.QRect(210, 180, 91, 20))
        self.leSensor2.setObjectName("leSensor2")
        self.leSensor3 = QtWidgets.QLineEdit(Form)
        self.leSensor3.setGeometry(QtCore.QRect(210, 200, 91, 20))
        self.leSensor3.setObjectName("leSensor3")
        self.leSensor4 = QtWidgets.QLineEdit(Form)
        self.leSensor4.setGeometry(QtCore.QRect(210, 220, 91, 20))
        self.leSensor4.setObjectName("leSensor4")
        self.leSensor5 = QtWidgets.QLineEdit(Form)
        self.leSensor5.setGeometry(QtCore.QRect(210, 240, 91, 20))
        self.leSensor5.setObjectName("leSensor5")
        self.leSensor6 = QtWidgets.QLineEdit(Form)
        self.leSensor6.setGeometry(QtCore.QRect(210, 260, 91, 20))
        self.leSensor6.setObjectName("leSensor6")
        self.cbInstitution = QtWidgets.QComboBox(Form)
        self.cbInstitution.setGeometry(QtCore.QRect(160, 110, 101, 21))
        self.cbInstitution.setObjectName("cbInstitution")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")
        self.cbInstitution.addItem("")

        self.retranslateUi(Form)
        self.cbInstitution.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Kapton step ID"))
        self.lineEdit_2.setText(_translate("Form", "who performed step"))
        self.lineEdit_8.setText(_translate("Form", "cure temp (C)"))
        self.lineEdit_9.setText(_translate("Form", "cure humidity (%)"))
        self.pbGoSensor1.setText(_translate("Form", "go to"))
        self.pbGoSensor2.setText(_translate("Form", "go to"))
        self.pbGoSensor3.setText(_translate("Form", "go to"))
        self.pbGoSensor6.setText(_translate("Form", "go to"))
        self.pbGoSensor4.setText(_translate("Form", "go to"))
        self.pbGoSensor5.setText(_translate("Form", "go to"))
        self.pbNew.setText(_translate("Form", "New"))
        self.pbEdit.setText(_translate("Form", "Edit"))
        self.pbCancel.setText(_translate("Form", "Cancel"))
        self.pbSave.setText(_translate("Form", "Save"))
        self.lineEdit_11.setText(_translate("Form", "araldite batch"))
        self.lineEdit_12.setText(_translate("Form", "position"))
        self.lineEdit_13.setText(_translate("Form", "sensor tool ID"))
        self.lineEdit_14.setText(_translate("Form", "sensor serial"))
        self.lineEdit_15.setText(_translate("Form", "1 (1, 1)"))
        self.lineEdit_16.setText(_translate("Form", "2 (1, 2)"))
        self.lineEdit_17.setText(_translate("Form", "3 (2, 1)"))
        self.lineEdit_18.setText(_translate("Form", "4 (2, 2)"))
        self.lineEdit_19.setText(_translate("Form", "5 (3, 1)"))
        self.lineEdit_20.setText(_translate("Form", "6 (3, 2)"))
        self.pbGoTool5.setText(_translate("Form", "go to"))
        self.pbGoTool4.setText(_translate("Form", "go to"))
        self.pbGoTool1.setText(_translate("Form", "go to"))
        self.pbGoTool2.setText(_translate("Form", "go to"))
        self.pbGoTool6.setText(_translate("Form", "go to"))
        self.pbGoTool3.setText(_translate("Form", "go to"))
        self.lineEdit_21.setText(_translate("Form", "assembly tray"))
        self.lineEdit_22.setText(_translate("Form", "component tray (sensor)"))
        self.pbGoTrayAssembly.setText(_translate("Form", "go to"))
        self.pbGoTrayComponent.setText(_translate("Form", "go to"))
        self.pbGoBatchAraldite.setText(_translate("Form", "go to"))
        self.listIssues.setToolTip(_translate("Form", "list of issues"))
        self.lineEdit_23.setText(_translate("Form", "Status:"))
        self.lineEdit_24.setText(_translate("Form", "kapton inspected"))
        self.ckKaptonInspected1.setText(_translate("Form", "passed"))
        self.ckKaptonInspected2.setText(_translate("Form", "passed"))
        self.ckKaptonInspected4.setText(_translate("Form", "passed"))
        self.ckKaptonInspected3.setText(_translate("Form", "passed"))
        self.ckKaptonInspected5.setText(_translate("Form", "passed"))
        self.ckKaptonInspected6.setText(_translate("Form", "passed"))
        self.lineEdit_4.setText(_translate("Form", "location"))
        self.lineEdit_10.setText(_translate("Form", "run start"))
        self.pbRunStartNow.setText(_translate("Form", "set to now"))
        self.lineEdit_25.setText(_translate("Form", "Institution (for tools)"))
        self.cbInstitution.setItemText(0, _translate("Form", "CERN"))
        self.cbInstitution.setItemText(1, _translate("Form", "FNAL"))
        self.cbInstitution.setItemText(2, _translate("Form", "UCSB"))
        self.cbInstitution.setItemText(3, _translate("Form", "UMN"))
        self.cbInstitution.setItemText(4, _translate("Form", "HEPHY"))
        self.cbInstitution.setItemText(5, _translate("Form", "HPK"))

