# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_module.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1097, 737)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.sbID = QtGui.QSpinBox(Form)
        self.sbID.setGeometry(QtCore.QRect(80, 10, 161, 21))
        self.sbID.setMaximum(65535)
        self.sbID.setProperty("value", 0)
        self.sbID.setObjectName(_fromUtf8("sbID"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 420, 81, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 440, 81, 21))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 460, 81, 21))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.pbGoBaseplate = QtGui.QPushButton(Form)
        self.pbGoBaseplate.setGeometry(QtCore.QRect(160, 420, 41, 21))
        self.pbGoBaseplate.setObjectName(_fromUtf8("pbGoBaseplate"))
        self.pbGoSensor = QtGui.QPushButton(Form)
        self.pbGoSensor.setGeometry(QtCore.QRect(160, 440, 41, 21))
        self.pbGoSensor.setObjectName(_fromUtf8("pbGoSensor"))
        self.pbGoPcb = QtGui.QPushButton(Form)
        self.pbGoPcb.setGeometry(QtCore.QRect(160, 460, 41, 21))
        self.pbGoPcb.setObjectName(_fromUtf8("pbGoPcb"))
        self.lineEdit_5 = QtGui.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 210, 131, 21))
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pbCancel = QtGui.QPushButton(Form)
        self.pbCancel.setGeometry(QtCore.QRect(170, 30, 71, 21))
        self.pbCancel.setObjectName(_fromUtf8("pbCancel"))
        self.pbEdit = QtGui.QPushButton(Form)
        self.pbEdit.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.pbEdit.setObjectName(_fromUtf8("pbEdit"))
        self.pbNew = QtGui.QPushButton(Form)
        self.pbNew.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.pbNew.setObjectName(_fromUtf8("pbNew"))
        self.pbSave = QtGui.QPushButton(Form)
        self.pbSave.setGeometry(QtCore.QRect(90, 30, 71, 21))
        self.pbSave.setObjectName(_fromUtf8("pbSave"))
        self.sbSensor = QtGui.QSpinBox(Form)
        self.sbSensor.setGeometry(QtCore.QRect(90, 440, 71, 21))
        self.sbSensor.setReadOnly(True)
        self.sbSensor.setMinimum(-1)
        self.sbSensor.setMaximum(2147483647)
        self.sbSensor.setObjectName(_fromUtf8("sbSensor"))
        self.sbPcb = QtGui.QSpinBox(Form)
        self.sbPcb.setGeometry(QtCore.QRect(90, 460, 71, 21))
        self.sbPcb.setReadOnly(True)
        self.sbPcb.setMinimum(-1)
        self.sbPcb.setMaximum(2147483647)
        self.sbPcb.setObjectName(_fromUtf8("sbPcb"))
        self.sbBaseplate = QtGui.QSpinBox(Form)
        self.sbBaseplate.setGeometry(QtCore.QRect(90, 420, 71, 21))
        self.sbBaseplate.setReadOnly(True)
        self.sbBaseplate.setMinimum(-1)
        self.sbBaseplate.setMaximum(2147483647)
        self.sbBaseplate.setObjectName(_fromUtf8("sbBaseplate"))
        self.dsbThickness = QtGui.QDoubleSpinBox(Form)
        self.dsbThickness.setGeometry(QtCore.QRect(140, 210, 101, 21))
        self.dsbThickness.setMinimum(-1.0)
        self.dsbThickness.setMaximum(2147483647.0)
        self.dsbThickness.setObjectName(_fromUtf8("dsbThickness"))
        self.lineEdit_11 = QtGui.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 400, 131, 21))
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_12 = QtGui.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 340, 131, 21))
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lineEdit_13 = QtGui.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 380, 131, 21))
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.sbStepPcb = QtGui.QSpinBox(Form)
        self.sbStepPcb.setGeometry(QtCore.QRect(140, 400, 61, 21))
        self.sbStepPcb.setReadOnly(True)
        self.sbStepPcb.setMinimum(-1)
        self.sbStepPcb.setMaximum(2147483647)
        self.sbStepPcb.setObjectName(_fromUtf8("sbStepPcb"))
        self.sbStepSensor = QtGui.QSpinBox(Form)
        self.sbStepSensor.setGeometry(QtCore.QRect(140, 380, 61, 21))
        self.sbStepSensor.setReadOnly(True)
        self.sbStepSensor.setMinimum(-1)
        self.sbStepSensor.setMaximum(2147483647)
        self.sbStepSensor.setObjectName(_fromUtf8("sbStepSensor"))
        self.sbStepKapton = QtGui.QSpinBox(Form)
        self.sbStepKapton.setGeometry(QtCore.QRect(140, 340, 61, 21))
        self.sbStepKapton.setReadOnly(True)
        self.sbStepKapton.setMinimum(-1)
        self.sbStepKapton.setMaximum(2147483647)
        self.sbStepKapton.setObjectName(_fromUtf8("sbStepKapton"))
        self.pbGoStepPcb = QtGui.QPushButton(Form)
        self.pbGoStepPcb.setGeometry(QtCore.QRect(200, 400, 41, 21))
        self.pbGoStepPcb.setObjectName(_fromUtf8("pbGoStepPcb"))
        self.pbGoStepKapton = QtGui.QPushButton(Form)
        self.pbGoStepKapton.setGeometry(QtCore.QRect(200, 340, 41, 21))
        self.pbGoStepKapton.setObjectName(_fromUtf8("pbGoStepKapton"))
        self.pbGoStepSensor = QtGui.QPushButton(Form)
        self.pbGoStepSensor.setGeometry(QtCore.QRect(200, 380, 41, 21))
        self.pbGoStepSensor.setObjectName(_fromUtf8("pbGoStepSensor"))
        self.leLocation = QtGui.QLineEdit(Form)
        self.leLocation.setGeometry(QtCore.QRect(120, 80, 121, 21))
        self.leLocation.setText(_fromUtf8(""))
        self.leLocation.setReadOnly(True)
        self.leLocation.setObjectName(_fromUtf8("leLocation"))
        self.pbGoShipment = QtGui.QPushButton(Form)
        self.pbGoShipment.setGeometry(QtCore.QRect(120, 100, 121, 21))
        self.pbGoShipment.setObjectName(_fromUtf8("pbGoShipment"))
        self.listShipments = QtGui.QListWidget(Form)
        self.listShipments.setGeometry(QtCore.QRect(10, 120, 231, 61))
        self.listShipments.setObjectName(_fromUtf8("listShipments"))
        self.lineEdit_14 = QtGui.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.lineEdit_15 = QtGui.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.pteWriteComment = QtGui.QPlainTextEdit(Form)
        self.pteWriteComment.setGeometry(QtCore.QRect(10, 640, 231, 61))
        self.pteWriteComment.setPlainText(_fromUtf8(""))
        self.pteWriteComment.setObjectName(_fromUtf8("pteWriteComment"))
        self.lineEdit_16 = QtGui.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 520, 121, 21))
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.pbDeleteComment = QtGui.QPushButton(Form)
        self.pbDeleteComment.setGeometry(QtCore.QRect(130, 520, 111, 21))
        self.pbDeleteComment.setObjectName(_fromUtf8("pbDeleteComment"))
        self.listComments = QtGui.QListWidget(Form)
        self.listComments.setGeometry(QtCore.QRect(10, 540, 231, 91))
        self.listComments.setObjectName(_fromUtf8("listComments"))
        self.pbAddComment = QtGui.QPushButton(Form)
        self.pbAddComment.setGeometry(QtCore.QRect(10, 700, 81, 21))
        self.pbAddComment.setObjectName(_fromUtf8("pbAddComment"))
        self.cbSize = QtGui.QComboBox(Form)
        self.cbSize.setGeometry(QtCore.QRect(139, 250, 101, 20))
        self.cbSize.setObjectName(_fromUtf8("cbSize"))
        self.cbSize.addItem(_fromUtf8(""))
        self.cbSize.addItem(_fromUtf8(""))
        self.leNumKaptons = QtGui.QLineEdit(Form)
        self.leNumKaptons.setGeometry(QtCore.QRect(139, 230, 101, 20))
        self.leNumKaptons.setReadOnly(True)
        self.leNumKaptons.setObjectName(_fromUtf8("leNumKaptons"))
        self.lineEdit_17 = QtGui.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 230, 130, 21))
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.lineEdit_18 = QtGui.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 250, 130, 20))
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.sbRotation = QtGui.QSpinBox(Form)
        self.sbRotation.setGeometry(QtCore.QRect(140, 310, 101, 21))
        self.sbRotation.setReadOnly(True)
        self.sbRotation.setMinimum(-1)
        self.sbRotation.setMaximum(5)
        self.sbRotation.setObjectName(_fromUtf8("sbRotation"))
        self.cbChirality = QtGui.QComboBox(Form)
        self.cbChirality.setGeometry(QtCore.QRect(140, 290, 101, 21))
        self.cbChirality.setObjectName(_fromUtf8("cbChirality"))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.cbChirality.addItem(_fromUtf8(""))
        self.lineEdit_19 = QtGui.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 310, 131, 21))
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.lineEdit_20 = QtGui.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 270, 131, 21))
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.lineEdit_21 = QtGui.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 290, 131, 21))
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.sbChannels = QtGui.QSpinBox(Form)
        self.sbChannels.setGeometry(QtCore.QRect(140, 190, 101, 21))
        self.sbChannels.setReadOnly(True)
        self.sbChannels.setMinimum(-1)
        self.sbChannels.setMaximum(2147483647)
        self.sbChannels.setObjectName(_fromUtf8("sbChannels"))
        self.lineEdit_22 = QtGui.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 190, 131, 21))
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 480, 81, 21))
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.sbProtomodule = QtGui.QSpinBox(Form)
        self.sbProtomodule.setGeometry(QtCore.QRect(90, 480, 71, 21))
        self.sbProtomodule.setReadOnly(True)
        self.sbProtomodule.setMinimum(-1)
        self.sbProtomodule.setMaximum(2147483647)
        self.sbProtomodule.setObjectName(_fromUtf8("sbProtomodule"))
        self.pbGoProtomodule = QtGui.QPushButton(Form)
        self.pbGoProtomodule.setGeometry(QtCore.QRect(160, 480, 41, 21))
        self.pbGoProtomodule.setObjectName(_fromUtf8("pbGoProtomodule"))
        self.lineEdit_24 = QtGui.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 360, 131, 21))
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.pbGoStepKapton_2 = QtGui.QPushButton(Form)
        self.pbGoStepKapton_2.setGeometry(QtCore.QRect(200, 360, 41, 21))
        self.pbGoStepKapton_2.setObjectName(_fromUtf8("pbGoStepKapton_2"))
        self.sbStepKapton_2 = QtGui.QSpinBox(Form)
        self.sbStepKapton_2.setGeometry(QtCore.QRect(140, 360, 61, 21))
        self.sbStepKapton_2.setReadOnly(True)
        self.sbStepKapton_2.setMinimum(-1)
        self.sbStepKapton_2.setMaximum(2147483647)
        self.sbStepKapton_2.setObjectName(_fromUtf8("sbStepKapton_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 60, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 200, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(280, 220, 223, 481))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pteWirebondsDamaged = QtGui.QPlainTextEdit(self.frame)
        self.pteWirebondsDamaged.setGeometry(QtCore.QRect(1, 320, 221, 51))
        self.pteWirebondsDamaged.setObjectName(_fromUtf8("pteWirebondsDamaged"))
        self.cbTestBondsPulledOK = QtGui.QComboBox(self.frame)
        self.cbTestBondsPulledOK.setGeometry(QtCore.QRect(130, 200, 91, 21))
        self.cbTestBondsPulledOK.setObjectName(_fromUtf8("cbTestBondsPulledOK"))
        self.cbTestBondsPulledOK.addItem(_fromUtf8(""))
        self.cbTestBondsPulledOK.addItem(_fromUtf8(""))
        self.leWirebondsRepairedUser = QtGui.QLineEdit(self.frame)
        self.leWirebondsRepairedUser.setGeometry(QtCore.QRect(130, 460, 91, 20))
        self.leWirebondsRepairedUser.setText(_fromUtf8(""))
        self.leWirebondsRepairedUser.setReadOnly(True)
        self.leWirebondsRepairedUser.setObjectName(_fromUtf8("leWirebondsRepairedUser"))
        self.lineEdit_32 = QtGui.QLineEdit(self.frame)
        self.lineEdit_32.setGeometry(QtCore.QRect(1, 180, 131, 21))
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.ckTestBonds = QtGui.QCheckBox(self.frame)
        self.ckTestBonds.setGeometry(QtCore.QRect(1, 140, 121, 17))
        self.ckTestBonds.setObjectName(_fromUtf8("ckTestBonds"))
        self.cbTestBondsRebondedOK = QtGui.QComboBox(self.frame)
        self.cbTestBondsRebondedOK.setGeometry(QtCore.QRect(130, 260, 91, 21))
        self.cbTestBondsRebondedOK.setObjectName(_fromUtf8("cbTestBondsRebondedOK"))
        self.cbTestBondsRebondedOK.addItem(_fromUtf8(""))
        self.cbTestBondsRebondedOK.addItem(_fromUtf8(""))
        self.leTestBondsPulledUser = QtGui.QLineEdit(self.frame)
        self.leTestBondsPulledUser.setGeometry(QtCore.QRect(130, 180, 91, 20))
        self.leTestBondsPulledUser.setText(_fromUtf8(""))
        self.leTestBondsPulledUser.setReadOnly(True)
        self.leTestBondsPulledUser.setObjectName(_fromUtf8("leTestBondsPulledUser"))
        self.ckWirebondsInspected = QtGui.QCheckBox(self.frame)
        self.ckWirebondsInspected.setGeometry(QtCore.QRect(1, 300, 221, 17))
        self.ckWirebondsInspected.setObjectName(_fromUtf8("ckWirebondsInspected"))
        self.ckWirebondsRepaired = QtGui.QCheckBox(self.frame)
        self.ckWirebondsRepaired.setGeometry(QtCore.QRect(1, 390, 171, 17))
        self.ckWirebondsRepaired.setObjectName(_fromUtf8("ckWirebondsRepaired"))
        self.leTestBondsRebondedUser = QtGui.QLineEdit(self.frame)
        self.leTestBondsRebondedUser.setGeometry(QtCore.QRect(130, 240, 91, 20))
        self.leTestBondsRebondedUser.setText(_fromUtf8(""))
        self.leTestBondsRebondedUser.setReadOnly(True)
        self.leTestBondsRebondedUser.setObjectName(_fromUtf8("leTestBondsRebondedUser"))
        self.leWirebondingUser = QtGui.QLineEdit(self.frame)
        self.leWirebondingUser.setGeometry(QtCore.QRect(130, 20, 91, 20))
        self.leWirebondingUser.setText(_fromUtf8(""))
        self.leWirebondingUser.setReadOnly(True)
        self.leWirebondingUser.setObjectName(_fromUtf8("leWirebondingUser"))
        self.lineEdit_31 = QtGui.QLineEdit(self.frame)
        self.lineEdit_31.setGeometry(QtCore.QRect(1, 20, 131, 21))
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(2, 50, 81, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.ckWirebonding = QtGui.QCheckBox(self.frame)
        self.ckWirebonding.setGeometry(QtCore.QRect(1, 0, 141, 17))
        self.ckWirebonding.setObjectName(_fromUtf8("ckWirebonding"))
        self.ckTestBondsRebonded = QtGui.QCheckBox(self.frame)
        self.ckTestBondsRebonded.setGeometry(QtCore.QRect(1, 220, 131, 17))
        self.ckTestBondsRebonded.setObjectName(_fromUtf8("ckTestBondsRebonded"))
        self.lineEdit_35 = QtGui.QLineEdit(self.frame)
        self.lineEdit_35.setGeometry(QtCore.QRect(1, 200, 131, 21))
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.lineEdit_36 = QtGui.QLineEdit(self.frame)
        self.lineEdit_36.setGeometry(QtCore.QRect(1, 460, 131, 20))
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName(_fromUtf8("lineEdit_36"))
        self.pteUnbondedSites = QtGui.QPlainTextEdit(self.frame)
        self.pteUnbondedSites.setGeometry(QtCore.QRect(1, 70, 221, 51))
        self.pteUnbondedSites.setObjectName(_fromUtf8("pteUnbondedSites"))
        self.pteWirebondsRepairedList = QtGui.QPlainTextEdit(self.frame)
        self.pteWirebondsRepairedList.setGeometry(QtCore.QRect(1, 410, 221, 51))
        self.pteWirebondsRepairedList.setObjectName(_fromUtf8("pteWirebondsRepairedList"))
        self.ckTestBondsPulled = QtGui.QCheckBox(self.frame)
        self.ckTestBondsPulled.setGeometry(QtCore.QRect(1, 160, 121, 17))
        self.ckTestBondsPulled.setObjectName(_fromUtf8("ckTestBondsPulled"))
        self.lineEdit_34 = QtGui.QLineEdit(self.frame)
        self.lineEdit_34.setGeometry(QtCore.QRect(1, 260, 131, 21))
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.lineEdit_33 = QtGui.QLineEdit(self.frame)
        self.lineEdit_33.setGeometry(QtCore.QRect(1, 240, 131, 21))
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(280, 80, 223, 101))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.leUnbondedDaqUser = QtGui.QLineEdit(self.frame_2)
        self.leUnbondedDaqUser.setGeometry(QtCore.QRect(130, 60, 92, 20))
        self.leUnbondedDaqUser.setText(_fromUtf8(""))
        self.leUnbondedDaqUser.setReadOnly(True)
        self.leUnbondedDaqUser.setObjectName(_fromUtf8("leUnbondedDaqUser"))
        self.lineEdit_25 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_25.setGeometry(QtCore.QRect(1, 80, 130, 20))
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.leUnbondedDaq = QtGui.QLineEdit(self.frame_2)
        self.leUnbondedDaq.setGeometry(QtCore.QRect(130, 40, 92, 20))
        self.leUnbondedDaq.setText(_fromUtf8(""))
        self.leUnbondedDaq.setReadOnly(True)
        self.leUnbondedDaq.setObjectName(_fromUtf8("leUnbondedDaq"))
        self.lineEdit_27 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_27.setGeometry(QtCore.QRect(1, 60, 130, 21))
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.lineEdit_30 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_30.setGeometry(QtCore.QRect(1, 1, 130, 20))
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.lineEdit_29 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_29.setGeometry(QtCore.QRect(1, 20, 130, 20))
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.cbCheckEdgeContact = QtGui.QComboBox(self.frame_2)
        self.cbCheckEdgeContact.setGeometry(QtCore.QRect(130, 1, 92, 20))
        self.cbCheckEdgeContact.setObjectName(_fromUtf8("cbCheckEdgeContact"))
        self.cbCheckEdgeContact.addItem(_fromUtf8(""))
        self.cbCheckEdgeContact.addItem(_fromUtf8(""))
        self.cbCheckGlueSpill = QtGui.QComboBox(self.frame_2)
        self.cbCheckGlueSpill.setGeometry(QtCore.QRect(130, 20, 92, 20))
        self.cbCheckGlueSpill.setObjectName(_fromUtf8("cbCheckGlueSpill"))
        self.cbCheckGlueSpill.addItem(_fromUtf8(""))
        self.cbCheckGlueSpill.addItem(_fromUtf8(""))
        self.lineEdit_26 = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_26.setGeometry(QtCore.QRect(1, 40, 130, 21))
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName(_fromUtf8("lineEdit_26"))
        self.cbUnbondedDaqOK = QtGui.QComboBox(self.frame_2)
        self.cbUnbondedDaqOK.setGeometry(QtCore.QRect(130, 80, 92, 21))
        self.cbUnbondedDaqOK.setObjectName(_fromUtf8("cbUnbondedDaqOK"))
        self.cbUnbondedDaqOK.addItem(_fromUtf8(""))
        self.cbUnbondedDaqOK.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(540, 60, 141, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(540, 160, 141, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(540, 80, 203, 61))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.cbWirebondingFinalInspectionOK = QtGui.QComboBox(self.frame_3)
        self.cbWirebondingFinalInspectionOK.setGeometry(QtCore.QRect(110, 40, 92, 21))
        self.cbWirebondingFinalInspectionOK.setObjectName(_fromUtf8("cbWirebondingFinalInspectionOK"))
        self.cbWirebondingFinalInspectionOK.addItem(_fromUtf8(""))
        self.cbWirebondingFinalInspectionOK.addItem(_fromUtf8(""))
        self.lineEdit_37 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_37.setGeometry(QtCore.QRect(1, 40, 110, 20))
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName(_fromUtf8("lineEdit_37"))
        self.ckWirebondingFinalInspection = QtGui.QCheckBox(self.frame_3)
        self.ckWirebondingFinalInspection.setGeometry(QtCore.QRect(1, 0, 171, 17))
        self.ckWirebondingFinalInspection.setObjectName(_fromUtf8("ckWirebondingFinalInspection"))
        self.lineEdit_40 = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_40.setGeometry(QtCore.QRect(1, 20, 110, 21))
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName(_fromUtf8("lineEdit_40"))
        self.leWirebondingFinalInspectionUser = QtGui.QLineEdit(self.frame_3)
        self.leWirebondingFinalInspectionUser.setGeometry(QtCore.QRect(111, 20, 91, 20))
        self.leWirebondingFinalInspectionUser.setText(_fromUtf8(""))
        self.leWirebondingFinalInspectionUser.setReadOnly(True)
        self.leWirebondingFinalInspectionUser.setObjectName(_fromUtf8("leWirebondingFinalInspectionUser"))
        self.frame_4 = QtGui.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(540, 180, 251, 101))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.ckEncapsulation = QtGui.QCheckBox(self.frame_4)
        self.ckEncapsulation.setGeometry(QtCore.QRect(0, 0, 171, 17))
        self.ckEncapsulation.setObjectName(_fromUtf8("ckEncapsulation"))
        self.leEncapsulationUser = QtGui.QLineEdit(self.frame_4)
        self.leEncapsulationUser.setGeometry(QtCore.QRect(110, 20, 140, 20))
        self.leEncapsulationUser.setText(_fromUtf8(""))
        self.leEncapsulationUser.setReadOnly(True)
        self.leEncapsulationUser.setObjectName(_fromUtf8("leEncapsulationUser"))
        self.lineEdit_38 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_38.setGeometry(QtCore.QRect(1, 20, 110, 21))
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName(_fromUtf8("lineEdit_38"))
        self.dtCureStart = QtGui.QDateTimeEdit(self.frame_4)
        self.dtCureStart.setGeometry(QtCore.QRect(60, 40, 131, 21))
        self.dtCureStart.setObjectName(_fromUtf8("dtCureStart"))
        self.dtCureStop = QtGui.QDateTimeEdit(self.frame_4)
        self.dtCureStop.setGeometry(QtCore.QRect(60, 60, 131, 21))
        self.dtCureStop.setObjectName(_fromUtf8("dtCureStop"))
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(1, 60, 60, 21))
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.pbCureStopNow = QtGui.QPushButton(self.frame_4)
        self.pbCureStopNow.setGeometry(QtCore.QRect(190, 60, 61, 21))
        self.pbCureStopNow.setObjectName(_fromUtf8("pbCureStopNow"))
        self.pbCureStartNow = QtGui.QPushButton(self.frame_4)
        self.pbCureStartNow.setGeometry(QtCore.QRect(190, 40, 61, 21))
        self.pbCureStartNow.setObjectName(_fromUtf8("pbCureStartNow"))
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(1, 40, 60, 21))
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_39 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_39.setGeometry(QtCore.QRect(1, 80, 120, 20))
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName(_fromUtf8("lineEdit_39"))
        self.cbEncapsulationInspection = QtGui.QComboBox(self.frame_4)
        self.cbEncapsulationInspection.setGeometry(QtCore.QRect(120, 80, 131, 20))
        self.cbEncapsulationInspection.setObjectName(_fromUtf8("cbEncapsulationInspection"))
        self.cbEncapsulationInspection.addItem(_fromUtf8(""))
        self.cbEncapsulationInspection.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(540, 300, 141, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_5 = QtGui.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(540, 320, 251, 251))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.ckHvCablesAttached = QtGui.QCheckBox(self.frame_5)
        self.ckHvCablesAttached.setGeometry(QtCore.QRect(0, 0, 171, 17))
        self.ckHvCablesAttached.setObjectName(_fromUtf8("ckHvCablesAttached"))
        self.lineEdit_42 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_42.setGeometry(QtCore.QRect(1, 20, 131, 21))
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName(_fromUtf8("lineEdit_42"))
        self.leHvCablesAttachedUser = QtGui.QLineEdit(self.frame_5)
        self.leHvCablesAttachedUser.setGeometry(QtCore.QRect(129, 20, 121, 20))
        self.leHvCablesAttachedUser.setText(_fromUtf8(""))
        self.leHvCablesAttachedUser.setReadOnly(True)
        self.leHvCablesAttachedUser.setObjectName(_fromUtf8("leHvCablesAttachedUser"))
        self.lineEdit_43 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_43.setGeometry(QtCore.QRect(1, 50, 129, 21))
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName(_fromUtf8("lineEdit_43"))
        self.lineEdit_44 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_44.setGeometry(QtCore.QRect(1, 90, 129, 20))
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName(_fromUtf8("lineEdit_44"))
        self.lineEdit_45 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_45.setGeometry(QtCore.QRect(1, 70, 129, 21))
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName(_fromUtf8("lineEdit_45"))
        self.leUnbiasedDaq = QtGui.QLineEdit(self.frame_5)
        self.leUnbiasedDaq.setGeometry(QtCore.QRect(129, 50, 121, 20))
        self.leUnbiasedDaq.setText(_fromUtf8(""))
        self.leUnbiasedDaq.setReadOnly(True)
        self.leUnbiasedDaq.setObjectName(_fromUtf8("leUnbiasedDaq"))
        self.cbUnbiasedDaqOK = QtGui.QComboBox(self.frame_5)
        self.cbUnbiasedDaqOK.setGeometry(QtCore.QRect(129, 90, 121, 21))
        self.cbUnbiasedDaqOK.setObjectName(_fromUtf8("cbUnbiasedDaqOK"))
        self.cbUnbiasedDaqOK.addItem(_fromUtf8(""))
        self.cbUnbiasedDaqOK.addItem(_fromUtf8(""))
        self.leUnbiasedDaqUser = QtGui.QLineEdit(self.frame_5)
        self.leUnbiasedDaqUser.setGeometry(QtCore.QRect(129, 70, 121, 20))
        self.leUnbiasedDaqUser.setText(_fromUtf8(""))
        self.leUnbiasedDaqUser.setReadOnly(True)
        self.leUnbiasedDaqUser.setObjectName(_fromUtf8("leUnbiasedDaqUser"))
        self.lineEdit_46 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_46.setGeometry(QtCore.QRect(1, 120, 129, 21))
        self.lineEdit_46.setReadOnly(True)
        self.lineEdit_46.setObjectName(_fromUtf8("lineEdit_46"))
        self.cbIvOK = QtGui.QComboBox(self.frame_5)
        self.cbIvOK.setGeometry(QtCore.QRect(129, 160, 121, 21))
        self.cbIvOK.setObjectName(_fromUtf8("cbIvOK"))
        self.cbIvOK.addItem(_fromUtf8(""))
        self.cbIvOK.addItem(_fromUtf8(""))
        self.leIvUser = QtGui.QLineEdit(self.frame_5)
        self.leIvUser.setGeometry(QtCore.QRect(129, 140, 121, 20))
        self.leIvUser.setText(_fromUtf8(""))
        self.leIvUser.setReadOnly(True)
        self.leIvUser.setObjectName(_fromUtf8("leIvUser"))
        self.leIv = QtGui.QLineEdit(self.frame_5)
        self.leIv.setGeometry(QtCore.QRect(129, 120, 121, 20))
        self.leIv.setText(_fromUtf8(""))
        self.leIv.setReadOnly(True)
        self.leIv.setObjectName(_fromUtf8("leIv"))
        self.lineEdit_47 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_47.setGeometry(QtCore.QRect(1, 160, 129, 20))
        self.lineEdit_47.setReadOnly(True)
        self.lineEdit_47.setObjectName(_fromUtf8("lineEdit_47"))
        self.lineEdit_48 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_48.setGeometry(QtCore.QRect(1, 140, 129, 21))
        self.lineEdit_48.setReadOnly(True)
        self.lineEdit_48.setObjectName(_fromUtf8("lineEdit_48"))
        self.lineEdit_49 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_49.setGeometry(QtCore.QRect(1, 190, 129, 21))
        self.lineEdit_49.setReadOnly(True)
        self.lineEdit_49.setObjectName(_fromUtf8("lineEdit_49"))
        self.cbBiasedDaqOK = QtGui.QComboBox(self.frame_5)
        self.cbBiasedDaqOK.setGeometry(QtCore.QRect(129, 230, 121, 21))
        self.cbBiasedDaqOK.setObjectName(_fromUtf8("cbBiasedDaqOK"))
        self.cbBiasedDaqOK.addItem(_fromUtf8(""))
        self.cbBiasedDaqOK.addItem(_fromUtf8(""))
        self.leBiasedDaqVoltage = QtGui.QLineEdit(self.frame_5)
        self.leBiasedDaqVoltage.setGeometry(QtCore.QRect(129, 210, 121, 20))
        self.leBiasedDaqVoltage.setText(_fromUtf8(""))
        self.leBiasedDaqVoltage.setReadOnly(True)
        self.leBiasedDaqVoltage.setObjectName(_fromUtf8("leBiasedDaqVoltage"))
        self.leBiasedDaq = QtGui.QLineEdit(self.frame_5)
        self.leBiasedDaq.setGeometry(QtCore.QRect(129, 190, 121, 20))
        self.leBiasedDaq.setText(_fromUtf8(""))
        self.leBiasedDaq.setReadOnly(True)
        self.leBiasedDaq.setObjectName(_fromUtf8("leBiasedDaq"))
        self.lineEdit_50 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_50.setGeometry(QtCore.QRect(1, 230, 129, 20))
        self.lineEdit_50.setReadOnly(True)
        self.lineEdit_50.setObjectName(_fromUtf8("lineEdit_50"))
        self.lineEdit_51 = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_51.setGeometry(QtCore.QRect(1, 210, 129, 21))
        self.lineEdit_51.setReadOnly(True)
        self.lineEdit_51.setObjectName(_fromUtf8("lineEdit_51"))
        self.lineEdit_28 = QtGui.QLineEdit(Form)
        self.lineEdit_28.setGeometry(QtCore.QRect(830, 270, 211, 21))
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.listDaqData = QtGui.QListWidget(Form)
        self.listDaqData.setGeometry(QtCore.QRect(830, 290, 211, 131))
        self.listDaqData.setObjectName(_fromUtf8("listDaqData"))
        self.pbDaqAddToPlotter = QtGui.QPushButton(Form)
        self.pbDaqAddToPlotter.setGeometry(QtCore.QRect(830, 420, 121, 21))
        self.pbDaqAddToPlotter.setObjectName(_fromUtf8("pbDaqAddToPlotter"))
        self.pbDaqGoPlotter = QtGui.QPushButton(Form)
        self.pbDaqGoPlotter.setGeometry(QtCore.QRect(960, 420, 81, 21))
        self.pbDaqGoPlotter.setObjectName(_fromUtf8("pbDaqGoPlotter"))
        self.pbIvGoPlotter = QtGui.QPushButton(Form)
        self.pbIvGoPlotter.setGeometry(QtCore.QRect(960, 230, 81, 21))
        self.pbIvGoPlotter.setObjectName(_fromUtf8("pbIvGoPlotter"))
        self.pbIvAddToPlotter = QtGui.QPushButton(Form)
        self.pbIvAddToPlotter.setGeometry(QtCore.QRect(830, 230, 121, 21))
        self.pbIvAddToPlotter.setObjectName(_fromUtf8("pbIvAddToPlotter"))
        self.lineEdit_41 = QtGui.QLineEdit(Form)
        self.lineEdit_41.setGeometry(QtCore.QRect(830, 80, 211, 21))
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName(_fromUtf8("lineEdit_41"))
        self.listIvData = QtGui.QListWidget(Form)
        self.listIvData.setGeometry(QtCore.QRect(830, 100, 211, 131))
        self.listIvData.setObjectName(_fromUtf8("listIvData"))
        self.cbShape = QtGui.QComboBox(Form)
        self.cbShape.setGeometry(QtCore.QRect(140, 270, 101, 20))
        self.cbShape.setObjectName(_fromUtf8("cbShape"))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))
        self.cbShape.addItem(_fromUtf8(""))

        self.retranslateUi(Form)
        self.cbSize.setCurrentIndex(-1)
        self.cbChirality.setCurrentIndex(-1)
        self.cbTestBondsPulledOK.setCurrentIndex(-1)
        self.cbTestBondsRebondedOK.setCurrentIndex(-1)
        self.cbCheckEdgeContact.setCurrentIndex(-1)
        self.cbCheckGlueSpill.setCurrentIndex(-1)
        self.cbUnbondedDaqOK.setCurrentIndex(-1)
        self.cbWirebondingFinalInspectionOK.setCurrentIndex(-1)
        self.cbEncapsulationInspection.setCurrentIndex(-1)
        self.cbUnbiasedDaqOK.setCurrentIndex(-1)
        self.cbIvOK.setCurrentIndex(-1)
        self.cbBiasedDaqOK.setCurrentIndex(-1)
        self.cbShape.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit.setText(_translate("Form", "Module ID", None))
        self.lineEdit_2.setText(_translate("Form", "Baseplate ID", None))
        self.lineEdit_3.setText(_translate("Form", "Sensor ID", None))
        self.lineEdit_4.setText(_translate("Form", "PCB ID", None))
        self.pbGoBaseplate.setText(_translate("Form", "Go to", None))
        self.pbGoSensor.setText(_translate("Form", "Go to", None))
        self.pbGoPcb.setText(_translate("Form", "Go to", None))
        self.lineEdit_5.setText(_translate("Form", "Thickness (mm)", None))
        self.pbCancel.setText(_translate("Form", "Cancel", None))
        self.pbEdit.setText(_translate("Form", "Edit", None))
        self.pbNew.setText(_translate("Form", "New", None))
        self.pbSave.setText(_translate("Form", "Save", None))
        self.lineEdit_11.setText(_translate("Form", "PCB placement step", None))
        self.lineEdit_12.setText(_translate("Form", "Kapton placement step", None))
        self.lineEdit_13.setText(_translate("Form", "Sensor placement step", None))
        self.pbGoStepPcb.setText(_translate("Form", "Go to", None))
        self.pbGoStepKapton.setText(_translate("Form", "Go to", None))
        self.pbGoStepSensor.setText(_translate("Form", "Go to", None))
        self.pbGoShipment.setText(_translate("Form", "go to selected", None))
        self.listShipments.setToolTip(_translate("Form", "ID (date sent) (SENDER to RECEIVER)", None))
        self.lineEdit_14.setText(_translate("Form", "location", None))
        self.lineEdit_15.setText(_translate("Form", "shipments", None))
        self.lineEdit_16.setText(_translate("Form", "Comments", None))
        self.pbDeleteComment.setText(_translate("Form", "delete selected", None))
        self.pbAddComment.setText(_translate("Form", "add comment", None))
        self.cbSize.setItemText(0, _translate("Form", "8", None))
        self.cbSize.setItemText(1, _translate("Form", "6", None))
        self.lineEdit_17.setText(_translate("Form", "number of kapton layers", None))
        self.lineEdit_18.setText(_translate("Form", "Size (inches)", None))
        self.cbChirality.setItemText(0, _translate("Form", "achiral", None))
        self.cbChirality.setItemText(1, _translate("Form", "left", None))
        self.cbChirality.setItemText(2, _translate("Form", "right", None))
        self.lineEdit_19.setText(_translate("Form", "Rotation", None))
        self.lineEdit_20.setText(_translate("Form", "Shape", None))
        self.lineEdit_21.setText(_translate("Form", "Chirality", None))
        self.lineEdit_22.setText(_translate("Form", "Channels", None))
        self.lineEdit_23.setText(_translate("Form", "Protomodule ID", None))
        self.pbGoProtomodule.setText(_translate("Form", "Go to", None))
        self.lineEdit_24.setText(_translate("Form", "Kapton placement step 2", None))
        self.pbGoStepKapton_2.setText(_translate("Form", "Go to", None))
        self.label.setText(_translate("Form", "Pre-wirebonding qualification", None))
        self.label_2.setText(_translate("Form", "Wirebonding", None))
        self.cbTestBondsPulledOK.setItemText(0, _translate("Form", "yes", None))
        self.cbTestBondsPulledOK.setItemText(1, _translate("Form", "no", None))
        self.lineEdit_32.setText(_translate("Form", "Test bond pull user", None))
        self.ckTestBonds.setText(_translate("Form", "Is test bond module", None))
        self.cbTestBondsRebondedOK.setItemText(0, _translate("Form", "yes", None))
        self.cbTestBondsRebondedOK.setItemText(1, _translate("Form", "no", None))
        self.ckWirebondsInspected.setText(_translate("Form", "Wirebonds inspected (list damaged below)", None))
        self.ckWirebondsRepaired.setText(_translate("Form", "Wirebonds repaired (list below)", None))
        self.lineEdit_31.setText(_translate("Form", "Wirebonding user", None))
        self.label_3.setText(_translate("Form", "Unbonded sites", None))
        self.ckWirebonding.setText(_translate("Form", "Wirebonding performed", None))
        self.ckTestBondsRebonded.setText(_translate("Form", "Test bonds rebonded", None))
        self.lineEdit_35.setText(_translate("Form", "Test bonds pulled OK?", None))
        self.lineEdit_36.setText(_translate("Form", "Wirebonds repaired user", None))
        self.ckTestBondsPulled.setText(_translate("Form", "Test bonds pulled", None))
        self.lineEdit_34.setText(_translate("Form", "Test bonds rebonded OK?", None))
        self.lineEdit_33.setText(_translate("Form", "Test bonds rebonded user", None))
        self.lineEdit_25.setText(_translate("Form", "Unbonded DAQ OK?", None))
        self.lineEdit_27.setText(_translate("Form", "Unbonded DAQ user", None))
        self.lineEdit_30.setToolTip(_translate("Form", "height difference between highest and lowers corners", None))
        self.lineEdit_30.setText(_translate("Form", "check edge contact", None))
        self.lineEdit_29.setToolTip(_translate("Form", "height difference between highest and lowers corners", None))
        self.lineEdit_29.setText(_translate("Form", "check glue spillage", None))
        self.cbCheckEdgeContact.setItemText(0, _translate("Form", "pass", None))
        self.cbCheckEdgeContact.setItemText(1, _translate("Form", "fail", None))
        self.cbCheckGlueSpill.setItemText(0, _translate("Form", "pass", None))
        self.cbCheckGlueSpill.setItemText(1, _translate("Form", "fail", None))
        self.lineEdit_26.setText(_translate("Form", "Unbonded DAQ dataset", None))
        self.cbUnbondedDaqOK.setItemText(0, _translate("Form", "yes", None))
        self.cbUnbondedDaqOK.setItemText(1, _translate("Form", "no", None))
        self.label_4.setText(_translate("Form", "Wirebonding qualification", None))
        self.label_5.setText(_translate("Form", "Encapsulation", None))
        self.cbWirebondingFinalInspectionOK.setItemText(0, _translate("Form", "pass", None))
        self.cbWirebondingFinalInspectionOK.setItemText(1, _translate("Form", "fail", None))
        self.lineEdit_37.setText(_translate("Form", "Final inspection OK?", None))
        self.ckWirebondingFinalInspection.setText(_translate("Form", "Final inspection done", None))
        self.lineEdit_40.setText(_translate("Form", "Final inspection user", None))
        self.ckEncapsulation.setText(_translate("Form", "Encapsulation done", None))
        self.lineEdit_38.setText(_translate("Form", "Encpasulation user", None))
        self.lineEdit_6.setText(_translate("Form", "cure stop", None))
        self.pbCureStopNow.setText(_translate("Form", "set to now", None))
        self.pbCureStartNow.setText(_translate("Form", "set to now", None))
        self.lineEdit_7.setText(_translate("Form", "cure start", None))
        self.lineEdit_39.setText(_translate("Form", "Post-curing inspection", None))
        self.cbEncapsulationInspection.setItemText(0, _translate("Form", "pass", None))
        self.cbEncapsulationInspection.setItemText(1, _translate("Form", "fail", None))
        self.label_6.setText(_translate("Form", "Finished module qualification", None))
        self.ckHvCablesAttached.setText(_translate("Form", "HV cables attached", None))
        self.lineEdit_42.setText(_translate("Form", "HV cable attachment user", None))
        self.lineEdit_43.setText(_translate("Form", "Unbiased DAQ dataset", None))
        self.lineEdit_44.setText(_translate("Form", "Unbiased DAQ OK?", None))
        self.lineEdit_45.setText(_translate("Form", "Unbiased DAQ user", None))
        self.cbUnbiasedDaqOK.setItemText(0, _translate("Form", "yes", None))
        self.cbUnbiasedDaqOK.setItemText(1, _translate("Form", "no", None))
        self.lineEdit_46.setText(_translate("Form", "IV dataset", None))
        self.cbIvOK.setItemText(0, _translate("Form", "yes", None))
        self.cbIvOK.setItemText(1, _translate("Form", "no", None))
        self.lineEdit_47.setText(_translate("Form", "IV OK?", None))
        self.lineEdit_48.setText(_translate("Form", "IV user", None))
        self.lineEdit_49.setText(_translate("Form", "Biased DAQ dataset", None))
        self.cbBiasedDaqOK.setItemText(0, _translate("Form", "yes", None))
        self.cbBiasedDaqOK.setItemText(1, _translate("Form", "no", None))
        self.lineEdit_50.setText(_translate("Form", "Biased DAQ OK?", None))
        self.lineEdit_51.setText(_translate("Form", "Biased DAQ voltage", None))
        self.lineEdit_28.setText(_translate("Form", "DAQ datasets", None))
        self.pbDaqAddToPlotter.setText(_translate("Form", "add selected to plotter", None))
        self.pbDaqGoPlotter.setText(_translate("Form", "go to plotter", None))
        self.pbIvGoPlotter.setText(_translate("Form", "go to plotter", None))
        self.pbIvAddToPlotter.setText(_translate("Form", "add selected to plotter", None))
        self.lineEdit_41.setText(_translate("Form", "IV datasets", None))
        self.cbShape.setItemText(0, _translate("Form", "full", None))
        self.cbShape.setItemText(1, _translate("Form", "half", None))
        self.cbShape.setItemText(2, _translate("Form", "five", None))
        self.cbShape.setItemText(3, _translate("Form", "three", None))
        self.cbShape.setItemText(4, _translate("Form", "semi", None))
        self.cbShape.setItemText(5, _translate("Form", "semi(-)", None))
        self.cbShape.setItemText(6, _translate("Form", "choptwo", None))

